server/uidassigner/main_test.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/17)

Unit test for uidassigner

---

tools/merge/merge.cc
tools/merge/merge_heap.cc

1. Correction to the execution instruction of merge.cc and merge_heap.cc
2. Adding reference to rocksdb headers
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/26)

Correction to execution instruction and reference to headers

---

gql/parser.go
gql/parser_test.go
gql/state.go
gql/state_test.go
lex/lexer.go
loader/loader.go
posting/lists.go
query/query.go
query/query_test.go
rdf/parse.go
server/loader/main.go
server/main.go
server/main_test.go
server/uidassigner/main.go
server/uidassigner/main_test.go
uid/assigner.go
uid/assigner_test.go
worker/worker.go
worker/worker_test.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/28)

Remove store and pass it as argument plus mod sharding based on attributes

---

loader/loader.go
rdf/parse.go
server/loader/main.go
server/uidassigner/main.go
server/uidassigner/main_test.go
uid/assigner.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/30)

Changes to limit line length to 80 chars

---

loader/loader.go
server/uidassigner/main.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/31)

Change function names to make their purpose clear

---

query/query.go
query/query_test.go
server/main.go
server/main_test.go
worker/worker.go
worker/worker_test.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/38)

Added a seperate store for xid & uid in server

---

:q
conn/pool.go
query/query.go
query/query_test.go
server/main.go
server/main_test.go
worker/worker.go
worker/worker_test.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/40)

Distributed server

---

Dockerfile
lex/lexer.go
loader/loader.go
posting/list.go
query/query.go
rdf/README.txt
rdf/parse.go
server/main.go
server/uidassigner/README.txt
server/uidassigner/main.go
uid/assigner.go
worker/assign.go
worker/mutation.go
worker/task.go
worker/worker.go

Fix the bugs encountered during testing running mutations via GraphQL.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/43)

Distributed query and mutation testing

---

gql/parser.go

fix build break
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/44)

use new Lexer initializer

---

tools/merge/main.go

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/57)

Batch write while merging

---

query/query.go
tools/dlist/main.go
worker/task.go
worker/worker.go

Fixes #49
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/56)

Fix a bug due to which we were unable to retrieve xids.

---

conn/client.go
conn/server.go
loader/loader.go
posting/lists.go
rdf/parse.go
rdf/parse_test.go
server/testrun.sh
store/store.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/60)

Performance improvements and bug fixes

---

rdf/parse.go
rdf/parse_test.go
rdf/state.go
server/main.go

For both subject and object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/68)

Bug Fix: Parse RDFs with _uid_:0xid

---

worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/69)

Don't log fatal on call to ServeTask. Just return error for that query.

---

query/query.go
query/query_test.go
server/main.go
server/main_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/76)

Set 1 min timeout on query processing

---

rdf/parse.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/80)

Output the offending line in error log if rdf.Parse fails.

---

server/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/89)

Adding support for mutations in goclient

---

commit/log.go
commit/log_test.go
posting/list.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/90)

Modifying AddMutation and AddLog

---

vendor/github.com/tecbot/gorocksdb/LICENSE
vendor/github.com/tecbot/gorocksdb/README.md
vendor/github.com/tecbot/gorocksdb/backup.go
vendor/github.com/tecbot/gorocksdb/cache.go
vendor/github.com/tecbot/gorocksdb/cf_handle.go
vendor/github.com/tecbot/gorocksdb/compaction_filter.go
vendor/github.com/tecbot/gorocksdb/comparator.go
vendor/github.com/tecbot/gorocksdb/db.go
vendor/github.com/tecbot/gorocksdb/doc.go
vendor/github.com/tecbot/gorocksdb/dynflag.go
vendor/github.com/tecbot/gorocksdb/embedflag.go
vendor/github.com/tecbot/gorocksdb/env.go
vendor/github.com/tecbot/gorocksdb/filter_policy.go
vendor/github.com/tecbot/gorocksdb/gorocksdb.c
vendor/github.com/tecbot/gorocksdb/gorocksdb.h
vendor/github.com/tecbot/gorocksdb/iterator.go
vendor/github.com/tecbot/gorocksdb/merge_operator.go
vendor/github.com/tecbot/gorocksdb/options.go
vendor/github.com/tecbot/gorocksdb/options_block_based_table.go
vendor/github.com/tecbot/gorocksdb/options_compaction.go
vendor/github.com/tecbot/gorocksdb/options_compression.go
vendor/github.com/tecbot/gorocksdb/options_flush.go
vendor/github.com/tecbot/gorocksdb/options_read.go
vendor/github.com/tecbot/gorocksdb/options_write.go
vendor/github.com/tecbot/gorocksdb/slice.go
vendor/github.com/tecbot/gorocksdb/slice_transform.go
vendor/github.com/tecbot/gorocksdb/snapshot.go
vendor/github.com/tecbot/gorocksdb/util.go
vendor/github.com/tecbot/gorocksdb/write_batch.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/106)

Add gorocksdb to govendor

---

.gitignore
.travis.yml
contrib/README.md
contrib/build-rocksdb.sh
contrib/cover.sh

Contains the initial scripts and configuration for travis-ci and
coveralls integration.
Fixes #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/121)

Initial travis-ci and coveralls Integration

---

.travis.yml
vendor/github.com/zond/gotomic/list.go
vendor/github.com/zond/gotomic/stm.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/122)

Fixing go1.7 compatability issues

---

store/store.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/145)

Store: Handle error to avoid panic bug

---

cluster/predicates_test.go
cmd/dgraph/main.go
cmd/dgraphassigner/main.go
cmd/dgraphassigner/main_test.go
cmd/dgraphlist/main.go
cmd/dgraphloader/main.go
cmd/dgraphloader/main_test.go
cmd/dgraphmerge/main.go
cmd/dgraphmerge/main_test.go
commit/log.go
loader/loader.go
posting/list.go
posting/lists.go
query/query.go
query/query_test.go
store/store.go
uid/assigner.go
uid/assigner_test.go
worker/assign.go
worker/assign_test.go
worker/mutation.go
worker/task.go
worker/worker.go
worker/worker_test.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/151)

Style changes for test PR

---

build.sh
cmd/dgraph/testrun.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/160)

Add nomutations flag in testrun

---

cmd/dgraph/main.go
cmd/dgraph/main_test.go
query/query.go
query/query_test.go

Some simple style changes:
1) When referencing self, use the same variable name.
2) Use composite literal to simplify construction of new objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/174)

Style changes

---

cmd/dgraph/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/219)

Shutdown without exit call

---

contrib/daemon/README.md
contrib/daemon/dgraph

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/357)

Improve: add daemon script to start/stop dgraph as service

---

cmd/dgraph/config.yaml
cmd/dgraph/main.go
x/init.go

Now configuration parameters can be saved in a yaml file and it can be specified as a command line parameter while launching dgraph using.
./dgraph -conf="<file_path>/<file_name>.yaml"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/385)

Added support for reading from configuration file.

---

build.sh

Fixes one half of https://github.com/dgraph-io/dgraph/issues/446 by replacing the MD5 message digest with sha256. Uses `shasum` as the command on both macOS and linux systems. Manually tested on macOS 10.12.2, Ubuntu, and Arch Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/484)

replace md5 digest with sha256 in build.sh

---

gql/bench_test.go

Using the new grammar definition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/541)

Fix benchmark test queries

---

query/proto.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/613)

handle default type in proto value

---

posting/hash.go
posting/hash_test.go
posting/lists.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/653)

don't delete lhmap in commit lists to avoid race condition

---

posting/index.go

This is in response to #672 . Fix was easier than I thought it would be...never made a 1 line pull request before:-P **However, I can't actually verify if it works.**
I tried to add tests but I can't succeed in building and testing the code. Maybe a nice makefile and contribution guide should be added. (Would also make it easier to do "nightly" Docker builds instead of pulling latest binaries in Dockerfile.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/692)

WIP: Copy Facets to Reverse Edges

---

types/sort.go
worker/aggregator.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/733)

handle default type during sorting

---

query/query.go
query/query_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/740)

mark the variables as done even if subgraph is not visited

---

posting/index.go
posting/index_test.go
posting/list.go
posting/list_test.go
posting/lists.go
query/common_test.go
query/query_test.go
worker/backup_test.go
worker/draft.go
worker/index.go
worker/mutation.go
worker/sort.go
worker/task.go
worker/worker_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/737)

make lhmap per group, avoid stoptheworld locks during reindexing or populating snapshot

---

contrib/loader.sh
posting/lists.go
schema/parse.go
schema/parse_test.go
schema/schema.go
schema/testfiles/test_schema
schema/testfiles/test_schema1
schema/testfiles/test_schema2
schema/testfiles/test_schema3
schema/testfiles/test_schema_index1
schema/testfiles/test_schema_index3
schema/testfiles/test_schema_index4
schema/testfiles/test_schema_index5
worker/groups.go

update loader script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/745)

remove schema file

---

README.md

We just released the extended FOSSA badge with deep dependency stats and a license scan report.
Here's an open PR to use the large badge if you're interested!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/790)

Upgrade to large FOSSA badge

---

client/client.go
cmd/dgraphloader/main.go

As discussed in the slack channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/797)

Change NewBatchMutation to accept a DgraphClient rather than a grpc.ClientConn for consistency

---

algo/uidlist.go
algo/uidlist_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/804)

fix set difference bug

---

wiki/content/query-language/index.md

Remove the links from the storage type list, now shows the tag instead of broken links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/820)

Remove links from storage types

---

gql/bench_test.go

Update queries to match with the current grammar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/825)

Fix gql benchmark tests

---

types/conversion.go
types/conversion_test.go
types/facets/utils.go
types/scalar_types.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/916)

better handling of datetime parsing

---

wiki/README.md
wiki/scripts/local.sh

Document the feature from https://github.com/dgraph-io/hugo-docs/pull/13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/938)

Document doc feature for custom go grpc example

---

cmd/dgraph/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/958)

return server latency for schema block

---

vendor/vendor.json

The conflicts seem to have been resolved properly, but the markers where left behind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/977)

vendor.json: remove conflict markers

---

posting/index_test.go
posting/list.go
posting/lists.go
raftwal/wal.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/997)

badger get api change

---

query/query.go
query/query_test.go

This resolves #1020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1029)

Concurrent filtering data race removed

---

wiki/scripts/build.sh
wiki/scripts/local.sh

Please review together: https://github.com/dgraph-io/hugo-docs/pull/17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1042)

Warn if documentation version is outdated

---

posting/hash.go
posting/index_test.go
posting/lists.go
worker/draft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1087)

take stw per shard

---

cmd/dgraph/main.go
cmd/dgraph/main_test.go
dgraph/config.go
dgraph/server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1188)

allow users to specify badger table options

---

query/outputnode.go
query/outputnode_test.go
query/query_test.go

Changes:
- removed heap-based ordering
- added sorting of attributes when normalize'ing
- corrected all tests
This resolves #1240.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1273)

Results in the same order as query in JSON

---

dashboard/src/actions/frames.js
dashboard/src/actions/index.js
dashboard/src/actions/query.js
dashboard/src/assets/css/Frames.scss
dashboard/src/components/EditorPanel.js
dashboard/src/components/FrameCodeTab.js
dashboard/src/components/FrameError.js
dashboard/src/components/FrameHeader.js
dashboard/src/components/FrameItem.js
dashboard/src/components/FrameLayout.js
dashboard/src/components/FrameList.js
dashboard/src/components/FrameSession.js
dashboard/src/components/FrameSuccess.js
dashboard/src/components/SessionFooter.js
dashboard/src/components/SessionFooterResult.js
dashboard/src/components/SessionGraphTab.js
dashboard/src/components/SessionTreeTab.js
dashboard/src/containers/App.js
dashboard/src/containers/AppProvider.js
dashboard/src/containers/Editor.js
dashboard/src/lib/helpers.js
dashboard/src/reducers/index.js
dashboard/src/reducers/query.js

1. No longer store response in UI. fix #981
2. Improve performance by storing query in redux not in app, thus avoiding re-rendering the whole `<App />`
To test:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1305)

UI remove cache response.

---

dgraph/embedded.go
worker/lease.go

This resolves  #1310.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1316)

Lease manager returns error if not initialized

---

algo/benchmarks
algo/uidlist.go
algo/uidlist_test.go
bp128/bp128.go
posting/list.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1332)

check max int a block before decoding

---

raftwal/wal.go
worker/groups.go
worker/predicate.go
worker/sort.go
worker/task.go

Implements backup requests.
Connected to #1121.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1343)

Backup requests

---

query/query_test.go
tok/tok_test.go
tok/tokens.go
worker/tokens.go

This resolves #1337.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1339)

'.' language handling in functions

---

posting/list.go
query/groupby.go
query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1417)

return error all the way up in query package

---

.gitignore
cmd/bulkloader/loader.go
cmd/bulkloader/main.go
cmd/bulkloader/speed_tests/run.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1416)

Bulkloader: multiple RDFs

---

cmd/bulkloader/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1424)

Bulkloader: add HTTP server

---

cmd/dgraph/main.go
dgraph/server.go
worker/mutation.go
worker/task.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1425)

enable tracking for queries received over serveTask endpoint

---

cmd/bulkloader/loader.go
cmd/bulkloader/main.go
cmd/bulkloader/mapper.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1438)

Bulkloader: skip expand edges

---

cmd/bulkloader/loader.go
cmd/bulkloader/mapper.go
posting/list.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1439)

Bulkloader: sort and encode in goroutine

---

cmd/bulkloader/loader.go
cmd/bulkloader/main.go
cmd/bulkloader/speed_tests/run.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1440)

Bulkloader: lease file

---

cmd/bulkloader/loader.go
cmd/bulkloader/mapper.go
cmd/bulkloader/reduce.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1442)

Bulkloader: Fix bug in reduce goroutine data handover

---

cmd/bulkloader/loader.go
cmd/bulkloader/uid_map.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1443)

Bulkloader: shard uid map

---

cmd/bulkloader/uid_map.go

I wasn't updating the `lastUsed` UID to be the previous lease position, thus clobbering ranges used by other shards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1449)

Bulkloader: fix bug in lease for UID map

---

client/client.go
worker/index.go
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1450)

check for empty predicate in schema mutation

---

x/watermark.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1451)

simplify watermark logic

---

cmd/bulkloader/loader.go
cmd/bulkloader/main.go
cmd/bulkloader/mapper.go
cmd/bulkloader/progress.go
cmd/bulkloader/reduce.go
cmd/bulkloader/split_gz.sh
cmd/bulkloader/uid_map.go

Main changes:
* Read from many RDF files concurrently.
* Mappers now do the parsing into string objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1457)

Bulkloader: mapper improvements for using many cores

---

cmd/bulkloader/count_index.go
cmd/bulkloader/loader.go
cmd/bulkloader/main.go
cmd/bulkloader/mapper.go
cmd/bulkloader/metrics.go
cmd/bulkloader/progress.go
cmd/bulkloader/reduce.go
cmd/bulkloader/shard_map.go
cmd/bulkloader/shuffle.go
cmd/bulkloader/speed_tests/run.sh
x/max_waitgroup.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1480)

Bulkloader: sharded map and shuffle

---

cmd/bulkloader/reduce.go

Fixes the issue @pawanrawal was seeing where we were getting some duplicate UIDs in posting lists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1485)

Bulkloader: filter out duplicate postings in the shuffler

---

cmd/bulkloader/mapper.go
cmd/bulkloader/shuffle.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1490)

Bulkloader: add UID to map entry comparison

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1496)

Wiki: update deploy notes for bulkloader

---

cmd/bulkloader/mapper.go
cmd/bulkloader/systest/run.sh
cmd/bulkloader/systest/suite03/query.json
cmd/bulkloader/systest/suite03/rdfs.rdf
cmd/bulkloader/systest/suite03/result.json
cmd/bulkloader/systest/suite03/schema.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1498)

Bulkloader: support for multiple values

---

cmd/bulkloader/loader.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1511)

Bulkloader: allow gzipped schema files

---

worker/export.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1514)

Use schema.gz for schema file extension in export

---

vendor/github.com/paulmach/go.geojson/LICENSE
vendor/github.com/paulmach/go.geojson/README.md
vendor/github.com/paulmach/go.geojson/feature.go
vendor/github.com/paulmach/go.geojson/feature_collection.go
vendor/github.com/paulmach/go.geojson/geometry.go
vendor/github.com/paulmach/go.geojson/properties.go
vendor/vendor.json

Travis currently failing, ~this should fix it.~ fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1525)

Vendor paulmach/go.geojson

---

cmd/dgraph-bulk-loader/loader.go
cmd/dgraph-bulk-loader/main.go
cmd/dgraph-bulk-loader/mapper.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1532)

Bulkloader: Invert edge expand flag

---

client/mutations.go
cmd/dgraphzero/raft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1581)

Fix Issue #1571

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1585)

Wiki: walkthrough how to use the bulk loader

---

cmd/dgraph-bulk-loader/mapper.go
systest/fixture_test.go
systest/tests_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1591)

Bulkloader: Add support for facets

---

cmd/dgraph-bulk-loader/loader.go
cmd/dgraph-bulk-loader/main.go
cmd/dgraph-bulk-loader/mapper.go
cmd/dgraph-bulk-loader/schema.go
cmd/dgraph-bulk-loader/uid_map.go
systest/fixture_test.go
systest/tests_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1604)

Bulkloader: add xid edges

---

cmd/dgraph-bulk-loader/schema.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1608)

Remove `schemaState` type (use `Explicit` field instead)

---

docker/base/Dockerfile

- Remove unused packages
- Reduce layers and size of the docker image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1639)

Reduce layers and size of base dockerfile

---

types/sort.go
types/sort_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1641)

Allow comparison between facets of different type

---

query/query.go
worker/export.go
worker/export_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1646)

Output "" instead of "_nil_" for empty strings

---

worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1651)

Maintain uid/value/facet matrices in the same dimension

---

gql/parser.go
gql/parser_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1659)

Don't allow uid as argument in root function

---

client/client.go
client/testtxn/main.go
dgraph/server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1662)

Remove hardcoded timeout and pass context.Context through client

---

cmd/dgraphzero/raft.go
cmd/dgraphzero/zero.go
conn/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1665)

Add server level linearizable reads to Dgraph zero.

---

schema/schema.go
worker/predicate_move.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1680)

load schema after predicate move

---

cmd/dgraphzero/oracle.go
cmd/dgraphzero/zero.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1699)

Mechanism to stream Oracle deltas to Dgraph servers.

---

client/client.go

Stops a tight retry loop in two scenarios I've noticed:
- Dgraphzero is not up yet.
- Dgraphzero is overwhelmed with other requests (e.g. lots of concurrent clients).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1708)

Exponential backoff when requesting timestamps in client

---

wiki/content/contribute/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1718)

Adjusted grammar.

---

cmd/dgraphzero/oracle.go
contrib/acctupsert/.gitignore
contrib/acctupsert/main.go
contrib/sentenceswap/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1728)

Add account themed upsert test

---

contrib/sentenceswap/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1729)

Add intermediate delete and garbage values to sentence swap test

---

client/txn.go
contrib/acctupsert/main.go
contrib/bank/main.go
contrib/sentenceswap/main.go
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1731)

Discard transaction method

---

cmd/dgraph-live-loader/batch.go
systest/bulk_live_cases_test.go
systest/bulk_live_fixture_test.go
systest/cluster_test.go
systest/mutations_test.go
systest/plugin_test.go

The count indexes don't actually pass -- @janardhan1993 said he'll fix corresponding issue in dgraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1736)

Fix systest package

---

systest/bulk_live_fixture_test.go
systest/cluster_test.go
systest/mutations_test.go
systest/plugin_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1748)

Fix systest breakage from cobra changes

---

worker/sort.go

Fixes #1741
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1758)

Fix sorting on predicate when doesn't exist on child

---

client/client.go
client/doc.go
client/txn.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1765)

Add godocs for client

---

wiki/content/clients/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1770)

Add Go example for wiki/clients

---

wiki/content/clients/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1772)

More wiki/clients changes for raw http

---

dgraph/cmd/server/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1776)

Simpler UI asset flag

---

CHANGELOG.md
contrib/scripts/functions.sh
contrib/scripts/goldendata-queries.sh
dgraph/cmd/zero/assign.go
dgraph/cmd/zero/oracle.go
dgraph/cmd/zero/raft.go
dgraph/cmd/zero/tablet.go
dgraph/cmd/zero/zero.go
posting/mvcc.go
query/common_test.go
systest/bulk_live_cases_test.go
worker/groups.go
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1779)

Try to abort long running Txns, abort old transactions after leader change in zero.

---

client/examples_test.go

* The query had a typo in it.
* The naming of struct fields was a bit confusing, so changed that as
well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1810)

Fix DeleteEdge examples.

---

client/txn.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1812)

Discard transaction when a mutation fails

---

CHANGELOG.md
posting/index.go
systest/mutations_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1820)

Fix bug in index maintenance for delete star

---

CHANGELOG.md
dgraph/cmd/server/http.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1837)

Allow GraphQL vars to be set when using HTTP endpoint

---

wiki/content/query-language/index.md
wiki/scripts/local.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1843)

Graphql vars docs update

---

dgraph/cmd/server/run_test.go
edgraph/server.go
gql/parser.go
gql/parser_test.go
query/common_test.go
query/query_facets_test.go
query/query_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1845)

Remove dead code from graphql style vars

---

query/mutation.go
worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1850)

Make uid vs max lease check more accurate

---

CHANGELOG.md
dgraph/cmd/live/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1848)

Allow live loader to use existing nodes

---

dgraph/cmd/bulk/loader.go

This change makes the build green again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1858)

Bulk loader retries when obtaining write ts from zero

---

conn/node.go
dgraph/cmd/zero/raft.go
worker/draft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1862)

Initialize peer map from membership information

---

x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1861)

Increase grpc max size to 4GB (maximum possible)

---

contrib/scripts/install.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1871)

Fix travis (reduce amount of grpc related dependencies)

---

CHANGELOG.md
gql/parser.go
gql/parser_test.go

Fixes #1868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1874)

Ensure variable defined before substituting

---

contrib/integration/testtxn/main_test.go
posting/btree.go
posting/list.go
posting/lists.go
posting/mvcc.go
worker/sort.go
worker/task.go
worker/tokens.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1875)

Store list of keys in memory until they have been written to disk.

---

client/txn.go

Fixes #1882
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1884)

Commit now should finish the transaction

---

gql/parser.go
query/outputnode.go
query/query.go
systest/mutations_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1881)

Fix alias edge cases in normalize directive

---

wiki/content/clients/index.md

Duplicate "this" on the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1902)

Duplicate words

---

systest/mutations_test.go
worker/sort.go
worker/sort_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1921)

Fix bad language/sort interaction

---

worker/mutation.go
worker/mutation_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1922)

Prohibit string to password schema change

---

dgraph/cmd/zero/raft.go
dgraph/cmd/zero/run.go

Doesn't necessarily solve the issue #1898 but should be done anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1923)

Shutdown raft node in zero

---

wiki/content/contribute/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1927)

Use `$GOPATH` in installation instructions

---

CHANGELOG.md
dgraph/cmd/zero/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1928)

Only wait 5s for graceful grpc shutdown in zero

---

wiki/content/contribute/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1930)

Add `go install` instruction to generate the dgraph binary

---

wiki/content/howto/index.md
wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1944)

Docs for upsert (howto) and reorder string index table

---

dgraph/cmd/server/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1948)

Fix `grpc.EnableTracing = false` race in startup

---

CHANGELOG.md
edgraph/server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1980)

Add error handling for ApplyMutations when using CommitNow

---

CHANGELOG.md
systest/mutations_test.go
worker/tokens.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1983)

Bug fix in eq with fulltext index

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1987)

Wiki: add doco for json mutations

---

posting/lists.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1999)

Don't let _dummy_ become visible outside transaction

---

client/README.md

I could have committed this directly, but I just wanted to make sure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/1899)

Remove reference to obsolete function.

---

dgraph/cmd/zero/raft.go
dgraph/cmd/zero/zero.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2020)

Fix race in replica count

---

posting/mvcc.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2025)

Send only the new keys

---

worker/tokens.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2028)

fix out of range error in ineqtokens

---

client/examples_test.go
contrib/integration/testtxn/main_test.go
contrib/scripts/loader.sh
contrib/tlstest/client_12.sh
contrib/tlstest/client_nocert.sh
contrib/tlstest/client_nopass.sh
contrib/tlstest/client_pass.sh
contrib/tlstest/server_11.sh
contrib/tlstest/server_nopass.sh
contrib/tlstest/server_nopass_client_auth.sh
contrib/tlstest/server_pass.sh
contrib/tlstest/server_reload.sh
dgraph/cmd/bulk/run.go
dgraph/cmd/live/run.go
dgraph/cmd/server/run_test.go
dgraph/cmd/zero/run.go
edgraph/config.go
query/query_test.go
systest/bulk_live_fixture_test.go
systest/cluster_setup.go
wiki/content/deploy/index.md
x/x.go

* gRPC-external: 5080
* http-external: 6080
These changes are part of #2042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2050)

New default ports for Dgraph Zero

---

wiki/content/deploy/index.md
wiki/content/get-started/index.md

Newbies who wants to get started needs to be aware of different node types and 
should know what a minimum setup would looks like inorder to correctly setup Dgraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2056)

Adding node definitions to getting started guide.

---

contrib/config/docker/docker-compose-ha.yml
contrib/config/docker/docker-compose-multi.yml
contrib/config/docker/docker-compose.yml

contrib/config has docker-compose files that are oftern referred by users.
Updated these compose files to reflect the new default ports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2064)

docker configuration files to reflect the new default ports.

---

posting/index.go
posting/index_test.go
posting/list.go
posting/lists.go
posting/mvcc.go
test
vendor/github.com/dgraph-io/badger/README.md
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/errors.go
vendor/github.com/dgraph-io/badger/iterator.go
vendor/github.com/dgraph-io/badger/managed_db.go
vendor/github.com/dgraph-io/badger/table/builder.go
vendor/github.com/dgraph-io/badger/table/iterator.go
vendor/github.com/dgraph-io/badger/table/table.go
vendor/github.com/dgraph-io/badger/transaction.go
vendor/github.com/dgraph-io/badger/value.go
vendor/github.com/dgraph-io/badger/y/file_dsync.go
vendor/github.com/dgraph-io/badger/y/file_nodsync.go
vendor/vendor.json
worker/mutation.go
worker/predicate.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2062)

vendor badger changes with purge

---

.gitignore

* github/gitignore for golang
* Ignore GoLand's project directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2078)

Standard gitignore for a golang project

---

contrib/config/kubernetes/dgraph-ha.yaml
contrib/config/kubernetes/dgraph-multi.yaml
contrib/config/kubernetes/dgraph-single.yaml
wiki/content/deploy/index.md
wiki/content/design-concepts/index.md

* updated manifest files to reflect new defaults
* removed XID reference as it is now not supported
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2077)

k8s manifest files are updated to reflect the new defaults.

---

wiki/content/design-concepts/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2104)

Removed section on transactions are unsupported

---

dgraph/cmd/zero/zero.go
dgraph/cmd/zero/zero_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2136)

RemoveNode should check if the node with Id exists

---

dgraph/cmd/server/run.go
query/recurse.go
query/shortest.go
x/config.go

https://github.com/dgraph-io/dgraph/issues/2174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2176)

add max_num_edge_limit flag

---

contrib/systemd/centos/README.md
contrib/systemd/centos/add_dgraph_account.sh
contrib/systemd/centos/dgraph-ui.service
contrib/systemd/centos/dgraph-zero.service
contrib/systemd/centos/dgraph.service

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2185)

contrib: system unit files and docs

---

posting/list.go
posting/list_test.go

Fixes #2182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2186)

Fix bug in syncifdirty

---

raftwal/wal.go

Fix #2156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2187)

Fix txntoobig error

---

worker/draft.go

Fix #2180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2189)

Run cleanPredicate and proposeKeyValues sequentially

---

dgraph/cmd/zero/raft.go
dgraph/cmd/zero/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2190)

WIP:Snapshot in goroutine and move groups logging to elog

---

dgraph/cmd/zero/zero.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2204)

serialize connect requests in zero

---

conn/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2223)

fix: set MyAddr when creating node

---

dgraph/cmd/live/batch.go
dgraph/cmd/zero/raft.go
dgraph/cmd/zero/tablet.go
dgraph/cmd/zero/zero.go
posting/mvcc.go
raftwal/wal.go
worker/draft.go
worker/groups.go
worker/predicate_move.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2235)

Bunch of updates to logging and snapshot

---

gql/parser.go

Tiny typo fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2234)

Typo: collon -> colon.

---

wiki/content/clients/index.md
wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2270)

Fixing some spelling mistakes in the docs

---

dgraph/cmd/server/dashboard.go

Fixes: [#2295](https://github.com/dgraph-io/dgraph/issues/2295)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2296)

Rename regex to regexp

---

dgraph/cmd/server/run.go
edgraph/config.go
wiki/content/deploy/index.md
wiki/content/get-started/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2315)

Change default to memorymap and update recommendation to one-third RAM in docs.

---

query/query_test.go
worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2317)

Allow filtering inside of list for lossy tokenizers

---

systest/mutations_test.go
types/geofilter.go
worker/task.go

Fixes https://github.com/dgraph-io/dgraph/issues/2271 for regexp
To be resolved:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2330)

Allow filtering inside of lists for regexp tokenizers

---

wiki/README.md
wiki/content/_index.md
wiki/content/deploy/index.md
wiki/content/design-concepts/index.md
wiki/content/faq/index.md
wiki/content/get-started/index.md
wiki/content/mutations/index.md

Also update README for docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2347)

Make docs work with latest version of Hugo

---

gql/parser.go
systest/mutations_test.go

Fixes #2355 and #2088.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2359)

Support GraphQL variables with filters.

---

query/aggregator.go
systest/mutations_test.go

Fixes #2362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2365)

Fix math >= evaluation.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2375)

Add unofficial clients to README

---

edgraph/nquads_from_json.go
edgraph/server_test.go

With JSON mutations, we previously couldn't distinguish an int from float, using the standard json.Unmarshal. Now, we use a json.Decoder, with `UseNumber`, which allows us to correctly distinguish int from float.
This fixes #2377 and #2378 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2398)

Ability to correctly distinguish float from int

---

contrib/integration/testtxn/main_test.go
edgraph/nquads_from_json.go
posting/lists.go
posting/mvcc.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2400)

Fix the build

---

worker/draft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2404)

Fix print format.

---

posting/index.go
posting/index_test.go
posting/list.go
posting/list_test.go
posting/mvcc.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2426)

Simplify Posting List

---

contrib/integration/bank/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2479)

Update bank test to follow Jepsen style testing

---

wiki/content/query-language/index.md

The Blank Node should be the same, for connecting <loc> and <name>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2507)

Corrected Geolocation docs for adding a Point

---

wiki/content/mutations/index.md

- Changed few notice notes.
- Add topic "Creating a list with JSON and interacting with"
- Add topic "JSON Syntax using Raw HTTP or Ratel UI".
- Add topic "Using JSON operations via cURL"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2512)

update the wiki

---

wiki/content/mutations/index.md

Mainly edits on top of Michel's changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2525)

Edits for wiki mutations page about JSON

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/issue--question.md

- Adding improvements to the Issues tracker system (altering some things). 
- With 4 issue templates.
- Ref: https://blog.github.com/2018-05-02-issue-template-improvements/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2535)

Update issue templates

---

dgraph/cmd/server/admin.go
dgraph/cmd/server/run.go
worker/draft.go
worker/groups.go
worker/worker.go

Ensure that we can gracefully shut down Dgraph server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2537)

Graceful shutdown of server

---

wiki/content/deploy/index.md

First draft. Looking for feedback.
I made two Metric/Description tables.
1. Badger/Dgraph metrics
2. Go metrics.
A couple of of metrics are unused in the code, and I'm not sure I've described all of them correctly.
I also wanted to give hints what the metrics can help explain, but have only been able to write one for `dgraph_evicted_lists_total` -> "A large number here could indicate a large posting list".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2551)

Add docs about prometheus metrics.

---

contrib/integration/share/share_test.go
contrib/integration/testtxn/main_test.go
contrib/scripts/loader.sh
dgraph/cmd/live/run.go
dgraph/cmd/server/http_test.go
dgraph/cmd/zero/oracle.go
dgraph/cmd/zero/telemetry.go
dgraph/docker-compose.yml
posting/list.go
posting/mvcc.go
posting/oracle.go
test.sh
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2556)

Decrease the number of aborts by using SPO for entity to entity connections.

---

edgraph/server.go
edgraph/server_test.go

Resolves #2500 and #2568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2579)

predicate and facetkeys validation

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2572)

Document sorting result count limitation

---

worker/task.go

Suggested by https://go-critic.github.io/overview#sloppyLen-ref
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2593)

worker: make "less than 1" check more self-explanatory

---

edgraph/nquads_from_json.go

Using type switch guard var makes it possible to remove
repetitive type assertions inside case clause bodies.
Found using https://go-critic.github.io/overview#typeSwitchVar-ref
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2592)

edgraph: simplify type switches by using bound type var

---

rdf/state.go
x/keys.go

Found using https://go-critic.github.io/overview#unslice-ref
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2588)

simplify s[:] to s where s is a slice

---

dgraph/cmd/bulk/count_index.go
dgraph/cmd/bulk/loader.go
dgraph/cmd/bulk/schema.go
dgraph/cmd/bulk/shuffle.go
dgraph/cmd/debug/run.go
edgraph/server.go
posting/list_test.go
posting/lists.go
posting/mvcc.go
query/query0_test.go
schema/parse_test.go
schema/schema.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/managed_db.go
vendor/github.com/dgraph-io/badger/options.go
vendor/github.com/dgraph-io/badger/transaction.go
vendor/github.com/dgraph-io/badger/value.go
vendor/vendor.json
worker/predicate.go
worker/predicate_test.go
worker/stream_lists.go
worker/stream_lists_test.go
worker/worker.go
x/badger.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2603)

Pull in Badger changes which remove ManagedDB.

---

dgraph/cmd/server/run.go
dgraph/cmd/zero/run.go
edgraph/config.go
edgraph/server.go
vendor/github.com/dgraph-io/badger/options.go
vendor/github.com/dgraph-io/badger/value.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2605)

Switch Badger Options to reasonable settings for p and w directories.

---

worker/export.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2614)

Switch traces to glogs in worker/export.go

---

README.md

In addition to the quick install `curl | bash` installation, this adds installation instructions for Docker and building from source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2626)

Update README with instructions for Docker and source installation

---

posting/mvcc.go
raftwal/storage.go
schema/schema.go
vendor/github.com/dgraph-io/badger/README.md
vendor/github.com/dgraph-io/badger/backup.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/dir_windows.go
vendor/github.com/dgraph-io/badger/errors.go
vendor/github.com/dgraph-io/badger/iterator.go
vendor/github.com/dgraph-io/badger/levels.go
vendor/github.com/dgraph-io/badger/managed_db.go
vendor/github.com/dgraph-io/badger/options.go
vendor/github.com/dgraph-io/badger/test.sh
vendor/github.com/dgraph-io/badger/transaction.go
vendor/github.com/dgraph-io/badger/value.go
vendor/github.com/dgraph-io/badger/y/watermark.go
vendor/github.com/dgraph-io/badger/y/y.go
vendor/vendor.json
worker/export.go
worker/predicate_move.go
xidmap/xidmap.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2634)

Bring in Badger v2.0-rc1

---

Makefile
dgraph/Makefile
vendor/vendor.json

First pass at global make file and dgraph binary make file.
Type `make help` for help.
Closes #2625
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2637)

Created make files for building binaries

---

posting/lists.go
wiki/content/deploy/index.md
x/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2636)

Rename memory metrics

---

wiki/content/clients/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2663)

Fix small typo in go client docs

---

conn/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2684)

Set Raft logging to higher log level for less log noise.

---

conn/node.go
contrib/integration/bank/main.go
contrib/integration/increment/main.go
contrib/integration/mutates/main.go
contrib/integration/swap/main.go
contrib/integration/testtxn/main_test.go
contrib/systemd/centos/dgraph.service
contrib/tlstest/server_11.sh
contrib/tlstest/server_nopass.sh
contrib/tlstest/server_nopass_client_auth.sh
contrib/tlstest/server_pass.sh
dgraph/cmd/alpha/run.go
dgraph/cmd/live/run.go
dgraph/cmd/zero/http.go
dgraph/cmd/zero/run.go
systest/cluster_test.go
systest/loader_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2674)

Rename Server to Alpha in favor of #2667

---

dgraph/cmd/live/run.go

Performed testing using the following steps:
1. The alpha server is started with the --auth_token option
2.a The live loader command is run _without_ any change of schema through the --schema option, then the --auth_token option is _not_ required, i.e. the rdf file can still be processed successfully without the --auth_token option
2.b The live loader command is run _with_ a schema change through the --schema option, then the --auth_token option _must_ be provided, otherwise the Alter gRPC call fails with an error complaining about missing the auth token
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2692)

Adding auth token support

---

posting/index.go
posting/index_test.go
query/common_test.go
query/mutation.go
worker/draft.go
worker/index.go
worker/mutation.go
worker/predicate.go
worker/predicate_test.go
worker/proposal.go
x/badger.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2695)

Add more logging for index rebuilds

---

contrib/config/kubernetes/dgraph-ha.yaml

Addresses #2698.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2703)

Set Kubernetes graceful shutdown timeout to 10 minutes.

---

posting/lists.go
wiki/content/deploy/index.md
x/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2714)

Rename lru cache metrics with a unified "dgraph_lru" prefix.

---

gql/parser.go
gql/parser_test.go

Fixes #2675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2711)

Forbidding duplicate query aliases

---

wiki/content/query-language/index.md

Should be possessive, not contractive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2720)

Fixed grammar

---

dgraph/cmd/alpha/run.go
dgraph/docker-compose.yml
edgraph/server.go
worker/draft.go
worker/mutation.go
worker/proposal.go

As the first priority, trace the mutation and proposal path. Already found an issue with latency (caused by unnecessary proposal retries), so this integration is already reaping results -- will fix that in the next PR.
Integrate with Jaeger. Can add more exporters over time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2739)

Integrate Open Census in Dgraph

---

worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2746)

Log when removing a tablet.

---

contrib/blockade/blockade.yml
contrib/blockade/main.go
contrib/integration/increment/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2751)

Integrate flaky, slow, stop and partition test cases

---

contrib/blockade/blockade.yml
contrib/blockade/run.sh

The run script is currently configured to run in TeamCity CI every night at 9 PM PST.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2756)

Add script to run blockade network partition tests.

---

gql/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2761)

Fix tiny typo

---

posting/index.go

Closes #2752.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2763)

Remove assert for zero-length posting lists.

---

README.md

The current link doesn't work, this should fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2774)

Fix link to help_wanted

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2785)

docs: Document /assign endpoint for uids and timestamps.

---

dgraph/cmd/alpha/admin.go
dgraph/cmd/root.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2788)

Enterprise features flag for Alpha

---

wiki/content/query-language/index.md

This PR adds sections to explain IRI usage in predicates and facets for internationalization (i18n) support.
Closes #2423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2792)

Documentation on IRI predicates and facets

---

CHANGELOG.md
wiki/scripts/build.sh

Work-in-progress before the official release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2787)

Update CHANGELOG for v1.0.11.

---

edgraph/nquads_from_json.go
edgraph/server.go
query/query.go
query/shortest.go
systest/mutations_test.go
types/facets/facet_types.go
types/facets/utils.go
worker/export.go
worker/task.go

- Removed the TryValFor function
- Simplified TypeIDFor and ValFor
- Converting facets to binary format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2797)

Validate and converting facets to binary

---

contrib/config/kubernetes/dgraph-ha.yaml

Minor fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2806)

Fix YML syntax error in Kube HA setup

---

dgraph/cmd/alpha/run_test.go
posting/index.go
schema/schema.go
systest/mutations_test.go
x/x.go

so that the acl_test.go can still succeed after other tests run DropAll requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2812)

Avoid dropping acl predicates for the drop all request

---

wiki/content/deploy/index.md

Add a section about viewing OpenCensus trace data with zPages and Jaeger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2841)

docs: Add tracing section.

---

posting/list.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2853)

Fix linter warnings in list.go

---

algo/uidlist.go
algo/uidlist_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2861)

Fix linter errors in algo/

---

posting/index.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2866)

Fix equality in needsCountIndexRebuild

---

.golangci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2865)

Add line length lt 100 check to linter

---

dgraph/cmd/bulk/chunk.go
dgraph/cmd/bulk/schema.go
dgraph/cmd/cert/cert.go
dgraph/cmd/conv/conv.go
query/math_test.go
query/query2_test.go
query/shortest.go
systest/mutations_test.go
types/sort.go
types/sort_test.go
worker/sort.go

This is to fix the warnings in the go report card.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2874)

Apply "gofmt -s" to all packages.

---

algo/uidlist_test.go
codec/benchmark/benchmark.go
dgraph/cmd/alpha/run_test.go
dgraph/cmd/zero/zero_test.go
ee/backup/systest/backup_test.go
query/aggregator.go
query/outputnode.go
schema/parse_test.go
systest/loader_test.go
systest/mutations_test.go
types/geofilter_test.go
worker/schema.go
worker/task.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2878)

Fix ineffassign warnings in dgraph.

---

README.md
wiki/content/clients/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2826)

Add alternative Elixir client to README and wiki page

---

systest/queries_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2903)

Test for multi-block var eval

---

query/outputnode.go
query/query.go
systest/queries_test.go

This PR changes the type of unset vars to default from float. This change fixes comparisons of unknown vars against a string value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2906)

Change unset vars to default

---

query/outputnode.go
query/query.go
systest/queries_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2909)

Conflict 2906

---

gql/parser.go
gql/parser_test.go
gql/state.go
query/query.go
query/query0_test.go
worker/task.go

This PR introduces the syntax pred@* which returns all the values of a
predicate which contain a language tag.
Fixes #2141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2910)

Allow querying all lang values of a predicate.

---

contrib/scripts/functions.sh
gql/parser.go
gql/parser_mutation.go
gql/parser_test.go
gql/state.go
lex/lexer.go
rdf/parse.go
rdf/state.go
schema/parse.go
schema/state.go

- added line and column number to lexer and items
- checking item error from lexer and return immediately when found
- enforcing 100 chars
fixes #2900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2914)

Fixes error found by gofuzz and reports line-column numbers for lexer/parser errors

---

wiki/content/mutations/index.md

Fixes #2419
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2919)

Add documentation for non-list predicate deletion.

---

wiki/content/query-language/index.md

Fixes #2141 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2920)

Documentation for <predicate>@* syntax.

---

dgraph/cmd/alpha/run.go
dgraph/cmd/alpha/run_test.go
systest/mutations_test.go
systest/queries_test.go
worker/config.go
worker/groups.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2924)

don't create ACL predicates when the ACL feature is not turned on

---

dgraph/cmd/alpha/run_test.go
gql/parser.go
gql/parser_test.go
query/common_test.go
query/query.go
query/query3_test.go
systest/mutations_test.go
systest/queries_test.go
worker/groups.go
x/x.go

type(typeName) is the equivalent of eq("type", typeName).
Also added the type predicate as one of the initial predicates
and made sure it does not get deleted when the schema is dropped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2933)

Add type function to allow querying types.

---

wiki/content/howto/index.md

matches should be commented
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2939)

docs: Fix code comment in How To section.

---

contrib/config/kubernetes/dgraph-ha.yaml
contrib/tlstest/openssl.cnf
ee/acl/run_ee.go
posting/index.go
query/math.go
wiki/content/deploy/index.md
wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2960)

Fix misspellings

---

conn/pool.go

I noticed there were some instances of locking in conn/pool.go that were
not using the "defer l.Unlock()" pattern so I changed them to use it for
consistency with the rest of the codebase. There was an instance where
the lock is acquired and released inside a for-loop so I didn't change
that one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2962)

Use defer statements to release locks.

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2965)

Fix mistake in docs

---

worker/backup_ee.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2973)

fixed bug with backup fan-out code

---

schema/schema.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2990)

Update outdated comment in DeleteAll.

---

vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2989)

Add opencensus deps to vendor using govendor

---

protos/Makefile
protos/depcheck.sh

This PR adds a script and a make command to check protobuf dependencies.
- New command 'make check' in proto dir.
- New script depcheck.sh that compares the minimum protoc version against the system version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2968)

New make command to check protoc deps

---

dgraph/cmd/alpha/run_test.go

I noticed TestDeleteScalarValue was flaky (was failing twice out of 100
times). I added logic to verify value can be queried before performing
any deletion. Ran the test 200 times and it didn't fail once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3007)

Fix flaky delete scalar test.

---

query/query.go

Closes #3006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3015)

Improve error of empty block queries

---

query/query.go
query/query3_test.go
query/shortest.go

This change adds a field _totalWeight_ to the first node of each path
showing the total weight of the path.
Addresses #2127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/2954)

Show total weight of path in shortest path algorithm.

---

dgraph/docker-compose.yml
ee/backup/systest/docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3014)

Use more readable CIDR format for whitelists.

---

wiki/content/query-language/index.md

Improve the Inequality syntax example and add a GraphQL var example for array.
related to https://github.com/dgraph-io/dgraph/pull/2981
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3016)

Wiki: Improve the Inequality and GraphQL Var examples.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3035)

Fix client libraries information in README

---

wiki/content/clients/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3044)

Docs for new /commit endpoint format.

---

wiki/content/design-concepts/index.md
wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3040)

Updates Queries Design.

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3036)

CHANGELOG: Add link to issues

---

systest/21million/test-21million.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3058)

Fix typo in test-21million.sh

---

wiki/content/query-language/index.md

#3068 - Fixed and resubmitted with email for licence checks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3070)

Issue 3068: Added missing parenthesis to uid_in docs

---

contrib/compose/main.go

Features supported right now:
* number of zeros in cluster
* number of alphas
* number of groups
* lru size
* enterprise features on or off
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3075)

compose tool

---

dgraph/run.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3082)

Stop if compilation fails

---

dgraph/cmd/bulk/loader.go
dgraph/cmd/bulk/run.go
x/file.go

Don't blindly replace the bulk out directory if it already exists and contains data. Fixes #3034.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3089)

Add --replace_out option to bulk command.

---

ristretto/cache.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3104)

Add interface Cache to ristretto package

---

chunker/chunk.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3106)

Fix error to print string instead of character in live loader

---

wiki/content/query-language/index.md

Hold this if we gonna have a cut and update in Play Dgraph. So I can test again and fix the UIDs after release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3039)

Fix UIDs in Docs

---

.gitignore
wiki/content/deploy/index.md

Related to https://github.com/dgraph-io/dgraph/commit/87c36746b456e440560d39f467b1e48eeb5beef7
and https://github.com/dgraph-io/dgraph/commit/bcc7796d935795873030664c8e9edeb4a82545ef
and https://github.com/dgraph-io/dgraph/issues/3011
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3099)

Docs: Changes in Liveloader and Bulk.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3131)

- update readme to make 2 words clearer.

---

query/common_test.go
query/query0_test.go
query/query1_test.go

Related to #3150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3168)

Add test to verify results are not flattened by default.

---

ee/acl/acl_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3177)

Adding sleeping time after dropall to clear previous ACL rules

---

wiki/content/query-language/index.md

close #3174
Please delete the branch after all done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3176)

Docs: Fix Password typo and update it.

---

wiki/content/query-language/index.md

Fixes #3162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3167)

Improve documentation for recurse loop parameter.

---

contrib/blockade/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3180)

Blockade test for best effort queries

---

edgraph/acl_cache_test.go
gql/parser.go
schema/parse_test.go
schema/schema.go
worker/export.go
z/exec.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3145)

Fix errors reported by "gofmt -s"

---

dgraph/cmd/alpha/run.go
schema/schema.go
x/file.go
xidmap/xidmap.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3146)

Fix warnings reported by "go lint"

---

wiki/content/clients/index.md

Fixes #3159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3165)

Improve documentation on read-only transactions.

---

contrib/release.sh
protos/Makefile
protos/pb/pb.pb.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3189)

Update protos, proto regeneration Makefile, and release script.

---

worker/backup.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3195)

Fix Backup() sig for OSS version

---

ee/acl/acl_curl_test.go

An issue was introduced in #3147, since updating the accessJwt variable is required for subsequent steps to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3206)

Fix ACL test failure introduced in #3147

---

dgraph/cmd/alpha/run_test.go
ee/acl/acl.go
ee/acl/utils.go
query/common_test.go
query/query.go
schema/schema.go
systest/mutations_test.go
systest/queries_test.go
x/keys.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3204)

Rename type predicate to dgraph.type

---

conn/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3216)

Remove an unnecessary warning log

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3213)

Add section about language tags in JSON mutations to documentation.

---

query/common_test.go
query/query_facets_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3215)

Change query tests to use standard lang RDF syntax

---

dgraph/cmd/counter/increment_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3241)

Fix the flaky TestIncrement by removing the timestamp check

---

ee/backup/backup.env
ee/backup/docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3233)

Add basic minio setup to backup docker-compose file

---

compose/compose.go
ee/backup/docker-compose.yml

Minor change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3248)

Add UID reminder to generated compose files.

---

wiki/content/enterprise-features/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3244)

Using the ACL over TLS as the sample code

---

dgraph/docker-compose.yml

--enterprise_features is not a valid zero flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3247)

Remove invalid flag from docker-compose file.

---

dgraph/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3259)

Change make install to use sha256sum instead of md5sum.

---

Makefile
dgraph/Makefile

by turning off the compiler optimizations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3260)

Add a make command to install the dgraph binary for dlv debugging

---

contrib/scripts/load-test.sh

Minor change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3274)

Reduce required memory.

---

edgraph/access_ee.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3256)

Using read-only queries for ACL refreshes

---

dgraph/cmd/bulk/shuffle.go

#3276 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3283)

Add comments, use defer instead in bulk loader

---

edgraph/access_ee.go
edgraph/server.go
x/metrics.go

This reverts commit 4f9bf94add87d85b36d298f0dbf5ef9ac2dd9876.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3286)

Revert "UpsertSpan so successful ACL accesses are sent to Jaeger"

---

ee/backup/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3289)

Fix accidental rename.

---

systest/posting-list-benchmark/main.go

This tool adds a bunch of triples with the same predicate and object and creates a full-text index on the predicate. This should generate very large posting lists, allowing us to measure their performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3294)

Tool to benchmark posting list performance.

---

vendor/github.com/dgraph-io/dgo/protos/api/api.pb.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3298)

Vendor dgo changes.

---

compose/compose.go

Allow creating a docker-compose.yml with a different zero offset. Other minor changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3293)

Compose tool offset

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3296)

Documentation for type system.

---

compose/compose.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3303)

Run go fmt on master.

---

systest/mutations_test.go
systest/posting-list-benchmark/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3304)

Fix ineffassign warnings.

---

systest/21million/run_test.go
systest/21million/test-21million.sh

Change summary:
* Add a --quiet flag that skips showing the diff when query results differ. Makes it easier to see a summary of all query results.
* Add a query timeout to minimize wasted time waiting if dgraph doesn't respond.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3282)

Add --quiet flag and timeout to test-21million.sh

---

worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3312)

Merge cases in handleUidPostings since their bodies are the same.

---

wiki/content/clients/index.md

Closes #3236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3302)

Document DropData operation.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3315)

Add VMware Purser to list of projects using Dgraph in README.

---

dgraph/cmd/debug/run.go
posting/list.go
posting/list_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3330)

Run gofmt -s -w on codebase.

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3332)

Add section on how to delete type definitions.

---

contrib/jepsen/main.go
dgraph/cmd/debug/run.go
dgraph/cmd/live/run.go
posting/list.go
posting/list_test.go
x/file.go
z/client.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3331)

Fix golint warnings

---

wiki/content/clients/index.md

Fixes https://github.com/dgraph-io/dgo/issues/58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3344)

Add section on how to Mutate in dgo using RDF triples.

---

query/outputnode.go
query/outputnode_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3350)

Fix typo in outputnode.go

---

dgraph/docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3342)

Rename services in default docker-compose.yml to match names in compose tool

---

vendor/github.com/dgraph-io/badger/README.md
vendor/github.com/dgraph-io/badger/compaction.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/histogram.go
vendor/github.com/dgraph-io/badger/iterator.go
vendor/github.com/dgraph-io/badger/levels.go
vendor/github.com/dgraph-io/badger/options.go
vendor/github.com/dgraph-io/badger/table/table.go
vendor/github.com/dgraph-io/badger/value.go
vendor/github.com/dgraph-io/badger/y/watermark.go
vendor/github.com/dgraph-io/badger/y/y.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3347)

Vendor in latest badger with nil pointer dereference fix.

---

worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3356)

Initialize tablets map when creating a group.

---

worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3360)

Initialize tablets map when creating a group. (#3356)

---

worker/docker-compose.yml
worker/snapshot_test.go
z/client.go

- Retry mutations when transaction is aborted.
- Retrieve all the values and do the sum in the test instead of relying
on the sum function inside Dgraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3355)

Fix flakiness in snapshot_test.

---

vendor/github.com/dgraph-io/badger/batch.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/iterator.go
vendor/github.com/dgraph-io/badger/levels.go
vendor/github.com/dgraph-io/badger/value.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3371)

release/v1.0: Vendor in latest bug fixes from badger.

---

dgraph/cmd/debug/wal.go
systest/21million/run_test.go
worker/export.go
worker/snapshot_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3373)

Fix warnings in golang health report.

---

dgraph/cmd/bulk/schema.go
dgraph/cmd/bulk/systest/test-bulk-schema.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3380)

Fix test-bulk-schema.sh

---

worker/docker-compose.yml

Add whitelist to worker test  docker-compose file so that admin url requests are not rejected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3384)

Fix export format test

---

worker/docker-compose.yml
worker/snapshot_test.go

Now that the frequency of snapshots can be configured, the snapshot test
can be reduced in size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3378)

Decrease size of snaphsot test.

---

contrib/scripts/functions.sh
dgraph/cmd/live/load-json/load_test.go
dgraph/cmd/live/load-uids/load_test.go
dgraph/docker-compose.yml
z/client.go

The compose tool generates configs where the zero ports ar offset by
100. This change modifies the default docker-compose config to match
this convention.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3385)

Offset zero ports in default docker-compose.yml by 100.

---

tlstest/certrequest/certrequest_test.go
z/client.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3362)

Fixed one test and checking of the failure messages

---

vendor/github.com/dgraph-io/badger/batch.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/iterator.go
vendor/github.com/dgraph-io/badger/levels.go
vendor/github.com/dgraph-io/badger/value.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3369)

Vendor in latest bug fixes from badger.

---

z/docker.go

Backup tests will need this method to retrieve backup results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3390)

Add DockerCp to docker util functions.

---

z/docker.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3395)

Add DockerExec test util function.

---

x/keys.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3396)

Fix gofmt warnings.

---

ee/backup/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3407)

Fix golint warnings in ee/backup package.

---

dgraph/cmd/migrate/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3414)

adding migration tool docs

---

ee/backup/run.go
vendor/github.com/dgraph-io/badger/backup.go
vendor/github.com/dgraph-io/badger/batch.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/levels.go
vendor/github.com/dgraph-io/badger/logger.go
vendor/github.com/dgraph-io/badger/merge.go
vendor/github.com/dgraph-io/badger/options.go
vendor/github.com/dgraph-io/badger/stream.go
vendor/github.com/dgraph-io/badger/table/table.go
vendor/github.com/dgraph-io/badger/txn.go
vendor/github.com/dgraph-io/badger/value.go
vendor/github.com/dgraph-io/badger/y/y.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3416)

release/v1.0: Vendor in badger optimization for LoadToRAM option.

---

.golangci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3419)

Add more checks to golangci config.

---

.github/CODEOWNERS

@MichaelJCompton This PR adds your name to the CODEOWNERS file for /wiki/. This automatically requests you to review PRs related to https://docs.dgraph.io which is stored in the wiki directory.
For more info about CODEOWNERS, see: https://help.github.com/en/articles/about-code-owners
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3421)

Add Michael to docs code reviews.

---

conn/node.go
conn/pool.go
conn/raft_server.go
dgraph/cmd/zero/raft.go
dgraph/cmd/zero/zero.go
query/query.go
worker/draft.go
worker/groups.go
worker/proposal.go
worker/task.go

- Unexport some variables and types that were not needed outside the
package.
- Add doc comments to exported types and vars.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3413)

Fix golint warnings in package conn.

---

wiki/content/clients/index.md

Also remove references to Dgraph v0.9 since it's fairly old at this
point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3423)

Add explicit definition of what a transaction is.

---

worker/export.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3426)

Rename jsonString function to better convey its purpose.

---

dgraph/cmd/zero/oracle.go

Currently, we pass a pointer to a delta to a channel and then set the
group checksums. This results in a race condition because the pointer
is sent to multiple channels. This change changes the channel to send
a delta instead of a pointer. This should fix this particular race
condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3417)

Fix race condition in oracle.go

---

dgraph/cmd/counter/increment.go

Add query, mutation and total txn latency numbers to increment tool.
Set `CommitNow` to be true in mutation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3422)

Add latency numbers to increment tool

---

compose/compose.go
contrib/config/datadog/docker-compose.yml
dgraph/cmd/alpha/run.go
dgraph/cmd/zero/run.go
vendor/github.com/DataDog/datadog-go/LICENSE.txt
vendor/github.com/DataDog/datadog-go/statsd/README.md
vendor/github.com/DataDog/datadog-go/statsd/options.go
vendor/github.com/DataDog/datadog-go/statsd/statsd.go
vendor/github.com/DataDog/datadog-go/statsd/udp.go
vendor/github.com/DataDog/datadog-go/statsd/uds.go
vendor/github.com/DataDog/datadog-go/statsd/uds_async.go
vendor/github.com/DataDog/datadog-go/statsd/uds_blocking.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/LICENSE
vendor/github.com/DataDog/opencensus-go-exporter-datadog/LICENSE-3rdparty.csv
vendor/github.com/DataDog/opencensus-go-exporter-datadog/NOTICE
vendor/github.com/DataDog/opencensus-go-exporter-datadog/README.md
vendor/github.com/DataDog/opencensus-go-exporter-datadog/datadog.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/doc.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/errors.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/msgpack.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/msgpack_gen.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/sampler.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/span.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/stats.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/trace.go
vendor/github.com/DataDog/opencensus-go-exporter-datadog/transport.go
vendor/vendor.json
x/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3428)

Adding datadog trace collector

---

test.sh

This fixes the issues in TeamCity due to the -c flag not being present
in the version of test.sh in this branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3453)

Cherry pick updated test.sh into release/v1.0 branch.

---

worker/aggregator.go
worker/compare.go
worker/export.go
worker/groups.go
worker/stringfilter.go
worker/task.go
worker/tokens.go
worker/worker.go

Added comments and unexported variable and methods that didn't need to
be exported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3451)

Fix golint warnings in worker package.

---

z/client.go
z/json.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3405)

Fix golint warnings in package z.

---

vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/errors.go
vendor/github.com/dgraph-io/badger/publisher.go
vendor/github.com/dgraph-io/badger/stream_writer.go
vendor/github.com/dgraph-io/badger/value.go
vendor/vendor.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3460)

release/v1.0: Vendor in latest badger with bug fix for StreamWriter.

---

ee/backup/tests/filesystem/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3456)

Add test for the force full backup feature.

---

dgraph/cmd/alpha/run_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3465)

Run go fmt ./... on master

---

dgraph/docker-compose.yml
dgraph/minio.env
z/minio.go
z/minio_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3459)

Add basic test utils for creating minio clients.

---

ee/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3484)

Add link to Dgraph Community License

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3488)

Typo in query doc. s/performance,character/performance.character/

---

wiki/content/mutations/index.md

The documentation should state clearly that a node needs to have its
type information properly setup in order for the delete operation to
properly select the correct predicates to try for deletion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3489)

Include clarification about "S * *" deletion syntax.

---

dgraph/cmd/alpha/run.go
query/outputnode.go
query/outputnode_test.go
x/config.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3490)

Allow the normalize limit to be changed via a flag.

---

query/outputnode_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3491)

Fix default value for NormalizeNodeLimit param in tests.

---

types/compare.go
types/conversion.go
types/facets/facet_types.go
types/facets/utils.go
types/password.go
types/s2index.go
types/scalar_types.go
types/sort.go

Add comments to unexported methods, types, and variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3452)

Fix golint warnings in types package.

---

dgraph/cmd/bulk/reduce.go
dgraph/cmd/bulk/schema.go
posting/mvcc.go
posting/writer.go
vendor/github.com/dgraph-io/badger/backup.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/errors.go
vendor/github.com/dgraph-io/badger/merge.go
vendor/github.com/dgraph-io/badger/publisher.go
vendor/github.com/dgraph-io/badger/stream_writer.go
vendor/github.com/dgraph-io/badger/structs.go
vendor/github.com/dgraph-io/badger/txn.go
vendor/github.com/dgraph-io/badger/value.go
vendor/vendor.json
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3502)

 Bring in latest changes from badger and fix broken API calls

---

dgraph/cmd/migrate/datatype.go
dgraph/cmd/migrate/dump.go
dgraph/cmd/migrate/table_guide.go
dgraph/cmd/migrate/table_info.go
dgraph/cmd/migrate/utils.go
types/scalar_types.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3480)

migration-tool: remove cell values under the foreign key columns

---

systest/group-delete/group_delete_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3507)

Fix ineff assign in group_delete_test.go

---

chunker/json/parse.go
chunker/rdf/parse.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3508)

Fix golint warnings in chunker package.

---

dgraph/cmd/zero/zero.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3516)

Fix tautological condition in zero.go

---

chunker/rdf/parse.go
chunker/rdf/state.go
contrib/embargo/main.go
dgraph/cmd/live/batch.go
dgraph/cmd/live/run.go
dgraph/cmd/zero/raft.go
gql/parser.go
gql/state.go
query/groupby.go
worker/draft.go

Removed unused vars, fields, and functions except for those meant to be
used for testing or debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3521)

Fix unused warnings.

---

chunker/json/parse.go
compose/compose.go
dgraph/cmd/alpha/run.go
dgraph/cmd/bulk/reduce.go
dgraph/cmd/bulk/shuffle.go
dgraph/cmd/cert/info.go
dgraph/cmd/conv/conv.go
dgraph/cmd/migrate/run.go
dgraph/cmd/zero/run.go
dgraph/cmd/zero/tablet.go
lex/lexer.go
query/recurse.go
task/conversion.go
worker/groups.go
worker/stringfilter.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3519)

Fix gosimple warnings.

---

chunker/json/parse.go
x/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3534)

Fix leftover lll and gosimple warnings.

---

dgraph/cmd/alpha/http.go
dgraph/cmd/alpha/http_test.go
wiki/content/clients/index.md
wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3509)

Fix docs and add test for aborting a txn

---

dgraph/cmd/alpha/http_test.go
dgraph/cmd/alpha/run.go
wiki/content/clients/index.md
wiki/content/deploy/index.md

Related to #3496 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3526)

Update /health endpoint to return version of alpha

---

contrib/integration/bank/main.go
contrib/scripts/goldendata-queries.sh
contrib/scripts/loader.sh
dgraph/cmd/bulk/systest/test-bulk-schema.sh
systest/21million/test-21million.sh

* Test cluster Zero port runs on 5180.
* HTTP API queries require Content-Type header.
* Update test using S * * deletion to using S P V deletion since S * * only works with the type system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3556)

Fix CI full test suite on master.

---

contrib/integration/acctupsert/main.go
contrib/integration/bank/main.go
contrib/integration/bigdata/main.go
contrib/integration/swap/main.go
dgraph/cmd/alpha/dashboard.go
dgraph/cmd/alpha/http.go
dgraph/cmd/conv/run.go
dgraph/cmd/live/run.go
dgraph/cmd/root.go
dgraph/cmd/zero/oracle.go
dgraph/cmd/zero/raft.go
gql/parser.go
worker/draft.go
worker/groups.go
worker/mutation.go
worker/task.go
worker/worker.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3548)

Fix errcheck warnings.

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3552)

External ids and the new upsert transaction.

---

worker/draft.go
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3564)

Simplify the updateSchema function

---

ee/backup/handler.go
ee/backup/handler_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3569)

Add unit tests to verify filterManifests method.

---

query/common_test.go
query/query.go
query/query1_test.go

This fixes #3470.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3554)

Cherry pick fix for the panic in fillVars into release/v1.0 branch

---

ee/acl/acl_curl_test.go
tlstest/certrequest/certrequest_test.go
tlstest/certrequireandverify/certrequireandverify_test.go
tlstest/certverifyifgiven/certverifyifgiven_test.go
z/client.go
z/json.go
z/zero.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3563)

Fix more golint warnings in the z package.

---

dgraph/cmd/zero/oracle.go
dgraph/cmd/zero/run.go
dgraph/cmd/zero/telemetry.go
dgraph/cmd/zero/zero.go
worker/draft.go
worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3562)

Fix more golint warnings in the zero package.

---

schema/schema.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3577)

Fix golint warnings in the schema package.

---

dgraph/cmd/bulk/loader.go
gql/state.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3576)

Fix ineffassign and unused warnings.

---

raftwal/storage.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3579)

Fix golint warnings for the raftwal package.

---

task/conversion.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3581)

Fix golint warnings in task package.

---

dgraph/cmd/debug/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3580)

Fix golint warnings in the debug package.

---

contrib/integration/testtxn/main_test.go
ee/backup/handler_test.go
ee/backup/tests/filesystem/backup_test.go
ee/backup/tests/minio/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3578)

Fix more ineffassign warnings.

---

x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3574)

Fix more golint warnings in the x package.

---

worker/export.go
worker/mutation.go
worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3561)

Fix more golint warnings in worker package.

---

task/conversion.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3588)

Run gofmt on master.

---

compose/compose.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3589)

Fix golint warnings in compose tool.

---

dgraph/cmd/bulk/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3591)

Fix golint warnings in bulk package.

---

dgraph/cmd/alpha/run.go
dgraph/cmd/cert/run.go
dgraph/cmd/conv/run.go
dgraph/cmd/live/run.go
dgraph/cmd/migrate/run.go
dgraph/cmd/version/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3593)

Fix golint warnings regarding subcommands.

---

query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3592)

Fix more golint warnings in the query package.

---

codec/codec.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3590)

Fix golint warnings in codec package.

---

posting/list.go
posting/lists.go
posting/mvcc.go
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3595)

Fix more golint warnings in the posting package.

---

dgraph/cmd/counter/increment.go
task/conversion.go

Fixes #3568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3584)

Add flag to specify number of retries when setting up the gRPC connection.

---

contrib/jepsen/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3596)

Fix golint warnings in jepsen tool.

---

gql/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3597)

Remove unused createEdge function.

---

wiki/content/howto/index.md
wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3585)

Update docs for Upsert Block

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3599)

Upsert Transaction -> Upsert Block

---

contrib/integration/bank/main.go
contrib/integration/mutates/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3603)

Fix golint warnings in integration directory.

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3608)

Fix doc for Upsert Block

---

ee/acl/acl.go
ee/acl/utils.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3602)

Fix golint warnings in the ACL package.

---

dgraph/cmd/migrate/datatype.go
dgraph/cmd/migrate/dump.go
dgraph/cmd/migrate/table_guide.go
dgraph/cmd/migrate/table_info.go
dgraph/cmd/migrate/utils.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3613)

Fix golint warnings in the migrate package.

---

dgraph/cmd/live/batch.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3616)

Remove unused error in live/batch.go

---

tok/tok.go
tok/tokens.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3615)

Fix golint warnings in the tok package.

---

x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3614)

More golint fixes for the x package.

---

dgraph/cmd/counter/increment_test.go

Fix flaky test in release/v1.0 branch's CI full test suite with the same fix from #3241.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3632)

release/v1.0: Cherrypick fix for TestIncrement.

---

gql/math.go
gql/mutation.go
gql/parser.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3639)

Fix golint warnings in the gql package.

---

wiki/content/faq/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3644)

Point the product roadmap link to the 2019 issue

---

wiki/content/faq/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3647)

Point the product roadmap link to the 2019 issue (#3644)

---

x/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3641)

Fix golint warnings in x/metrics.go file.

---

lex/iri.go
lex/lexer.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3654)

Fix warnings in the lex package.

---

codec/decoderversion.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3650)

Fix glog in init bug casued by #3527

---

x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3655)

Fix more errcheck warnings.

---

dgraph/cmd/bulk/count_index.go

Fixes: #3607 
Signed-off-by: பாலாஜி ஜின்னா <balaji@dgraph.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3649)

Set user meta 

---

compose/compose.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3683)

In the compose tool, make each alpha use the raftId corresponding to its name

---

posting/index.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3696)

Add log prefix to stream used to rebuild indices.

---

dgraph/cmd/bulk/count_index.go
dgraph/cmd/bulk/reduce.go
worker/export.go

This reverts commit a1e36819367577cf4b898d01163d3fea3a54f113.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3704)

Revert "fix race conditions in bulk loader and export (#3697)"

---

posting/index.go
posting/index_test.go
posting/lists.go
posting/oracle.go

Fixes #3594
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3703)

Add documentation for LocalCache.Set method.

---

gql/fuzz-data/corpus/test004.in
gql/fuzz-data/corpus/test005.in
gql/fuzz-data/corpus/test006.in
gql/fuzz-data/corpus/test007.in

I ran the tests with a couple of failures but none of them were related to the queries that are being changed by this PR.
Fixes #3389
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3712)

Remove mentions of _predicate_ from fuzz data.

---

chunker/json/parse.go

Change tryParseAsGeo to reduce indentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3672)

Clean up JSON geolocation logic.

---

wiki/content/query-language/index.md

Fixes #3718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3720)

Add documentation on type queries.

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3722)

Clarify both uid and literal edges are deleted in JSON "S * *" syntax.

---

.golangci.yml
gql/math.go
gql/parser.go
z/exec.go

- Fix config file to exclude issues like "type Uid should be UID".
- Remove unused warnings for a few functions that are meant for
debugging.
- Fix a few unadressed warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3729)

Fix more golangci issues.

---

wiki/content/faq/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3739)

Fixed bad link for export-database in FAQ

---

dgraph/cmd/alpha/run.go
edgraph/config.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3734)

Security fix: prevent the HmacSecret from being logged

---

wiki/content/enterprise-features/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3660)

Add more documentation for backup and restore features.

---

gql/parser_mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3760)

use Item.Errorf to report errors that include line and column numbers.

---

dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/gqlschema_test.yml
dgraph/cmd/graphql/schema/rules.go
dgraph/cmd/graphql/schema/schemagen.go

Split the validation rules into pre gql validation and post gql validation rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3777)

Seperate pre and post gql validation

---

test.sh

This takes advantage of TeamCity's Go test integration.
https://blog.jetbrains.com/teamcity/2019/08/building-go-programs-in-teamcity/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3775)

Use go test -json when running tests in TeamCity.

---

vendor/github.com/dgraph-io/badger/backup.go
vendor/github.com/dgraph-io/badger/batch.go
vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/levels.go
vendor/github.com/dgraph-io/badger/managed_db.go
vendor/github.com/dgraph-io/badger/manifest.go
vendor/github.com/dgraph-io/badger/stream_writer.go
vendor/github.com/dgraph-io/badger/structs.go
vendor/github.com/dgraph-io/badger/table/builder.go
vendor/github.com/dgraph-io/badger/table/iterator.go
vendor/github.com/dgraph-io/badger/table/table.go
vendor/github.com/dgraph-io/badger/value.go
vendor/github.com/dgraph-io/badger/y/y.go
vendor/vendor.json

Update badger in dgraph using `govendor fetch github.com/dgraph-io/badger/...`.
This is the **Latest Master** version of badger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3784)

Vendor latest badger

---

edgraph/server.go
posting/list.go
posting/list_test.go
types/s2.go
worker/task.go

- Remove query cache which is causing contention.
- Make geo filtering execute in parallel.
- Fix up convertGeom to also take geometries, not just coordinates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3805)

Various optimizations for Geo queries

---

systest/21million/queries/query-044

Changed the recursive query test to one where all the results are sorted by name.
In #3809 we add the same query to the "tips and tricks" section since this sort-by-nested-edge query is not obvious.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3810)

tests: Fix flaky 21-million query.

---

dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/schemagen.go
dgraph/cmd/graphql/schema/schemagen_test.yml
dgraph/cmd/graphql/schema/testdata/output/schema1

schemaHandler now stores definitons, in order in which they are specified in schemaDocument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3798)

modify schemahandler

---

dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/rules.go
dgraph/cmd/graphql/schema/schemagen.go
dgraph/cmd/graphql/schema/schemagen_test.yml
dgraph/cmd/graphql/schema/testdata/output/schema1

Refactor how the GraphQL validation rules are called - moves from each rule looping through whole schema to one loop through schema and rules being applied at the right points.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3797)

Change validation infra

---

dgraph/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3786)

Print commit SHA256 when invoking "make install"

---

gql/parser.go
query/query0_test.go

This fixes #3814.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3837)

Bugfix: Reset alias after assigning it to UidCountAlias

---

vendor/golang.org/x/crypto/openpgp/canonical_text.go
vendor/golang.org/x/crypto/openpgp/keys.go
vendor/golang.org/x/crypto/openpgp/read.go
vendor/golang.org/x/crypto/openpgp/write.go
vendor/vendor.json
wiki/content/deploy/index.md
wiki/content/enterprise-features/index.md

Mention about the changes and remove references to `--enterprise_features` flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3842)

Update docs about enterprise features to mention the new change.

---

dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/gqlschema_test.yml
dgraph/cmd/graphql/schema/rules.go
dgraph/cmd/graphql/schema/schemagen.go
dgraph/cmd/graphql/schema/schemagen_test.go
dgraph/cmd/graphql/schema/testdata/input/schema2
dgraph/cmd/graphql/schema/testdata/output/schema1
dgraph/cmd/graphql/schema/testdata/output/schema2

Add support for @hasInverse directive and tests around it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3812)

graphql directives

---

dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/testdata/output/schema1
dgraph/cmd/graphql/schema/testdata/output/schema2

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3852)

remove some non-nullables for better GQL schema

---

dgraph/cmd/graphql/run.go
dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/rules.go
dgraph/cmd/graphql/schema/schemagen.go
dgraph/cmd/graphql/schema/schemagen_test.go

Just some light refactoring around how we process the input schema.  Notes in line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3863)

GraphQL schema processing refactor

---

dgraph/cmd/zero/telemetry.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3872)

Change telemetry endpoint

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3891)

Update CHANGELOG for v1.0.17.

---

dgraph/cmd/zero/raft.go
worker/draft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3901)

Change warning time

---

wiki/content/howto/index.md
wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3856)

Add docs for upsert

---

dgraph/cmd/alpha/admin.go
dgraph/cmd/alpha/http_test.go
dgraph/cmd/alpha/run.go
edgraph/access.go
edgraph/access_ee.go
x/health.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3880)

adding the draining mode

---

vendor/github.com/dgraph-io/badger/db.go
vendor/github.com/dgraph-io/badger/go.mod
vendor/github.com/dgraph-io/badger/go.sum
vendor/github.com/dgraph-io/badger/txn.go
vendor/github.com/dgraph-io/badger/value.go
vendor/github.com/dgraph-io/ristretto/z/bbloom.go
vendor/github.com/dgraph-io/ristretto/z/rtutil.go
vendor/github.com/dgraph-io/ristretto/z/z.go
vendor/vendor.json

This change vendors in the latest Badger to bring in the vlog data format change made in https://github.com/dgraph-io/badger/commit/fbcd608981982d2d8c1612d310ac491d01dbde96. **This is a breaking change**: Clusters running v1.1.0-rc3 or latest master must export/re-import the data into a new cluster as outlined in the [Upgrade Database docs](https://docs.dgraph.io/deploy/#upgrade-database).
Full Badger changelist between vendored versions:
https://github.com/dgraph-io/badger/compare/398445a29fa79e38366ae4f29da1ba133778ff25...fbcd608981982d2d8c1612d310ac491d01dbde96
* Vendor in latest Badger
* Vendor in latest ristretto/z package (dependency of Badger)
--- …

Breaking change: Vendor in latest Badger with data-format changes.

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3907)

Add clarification on interaction between type system and reverse edges

---

CHANGELOG.md

Update CHANGELOG.md with all the changes in the latest master up to https://github.com/dgraph-io/dgraph/commit/f437d0161cb7ad045e314027ef6654af66fb8256.
* Highlight the breaking changes between v1.0 and v1.1 at the top of the changelog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3911)

Update CHANGELOG for Dgraph v1.1.0.

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3914)

Set the v1.1.0 as the latest docs

---

codec/codec.go
dgraph/cmd/zero/pgp_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3917)

Fix misspell and ineffassign warnings.

---

dgraph/cmd/alpha/metrics_test.go
wiki/content/deploy/index.md

This test checks and ensures that the essential metrics exist in the prometheus_metrics page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3908)

Adding test to ensure the required metrics exist in the metrics page

---

wiki/content/enterprise-features/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3915)

Fix docs (minor changes)

---

README.md

This is just a quick update to the README so that people who want to find out what's on the roadmap will be directed to the 2019 roadmap instead of the 2015 one (which is completed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3923)

Update roadmap link.

---

schema/parse.go
schema/parse_test.go

Fixes #3924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3925)

Verify type definitions do not have duplicate fields.

---

wiki/content/clients/index.md

Updating documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3930)

Update docs about Dgo client

---

dgraph/cmd/graphql/schema/schemagen.go
dgraph/cmd/graphql/schema/schemagen_test.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3941)

fix list bug

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3933)

Docs site: moved master to below latest

---

README.md

Update the Status subheading which is part of README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3944)

Update README to mention v1.1.x

---

dgraph/cmd/bulk/mapper.go
dgraph/cmd/live/run.go
xidmap/xidmap.go
xidmap/xidmap_test.go

Fixes https://github.com/dgraph-io/dgraph/issues/3922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3950)

Fix bulk loader store_xids issue

---

chunker/json_parser.go
chunker/json_parser_test.go
dgraph/cmd/alpha/upsert_test.go

This lets the user to use val function inside a JSON format upsert.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3947)

Added Val support for JSON

---

.github/CODEOWNERS

Signed-off-by: பாலாஜி ஜின்னா <balaji@dgraph.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3980)

Add pawan as code owner for query package

---

wiki/content/query-language/index.md

Also includes a few formatting changes to better fit the paragraphs but
no changes in the text are included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3995)

Move type docs into its own section.

---

query/groupby.go
query/outputnode.go
query/query.go
query/shortest.go

- Format all documentation for the fields in params in the standard
golang way.
- Add documentation to the few fields that didn't have it.
- All fields in params start with an uppercase now for consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3976)

Minor fixes to query params.

---

chunker/rdf_state.go
dgraph/cmd/alpha/upsert_test.go
dgraph/cmd/zero/pgp.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4000)

fix ineffassing and spelling warnings.

---

gql/parser.go
gql/parser_test.go

Fixes #3974 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3975)

Allow @type directive in the query root.

---

ee/acl/acl.go

Fixes #3966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3990)

Call cancel function only if err is not nil

---

wiki/scripts/build.sh

See discussion at 
https://app.asana.com/0/857905837377150/1139225286106945/f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3957)

Stop building docs for dgraph 1.0.5 and below

---

gql/parser.go
gql/parser_test.go

Signed-off-by: பாலாஜி ஜின்னா <balaji@dgraph.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/3725)

return error if keywords used as alias in groupby

---

vendor/github.com/inconshreveable/mousetrap/LICENSE
vendor/github.com/inconshreveable/mousetrap/README.md
vendor/github.com/inconshreveable/mousetrap/trap_others.go
vendor/github.com/inconshreveable/mousetrap/trap_windows.go
vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
vendor/vendor.json

* github.com/inconshreveable/mousetrap is a Windows-only dependency of Cobra
that is needed for Windows builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4013)

Vendor in Windows dependencies.

---

contrib/config/kubernetes/helm/values.yaml

It was currently `flase` .. fixed to `false`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4018)

Fixed boolean value for readinessProbe

---

contrib/standalone/run.sh

Fixes #4039.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4046)

standalone: Set lru_mb minimum to 1024.

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4052)

Update CHANGELOG for upcoming v1.0.18.

---

x/x.go

I may be mistaken but it seems that `i` should be getting incremented in this loop rather than `retries`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4036)

x: increment loop variable

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4060)

Documentation for extended cascade

---

CHANGELOG.md

- v1.0.18 (unreleased)
- Fix some GitHub links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4073)

docs: Update CHANGELOG.

---

dgraph/cmd/alpha/run_test.go
dgraph/cmd/bulk/run.go
x/file.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4068)

Handle errors on Close()

---

dgraph/cmd/alpha/run_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4090)

Remove unnecessary type assertions.

---

dgraph/cmd/alpha/run_test.go
dgraph/cmd/counter/increment_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4092)

Replace call to strings.Index with strings.Contains

---

dgraph/cmd/counter/increment.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4091)

Remove usage of nil context.

---

ee/backup/tests/minio/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4109)

Remove defer statement inside loop.

---

chunker/rdf_state.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4112)

Run "go fmt" on master.

---

wiki/content/clients/index.md

Recently a user using C ++ requested a way to make queries using JSON and this was undocumented. Although it can be seen in the runnable code panel, it is not obvious to users. So I've added it to the client's topic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4117)

add Run a query as a JSON object

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4059)

Updating sort example query

---

dgraph/cmd/bulk/mapper.go
dgraph/cmd/bulk/merge_shards.go
dgraph/cmd/root.go

Change file permissions when creating directories to 0750 and when creating files to 0600 for security reasons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4088)

Fix file permissions.

---

wiki/content/dgraph-compared-to-other-databases/index.md

- Removing references to Cypher and Gremlin.
- Updating the GraphQL site link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4010)

Minor enhancements to docs

---

dgraph/cmd/graphql/dgraph/schema.graphql
dgraph/cmd/graphql/e2e_test_schema.graphql
dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/gqlschema_test.yml
dgraph/cmd/graphql/schema/rules.go
dgraph/cmd/graphql/schema/schemagen.go
dgraph/cmd/graphql/schema/schemagen_test.go
dgraph/cmd/graphql/schema/schemagen_test.yml
dgraph/cmd/graphql/schema/testdata/schemagen/input/interfaces-with-types.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/input/no-id-field-with-searchables.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/input/searchables-references.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/input/searchables.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/input/type-implements-multiple-interfaces.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/enums-generate-nothing.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/hasInverse.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/no-id-field.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/searchables-references.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/searchables.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/single-type.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/type-reference.graphql

Asana Task https://app.asana.com/0/1125577271667196/1138888774457265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4098)

Searchable changed to search

---

dgraph/cmd/counter/increment_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4147)

Fix tests broken by #4144

---

wiki/content/tips/index.md

The resolve of issue #4009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4131)

Added docs to obtain unique results using variables

---

dgraph/cmd/graphql/e2e_test_schema.graphql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4148)

Fixed some reamining searchables

---

gql/parser.go
query/outputnode.go
query/query.go
query/query4_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4122)

Support for count(uid) with alias

---

wiki/content/query-language/index.md

Fixes #4165 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4166)

Clarify interaction between schema queries and normal queries.

---

query/common_test.go
query/query.go
wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4171)

Breaking change: Change _all_ functionality to only include the preds in the type.

---

systest/cluster_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4173)

Replace log.Fatal with t.Fatal.

---

wiki/content/tips/index.md

Relates to #4009
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4161)

Using the minimal query to obtain unique nodes

---

wiki/content/deploy/index.md

Fixes #4086 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4164)

Adding more description about mutation flag

---

wiki/content/query-language/index.md

Fixes #4087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4186)

Adding documentation on valid predicate names

---

edgraph/access_ee.go
ee/acl/utils.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4127)

Refactor ACL code

---

wiki/content/clients/index.md
wiki/content/get-started/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4213)

Cherry pick: Revert some changes in favor of 1.1.0 docs

---

dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/rules.go
dgraph/cmd/graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql

There's a bug where we are copying the @hasInverse directive from the interface into the implementing types.
Looks like a simple fix ... checking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4220)

[WIP] Fix interfaces+hasInverse

---

dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/schemagen.go
dgraph/cmd/graphql/schema/schemagen_test.go
dgraph/cmd/graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql

Looks like we weren't creating references properly for Interfaces ... why wasn't this caught by schema gen testing???
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4221)

Fix interface ref types

---

dgraph/cmd/debug/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4237)

Fix unhandled error warnings in debug tool.

---

gql/fuzzit.sh

Enabled GO Modules in the script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4239)

Enable GOmodules for the fuzzit.sh script

---

dgraph/cmd/alpha/run_test.go
ee/acl/acl_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4241)

Remove unused vars and disabled tests.

---

gql/math.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4242)

Remove unchecked error warnings in MathTree.stringHelper.

---

chunker/chunk.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4243)

Fix unhandled error warnings in chunker package.

---

gql/parser.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4244)

Fix unhandled error warnings in gql/parser.go

---

query/outputnode.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4246)

Fix unhandled error warnings in query/outputnode.go

---

dgraph/cmd/alpha/http.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4247)

Fix unhandled error warnings in alpha/http.go

---

dgraph/cmd/bulk/merge_shards.go
dgraph/cmd/cert/info.go
dgraph/cmd/migrate/utils.go
dgraph/cmd/zero/run.go
ee/backup/s3_handler.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4248)

Fix unhandled error warnings in several packages.

---

dgraph/cmd/graphql/dgraph/graphquery.go
dgraph/cmd/graphql/e2e_query_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4249)

Added order and pagination to root graphQL query

---

lex/lexer.go
rdf/parse_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4252)

Change lexer to allow unicode escape sequences. (#4175)

---

dgraph/cmd/bulk/merge_shards.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4253)

Exit early if data files given to bulk loader are empty.

---

worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4277)

Rename variable so that schema package is not shadowed.

---

CHANGELOG.md

Remove a duplicate changelog section that was added in #4276.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4278)

Remove duplicate changelog section.

---

dgraph/cmd/graphql/e2e_query_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4285)

graphql fix test

---

wiki/content/enterprise-features/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4280)

Document how to disable HTTPS in a S3 container during backups.

---

query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4290)

Fix deepsource warnings in query.go

---

conn/node.go
dgraph/cmd/zero/raft.go
systest/group-delete/group_delete_test.go
worker/draft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4293)

Fix more deepsource warnings in raft.go

---

posting/size.go
posting/size_test.go
posting/size_test.sh
test.sh

helper method added to calculate the size of List based on https://github.com/golang/go/issues/34561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4271)

Add helper method to calculate the size of List

---

dgraph/cmd/graphql/resolve/query_test.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4294)

Added query rewriting test for order and pagination at root level

---

wiki/content/query-language/index.md

Small fix in docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4299)

Fix broken queries in docs

---

go.mod
go.sum

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4304)

Pull in latest dgo

---

conn/pool.go

* Fixes #4298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4303)

chore: fix connection log information in dgraph alpha

---

test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4308)

Run posting list size tests as part of the systest suite only.

---

ee/backup/tests/minio-large/backup_test.go
ee/backup/tests/minio-large/docker-compose.yml

This test verifies backups to minio work with a relatively large amount
of data (20000 triples). It also adds data to every group to verify that
backup works accross multiple groups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4320)

Add test for large backups.

---

dgraph/cmd/counter/increment.go
edgraph/server.go
go.mod
go.sum

Example response:
```
{
"data": {
"q": [],
"code": "Success",
"message": "Done",
"uids": {
"uid(v)": "0x2"
}
},
"extensions": {
"server_latency": {
"parsing_ns": 50139,
"processing_ns": 12188065,
"encoding_ns": 5040,
"assign_timestamp_ns": 694780,
"total_ns": 13175112
},
"txn": {
"start_ts": 14,
"commit_ts": 15,
"preds": [
"1-email",
"1-name"
]
}
}
}
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4312)

Add total time taken to process a query in result

---

dgraph/cmd/alpha/upsert_test.go
edgraph/server.go

fixes #4021
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4268)

Limit UIDs per variable in upsert

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4270)

Add docs for multiple mutation blocks

---

posting/size.go
posting/size_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4330)

Acquire lock before calculating computing deepsize

---

wiki/content/mutations/index.md

I think something went wrong in this PR https://github.com/dgraph-io/dgraph/pull/4270 and changes didn't get merged correctly. This PR fixes those docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4332)

Fix docs for multiple mutation blocks

---

dgraph/cmd/graphql/resolve/schema.graphql
dgraph/cmd/graphql/schema/gqlschema_test.yml
dgraph/cmd/graphql/schema/rules.go
dgraph/cmd/graphql/schema/testdata/schemagen/input/hasInverse-with-interface.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4325)

Updated hasInverse rules

---

dgraph/cmd/graphql/e2e_query_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4336)

Fixes a flakey enum filter test

---

dgraph/cmd/graphql/e2e_mutation_test.go
dgraph/cmd/graphql/resolve/mutation_query_test.yaml
dgraph/cmd/graphql/resolve/mutation_test.go
dgraph/cmd/graphql/resolve/query_rewriter.go
dgraph/cmd/graphql/schema/gqlschema.go
dgraph/cmd/graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/hasInverse.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/no-id-field.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/searchables-references.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/searchables.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/single-type.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
dgraph/cmd/graphql/schema/testdata/schemagen/output/type-reference.graphql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4292)

Added filter argument inside updateMutation 

---

wiki/content/query-language/index.md

- add uid() func to shortest path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4327)

Documents important feature in shortest path.

---

dgraph/cmd/alpha/admin.go
dgraph/cmd/alpha/run.go
edgraph/access_ee.go
edgraph/config_mem.go
edgraph/server.go
worker/config.go
worker/server_state.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4346)

Refactor ServerState from edgraph to worker pkg. 

---

ee/backup/tests/filesystem/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4354)

Fix unused var warning from DeepSource.

---

chunker/chunk.go
chunker/json_parser.go
chunker/rdf_parser.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4355)

Fix DeepSource warnings in chunker package.

---

x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4366)

Fix unhandled error warnings in x.go

---

dgraph/cmd/alpha/run.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4356)

close store after stoping worker

---

go.mod
go.sum

```
git log --oneline v2.0.0...8b99eb433aa7 
```
The following changes are introduced in this PR 
```
8b99eb4 Fix encryption in stream writer (#1146)
1ee50f7 Add Value Checksum success test (#1147)
e28642f Fix VerifyValueChecksum checks (#1138)
969a8e8 Fix windows dataloss issue (#1134)
690488d Fix removeDir function in tests. (#1145)
407e5bd Optimize createTable in stream_writer.go (#1132)
f5b6321 Introduce in-memory mode in badger (#1113)
3eb4e72 Set level 15 as default compression level in ZSTD (#1111)
ad770ca Fix request increment ref bug (#1121)
fb0cdb8 Cast idx to uint32 to fix compilation on i386 (#1118)
5f94f68 Limit manifest's change set size (#1119)
ffb3450 Fix TestGoroutineLeak and Example_subscribe test (#1123)
```
--- …

Update badger to commit 8b99eb433aa7

---

query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4374)

Fix comments to calculateMetrics functions.

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4376)

change log for dgraph 1.1.1 release

---

edgraph/access_ee.go
ee/acl/acl_test.go

Add predicates of delete mutation in `authorizeMutation` 
Fixes #4265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4349)

Block delete if predicate permission is zero

---

query/query1_test.go

Fixes #4286 
Fixed by #4269, just adding a test for using graphql variables with an upsert.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4377)

Add test for graphql vars in upsert

---

wiki/content/enterprise-features/index.md

Added documentation of encryption for new Dgraph release.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4363)

Added documentation for encryption in Dgraph

---

contrib/integration/testtxn/main_test.go
edgraph/server.go

Related to https://github.com/dgraph-io/dgraph-js/issues/48
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4389)

Donot return dgo.ErrAborted when client calls txn.Discard()

---

wiki/content/clients/index.md

Related to this: https://github.com/dgraph-io/dgraph-js/issues/62#issuecomment-532293754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4388)

Adding unofficial JS clients to docs

---

query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4397)

Removed unused functions in query.go

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4401)

Update CHANGELOG for v1.1.1.

---

edgraph/server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4403)

Fix deep source warnings in server.go

---

dgraph/cmd/bulk/loader.go
dgraph/cmd/bulk/mapper.go
dgraph/cmd/bulk/reduce.go
dgraph/cmd/bulk/schema.go
query/shortest.go
worker/export.go
worker/groups.go
worker/mutation.go
worker/snapshot.go
worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4412)

Fix import shadowing warnings.

---

posting/lists.go
posting/size_test.go
worker/predicate_test.go
worker/worker_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4413)

 Fix unused code warnings

---

worker/draft_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4414)

Fix multiple appends warnings.

---

dgraph/cmd/alpha/upsert_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4420)

Fix upsert tests to compare only predicates names

---

contrib/config/docker/docker-compose-ha.yml
contrib/config/docker/docker-compose-multi.yml
wiki/content/deploy/index.md

#3748
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4418)

Docs: Fix service name in docker config

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4421)

Add docs for ratel issues #31 and #51

---

schema/parse.go
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4423)

Fix some deepsource warnings.

---

posting/size.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4432)

Ignore use of unsafe module in size.go

---

gql/parser.go
gql/parser_mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4433)

Use switch statements instead of if-else in gql package.

---

gql/math.go
query/aggregator.go
query/groupby.go
query/outputnode.go
query/query.go
query/shortest.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4436)

Use switch statement instead of if-else in query package.

---

CONTRIBUTING.md

I forgot to add these links to CONTRIBUTING.md in #4434.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4437)

docs: Add to table of contents in CONTRIBUTING.md.

---

dgraph/cmd/live/load-json/load_test.go
dgraph/cmd/live/load-uids/load_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4448)

Fix unused variable warnings.

---

posting/list.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4450)

Fix ignored error warnings in List.iterate.

---

dgraph/cmd/alpha/run.go
dgraph/cmd/bulk/mapper.go
dgraph/cmd/counter/increment.go
dgraph/cmd/debug/run.go
dgraph/cmd/zero/oracle.go
edgraph/access_ee.go
gql/math.go
posting/index_test.go
posting/list.go
posting/list_test.go
worker/predicate_move.go
worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4449)

Replace else-if statements with switch.

---

conn/pool.go
dgraph/cmd/alpha/run.go
dgraph/cmd/live/run.go
worker/export.go
worker/predicate_move.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4458)

Fix unhandled error warnings.

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4456)

Adding more information about /state endpoint

---

chunker/rdf_parser.go
chunker/rdf_parser_test.go

Fixes #4460.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4465)

Add <xs:integer> RDF type for int schema type.

---

wiki/content/query-language/index.md

- Remove outdated comment regarding reverse types.
- Include an example of a type containing a reverse predicate.
- Fix ungrammatical sentence.
Fixes #4451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4477)

Fix documentation regarding reverse predicates and types.

---

chunker/json_parser_test.go
contrib/integration/testtxn/main_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4481)

Fix more unused code warnings.

---

schema/parse.go
schema/schema.go
worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4482)

Pass schema updates as pointers instead of values.

---

dgraph/cmd/debug/run.go
dgraph/cmd/debug/wal.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4484)

Fix copied argument warnings in debug tool.

---

dgraph/cmd/alpha/run.go
worker/config.go
worker/export.go
worker/export_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4485)

Fix copied argument warnings in worker package.

---

query/query4_test.go

Tests are failing in master after merging this PR. #4454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4491)

Fix failing test.

---

contrib/jepsen/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4499)

Combine multiple append statements.

---

graphql/admin/admin.go
graphql/e2e/common/common.go
graphql/e2e/common/error.go
graphql/e2e/common/mutation.go
graphql/e2e/directives/dgraph_directives_test.go
graphql/e2e/directives/schema.graphql
graphql/e2e/normal/normal_test.go
graphql/e2e/normal/schema.graphql
graphql/resolve/add_mutation_test.yaml
graphql/resolve/mutation_rewriter.go
graphql/resolve/mutation_test.go
graphql/resolve/resolver.go
graphql/resolve/resolver_error_test.go
graphql/resolve/schema.graphql
graphql/resolve/update_mutation_test.yaml
graphql/schema/wrappers.go
graphql/schema/wrappers_test.go

Make sure that deep mutations work with xids.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4462)

deep xid mutations

---

x/keys_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4505)

Add additional test for type keys.

---

edgraph/access_ee.go

Fixes #4503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4506)

Fix typo in error message.

---

dgraph/cmd/bulk/loader.go
dgraph/cmd/bulk/merge_shards.go
dgraph/cmd/bulk/run.go
dgraph/cmd/bulk/schema.go
testutil/backup.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4508)

Fix copied argument warnings in bulk loader.

---

contrib/jepsen/main.go
dgraph/cmd/debuginfo/archive.go
dgraph/cmd/debuginfo/pprof.go
dgraph/cmd/debuginfo/run.go
dgraph/cmd/root.go
graphql/e2e/directives/dgraph_directives_test.go

...oh, my bad.  Looks like Pawan had already done it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4501)

Merging master after Christmas/new year break

---

graphql/e2e/directives/schema.graphql
graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql

Some issues were introduced after the merging of the last two PRs. This PR fixes them. I will merge this change once the tests pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4502)

Fix tests on mjc/graphql branch

---

wiki/scripts/local.sh

Closed the [previously raised PR for Netlify](https://github.com/dgraph-io/dgraph/pull/4483). Replacing it with [surge.sh](https://surge.sh).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4512)

Updating local script to support docs preview of PR

---

dgraph/cmd/bulk/systest/test-bulk-schema.sh
graphql/e2e/common/common.go
graphql/e2e/common/query.go
graphql/e2e/directives/dgraph_directives_test.go
graphql/e2e/directives/test_data.json

Incorrect data was being added in the `test_data.json` file for some of the end to end tests. That has been fixed and a test case has been added to verify the fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4510)

Fix test data for e2e with dgraph directive

---

wiki/config.toml
wiki/scripts/local.sh

- changing SSH to HTTPS for git clone
- indentation fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4519)

Updating local build script

---

dgraph/cmd/bulk/systest/test-bulk-schema.sh
ee/backup/tests/filesystem/backup_test.go
ee/backup/tests/minio/backup_test.go
graphql/admin/admin.go
graphql/e2e/common/admin.go
graphql/e2e/common/schema.go
graphql/e2e/directives/dgraph_directives_test.go
graphql/e2e/normal/normal_test.go
graphql/e2e/schema_subscribe/docker-compose.yml
graphql/e2e/schema_subscribe/schema_subscribe_test.go
schema/schema.go
systest/queries_test.go
worker/groups.go
x/keys.go
x/x.go

Signed-off-by: balaji <rbalajis25@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4513)

Subscribe for graphql schema update

---

wiki/content/enterprise-features/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4470)

Add revised info about ACL in docs

---

compose/compose.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4525)

Fix warnings in compose tools.

---

contrib/config/marketplace/aws/README.md
contrib/config/marketplace/aws/deploy.sh
contrib/config/marketplace/aws/dgraph.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4431)

contrib: add cloudformation template to deploy dgraph on AWS in HA mode

---

go.mod

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4539)

Run "go mod tidy" on master.

---

graphql/dgraph/graphquery.go
graphql/schema/gqlschema.go
graphql/schema/rules.go
worker/proposal.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4547)

Fix Deepsource warnings regarding use of else-if.

---

go.mod

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4557)

Run "go mod tidy".

---

graphql/e2e/common/common.go
graphql/e2e/common/mutation.go
graphql/resolve/mutation_query_test.yaml
graphql/schema/gqlschema.go
graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
graphql/schema/testdata/schemagen/output/hasInverse.graphql
graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
graphql/schema/testdata/schemagen/output/no-id-field.graphql
graphql/schema/testdata/schemagen/output/searchables-references.graphql
graphql/schema/testdata/schemagen/output/searchables.graphql
graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
graphql/schema/testdata/schemagen/output/single-type.graphql
graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
graphql/schema/testdata/schemagen/output/type-reference.graphql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4565)

Added filter to add object mutation in graphql

---

graphql/e2e/common/mutation.go
graphql/e2e/common/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4567)

Changed require.notnil to requirenogqlerrors

---

graphql/e2e/common/error.go
graphql/e2e/common/mutation.go
graphql/resolve/add_mutation_test.yaml
graphql/schema/gqlschema.go
graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
graphql/schema/testdata/schemagen/output/hasInverse.graphql
graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
graphql/schema/testdata/schemagen/output/no-id-field.graphql
graphql/schema/testdata/schemagen/output/searchables-references.graphql
graphql/schema/testdata/schemagen/output/searchables.graphql
graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
graphql/schema/testdata/schemagen/output/single-type.graphql
graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
graphql/schema/testdata/schemagen/output/type-reference.graphql

Removing some inconsistencies in type names for the generated GraphQL schema.
* PatchT -> TPatch
* TInput -> AddTInput
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4563)

GraphQL type names

---

graphql/e2e/common/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4569)

Fix issue in graphql e2e tests introduced because of merge

---

dgraph/cmd/bulk/systest/test-bulk-schema.sh
ee/backup/tests/filesystem/backup_test.go
ee/backup/tests/minio/backup_test.go
graphql/admin/admin.go
graphql/admin/schema.go
graphql/e2e/common/admin.go
graphql/e2e/common/common.go
graphql/e2e/directives/dgraph_directives_test.go
graphql/e2e/normal/normal_test.go
graphql/e2e/schema_subscribe/schema_subscribe_test.go
graphql/schema/wrappers.go
schema/schema.go
systest/queries_test.go
x/keys.go
x/x.go

Changes the schema of the /admin endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4566)

graphql /admin changed

---

wiki/content/mutations/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4604)

docs: Fix JSON syntax example for geojson.

---

contrib/systemd/centos/README.md
contrib/systemd/centos/add_dgraph_account.sh
contrib/systemd/centos/dgraph-alpha.service
contrib/systemd/centos/dgraph-ui.service
contrib/systemd/centos/dgraph-zero.service

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4610)

contrib: Fix SystemD config to persist data across OS reboots

---

contrib/systemd/centos/add_dgraph_account.sh
contrib/systemd/centos/dgraph-alpha.service
contrib/systemd/centos/dgraph-ui.service
contrib/systemd/centos/dgraph-zero.service

> No review needed due to minor change.
Add minor changes to increase compatibility between more distros.
Also, make sure that distros have sudo, so use it.
It works in Centos 8 and Ubuntu 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4618)

Contrib: Minor changes in systemd files

---

x/keys.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4592)

fixes reversed predicate list

---

dgraph/cmd/alpha/run.go
graphql/admin/admin.go
worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4593)

Closes graphql admin properly

---

edgraph/access_ee.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4606)

Refactor glog uses in access_ee.go

---

conn/node.go
conn/node_test.go
contrib/release.sh
dgraph/cmd/alpha/run.go
dgraph/cmd/zero/assign.go
dgraph/cmd/zero/license_ee.go
dgraph/cmd/zero/oracle.go
dgraph/cmd/zero/raft.go
dgraph/cmd/zero/run.go
dgraph/cmd/zero/tablet.go
dgraph/cmd/zero/zero.go
edgraph/server.go
graphql/admin/admin.go
query/query0_test.go
worker/backup.go
worker/draft.go
worker/export.go
worker/export_test.go
worker/groups.go
worker/mutation.go
worker/predicate_move.go
worker/proposal.go
worker/proposal_test.go
worker/schema.go
worker/server_state.go
worker/sort.go
worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4629)

use stdlib context package instead now

---

worker/task.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4635)

Fix else-if warnings in task.go

---

graphql/resolve/mutation_rewriter.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4637)

Fix error message warnings.

---

graphql/resolve/mutation_rewriter.go

Also use the errors library instead of fmt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4611)

Fix error string warnings.

---

conn/node.go
conn/node_test.go
dgraph/cmd/zero/raft.go
raftwal/storage.go
worker/draft.go
worker/draft_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4638)

Fix copied argument warnings in raft code.

---

algo/uidlist.go
contrib/integration/acctupsert/main.go
dgraph/main.go
gql/state.go
types/facets/utils.go
types/geofilter_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4654)

Change if-else statements to switch statements.

---

dgraph/cmd/cert/create.go
dgraph/cmd/cert/run.go
testutil/docker.go
worker/stringfilter.go
worker/task.go

Also fixes a warning about repeated appends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4655)

Fix copied argument warnings.

---

lex/lexer.go
tok/tokens.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4657)

Fix warnings about switch statements with only one case.

---

contrib/integration/bank/main.go
contrib/integration/bigdata/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4664)

Fix error check warnings in contrib/integration.

---

worker/mutation.go
x/keys.go

Fixes JIRA DGRAPH-975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4656)

Check for reserved predicate in strict mode

---

x/keys.go

This fixes the scendaio when ACL is off and a <uid * *> deletion is issued
Fixes JIRA DGRAPH-975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4671)

Remove ACL predicates from the list of reserved predicates (#4656)

---

dgraph/cmd/alpha/run.go
dgraph/cmd/alpha/run_test.go
dgraph/cmd/bulk/systest/test-bulk-schema.sh
ee/backup/tests/filesystem/backup_test.go
ee/backup/tests/minio/backup_test.go
graphql/e2e/directives/dgraph_directives_test.go
graphql/e2e/normal/normal_test.go
graphql/e2e/schema_subscribe/schema_subscribe_test.go
query/mutation_test.go
schema/schema.go
systest/mutations_test.go
systest/queries_test.go
x/keys.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4665)

turn off  GraphQL in v1.2

---

graphql/dgraph/execute.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4649)

turn on readonly for GraphQL queries

---

CHANGELOG.md

Updating CHAGNELOG for Dgraph 2.0 Bata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4697)

Updating CHANGELOG for Dgraph 2.0 Beta

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4722)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1a6c011850-42737.surge.sh)

docs: Clarify removeNode only works on Zero leader.

---

wiki/content/deploy/index.md

Fixes #4622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4718)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9ed79a116c-42854.surge.sh)

Fix for docker docs

---

README.md
wiki/content/deploy/index.md
wiki/content/faq/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4727)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0003fe1680-42941.surge.sh)

docs: update product roadmap links

---

ee/backup/tests/minio-large/backup_test.go
ee/backup/tests/minio/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4732)

Fix comment in backup_test.go

---

dgraph/cmd/debug/run.go

This PR fixes the panic in the debug tool. The panic would happen because the same iterator was used in the `history` function. If the iterator becomes Invalid in `history` function and we do a `Next` on it in the `printKeys` function the code panics.
The `history` function already does a `Next` so we don't need to call `Next` in the `printkeys` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4728)

Fix iteration in debug tool danielmai/debug-tool-print-all branch

---

CHANGELOG.md

- added also new sections for "changed", "added", "fixed" so that we can start adding the entries for 2.0.0-beta2 (or the name the new release will take). I can remove them if needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4731)

2.0.0-beta1 changelog

---

wiki/content/deploy/index.md

Fixes #4524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4736)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4db049f16d-43046.surge.sh)

Minor fix for multi-host setup docs

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4743)

Update CHANGELOG for v1.2.1.

---

dgraph/cmd/zero/license_ee.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4747)

Add enterprise license URL

---

CHANGELOG.md

CHANGELOG updates for dgraph v2.0.0-rc1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4783)

CHANGELOG for v2.0.0-rc1

---

graphql/e2e/common/mutation.go
graphql/schema/wrappers.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4792)

fix graphql interface ID bug

---

wiki/content/mutations/index.md

There is no information in the documentation about such a procedure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4542)

add info about deleting facets.

---

graphql/schema/gqlschema.go
graphql/schema/testdata/schemagen/input/ignore-unsupported-directive.graphql
graphql/schema/testdata/schemagen/output/ignore-unsupported-directive.graphql

#4799
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4805)

graphql: ignore unsupported schema directive

---

edgraph/access_ee.go
ee/acl/acl_test.go
graphql/admin/admin.go
graphql/admin/current_user.go
graphql/admin/endpoints_ee.go
graphql/admin/health.go
graphql/admin/schema.go
graphql/resolve/query.go
graphql/resolve/query_rewriter.go
graphql/resolve/query_test.go
graphql/schema/wrappers.go
x/x.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4788)

graphql: Added getCurrentUser functionality

---

graphql/schema/gqlschema.go
graphql/schema/rules.go
graphql/schema/testdata/schemagen/output/ignore-unsupported-directive.graphql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4823)

graphql: Fixes secret validation test

---

dgraph/cmd/alpha/admin.go
dgraph/cmd/alpha/admin_backup.go
dgraph/cmd/alpha/http_test.go
dgraph/cmd/alpha/run.go
dgraph/cmd/bulk/systest/test-bulk-schema.sh
ee/backup/tests/filesystem/backup_test.go
ee/backup/tests/minio-large/backup_test.go
ee/backup/tests/minio/backup_test.go
systest/cluster_setup_test.go
systest/loader/loader_test.go
testutil/graphql.go
worker/export_test.go

Reverts dgraph-io/dgraph#4754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4822)

Revert "Remove HTTP admin endpoints"

---

dgraph/cmd/root_ee.go
ee/acl/acl.go
ee/acl/run.go
ee/acl/run_ee.go
ee/acl/utils.go

Reverts dgraph-io/dgraph#4775
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4821)

Revert "Remove ACL command line tool."

---

CHANGELOG.md

changes for v2.0.0 CHANGELOG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4826)

Update CHANGELOG for v2.0.0 (beta).

---

contrib/jepsen/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4833)

Fix Deepsource warnings in Jepsen tool.

---

graphql/resolve/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4835)

Change else-if to switch-case in graphql/resolve/mutation.go

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4836)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d327daae22-45697.surge.sh)

docs: Set v1.2.1 as default docs.

---

contrib/integration/bank/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4844)

contrib: Add flag to skip groot login in bank test.

---

dgraph/cmd/bulk/systest/test-bulk-schema.sh
ee/backup/tests/filesystem/backup_test.go
ee/backup/tests/minio-large/backup_test.go
ee/backup/tests/minio/backup_test.go
systest/cluster_setup_test.go
systest/loader/loader_test.go
testutil/graphql.go
worker/export_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4845)

Change backup and export tests to use the new GraphQL admin API

---

vendor/github.com/dgraph-io/badger/db.go

- Don't close the channell while closing the doWrite (#918)
- Close channel while closing the db
- Stop compaction after flushing the memtable
Signed-off-by: பாலாஜி ஜின்னா <balaji@dgraph.io>
(cherry picked from commit 2b39009229f09bc05bc229a2032e912b5c65d880)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4761)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://)

Badger: Stop compaction after flushing the memtable

---

dgraph/cmd/counter/increment_test.go
graphql/admin/draining.go
types/s2index_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4849)

Fix unused code warnings.

---

dgraph/cmd/bulk/reduce.go

No code changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4850)

Fix spacing and comments in reduce.go

---

wiki/content/deploy/index.md
wiki/content/enterprise-features/index.md

Updating docs for the admin endpoint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4847)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0c124ef137-46073.surge.sh)

Docs updated for GraphQL admin endpoint

---

ee/acl/acl_test.go
graphql/admin/admin.go
graphql/admin/endpoints_ee.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4852)

graphql: Changed password to secret directive

---

ee/backup/backup.go
ee/backup/file_handler.go
ee/backup/handler.go
ee/backup/restore.go
ee/backup/run.go
ee/backup/s3_handler.go
ee/backup/tests/filesystem/backup_test.go
ee/backup/tests/minio-large/backup_test.go
ee/backup/tests/minio/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4877)

Cherry-pick "Assign maxLeaseId during restore. (#4827)"

---

posting/list.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4891)

Print keys using hex encoding in error messages in list.go

---

dgraph/cmd/debug/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4893)

Properly initialize posting package in debug tool.

---

wiki/content/tutorial-5/index.md

the previous attempt at adding the video didn't pass all the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4894)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-bcfb1bf7fe-47155.surge.sh)

add video for step 5 of the tutorial to the page in docs for part 5

---

ee/acl/acl_test.go

Order query results so that the results have a consistent order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4903)

Fix flaky ACL tests.

---

wiki/content/deploy/index.md

Backport of https://github.com/dgraph-io/dgraph/pull/4863
Reference:
- https://github.com/dgraph-io/dgraph/issues/4839
- https://github.com/dgraph-io/dgraph/issues/4644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4876)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-43a7841436-46530.surge.sh)

docs: improve shutdown and upgrade sections

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4870)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c4da427412-46374.surge.sh)

Section headers should use -ing verbs.

---

CHANGELOG.md

adds missing entries
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4888)

docs: improve v1.2.0 changelog

---

wiki/content/deploy/index.md
wiki/content/enterprise-features/index.md
wiki/content/faq/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4909)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-8723070c8b-47415.surge.sh)

Update the relative links that were changed in #4870

---

go.sum

Running make in master is modifying the go.sum file. Updating this
file to have the latest version of the go.sum file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4918)

Update go.sum file.

---

dgraph/cmd/alpha/run.go
graphql/web/http.go

Fixes #4926
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4928)

Allow options HTTP method for /admin

---

x/init.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4936)

Update copyright year to 2020.

---

dgraph/cmd/debug/run.go
ee/backup/handler.go
ee/backup/restore.go
ee/backup/s3_handler.go
go.sum
gql/parser.go
gql/parser_test.go
gql/state.go
posting/list.go
posting/mvcc.go
query/outputnode.go
query/query.go
systest/mutations_test.go
wiki/content/mutations/index.md
worker/export.go
worker/export_test.go
worker/task.go

I will not squash this PR so the log is preserved.
My changes to the bulk loader are missing because the bulk loader has a lot of changes
and not all of them have been cherry-picked into this branch. Not sure what to do about
that since I didn't make all of those changes so I am not sure exactly what commits should
be cherry-picked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4951)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-710d4db3af-48799.surge.sh)

Cherry-pick changes required for 1.2.2 release.

---

dgraph/cmd/zero/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4950)

ignore 2nd and hard-kill on 3rd signal in the zero sig handler

---

dgraph/cmd/zero/run.go

Cherry-picker 474661fb2 from master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4957)

ignore 2nd and hard-kill on 3rd signal in the zero sig handler (#4950)

---

wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4943)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-dafce04d46-48989.surge.sh)

Add docs for background indexing

---

dgraph/cmd/live/batch.go
dgraph/cmd/live/run.go
go.mod
go.sum
query/common_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4906)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6c24567989-47384.surge.sh)

namespace support for live-loader. 

---

CHANGELOG.md

Editing CHANGELOG for changes for 1.2.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4971)

Update CHANGELOG for v1.2.2.

---

posting/list_test.go

Also use unique ids in the tests to avoid flakiness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4956)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e03a790aa3-49199.surge.sh)

Add test to check the versions of the keys returned by rollout.

---

x/keys.go
x/keys_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4987)

Better error handling in x.Parse

---

wiki/config.toml
wiki/content/releases/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4954)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-40a9a2b334-49598.surge.sh)

docs: Add Releases page.

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4993)

docs: Set v1.2.2 as latest docs.

---

dgraph/cmd/bulk/reduce.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4982)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-820e784f46-49835.surge.sh)

Add comment regarding stream IDs for split lists in bulk loader.

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4994)

Update CHANGELOG for v20.03.0-beta.20200320.

---

systest/21million/queries/query-053
systest/21million/queries/query-054
systest/21million/queries/query-055
systest/21million/queries/query-056
systest/21million/queries/query-057
systest/21million/queries/query-058
systest/21million/queries/query-059
systest/21million/queries/query-060
systest/21million/queries/query-061
systest/21million/queries/query-062
systest/21million/queries/query-063
systest/21million/queries/query-064
systest/21million/queries/query-065
systest/21million/queries/query-066
systest/21million/queries/query-067
systest/21million/queries/query-068
systest/21million/queries/query-069
systest/21million/queries/query-070
systest/21million/queries/query-071
systest/21million/queries/query-072
test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5001)

Add count queries to 21 million systest

---

dgraph/cmd/alpha/dashboard.go
dgraph/cmd/alpha/http_test.go

Fixes #4946.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4992)

add OPTIONS support for /ui/keywords

---

graphql/resolve/resolver.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5025)

fix error message
