worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5005)

Propose snapshot once indexing is complete

---

worker/mutation.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5033)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-aa879453ba-50566.surge.sh)

Sleep a bit before building indexes

---

posting/index.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5035)

Return immediately when maxassigned is zero while reindexing (#5032)

---

wiki/content/clients/index.md
wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5015)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9280cc6cff-50685.surge.sh)

Update docs for /health endpoint

---

.dockerignore
Makefile
contrib/scripts/functions.sh
test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5027)

Fixing `make image` to run on OSX

---

wiki/config.toml
wiki/scripts/build.sh

This PR updates the docs build script with configurable parameters for the host, public directory, Hugo command, and whether the script runs in a loop.
These changes are needed to move the docs from docs.dgraph.io to dgraph.io/docs (subdomain to subfolder migration).
Docs build script.
No. The build script can be used as-is with the same behavior with no arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5050)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-de744b8554-50940.surge.sh)

docs: Update docs build script with configurable parameters.

---

wiki/content/tips/index.md
wiki/scripts/local.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5041)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-10930157c1-50897.surge.sh)

Fix for the broken link found using linkchecker

---

dgraph/cmd/alpha/http.go
dgraph/cmd/alpha/run_test.go
wiki/content/query-language/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5057)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-772e3d0641-51166.surge.sh)

change run_in_background -> runInBackground

---

wiki/content/clients/index.md
wiki/content/deploy/index.md
wiki/content/query-language/index.md
wiki/content/releases/index.md
wiki/content/tips/index.md
wiki/scripts/local.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5060)

Pull docs from master

---

x/error.go
x/init.go
x/sentry_integration.go
x/x_test.go

cherry picked from commit 7e7278500a962c61da344aa84360281222727f9a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5061)

Indicate dev environment in Sentry events (#5051)

---

dgraph/cmd/root.go
edgraph/access_ee.go
upgrade/acl.go
upgrade/upgrade.go
wiki/content/deploy/index.md

This is a cherry-pick PR of #5016.
This is the upgrade tool for ACLs for v20.03.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5065)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-689bb6f7f7-51373.surge.sh)

release/v20.03: Add tool to upgrade ACLs

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5030)

Fix the Go version in the docs

---

wiki/content/enterprise-features/index.md

Set up ACL section GraphQL indentation fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5043)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5d7e9f5cdb-51541.surge.sh)

Minor indentation fix

---

wiki/content/releases/index.md

This updates the docs Releases page for the v20.03.0 release.
v20.03.0 was released. This documents the support and end-of-life policy for v20.03.
Documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5070)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3be07e923a-51505.surge.sh)

docs: Update releases page for v20.03.0.

---

worker/draft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5081)

Fix panic in Task FrameWork, fixes #5034

---

systest/backup/encryption/backup_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5101)

Use dgo v200 in encryption backup code.

---

wiki/content/deploy/index.md

Fixes #4772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5089)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-08a4ffabdf-52208.surge.sh)

Updating prometheus metrics documentation

---

upgrade/acl.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5098)

Uncapitalize error messages.

---

dgraph/cmd/alpha/upsert_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5099)

Fix conditions in tests to clear lint warnings.

---

systest/mutations_test.go

Fixes #3721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5104)

Add test to verify deletes are reflected in queries using the same txn.

---

dgraph/cmd/alpha/upsert_test.go
dgraph/cmd/zero/raft.go
dgraph/cmd/zero/run.go
posting/index_test.go
posting/list.go
posting/list_test.go
posting/lists.go
posting/lmap_test.go
posting/mvcc.go
posting/mvcc_test.go
systest/backup/encryption/backup_test.go
systest/mutations_test.go
upgrade/acl.go
worker/background_mutation.go
worker/draft.go
worker/match.go
worker/sort.go
worker/task.go
worker/trigram.go
worker/worker_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5121)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0d8614d273-52782.surge.sh)

Add new changes to 20.03 release branch.

---

worker/worker.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5133)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ed260549f5-53031.surge.sh)

Update RAFT checkpoint when doing a clean shutdown

---

wiki/content/deploy/index.md
wiki/content/tips/index.md
wiki/scripts/local.sh

(cherry picked of #5089)
Fixes #4772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5118)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e5432c062a-53179.surge.sh)

release/v1.2: Updating prometheus metrics documentation

---

wiki/content/deploy/index.md

(cherry picked of #5089)
Fixes #4772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5117)

release/v20.03: Updating prometheus metrics documentation

---

graphql/admin/admin.go
systest/backup/encryption/backup_test.go

Fixes master build failure due to merging #5054.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5136)

fix dgo version change

---

dgraph/cmd/live/run.go

The live loader is having trouble loading exported data with the
existing uids because there are too many requests for new uids.
The current version requests new Uids to be allocated for every
uids greater than the maximum. In the exported data, the uids can come
in increasing order, which causes a new request for uids with every
NQuad.
This PR changes the code to pre-allocate the uids, once per batch of
NQuad received from the NQuad buffer channel.
Tested it with the 1 million movie data set and now I am getting times
similar to the live loader with the --new_uids option enabled.
Fixes #4996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5151) …

Cherry-pick "Optimize uid allocation in live loader"

---

ee/backup/run.go
systest/backup/encryption/backup_test.go
testutil/backup.go
worker/restore.go

cherry-picked from commit fa4824022d943f76ed00da0d712891421d8e3669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5143)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fa4824022d-53374.surge.sh)

re-encrypt restore from encrypted backups (#5140)

---

query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5152)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d6ec84be9d-53693.surge.sh)

Cherry-pick "Check uid list is empty when filling shortest path vars." (#5141)

---

query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5153)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d898ba2bc6-53716.surge.sh)

Cherry-pick Check uid list is empty when filling shortest path vars. (#5141)

---

chunker/chunk.go
dgraph/cmd/bulk/loader.go
dgraph/cmd/live/run.go
ee/enc/util.go
ee/enc/util_ee_test.go
systest/21million/run_test.go
worker/export.go

Add encryption support for export and import (via bulk, live loaders)
https://dgraph.atlassian.net/browse/DGRAPH-1045
20.07
Yes.
https://dgraph.atlassian.net/browse/DGRAPH-1216
https://dgraph.atlassian.net/browse/DGRAPH-1217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5129)

Add encryption support for export and import (via bulk, live loaders)

---

ee/backup/backup_oss.go
ee/backup/restore.go
ee/backup/run.go
ee/backup/tests/encryption/backup_test.go
testutil/backup.go

(cherry-picked from commit fa4824022d943f76ed00da0d712891421d8e3669)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5144)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1a00e7ec37-53381.surge.sh)

 re-encrypt restore from encrypted backups (#5140) 

---

chunker/chunk.go
dgraph/cmd/bulk/loader.go
dgraph/cmd/live/run.go
ee/enc/util.go
ee/enc/util_ee_test.go
systest/21million/run_test.go
worker/export.go

(cherry-picked from commit dc00f505495e0f0477357d9b6e8c33812dc93b3d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5155)

Add encryption support for export and import (via bulk, live loaders) (#5129)

---

chunker/chunk.go
dgraph/cmd/bulk/loader.go
dgraph/cmd/live/run.go
ee/enc/util.go
ee/enc/util_ee_test.go
systest/21million/run_test.go
worker/export.go

(cherry-picked from commit dc00f505495e0f0477357d9b6e8c33812dc93b3d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5154)

Add encryption support for export and import (via bulk, live loaders)  (#5129)

---

dgraph/cmd/alpha/run.go
dgraph/cmd/zero/run.go

flag to disable sending sentry events. default false
https://dgraph.atlassian.net/browse/DGRAPH-1198
20.07.0
added
https://dgraph.atlassian.net/browse/DGRAPH-1198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5156)

flag to disable sending sentry events. default false. Fixed #1198

---

graphql/schema/gqlschema.go
graphql/schema/testdata/schemagen/input/ignore-unsupported-directive.graphql
graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
graphql/schema/testdata/schemagen/output/deprecated.graphql
graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-on-concrete-type-with-interfaces.graphql
graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-with-interfaces.graphql
graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
graphql/schema/testdata/schemagen/output/field-with-reverse-predicate-in-dgraph-directive.graphql
graphql/schema/testdata/schemagen/output/hasInverse-with-interface-having-directive.graphql
graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
graphql/schema/testdata/schemagen/output/hasInverse-with-type-having-directive.graphql
graphql/schema/testdata/schemagen/output/hasInverse.graphql
graphql/schema/testdata/schemagen/output/ignore-unsupported-directive.graphql
graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
graphql/schema/testdata/schemagen/output/interfaces-with-types-and-password.graphql
graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
graphql/schema/testdata/schemagen/output/no-id-field.graphql
graphql/schema/testdata/schemagen/output/password-type.graphql
graphql/schema/testdata/schemagen/output/searchables-references.graphql
graphql/schema/testdata/schemagen/output/searchables.graphql
graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
graphql/schema/testdata/schemagen/output/single-type.graphql
graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
graphql/schema/testdata/schemagen/output/type-reference.graphql

Just add the directive and updates schema gen tests.  
Doesn't do anything with the directive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5178)

graphql: Add `@auth` directive

---

wiki/content/howto/index.md

I deleted my fork and submitted this PR to fix some of the issues I was having. Hope this helps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5110)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9e0e0377e9-52523.surge.sh)

Document nginx load balancing

---

worker/draft.go

Just a small test PR because github is telling me that I am an admin of
the Dgraph repo but we are not sure why.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5218)

Fix grammar.

---

ee/acl/acl_test.go
graphql/admin/admin.go
graphql/admin/backup.go
graphql/admin/config.go
graphql/admin/draining.go
graphql/admin/export.go
graphql/admin/health.go
graphql/admin/login.go
graphql/admin/restore.go
graphql/admin/shutdown.go
graphql/admin/state.go
graphql/e2e/common/error.go
graphql/schema/response.go
graphql/schema/response_test.go
graphql/schema/wrappers.go
testutil/client.go

Removes a bunch of code and refactors how the admin endpoints work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5203)

graphql: refactor admin endpoints

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5112)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-736dd4cfb3-52537.surge.sh)

Docker swarm install improvements

---

graphql/e2e/common/subscription.go
task/conversion.go
upgrade/acl.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5225)

Fix deepsource warnings.

---

wiki/content/deploy/index.md

Fixes https://github.com/dgraph-io/dgraph/issues/5222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5223)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-72d5d2aea3-55487.surge.sh)

Fix broken links to binary backups

---

worker/draft.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5236)

Fix grammar and pharsing in comments in draft.go

---

wiki/content/deploy/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5201)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-69b8f44c92-55801.surge.sh)

docs: Add a section on glog format and query logging.

---

graphql/e2e/auth/auth_test.go
graphql/e2e/auth/docker-compose.yml
graphql/e2e/auth/schema.graphql
graphql/e2e/auth/test_data.json
graphql/resolve/auth-schema.graphql
graphql/resolve/auth_query_rewritter_test.go
graphql/resolve/auth_tests.yaml

Fixes #GRAPHQL-318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5229)

Added query rewriting and e2e tests

---

graphql/e2e/auth/auth_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5245)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d6d45137cf-56140.surge.sh)

graphql: skip all temp auth tests and make compile

---

graphql/schema/auth.go
graphql/schema/auth_schemas_test.yaml
graphql/schema/wrappers.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5210)

Parse and evaluate RBAC rules.

---

wiki/content/deploy/index.md

Related to #4741
Adding more information about the node health information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5239)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-63935c0480-56330.surge.sh)

docs: updating health information documentation

---

dgraph/cmd/bulk/mapper.go
gql/mutation.go
posting/index.go
worker/backup_processor.go
worker/draft.go
worker/export.go
x/keys.go
x/keys_test.go

Fixes #DGRAPH-1272
Fixes #5238 
Add 0 value UID checks and bail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5243)

Invalid UID checks

---

wiki/content/howto/index.md

PR for https://dgraph.atlassian.net/browse/DGRAPH-1245?atlOrigin=eyJpIjoiZmIxZGE1ZmVhOTlkNDAwYmE4YTkwZmI0MjlmMTEyMDUiLCJwIjoiaiJ9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5211)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6920af5c3d-55962.surge.sh)

Document Sentry Intergration

---

wiki/content/enterprise-features/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5109)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d7073c833e-55985.surge.sh)

Document encrypted backup process

---

dgraph/cmd/bulk/mapper.go
gql/mutation.go
posting/index.go
worker/backup_processor.go
worker/draft.go
worker/export.go
x/keys.go
x/keys_test.go

Fixes #DGRAPH-1272
Fixes #5238 
(cherry-picked from commit 09b2def0c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5251)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4f9d8952ab-56390.surge.sh)

Chery-pick Invalid UID checks (#5243)

---

dgraph/cmd/bulk/mapper.go
ee/backup/backup.go
ee/backup/backup_oss.go
gql/mutation.go
posting/index.go
worker/draft.go
worker/export.go
x/keys.go
x/keys_test.go

Fixes #DGRAPH-1272
Fixes #5238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5252)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-abf2181711-56463.surge.sh)

v1.2 Cherrypick - Invalid UID checks (#5243)

---

graphql/schema/auth.go
graphql/schema/auth_schemas_test.yaml
graphql/schema/schemagen_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5195)

Added test cases for auth schema parsing.

---

wiki/content/deploy/index.md

(cherry picked from commit cc07b80312a087f907d7916fd39da4b45dfa8af2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5274)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3320845063-57402.surge.sh)

release/v1.2: wiki: Add info about multiple zeros in HA (#5262)

---

dgraph/cmd/alpha/upsert_test.go
edgraph/server.go

Cherry-pick of #4767 to release/v1.2. Fixes #4712.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5277)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cfd9aa6a69-57521.surge.sh)

release/v1.2: Fix bug, aggregate value var works with blank node in upsert (#4767)

---

query/outputnode.go

`encoder()` has some repetitive code. This PR tries to simplify it for better readability and
understanding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5250)

Simplify encode()

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5267)

Update CHANGELOG for v1.2.3 and v20.03.1

---

.github/PULL_REQUEST_TEMPLATE.md

Edit phrasing for referencing Jira tickets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5295)

Update pull request template.

---

x/sentry_integration.go

(cherry picked from commit 4756f5c4569314019f57a07be6ed8f2717956df8)
Fixes DGRAPH-1270
This commit makes the following improvements:
1. Segregate dev and prod events into their own Sentry projects. 
2. Remove Panic back-traces 
3. Set the type of exception to the panic message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5305)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-aa8a016114-58685.surge.sh)

Cherry pick to v20.03 -  Sentry Improvements

---

graphql/authorization/auth.go
graphql/e2e/auth/schema.graphql
graphql/resolve/auth_test.go
graphql/resolve/mutation_rewriter.go
graphql/resolve/query_rewriter.go
graphql/schema/schemagen.go
graphql/web/http.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5269)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0b6a731f83-57237.surge.sh)

Parse auth meta info from schema.

---

worker/online_restore_ee.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5321)

Remove TODO that's been already done.

---

wiki/config.toml
wiki/content/deploy/index.md
wiki/content/releases/index.md
wiki/scripts/build.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5318)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-509975a5db-58978.surge.sh)

docs: backport recent doc commits to the 20.03 branch

---

graphql/e2e/custom_logic/cmd/.gitignore
graphql/e2e/custom_logic/cmd/Dockerfile
graphql/e2e/custom_logic/cmd/graphqlresponse.yaml
graphql/e2e/custom_logic/cmd/index.js
graphql/e2e/custom_logic/cmd/main.go
graphql/e2e/custom_logic/cmd/package-lock.json
graphql/e2e/custom_logic/cmd/package.json
graphql/e2e/custom_logic/custom_logic_test.go
graphql/schema/gqlschema.go
graphql/schema/remote.go
graphql/schema/rules.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5299)

add nested type checking to graphql custom logic

---

wiki/content/enterprise-features/index.md
wiki/content/howto/index.md

cherry-picks 
1. fac60ed
2. 2062a20
3. 0750a16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5330)

Cherry-pick v20.03 -  docs tickets

---

wiki/content/enterprise-features/index.md
wiki/content/howto/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5331)

Cherry pick v1.2 - Docs tickets

---

posting/mvcc.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5334)

Add a check to throw an error is a nil pointer is passed to unmarshalOrCopy

---

dgraph/cmd/zero/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5342)

Print error when applying enterprise license fails.

---

wiki/content/enterprise-features/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5345)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d6d3edeb03-60136.surge.sh)

Removing Bulk Loader Encryption content to Deploy

---

wiki/content/deploy/index.md
wiki/content/enterprise-features/index.md

Cherry pick
f68cea901cda96e64fd07b8adf7ea402566d1a7d
74ec2a4c4807c71d5faa7c4abcdba0be4c559562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5370)

Fixes DGRAPH-1216 cherry-pick for v20.03

---

wiki/content/deploy/index.md
wiki/content/enterprise-features/index.md

Cherry picks
f68cea901cda96e64fd07b8adf7ea402566d1a7d
74ec2a4c4807c71d5faa7c4abcdba0be4c559562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5371)

Cherry pick to v1.2

---

.github/labeler.yml
.github/workflows/label.yml

This adds a Github Actions "scripts" that will run every new PR. It will check for the files changes and add its respective Label automatically.
> I affectionately call it CL (Continuous Labeling)
>This requires no installations, just works out of the box.
No Jira.
No Breaking changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5365)

Adds Github Actions Labeler

---

wiki/README.md

Including the specific hugo version that the Dgraph docs work with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5325)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-613b3622bc-60836.surge.sh)

Update docs README.md.

---

worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5396)

Fix more empty string checks.

---

go.mod
go.sum
systest/backup/encryption/backup_test.go
systest/backup/minio-large/backup_test.go
systest/backup/minio/backup_test.go
testutil/minio.go
worker/backup_common.go
worker/s3_handler.go

This PR allows you to create backups with credentials provided from IAM roles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5387)

Checking IAM for permissions

---

graphql/authorization/auth.go
graphql/schema/schemagen.go
graphql/schema/wrappers_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5388)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c57ac668d0-62269.surge.sh)

Add Auth header to Allowed headers list

---

graphql/admin/schema.go

This PR makes sure that all schema related errors are reported during schema update.
Fixes #GRAPHQL-455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5425)

graphql: report all errors during schema update

---

graphql/e2e/auth/schema.graphql
graphql/e2e/auth/test_data.json
graphql/e2e/auth/update_mutation_test.go
graphql/resolve/mutation_rewriter.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5413)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-88a3f34b15-62558.surge.sh)

graphql: E2E Update mutation tests 

---

graphql/e2e/auth/schema.graphql
graphql/resolve/auth_query_test.yaml
graphql/resolve/auth_test.go
graphql/resolve/query_rewriter.go
graphql/schema/auth.go
graphql/schema/wrappers.go

Fixes GRAPHQL-457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5421)

Pre evaluate auth rule with missing variable.

---

graphql/e2e/auth/add_mutation_test.go
graphql/e2e/auth/auth_test.go
graphql/e2e/auth/schema.graphql
graphql/e2e/auth/test_data.json
graphql/e2e/auth/update_mutation_test.go
graphql/resolve/auth_add_test.yaml
graphql/resolve/mutation.go
graphql/resolve/mutation_rewriter.go

Added E2E tests for Add mutations in auth (#5391) and Update mutations in auth(#5413) 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5431)

graphql: E2E tests for Auth GraphQL

---

graphql/resolve/mutation.go
graphql/resolve/mutation_rewriter.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5434)

graphql: Changes evaluateRBAC to evaluateStatic

---

dgraph/cmd/live/batch.go
dgraph/cmd/live/run.go

Introduces ludicrous mode to live loader. It significantly reduces the memory utilized by live loader, and marginally increases ingestion speed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5419)

Adds ludicrous mode to live loader

---

graphql/authorization/auth.go
graphql/schema/wrappers_test.go
testutil/graphql.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5441)

Change auth tag in schema to Dgraph.Authorization.

---

graphql/e2e/auth/auth_test.go
graphql/e2e/auth/schema.graphql
graphql/e2e/auth/test_data.json
graphql/e2e/auth/update_mutation_test.go
graphql/resolve/auth_query_test.yaml
graphql/resolve/auth_test.go
graphql/resolve/query_rewriter.go
graphql/schema/auth.go

Fixes GRAPHQL-426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5433)

Add E2E test cases for missing JWT in auth.

---

CHANGELOG.md

update CHANGELOG for 1.2.4 and 20.03.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5447)

update CHANGELOG for 1.2.4 and 20.03.2

---

graphql/admin/admin.go
graphql/admin/schema.go
graphql/e2e/custom_logic/custom_logic_test.go
graphql/e2e/subscription/subscription_test.go
graphql/resolve/resolver.go
graphql/schema/gqlschema.go
graphql/schema/schemagen.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5448)

disable subscription

---

worker/snapshot_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5465)

Fix warnings about unused variables in snapshot_test.go

---

worker/online_restore_ee.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5466)

Remove completed TODO.

---

raftwal/storage.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5478)

Remove redundant conversions between string and []byte.

---

ee/acl/acl_test.go
graphql/admin/admin.go
graphql/admin/backup.go
graphql/admin/config.go
graphql/admin/draining.go
graphql/admin/export.go
graphql/admin/health.go
graphql/admin/login.go
graphql/admin/schema.go
graphql/admin/shutdown.go
graphql/admin/state.go
graphql/e2e/common/common.go
graphql/e2e/common/error.go
graphql/resolve/mutation.go
graphql/resolve/query.go
graphql/resolve/resolver.go
graphql/schema/response.go
graphql/schema/response_test.go
graphql/schema/wrappers.go
testutil/client.go

* graphql: refactor types returned by completion and execution (#5196)
* graphql: refactor admin endpoints (#5203)
(cherry picked from commit 285064a3cd7f3d895ebd5892fc2ce485c8e23970)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5480)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d24b3786d8-65308.surge.sh)

graphql: refactor execution pipeline (#5219)

---

graphql/admin/add_group.go
graphql/admin/admin.go
graphql/admin/schema.go
graphql/admin/update_group.go
graphql/dgraph/execute.go
graphql/e2e/common/error.go
graphql/resolve/mutation.go
graphql/resolve/mutation_rewriter.go
graphql/resolve/mutation_test.go
graphql/resolve/query.go
graphql/resolve/resolver.go
graphql/resolve/resolver_error_test.go

(cherry picked from commit 17a9c79d166384bfa731fc6063e593dc2aae8d04)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5482)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-30709247cf-65352.surge.sh)

graphql: execution refactor (#5244)

---

graphql/resolve/query_rewriter.go
graphql/resolve/query_test.yaml

(cherry picked from commit 4687538836f645a7ef26fd8f33b22cf8955c1520)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5483)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fc1e1421ec-65384.surge.sh)

graphql: fix password rewriting (#5256)

---

worker/executor.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5491)

remove dupe code

---

worker/executor.go

(cherry picked from commit 1e2f0e72d7c68d5b703faccb32a4a3a84d56b8e2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5490)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ad86b9534d-65620.surge.sh)

Cherry-pick v20.03: Fix panic for sending on a closed channel (#5479)

---

graphql/e2e/auth/auth_test.go
graphql/e2e/auth/delete_mutation_test.go
graphql/e2e/auth/schema.graphql
graphql/e2e/auth/test_data.json
graphql/e2e/auth/update_mutation_test.go
graphql/resolve/auth_delete_test.yaml
graphql/resolve/auth_test.go
graphql/resolve/mutation_rewriter.go
graphql/resolve/query_rewriter.go

Fixes GRAPHQL-459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5474)

graphql: Fixed delete RBAC and adds delete auth E2E test cases.

---

graphql/e2e/custom_logic/custom_logic_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5492)

Fix warnings about unkeyed literals.

---

worker/export.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5498)

Fix long lines in export.go

---

ee/acl/acl_test.go
graphql/admin/endpoints_ee.go

Fixes #GRAPHQL-456.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5499)

graphql: fix some TODOs in ACL tests

---

wiki/content/clients/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5504)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4f0d67310b-66005.surge.sh)

Add link for new client in Rust lang

---

go.mod
go.sum
worker/server_state.go

This PR updates badger and enables storing indices in the cache which was added via https://github.com/dgraph-io/badger/pull/1336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5537)

Update badger to commit e7b6e76f96e8

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5543)

CHANGELOG for 1.2.5 and 20.03.3

---

wiki/nginx/docs.conf

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5522)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0a7abe171e-66803.surge.sh)

added redirection rule in docs.conf file

---

wiki/content/deploy/index.md

https://dgraph.atlassian.net/browse/DGRAPH-1157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5420)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-aba573e336-62852.surge.sh)

Fixes DGRAPH-1157 adding helm upgrade content

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5563)

Updating release dates in the CHANGELOG

---

graphql/e2e/auth/auth_test.go

Fixes DGRAPH-1621
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5586)

graphql: fixes flaky test in authorization 

---

dgraph/cmd/zero/run.go

(cherry picked from commit fa5c3a32ac5f27e8640114b890395b08c12f022e)
Fixes DGRAPH-1368
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5595)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f170ed7909-69171.surge.sh)

release/v1.2 Add check on rebalance interval (#5544)

---

dgraph/cmd/zero/raft.go

(cherry picked from commit 0cd1e4dc2331cd8796983ddd95d1c557ac7c1f84)
Fixes DGRAPH-1141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5592)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5d8af29cb9-69124.surge.sh)

release/v1.2 Remove noisy logs in tablet move (#5333)

---

query/common_test.go
query/query3_test.go
query/shortest.go
wiki/content/query-language/index.md

Fixes #5426, #5410, #4861 
Fixes DGRAPH-1258 DGRAPH-794 DGRAPH-1369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5548)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-8122db646f-67541.surge.sh)

release/v20.03 K shortest paths queries fix and documentation update

---

dgraph/cmd/zero/run.go

(cherry picked from commit fa5c3a32ac5f27e8640114b890395b08c12f022e)
Fixes DGRAPH-1368
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5594)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c68fe465d6-69164.surge.sh)

release/v20.03 Add check on rebalance interval (#5544)

---

dgraph/cmd/zero/raft.go

(cherry picked from commit 0cd1e4dc2331cd8796983ddd95d1c557ac7c1f84)
Fixes DGRAPH-1141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5591)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1eef1fd2fb-69117.surge.sh)

release/v20.03 Remove noisy logs in tablet move (#5333)

---

contrib/update-badger.sh

The current `update-badger.sh` script does not work.  Made some changes:
* Use POSIX environment variable for `RELEASE_BRANCHES` as bash cannot use bash arrays outside of script execution
* Use `exit 1` when an error occurs.  Many of the errors were returning exit 0 indicating success, when it had actually failed.
* Fetch git user.name and user.email if these are set. Defaults can be overridden if `GIT_NAME` and `GIT_EMAIL` are set.
Affects DGRAPH-1633.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5618)

fixes for update-badger

---

wiki/scripts/local.sh

This change fixes errors for the CI check for shellcheck on release/v1.2.
(cherry picked from commit 266a4dda777cd45787b62e73e0c92cf6be551acc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5611)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5d3eb838b9-69527.surge.sh)

docs: Add shellcheck fix for preview scripts.

---

.github/PULL_REQUEST_TEMPLATE.md
.github/prlint.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5654)

chore: Adding PRLint

---

worker/draft.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5664)

Table size: Remove continue statement.

---

worker/draft.go
worker/executor.go

Cherry pick https://github.com/dgraph-io/dgraph/commit/47359526f887acdd1d49e646d20be39220e4a7b1 to branch `release/v20.03`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5635)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cafde7a1c4-70259.surge.sh)

Cherrypick rampmeter changes to release/v20.03

---

graphql/admin/add_group.go
graphql/admin/schema.go
graphql/admin/update_group.go
graphql/e2e/common/common.go
graphql/e2e/common/mutation.go
graphql/e2e/directives/schema.graphql
graphql/e2e/normal/schema.graphql
graphql/resolve/add_mutation_test.yaml
graphql/resolve/auth_test.go
graphql/resolve/mutation.go
graphql/resolve/mutation_rewriter.go
graphql/resolve/mutation_test.go
graphql/resolve/schema.graphql
graphql/resolve/update_mutation_test.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5667)

fix(GraphQL): Fixes OOM issue in graphql mutation rewriting 

---

graphql/admin/endpoints_ee.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5675)

fix(Restore): Make backupId optional in restore GraphQL interface.

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5686)

docs(changelog): Update for v20.07.0-beta.Jun22, v20.03.4, and v1.2.6.

---

wiki/content/enterprise-features/index.md

This adds a new section to the docs to explain the how-to steps to reset the groot user password.
Related: DGRAPH-761
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5676)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6a89e9f7ab-71908.surge.sh)

docs(Enterprise): How to reset forgotten groot password.

---

graphql/e2e/custom_logic/cmd/main.go
systest/loader/loader_test.go
systest/online-restore/online_restore_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5705)

fix(formatting): Apply "go fmt" to master.

---

wiki/content/enterprise-features/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5660)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-80bb6152ca-71814.surge.sh)

docs: Added example on how to deal with reverse edges when ACL is turned on

---

x/sentry_integration.go

Fixes DGRAPH-1692
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5674)

feat(sentry): Tag sentry events with additional version details.

---

dgraph/cmd/alpha/run.go
dgraph/cmd/zero/run.go
x/sentry_integration.go

Fixes DGRAPH-1689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5672)

chore(sentry): Sentry opt out banner.

---

dgraph/cmd/alpha/run.go
dgraph/cmd/zero/run.go
x/sentry_integration.go

Fixes DGRAPH-1689.
(cherry picked from commit eeb0dcbcad65ec0d73c174328b6b6f880ac7be6a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5727)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-29782df308-72811.surge.sh)

Cherry-pick v20.07: chore(sentry): Sentry opt out banner. (#5672)

---

wiki/content/mutations/index.md

Important doc update due to the new List-type feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4582)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e30fab4a3c-72482.surge.sh)

Update docs and add Facets in List-type with JSON and RDF

---

graphql/admin/endpoints_ee.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5685)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b55d2718bd-71657.surge.sh)

release/v20.07: Make backupId optional in restore GraphQL interface.

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5734)

docs(changelog): Update CHANGELOG for 20.07.0-beta.Jun29.

---

posting/size_test.go
posting/size_test.sh

Signed-off-by: Balaji <rbalajis25@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5754)

test: Replace the old 21million p directory with new one for the size test.

---

wiki/content/deploy/index.md
wiki/content/get-started/index.md
wiki/content/tutorial-1/index.md

PR dependent on https://github.com/dgraph-io/hugo-docs/pull/54
Fixes DGRAPH-1595
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5553)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-bb544ca547-67843.surge.sh)

docs: Add dynamic versioning for Dgraph docker tag.

---

posting/size_test.go

- Print the line when an error occurs in filterUnit.
- Raise the error threshold to 10%. With 5% the test fails some times
but most of the failures are in the 5 to 10 percent range. Setting it
to 10 fixed the flakiness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5783)

test: more fixes for the size test.

---

testutil/client.go

Some tests down and up alphas so connection issues are expected and the
tests should retry until the alpha comes back up.
Fixes DGRAPH-1618
(cherry-picked from commit 49a3fa97a41c858f6b8bc52a2c30d569b20d9f41)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5746)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-069599f5f2-73429.surge.sh)

(release/v20.07) test: Retry due to connection issues in RetryMutations and RetryQuery

---

posting/size_test.go
posting/size_test.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5781)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-503651ad32-74221.surge.sh)

release/v20.07 test: Cherry-pick fixes to size tests.

---

dgraph/cmd/alpha/run.go
ee/acl/acl_test.go
graphql/admin/admin.go
graphql/admin/endpoints_ee.go
graphql/admin/restore.go
graphql/admin/restore_status.go
graphql/admin/shutdown.go
systest/online-restore/online_restore_test.go
worker/backup_common.go
worker/online_restore.go
worker/online_restore_ee.go
worker/server_state.go
worker/worker.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5805)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2beaf30659-74947.surge.sh)

(release/v20.07) Cherry-pick changes needed for online restore.

---

wiki/content/_index.md
wiki/content/get-started/index.md
wiki/content/tutorial-2/index.md
wiki/content/tutorial-4/index.md
wiki/content/tutorial-5/index.md
wiki/content/tutorial-6/index.md
wiki/content/tutorials/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5785)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ff7d1c0037-74384.surge.sh)

docs: remove slack link

---

graphql/admin/add_group.go
graphql/admin/update_group.go
graphql/e2e/common/common.go
graphql/e2e/common/mutation.go
graphql/e2e/directives/schema.graphql
graphql/e2e/normal/schema.graphql
graphql/resolve/add_mutation_test.yaml
graphql/resolve/auth_add_test.yaml
graphql/resolve/auth_test.go
graphql/resolve/mutation.go
graphql/resolve/mutation_rewriter.go
graphql/resolve/mutation_test.go
graphql/resolve/schema.graphql
graphql/resolve/update_mutation_test.yaml

(cherry picked from commit 8a5477328a76289497ff933f5475e64cefc02895)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5854)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4562da69c0-75674.surge.sh)

fix(GraphQL): Fixes OOM issue in graphql mutation rewriting  (#5667)

---

CONTRIBUTING.md
x/init.go

Remove slack references from init and contributing page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5878)

chore: Remove slack references

---

wiki/content/deploy/index.md

* doc fixes for mTLS/TLS dgraph live, dgraph cert, curl
(cherry picked from commit cd454e5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5872)

doc: documentation TLS updates

---

wiki/content/deploy/index.md

Documentation update for Kubernetes updates and Helm Chart Instructions
Cherry-Pick #5771 into release/v20.03
* resolve merge conflicts
* brought in documentation on helm charts #4337 and #5420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5867)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-788f327b7d-76123.surge.sh)

doc update for k8s changes and helm chart addition

---

wiki/content/_index.md
wiki/content/enterprise-features/index.md
wiki/content/tutorial-1/index.md
wiki/content/tutorial-3/index.md
wiki/content/tutorial-7/index.md
wiki/content/tutorial-8/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5881)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b8ef5ddd82-76580.surge.sh)

V20.03.1/remove/slack forum

---

wiki/content/_index.md
wiki/content/get-started/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5879)

remove slack and change forum to community

---

wiki/content/_index.md
wiki/content/enterprise-features/index.md
wiki/content/get-started/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5887)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://)

remove slack link and change forum to community

---

wiki/content/_index.md
wiki/content/get-started/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5889)

remobe slack and change forum to community

---

graphql/admin/restore.go
graphql/schema/rules.go
graphql/schema/schemagen.go
worker/backup_common.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5797)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-944ec4f149-76755.surge.sh)

chore: run "go fmt" on master.

---

testutil/client.go

Some tests down and up alphas so connection issues are expected and the
tests should retry until the alpha comes back up.
Fixes DGRAPH-1618
(cherry-pick of 49a3fa97a41c858f6b8bc52a2c30d569b20d9f41)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5747)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9c32b8dfb1-73436.surge.sh)

(release/v20.03) test: Retry due to connection issues in RetryMutations and RetryQuery

---

systest/online-restore/online_restore_test.go

There's still some flakiness in the online restore tests caused by
the server being in draining mode. I suspect this happens when the
follower is behind and the check succeeds only for draining mode to be
enabled right after. Previously the test checked that the alpha was
not in draining mode once. This change now requires the alpha to
have draining mode disabled three consecutive times before allowing
queries to be sent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5898) …

(release/v20.07) test: Fix flakiness in online restore tests.

---

posting/size_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5869)

test: Handle kB units in size_test.go

---

wiki/content/deploy/index.md

Documentation update for Kubernetes updates and Helm Chart Instructions 
Cherry-Pick #5771 into release/v20.03
* resolve merge conflicts
* brought in documentation on helm charts #4337 and #5420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5866)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4e4311a70f-76115.surge.sh)

doc: wiki deploy update for k8s changes and helm chart addition

---

wiki/content/deploy/index.md

Cherry-Pick #5771 into release/v20.03
* resolved merge conflict that added #5420 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5865)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-54940e2aea-76109.surge.sh)

doc: wiki deploy update for k8s and corrects to helm chart instructions

---

wiki/content/enterprise-features/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5851)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fb34997ea7-76838.surge.sh)

docs: Documentation for online restores.

---

wiki/content/enterprise-features/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5901)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-99ae45def5-76964.surge.sh)

(release/v20.07) docs: Documentation for online restores.

---

README.md
wiki/content/_index.md
wiki/content/get-started/index.md

This is an update to the docs to better fit our updated marketing message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5938)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7951fc92b6-78130.surge.sh)

chore: Change first sentence in docs to be more GraphQL focused.

---

wiki/content/_index.md
wiki/content/get-started/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5955)

Removed slack reference and changed forum to community

---

wiki/content/_index.md
wiki/content/enterprise-features/index.md
wiki/content/get-started-old/index.md
wiki/content/get-started/index.md
wiki/content/tutorial-1/index.md
wiki/content/tutorial-2/index.md
wiki/content/tutorial-3/index.md
wiki/content/tutorial-4/index.md
wiki/content/tutorial-5/index.md
wiki/content/tutorial-6/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5964)

Removed Slack references and changed forum to community

---

wiki/content/_index.md
wiki/content/get-started/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5959)

Removed slack reference and changed forum text to community

---

worker/backup_common.go
worker/minio_client.go
worker/s3_handler.go

Companion PR for #5925
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5968)

refactor: Move common minio logic into a new file

---

go.mod
go.sum
worker/server_state.go

This commit brings following new changes from badger
```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh dd332b04e6e7...0dfb8b45d4a4
Force KeepL0InMemory to be true when InMemory is true (dgraph-io/badger#1375)
Tests: Use t.Parallel in TestIteratePrefix tests  (dgraph-io/badger#1377)
Remove second initialization of writech in Open (dgraph-io/badger#1382)
Increase default …

fix(badger): release/v20.03- Update badger to v20.07.0-rc1

---

worker/snapshot_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5952)

test: Add sleep to snapshot test

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5990)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4b6d1fbc34-79635.surge.sh)

(release/v1.2) fix(badger): update badger to v20.07.0-rc2

---

edgraph/access_ee.go
edgraph/acl_cache.go
ee/acl/acl_test.go
gql/parser.go
query/query.go

Fixes DGRAPH-1711
(cherry picked from commit 8ce08caae7c8614e6be8dd1381cce5a5057f47f8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5993)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2d55c9e26d-79656.surge.sh)

fix(Query): Fix expand(_all_) queries in ACL (#5733)

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5989)

fix(badger): Update badger to v20.07.0-rc2

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5991)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-72cc63e84b-79646.surge.sh)

(release/v20.03) fix(badger): update badger to v20.07.0-rc2

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5992)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fbb7250f72-79647.surge.sh)

(release/v20.07) fix(badger): update badger to v20.07.0-rc2

---

edgraph/access_ee.go
ee/acl/acl_test.go

Fixes DGRAPH-1711
(cherry picked from commit 144685a84c71723d7ec76fd4b29160959221fc44)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5995)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-68a3d21f24-79715.surge.sh)

fix(Query): Fix val queries when ACL is enabled #5945

---

testutil/backup.go
testutil/client.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6012)

chore: fix deepsource warnings in testutil package.

---

systest/21million/test-21million.sh

Missed it in the previous PR, correcting it now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6017)

fix(dgraph): Correct minor merge conflict

---

dgraph/cmd/bulk/systest/test-bulk-schema.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5981)

fix(dgraph): remove orphan containers in the docker compose

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6024)

docs(Changelog): Update for CHANGELOG 20.03.4

---

CHANGELOG.md

Co-authored-by: parasssh <paras@dgraph.io>
(cherry picked from commit 07f32ea8417120a153e2cbf32a03b1a1f9ecd976)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6025)

docs(Changelog): Update for CHANGELOG 20.03.4 (#6024)

---

worker/groups.go

(cherry picked from commit 3c46878bc98856e5129933b143668a07b4513903)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6028)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-690e951d0d-80515.surge.sh)

fix(dgraph): Panic because of nil map in groups.go (#5999)

---

go.mod
go.sum

```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh 3ffaf3cd1d4a...37ee16d8ad1c
Various bug fixes: Break up list and run DropAll func (dgraph-io/badger#1439) (dgraph-io/badger#1440)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6035) …

release/v20.03: Update badger to 37ee16d

---

go.mod
go.sum

```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh 3ffaf3cd1d4a...37ee16d8ad1c
Various bug fixes: Break up list and run DropAll func (dgraph-io/badger#1439) (dgraph-io/badger#1440)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6034) …

release/20.07: Update badger to 37ee16d

---

go.mod
go.sum

```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh 3ffaf3cd1d4a...37ee16d8ad1c
Various bug fixes: Break up list and run DropAll func (dgraph-io/badger#1439) (dgraph-io/badger#1440)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6041) …

release/v1.2: Update badger to 37ee16d

---

query/common_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5924)

fix(dgraph): add retry for schema update

---

CHANGELOG.md

Changelog in preparation of v20.07.0-rc1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6030)

docs(CHANGELOG): Update for 1.2.6 and 20.07.0 releases

---

CHANGELOG.md

Changelog for 20.07.0-rc1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6052)

Cherry-Pick v20.07 - doc(changelog): Changelog for 20.07.0-rc1

---

README.md

title says it all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6068)

docs(Readme): current version from 1.1 to 20.03.4

---

graphql/e2e/custom_logic/cmd/graphqlresponse.yaml
graphql/e2e/custom_logic/cmd/main.go
graphql/e2e/custom_logic/custom_logic_test.go

Fixes GRAPHQL-562.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6078)

chore(GraphQL): remove skipped tests

---

CHANGELOG.md

Changelog for 20.07.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6111)

chore(changelog): Changelog for 20.07.0

---

CHANGELOG.md

Changelog for 20.07.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6112)

Cherry-pick chore(changelog): Changelog for 20.07.0

---

Makefile
dgraph/Makefile
x/init.go
x/sentry_integration.go

The v20.07 codename is `shuri`. For example:
```
For example:
Dgraph version   : v20.07.0-2-g2af036ef9
Dgraph codename  : shuri
Dgraph SHA-256   : 4b0bb2ccbe0e2267c0ad3bd46570a46facfefd5c237ab6cf2948911cfebc0b18
Commit SHA-1     : 2af036ef9
Commit timestamp : 2020-07-28 15:27:14 -0700
Branch           : release/v20.07
Go version       : go1.14.4
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6114)

chore(version): Add codename to v20.07.

---

contrib/scripts/functions.sh
contrib/scripts/goldendata-queries.sh
dgraph/cmd/bulk/systest/test-bulk-schema.sh
systest/1million/test-reindex.sh
systest/21million/test-21million.sh
systest/bgindex/test-bgindex.sh

(cherry picked from commit fc5927bbbe9f13a9e15fa9ea62075df6120eb45d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6088)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-568a15ee23-82743.surge.sh)

chore: Add remove-orphans flag to docker compose and update tests to use python3 (#6059)

---

contrib/scripts/functions.sh
contrib/scripts/goldendata-queries.sh
dgraph/cmd/bulk/systest/test-bulk-schema.sh
systest/21million/test-21million.sh

(cherry picked from commit fc5927b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6089)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d688cdd732-82751.surge.sh)

 chore: Add remove-orphans flag to docker compose and update tests to use python3 (#6059) 

---

CHANGELOG.md

Changelog for 1.2.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6121)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-12aac4f857-83775.surge.sh)

chore(changelog): Changelog for v1.2.6

---

query/common_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6096)

fix v1.1 add retry for schema update (#5924)

---

systest/21million/run_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6103)

fix v1.1 fix(dgraph): add retry mechanism for 21million test (#5820)

---

worker/docker-compose.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6093)

fix v1.1 add cluster lables to the jaeger containers (#5951)

---

worker/snapshot_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6090)

v1.1 fix add sleep to snapshot test (#5952)

---

posting/mvcc.go

(cherry picked from commit aca09216f0cfa5a125a81235127285d45e2fe546)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6138)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a5848af343-84219.surge.sh)

Cherry pick v20.03: fix(rollups): rollup a batch if more than 2 seconds elapsed since last batch (#6118)

---

systest/21million/run_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6105)

fix 20.07 fix(dgraph): add retry mechanism for 21million test (#5820)

---

systest/21million/run_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6104)

fix 20.03 fix(dgraph): add retry mechanism for 21million test (#5820)

---

query/common_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6098)

fix v20.07 add retry for schema update (#5924)

---

query/common_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6097)

fix v20.03 add retry for schema update (#5924)

---

worker/docker-compose.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6095)

fix v20.07 add cluster lables to the jaeger containers (#5951)

---

worker/docker-compose.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6094)

fix v20.03 add cluster lables to the jaeger containers (#5951)

---

worker/snapshot_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6092)

fix v20.07 add sleep to snapshot test (#5952)

---

worker/snapshot_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6091)

fix v20.03 add sleep to snapshot test (#5952)

---

dgraph/cmd/alpha/http.go
dgraph/cmd/alpha/http_test.go
edgraph/server.go
x/x.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6153)

feat: add metrics cost to grpc and http header (#6148)

---

wiki/content/deploy/fast-data-loading.md
wiki/content/enterprise-features/binary-backups.md
wiki/content/enterprise-features/encryption-at-rest.md

Fixes DGRAPH-1304.
Vault docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6163)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f98083fc1d-85220.surge.sh)

docs(vault): Vault docs

---

wiki/content/deploy/fast-data-loading.md
wiki/content/enterprise-features/binary-backups.md
wiki/content/enterprise-features/encryption-at-rest.md

(cherry picked from commit ccbc89cd46c0787e2b3d19a610c4ca52f36248fa)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6182)

docs(vault): Vault docs (#6163)

---

posting/list.go

This reverts commit 9d7fc94c4c1e712cf6090581e7d35290c77b6d18.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6181)

chore(revert): Revert #6127

---

wiki/content/deploy/download.md
wiki/content/enterprise-features/encryption-at-rest.md
wiki/content/faq/index.md
wiki/content/howto/loading-csv-data.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6189)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ccf2ca96d9-86114.surge.sh)

fix(docs: Fix URL paths

---

contrib/integration/bank/main.go

`go run main.go --alpha=free-pull.grpc.us-east-1.aws.thegaas.com:443 --login=false --slash-token=<api-token>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6187)

chore: Suport running bank test against slash

---

wiki/content/graphql/api/multiples.md
wiki/content/graphql/custom/custom-overview.md
wiki/content/graphql/custom/mutation.md
wiki/content/graphql/quick-start/index.md
wiki/content/graphql/schema/schema-overview.md
wiki/content/graphql/todo-app-tutorial/todo-overview.md
wiki/content/slash-graphql/admin/drop-data.md
wiki/content/slash-graphql/admin/import-export.md
wiki/content/slash-graphql/admin/overview.md
wiki/content/slash-graphql/admin/schema.md
wiki/content/slash-graphql/introduction.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6190)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-787ef3394e-86137.surge.sh)

fix(docs): Change URL path to absolute

---

wiki/content/deploy/kubernetes.md

This is a documentation update for Prometheus to add further clarity as well as document an additional solution with Helm chart `stable/prometheus-operator` to install both Prometheus and Grafana.  There's an updated version of Kubernetes oriented Grafana dashboard for Dgraph deployed on Kubernetes.
**NOTE**: This documentation references code that will be available once #6128 is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6133) …

docs: kubernetes prometheus update

---

dgraph/cmd/zero/run.go

Related JIRA ticket: DGRAPH-2185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6198)

fix: Error message for invalid idx for dgraph zero

---

dgraph/cmd/zero/run.go

Cherry-pick
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6199)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-be20f2c78a-86322.surge.sh)

fix: error message for idx = 0 for dgraph zero (#6198)

---

wiki/content/graphql/api/fragments.md

Fixes GRAPHQL-611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6224)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3355a4a033-86851.surge.sh)

feat(docs): Add docs for GraphQL fragments.

---

wiki/content/graphql/api/variables.md

Fixes GRAPHQL-612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6223)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f1d95fc87a-86845.surge.sh)

feat(docs): Add docs for GraphQL variables.

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6220)

Update CHANGELOG for 20.07.1, 20.03.5, 1.2.7

---

go.mod
go.sum

See https://github.com/dgraph-io/badger/compare/v20.07.0...v2.2007.1 for changelog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6232)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b257cf8272-86995.surge.sh)

release/v20.07: Update badger to v2.2007.1

---

go.mod
go.sum

See https://github.com/dgraph-io/badger/compare/v20.07.0...v2.2007.1 for changelog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6231)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6109838946-86989.surge.sh)

release/v20.03: Update badger to v2.2007.1

---

CHANGELOG.md

Changelog fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6236)

Cherry-pick chore(changelog): Changelog fix

---

CHANGELOG.md

Changelog for 20.07.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6233)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-64dd8298c1-87037.surge.sh)

Cherry-pick chore(changelog): Changelog for 20.07.1

---

CHANGELOG.md

Changelog for 20.03.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6234)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7d119bd4a9-87044.surge.sh)

Cherry-pick chore(changelog): Changelog for v20.03.5

---

go.mod
go.sum

See https://github.com/dgraph-io/badger/compare/v20.07.0...v2.2007.1 for changelog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6230)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-22ca52fd9d-86981.surge.sh)

release/v1.2: Update badger to v2.2007.1

---

CHANGELOG.md

Changelog for v1.2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6235)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5d1b69a53e-87051.surge.sh)

Cherry-pick chore(changelog): Changelog for v1.2.7

---

graphql/resolve/query_rewriter.go
graphql/resolve/query_test.yaml
graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6205)

feat(GraphQL): Add has filter in Query Rewriter

---

wiki/content/slash-graphql/admin/_index.md
wiki/content/slash-graphql/advanced-queries.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6241)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5a3e435a12-87211.surge.sh)

doc: Adding docs about ratel and Slash

---

wiki/config.toml
wiki/content/graphql/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6222)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0bc99b25eb-86807.surge.sh)

Port GraphQL docs to v20.03

---

dgraph/cmd/alpha/run.go
dgraph/cmd/alpha/run_test.go
dgraph/cmd/bulk/systest/test-bulk-schema.sh
dgraph/cmd/live/load-uids/load_test.go
edgraph/server.go
ee/acl/acl_test.go
graphql/admin/admin.go
graphql/admin/cors.go
graphql/e2e/common/admin.go
graphql/e2e/common/common.go
graphql/e2e/common/error.go
graphql/e2e/directives/dgraph_directives_test.go
graphql/e2e/normal/normal_test.go
graphql/e2e/schema/schema_test.go
graphql/e2e/subscription/subscription_test.go
graphql/resolve/resolver.go
graphql/web/http.go
query/mutation.go
schema/schema.go
systest/backup/encryption/backup_test.go
systest/backup/filesystem/backup_test.go
systest/backup/minio/backup_test.go
systest/export/export_test.go
systest/mutations_test.go
systest/queries_test.go
worker/export.go
x/keys.go
x/x.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6270)

feat: add dynamic cors support (#6174) slash cheery pick

---

x/sentry_integration.go

Fixes DGRAPH-2248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6264)

fix panicwrap parent check

---

contrib/integration/bank/main.go

Changes:
* Log output all the time, not just for errors. This brings back the "Moving / MOVED" logs for successful txns.
* Fix Printf args.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6318)

chore(contrib/bank): Fix logging.

---

posting/list.go
posting/list_test.go

- Optimize splits by doing binary search.
- Clear the pack from the main list.
- Add more assertions to the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6303)

fix(Dgraph): Fix split posting list issues.

---

compose/compose.go

Specify the version for the Docker images used for Jaeger, Prometheus, Grafana,
and the Node Exporter. This is better than specifying "latest" since folks
using the compose tool could be running any version that they happen to pull at
the time which may not work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6139)

chore(compose): Specify version for tracing/metrics images.

---

posting/list.go
posting/list_test.go

(cherry picked from commit deded8bfc13a2949537e596d3807ec626790bbdc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6333)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4d98154594-90010.surge.sh)

(release/v20.03) fix(Dgraph): posting list fixes.

---

posting/list.go
posting/list_test.go

(cherry picked from commit deded8bfc13a2949537e596d3807ec626790bbdc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6332)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-86ae20741a-90003.surge.sh)

(release/v20.07) fix(Dgraph): posting list fixes.

---

posting/list.go
posting/list_test.go

(cherry picked from commit deded8bfc13a2949537e596d3807ec626790bbdc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6334)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f5be69b5b2-90033.surge.sh)

(release/v1.2) fix(Dgraph): posting list fixes.

---

go.mod
go.sum

This badger update brings the following changes from badger.
```
b41e77a Fix(cleanup): Avoid truncating in value.Open on error (#1465) (#1489)
a0d4903 fix(cleanup): Do not close cache before compaction (#1464) (#1488)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6292)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e6e92bbc2e-89030.surge.sh)

release/v1.2 - Update badger to v2.2007.2

---

edgraph/server.go

(cherry picked from commit 7857fa2cfc5388fa1f5787eea473ab900f51299a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6374)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-53f80ae8e8-91086.surge.sh)

Cherrypick(v20.07) : fix(dgraph): sentry nil pointer check (#6372)

---

edgraph/server.go

(cherry picked from commit 7857fa2cfc5388fa1f5787eea473ab900f51299a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6375)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-acd7602769-91092.surge.sh)

Cherrypick(v20.03): fix(dgraph): sentry nil pointer check (#6372)

---

graphql/e2e/auth/delete_mutation_test.go

Fixes GraphQL CI failure.
`./delete_mutation_test.go:418:14: undefined: getJWT`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6377)

fix(GraphQL): Fix GraphQL E2E test

---

wiki/content/slash-graphql/introduction.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6383)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-058d071adf-91383.surge.sh)

doc: Fix allignment for list items in Slash introduction page

---

compose/.gitignore
compose/compose.go

Add an --acl flag to create the ACL secret file and enable the ACL feature in
the cluster.
Set the --whitelist flag to true by default to set the whitelist option so
alters work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6376)

chore(compose): Simplify ACL setup and set whitelist by default.

---

wiki/content/slash-graphql/introduction.md
wiki/content/slash-graphql/one-click-deploy.md

(cherry picked from commit e165710e85888fadfab9e21212a9b3469abe574e and c68fad3b459a64fd4760f002e6c4883eaf85be13)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6384)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ca5bc2465e-91418.surge.sh)

doc: One-Click Documentation for Slash (#6381 #6383)

---

dgraph/cmd/alpha/http_test.go
edgraph/server.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6386)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-773b792782-91468.surge.sh)

add cost for mutation (#6311)

---

dgraph/cmd/zero/raft.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6395)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9c53262f3d-91774.surge.sh)

cheery-pick CID and license change

---

wiki/content/enterprise-features/binary-backups.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6345)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fdb0109355-90642.surge.sh)

docs: Add section on automating backups.

---

wiki/content/enterprise-features/binary-backups.md

(cherry picked from commit 0fab710fdc207075c5ea0a75a8cb2317a3b75ba4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6405)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0b09563c4a-91925.surge.sh)

(release/v20.07) docs: Add section on automating backups.

---

wiki/content/_index.md

This is how the homepage would look after this PR is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6418)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e2266c4019-92510.surge.sh)

chore(docs): Add a reference for Badger on the homepage for docs.

---

wiki/content/_index.md

Add a link to Badger from Dgraph docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6430)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-70df23cab7-92865.surge.sh)

chore(docs): Add badger to docs

---

ee/acl/acl_test.go

Added some tests which involve use of value variables in mutations, when ACL is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6393)

Add value variable tests

---

dgraph/cmd/bulk/reduce.go

Fixes DGRAPH-2310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6446)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6cb5589813-93391.surge.sh)

fix(bulk): Batch list in bulk loader to avoid panic

---

edgraph/server.go

I only fixed a small typo error. No impact of the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6441)

fixed small error in server.go

---

.github/labeler.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6472)

chore: Add more paths to track labels

---

systest/group-delete/group_delete_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6468)

test: retry getting client in TestNodes.

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6410)

CHANGELOG for RC2: 1.2.7, 20.03.5, 20.07.1

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6487)

Update CHANGELOG for 20.07.1, 20.03.5 and 1.2.7

---

CHANGELOG.md
dgraph/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6488)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0eeca6cbe7-94434.surge.sh)

Update Changelog and Codename for v20.07.1 release

---

systest/group-delete/group_delete_test.go

(cherry picked from commit 512c69bf7ebd94b3e2a970b520f8794c72afa92a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6483)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d9a51cc6dd-94341.surge.sh)

(release/v20.03) test: retry getting client in TestNodes.

---

graphql/admin/admin.go
graphql/e2e/schema/schema_test.go

…ion after drop all (#6268)
Fixes GRAPHQL-623
This PR fixes the "Internal error" response when querying the GraphQL schema after performing drop_all operation.
(cherry picked from commit d3bee33)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6525)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-defecaaf7d-94891.surge.sh)

release/v20.07: fix(GraphQL): fix internal error when doing GraphQL schema introspection after drop all #6268

---

dgraph/cmd/alpha/run.go
graphql/e2e/auth/auth_test.go
graphql/e2e/auth/debug_off/debug_off_test.go
graphql/e2e/auth/debug_off/docker-compose.yml
graphql/e2e/common/common.go
graphql/e2e/common/error.go
graphql/e2e/common/fragment.go
graphql/e2e/common/mutation.go
graphql/e2e/common/query.go
graphql/e2e/common/schema.go
graphql/schema/response.go
testutil/graphql.go
x/config.go

#6329 
Cherry-pick into v20.07
Actually cherry-pick has merge conflicts and failing tests hence raising a new PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6532)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f3b216a1f4-94988.surge.sh)

fix(GraphQL): Remove auth error from mutation.

---

compose/compose.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6537)

fix(compose): Limit containers mem to 32G by default in compose tool

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6542)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c5112a75a2-95288.surge.sh)

Changelog for v1.2.7

---

wiki/content/releases/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6568)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c0640c94d9-96122.surge.sh)

CP(v20.03): Update releases page

---

wiki/content/releases/index.md

(cherry picked from commit 512c0a9d39b32d4ccefa556f2204b8368626c6eb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6567)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6be97e5f49-96115.surge.sh)

CP(v20.07): Update index.md (#6566)

---

gql/parser.go
query/common_test.go
query/query.go
query/query0_test.go
query/query_facets_test.go
worker/stringfilter.go
worker/task.go
worker/tokens.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6453)

feat(query): Support for between func at root

---

wiki/config.toml
wiki/content/releases/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6571)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5ee14d00e1-96195.surge.sh)

Release section in config.toml

---

wiki/config.toml
wiki/content/releases/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6570)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-8afb4cd3ed-96189.surge.sh)

CP(1.2): release page

---

wiki/content/get-started/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6066)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-363aaf551d-82081.surge.sh)

fix(docs): Grammar nits in Getting Started

---

wiki/content/graphql/directives/index.md
wiki/content/graphql/schema/types.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6369)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-8a4f49d5bb-97031.surge.sh)

docs: GraphQL password type.

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6612)

Fix dates in Changelog

---

x/x_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6605)

test: add more tests for ToHex function.

---

wiki/content/slash-graphql/admin/clone.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6620)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-079df77318-98246.surge.sh)

docs: add documentation for clone backend

---

compose/.gitignore
compose/compose.go

This PR adds a bunch of flags to the `compose` tool.
* `--tls_dir` option to set up a cluster with TLS using the provided TLS directory (default: "")
* `--vmodule` flag to set the glog `vmodule` flag to set the log verbosity. (default: "")
* `--encryption` flag to create an encryption key and use that on the cluster. (default: false)
* `--ludicrous_mode` flag to turn on ludicrous mode for both Zeros and Alphas. (default: false)
* `--snapshot_after` flag to set Alpha's `snapshot_after` flag for Raft snapshots. (default: "")
* `--expose_ports` flag to choose whether or not to expose the Docker ports to the host. Turning this off is useful when running many containers without worrying about port conflicts. (default: true)
* `--names` flag to choose whether container names should be set. …

chore(compose): Add more flags to compose tool.

---

systest/group-delete/group_delete_test.go

(cherry picked from commit 512c69bf7ebd94b3e2a970b520f8794c72afa92a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6484)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ac3b35a334-94348.surge.sh)

(release/v1.2) test: retry getting client in TestNodes.

---

wiki/content/enterprise-features/binary-backups.md

- Explicitly differentiate between online and offline restores.
- Add more details about the online restores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6642)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b7eb69f5d5-98839.surge.sh)

docs: Update restore documentation.

---

worker/backup_handler.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6668)

fix: allow passing credentials for list backups

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6669)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-56d02827f0-99965.surge.sh)

release/v20.07 - Update badger to 5e3d4b9

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6670)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ee6317c602-99979.surge.sh)

release/v20.03 - Update badger to 5e3d4b9

---

wiki/content/enterprise-features/binary-backups.md

Fixes DGRAPH-2548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6664)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-648b7092b0-99641.surge.sh)

docs: Document restoreStatus GraphQL endpoint.

---

graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6685)

fix(GraphQL): fix schema tests by adding geo type info to output of clean schema string.

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6671)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-29e0345dda-99985.surge.sh)

release/v1.2 - Update badger to 5e3d4b9

---

worker/task.go

Fixes DGRAPH-2491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6607)

fix(worker): Avoid panic in handleUidPostings

---

worker/backup_processor.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6703)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-dc4d869dea-100822.surge.sh)

perf(backup): Reduce number of goroutines in backup

---

wiki/content/enterprise-features/access-control-lists.md

Fixes DGRAPH-2245
This PR adds:
- details on how to run Dgraph in Enterprise mode
- more ACL examples (mutations/queries)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6696)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c85fb8873a-100596.surge.sh)

docs: add ACL examples and information

---

graphql/e2e/subscription/subscription_test.go

(cherry picked from commit b4c6a7314fa01fff18f8f190a2cf3078401d54f6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6733)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b7a5abfd0a-101879.surge.sh)

fix(GraphQL): fixes flaky test  for subscriptions. (#6065)

---

graphql/admin/schema.go
graphql/schema/gqlschema.go
graphql/schema/schemagen.go
graphql/schema/schemagen_test.go
graphql/schema/testdata/schemagen/input/filter-cleanSchema-all-empty.graphql
graphql/schema/testdata/schemagen/input/filter-cleanSchema-circular.graphql
graphql/schema/testdata/schemagen/input/filter-cleanSchema-custom-mutation.graphql
graphql/schema/testdata/schemagen/input/filter-cleanSchema-directLink.graphql
graphql/schema/testdata/schemagen/input/hasInverse-with-interface-having-directive.graphql
graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql

(cherry picked from commit 5ab44c453b28a32bb853819f85381b4cbe0c6dd0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6734)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-642fff0067-101885.surge.sh)

Feat(GraphQL): This PR add enable schema cleaning in GraphQL and reduce schema update time. (#6666)

---

graphql/subscription/poller.go

(cherry picked from commit b2d26971aaaf73c00cf78ebc46de3b333aa9a091)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6735)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6e4dbbc5c9-101892.surge.sh)

fix(GraphQL): This PR reduces polling duration of subscriptions. (#6661)

---

wiki/content/graphql/schema/ids.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6592)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-788b1b9a13-97192.surge.sh)

chore: Add note that @id directive must be string type 

---

wiki/content/slash-graphql/security.md

Backport doc fix (GQLSAAS-794)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6745)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-8c58d8cc1a-102266.surge.sh)

doc(fix): security.md

---

posting/list.go
systest/mutations_test.go

The iterate method does not account for delete postings in the same transaction
so they have to be preserved manually. Otherwise, if a deletion and an add operation
to the same uid happen in the same predicate, the deletion operation is not
applied.
Fixes DGRAPH-1309
(cherry picked from commit 56c8f3c670052ee999d1a77fbc351cc6159ea6ce)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6746)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-22e827e491-102287.surge.sh)

(release/v1.2) fix(Dgraph): fix bug when deleting and adding to a single UID predicate in the same transaction.

---

wiki/content/query-language/kshortest-path-quries.md

Fix DGRAPH-2559
This PR adds a graph traversal example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6759)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d8fe9ad3b0-102613.surge.sh)

docs:  add a graph traversal example

---

dgraph/cmd/alpha/run.go
edgraph/graphql.go
go.mod
graphql/admin/cors.go
graphql/e2e/common/admin.go
query/query.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6761)

fix: correct spelling of "retrieve"

---

dgraph/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6771)

build: Update codename to shuri-2 for v20.07.2.

---

wiki/content/releases/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6787)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-81d488ffc6-103716.surge.sh)

Update for 20.07.2 and 20.03.6

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6778)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d5548a2609-103467.surge.sh)

Add Changelog for 20.03.6

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6777)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b7d618e261-103454.surge.sh)

Add Changelog for 20.07.2

---

wiki/config.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6792)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d44c74fd74-103940.surge.sh)

docs(Slash):Fix relative path

---

wiki/content/mutations/delete.md

Cherry-pick of fixes to this file from PR #6657
Fixes GRAPHQL-751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6798)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d87d82202e-104130.surge.sh)

Cherry-pick (docs) v20.07: Update docs to note that only typed data can be deleted using `S * *`

---

worker/backup_ee.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6805)

security: Stop logging AWS secrets

---

graphql/e2e/directives/docker-compose.yml
graphql/e2e/normal/docker-compose.yml

This PR fixes the test docker-compose files for lambda service to match the latest docker image for lambda.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6807)

fix(GraphQL): fix lambda service

---

graphql/e2e/auth/auth_test.go
graphql/e2e/auth/schema.graphql
graphql/resolve/auth_query_test.yaml
graphql/resolve/query_rewriter.go
graphql/resolve/query_test.yaml
graphql/schema/auth.go
graphql/schema/testdata/schemagen/output/auth-on-interfaces.graphql
graphql/schema/testdata/schemagen/output/union.graphql
graphql/schema/wrappers.go

Fixes GRAPHQL-660.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6781)

feat(GraphQL): Auth on Interfaces should work correctly while querying them.

---

codec/codec.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6795)

fix(Dgraph): pointer misalignment in packBlock()

---

worker/groups.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6793)

fix(Dgraph): race condition in EnterpriseEnabled()

---

wiki/config.toml
wiki/content/_index.md

link to the new Slash home page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6825)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-789df42708-105782.surge.sh)

docs: Update Slash links

---

worker/task.go

Fixes DGRAPH-2491
(cherry picked from commit f77cfe34ebd289806097b682a78bb4952cb2e0eb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6701)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ee03ba4d9b-100741.surge.sh)

release/v20.07 - fix(worker): Avoid panic in handleUidPostings (#6607)

---

worker/task.go

Fixes DGRAPH-2491
(cherry picked from commit f77cfe34ebd289806097b682a78bb4952cb2e0eb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6700)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-584cc16f0b-100734.surge.sh)

release/v20.03 - fix(worker): Avoid panic in handleUidPostings (#6607)

---

worker/task.go

Fixes DGRAPH-2491
(cherry picked from commit f77cfe34ebd289806097b682a78bb4952cb2e0eb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6699)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7117b7ac35-100726.surge.sh)

release/v1.2 - fix(worker): Avoid panic in handleUidPostings (#6607)

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6780)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d94c49be6f-103564.surge.sh)

docs: Add Changelog for 1.2.8

---

graphql/e2e/common/common.go
graphql/e2e/common/error_test.yaml
graphql/e2e/common/mutation.go
graphql/e2e/directives/schema.graphql
graphql/e2e/directives/schema_response.json
graphql/e2e/normal/schema.graphql
graphql/e2e/normal/schema_response.json
graphql/schema/validation_rules.go

Fixes GRAPHQL-690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6823)

Fix(GraphQL): This PR fixes the bug which return error when we input list of integers.

---

systest/ludicrous/upsert_test.go
worker/draft.go

Post mortem of issue: https://discuss.dgraph.io/t/dgraph-missing-mutations-in-ludicrous-mode-post-mortem/11019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6797)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ca6a69e997-105817.surge.sh)

chore: Cherry picks for DGRAPH-2446

---

test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6824)

chore: Allow test.sh to run specific tests

---

testutil/zero.go
tlstest/mtls_internal/backup.env
tlstest/mtls_internal/backup/encryption/backup_test.go
tlstest/mtls_internal/backup/encryption/docker-compose.yml
tlstest/mtls_internal/backup/filesystem/backup_test.go
tlstest/mtls_internal/backup/filesystem/docker-compose.yml
tlstest/mtls_internal/backup/minio-large/backup_test.go
tlstest/mtls_internal/backup/minio-large/docker-compose.yml
tlstest/mtls_internal/backup/minio/backup_test.go
tlstest/mtls_internal/backup/minio/docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6802)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-179069342a-106060.surge.sh)

test(dgraph): Adding backup test cases in internal tls enabled

---

wiki/content/clients/_index.md
wiki/content/deploy/_index.md
wiki/content/dql/_index.md
wiki/content/enterprise-features/_index.md
wiki/content/graphql/_index.md
wiki/scripts/build.sh

This PR simplifies the version list available on the Docs sidebar's drop-down menu
Fixes DGRAPH-2583
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6835)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a644bcc62f-106252.surge.sh)

docs (chore): Clean the sidebar's dropdown menu 

---

wiki/content/graphql/custom/graphqlpm.md
wiki/content/query-language/fragments.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6859)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-94c302059b-107254.surge.sh)

 DQL (Docs):GraphQL -> DQL fixes II, clean-up from #6858 (forgot to push two typo fixes before merging)

---

contrib/manual_tests/README.md
contrib/manual_tests/test.sh

Adding a test for increment. The test runs increment in a loop with 1, 2, and finally 3 Alpha groups, and verifies that they always produce the correct value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6840)

chore: Add manual test for increment (DGRAPH-2613)

---

README.md
wiki/content/releases/index.md

Motivation:
Change latest version of Dgraph in README file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6861)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6444555ec2-107363.surge.sh)

Chore(Readme): Fix Dgraph latest version in README

---

dgraph/main.go
go.mod
go.sum
posting/index.go
query/outputnode.go
worker/draft.go
xidmap/trie.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6853)

chore: Update Badger to release/v3.2011 and Ristretto to latest master (DGRAPH-2630)

---

wiki/content/clients/raw-http.md
wiki/content/dql/_index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6863)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6645715955-107609.surge.sh)

DQL (docs) straggler "graphql+-" references to update

---

wiki/content/graphql/queries/persistent-queries.md

This PR adds documentation for the new Persistent query feature
Fixes GRAPHQL-723
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6852)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3fb0bdde98-107407.surge.sh)

docs (feat): Create documentation for Persistent Queries

---

wiki/content/enterprise-features/binary-backups.md

(cherry picked from commit ed481b14b732567a9f2baa0f817079032c2eaa13)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6682)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f5addfc1de-100158.surge.sh)

(release/v20.07) docs: Document restoreStatus GraphQL endpoint.

---

wiki/content/enterprise-features/binary-backups.md

(cherry picked from commit a86b4d8933abc11c14914f909cbd27ba80b912b3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6683)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-60db9682b9-100166.surge.sh)

(release/v20.07) docs: Document listBackups GraphQL endpoint.

---

Makefile
dgraph/Makefile

Setting the codename in the release/v20.11 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6882)

build: Set codename for v20.11.

---

dgraph/main.go
go.mod
go.sum
posting/index.go

Update badger to the latest release/v3.2011 to fix a memory leak in Badger stream (https://github.com/dgraph-io/badger/pull/1593)
Changes:
* Update Badger to dgraph-io/badger@e002a9d
* Quiet logs for tmp badger dbs in reindexing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6883)

fix(badger): Update Badger stream memory leak.

---

contrib/jepsen/Makefile
contrib/jepsen/main.go
dgraph/cmd/zero/oracle.go
dgraph/main.go
edgraph/server.go
go.mod
go.sum
raftwal/meta.go
x/x.go

- Decrease size of key commit file and rename it.
- Don't run Jaeger by default in Jepsen.
- If indexing is in progress, add an artificial one second delay to block the caller.
- Improve logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6889)

Small Improvements to make Jepsen run better

---

graphql/authorization/auth.go
graphql/schema/schemagen.go

Fixes GRAPHQL-790.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6891)

fix(GraphQL): change Default client to Client with timeout for fetching JWKs

---

wiki/content/graphql/schema/search.md

Fix a typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6900)

docs (chore): Fix typo

---

systest/plugin_test.go
t/main.go

Make it compile Dgraph and run with --j=2. Also, do a better job at scheduling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6914)

Improve test script

---

t/main.go

With this change, tests finish in 6m30s on my machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6915)

Set j=3 for tests

---

graphql/authorization/auth.go
graphql/schema/schemagen.go

…ng JWKs (#6891)
Fixes GRAPHQL-790.
(cherry picked from commit 4aa17fa5928fadaf9533c31b6b96641b7480d3c2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6904)

fix(GraphQL): change Default client to Client with timeout for fetching JWK

---

dgraph/docker-compose.yml
systest/backup/minio-large/backup_test.go
systest/backup/minio-large/docker-compose.yml
systest/backup/minio/backup_test.go
systest/backup/minio/docker-compose.yml
systest/export/docker-compose.yml
systest/export/export_test.go
systest/online-restore/docker-compose.yml
t/main.go
tlstest/acl/acl_over_tls_test.go
tlstest/mtls_internal/acl/acl_over_tls_test.go
tlstest/mtls_internal/acl/docker-compose.yml
tlstest/mtls_internal/backup/encryption/backup_test.go
tlstest/mtls_internal/backup/encryption/docker-compose.yml
tlstest/mtls_internal/backup/filesystem/backup_test.go
tlstest/mtls_internal/backup/filesystem/docker-compose.yml
tlstest/mtls_internal/backup/minio-large/backup_test.go
tlstest/mtls_internal/backup/minio-large/docker-compose.yml
tlstest/mtls_internal/backup/minio/backup_test.go
tlstest/mtls_internal/backup/minio/docker-compose.yml
tlstest/mtls_internal/ha_6_node/docker-compose.yml
tlstest/mtls_internal/ha_6_node/ha_test.go
tlstest/mtls_internal/loader/docker-compose.yml
tlstest/mtls_internal/multi_group/docker-compose.yml
tlstest/mtls_internal/multi_group/multi_group_test.go
tlstest/mtls_internal/online-restore/docker-compose.yml
tlstest/mtls_internal/online-restore/online_restore_test.go
tlstest/mtls_internal/single_node/docker-compose.yml
tlstest/mtls_internal/single_node/single_node_test.go

this fixes test cases which are failing with new go script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6911)

chore(test):fixing test cases to work with go script

---

netlify.toml
wiki/scripts/build.sh

Add a `netlify.toml` file and update the docs build script to support deploying via Netlify.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6929)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2f34956408-110258.surge.sh)

docs: Deploy on Netlify.

---

graphql/admin/admin.go
graphql/e2e/subscription/subscription_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6934)

fix(GraphQL): This PR cherryPick fix of  subscription flakey Tests to 20.11.

---

ee/acl/acl_test.go

This test was adding a user to multiple groups, but after adding a user to a particular group, to check that the group should be present in the admin `updateUser` GraphQL response, it was comparing the exact response of the admin call to match only the name of the particular group. This resulted in the failure of this test because there can also be other groups present in the response.
This PR fixes this test to only check that the group which is required to be present in the response is present in the response, and ignore other groups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6941)

fix(test): TestCrossGroupPermission (DGRAPH-2759)

---

graphql/e2e/common/common.go
graphql/resolve/query_rewriter.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6946)

fix(GraphQL): fix e2e test for multiple alias

---

wiki/content/releases/index.md

Motivation:
Change latest release version in wiki.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6862)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5f519ab7a0-107948.surge.sh)

Chore(wiki): Change latest release version in wiki

---

graphql/e2e/common/common.go
graphql/e2e/custom_logic/custom_logic_test.go
systest/export/export_test.go
t/main.go
testutil/client.go
tlstest/mtls_internal/ha_6_node/ha_test.go
worker/export_test.go

this PR fixes multiple flaky tests we are seeing with the integration of go script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6937)

chore(tests): fixing flaky tests

---

graphql/admin/admin.go
graphql/e2e/subscription/subscription_test.go

(cherry picked from commit 9cfe69c9d81ccdd9f26a5b5048607e956e609ea1)

fix(GraphQL): This PR fixes flaky subscriptions tests in 20.07.

---

dgraph/cmd/alpha/http_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6960)

Make TestHttpCompressionSupport run correctly

---

ee/acl/acl_test.go

This PR updates `TestGuardianOnlyAccessForAdminEndpoints` to check that the errors returned from the server contain the expected error instead of matching the whole error string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6963)

test: Refactor tests to be more resilient

---

graphql/e2e/schema/schema_test.go
systest/backup/encryption/backup_test.go
systest/backup/filesystem/backup_test.go
systest/backup/minio-large/backup_test.go
systest/backup/minio-large/docker-compose.yml
systest/backup/minio/backup_test.go
systest/online-restore/docker-compose.yml
testutil/client.go

This PR aims to fix flakyness in test cases.
1. TestSchemaSubscribe. The error was "There's no GraphQL schema in Dgraph.". Its an intermittent state and we should retry for this.
2. Other test cases are failing because of file not found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6968)

chore(test): fixing failing CI tests

---

x/init.go

remove slack ref in `init.go`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6975)

remove ref to slack in init.go

---

x/init.go

removed slack ref from init.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6976)

removed slack ref

---

dgraph/cmd/zero/oracle.go
dgraph/cmd/zero/raft.go

* add(log): Add num committed entries in purge log.
* add(log): Log if proposal took >1s to apply.
* remove(log): Remove Request readctx log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6993)

chore: Add log info for time taken in Zero proposals.

---

go.mod
go.sum

dgraph-io/badger@3d225d7
- Bug Fix: Create the right txn based on Badger mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6994)

fix: Bring in Badger bug fix for log file error.

---

dgraph/docker-compose.yml
ee/acl/acl_test.go
graphql/e2e/common/common.go
graphql/e2e/schema/schema_test.go
graphql/e2e/subscription/subscription_test.go
testutil/client.go
tlstest/mtls_internal/single_node/single_node_test.go
worker/export_test.go

This PR aims to fix flaky test cases we are seeing in team city
This fixes:
TestExportJson
TestCrossGroupPermission
TestClusterSetup
TestFailedLogin
TestSchemaSubscribe
TestQueryUserInfo
TestExportFormat
TestSubscription
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6997)

chore(test): fixing flaky test cases

---

wiki/content/graphql/lambda/overview.md

Fixes DGRAPH-880
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6978)

docs (fix): Update lambda resolvers documentation

---

gql/fuzzit.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7029)

release/1.2 - chore: Fix gql fuzz tests

---

gql/fuzzit.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7028)

release/20.03 - chore: Fix gql fuzz tests

---

gql/fuzzit.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7027)

release/20.07 - chore: Fix gql fuzz tests

---

wiki/content/deploy/fast-data-loading.md

Update ludicrous mode details
Fixes DGRAPH-2233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7021)

docs (chore): Update Live Loader's ludicrous mode notes

---

gql/fuzzit.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7026)

release/20.11 - chore: Fix gql fuzz tests

---

dgraph/cmd/root.go
dgraph/cmd/version/version_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7043)

release/v20.11-slash: fix: Undo normalization of glog files

---

gql/fuzzit.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7044)

release/v20.11-slash: chore: Fix gql fuzz tests

---

wiki/content/deploy/ludicrous-mode.md

Fixes DGRAPH-2531
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7041)

docs (chore): Minor adjustments to Ludicrous mode

---

graphql/e2e/common/admin.go

(cherry picked from commit 0b9eb4adec930bbea1c2ade96d4d150eb8d91b3c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7030)

release v20.07: don't compare counter in successive state calls (#6967)

---

graphql/e2e/common/admin.go

(cherry picked from commit 0b9eb4adec930bbea1c2ade96d4d150eb8d91b3c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7031)

release v20.03: don't compare counter in successive state calls (#6967)

---

go.mod
go.sum

Update Badger to bring in fixes to reduce memory usage during snapshot streaming. https://github.com/dgraph-io/badger/compare/3d225d79b515...70088c6e3493
- Keep the cheaper parts of the index within table struct. (dgraph-io/badger#1608)
- Fix(OOM): Reuse pb.KVs in Stream (dgraph-io/badger#1609)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7050)

fix(badger): Update Badger to fix OOMs.

---

wiki/content/graphql/queries/search-filtering.md

Adjust markdown formatting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7056)

docs (chore): adjust search-filtering.md format

---

wiki/content/graphql/todo-app-tutorial/todo-auth0-jwt.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7057)

docs (fix): Update Dgraph authorization format in tutorial (#6442)

---

netlify.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7061)

build: Ignore netlify build if changes not done in wiki

---

netlify.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7063)

Remove path since base is set

---

go.mod
go.sum

- Opt(pickTables): Fix an optimization regression (dgraph-io/badger@74f2e0277ca4830953fa3e43e7cd64bf1bc785b6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7058)

perf(badger): Update Badger to fix optimization regression.

---

dgraph/cmd/debug/run.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7067)

fix(debug): Set cache for encrypted directories.

---

go.mod
go.sum
worker/backup_processor.go
worker/predicate_move.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7068)

Fix(OOM): Use z.Allocator again

---

graphql/e2e/common/admin.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7071)

test: Fix health test.

---

go.mod
go.sum

This PR brings in 2 small (but important) changes from badger:
[fix(compaction): fix table size estimation on compaction (#1613)](https://github.com/dgraph-io/badger/commit/f492aa38111d551bda6ffc0c263ceed9ec728117)
[Fix typo in width calculation while creating split.](https://github.com/dgraph-io/badger/commit/6142e81c26a8cddf489144ec9746ff8bafd56e75)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7075)

update badger to bring in minor fixes

---

wiki/content/deploy/cluster-setup.md

This is a rephrase PR of https://github.com/dgraph-io/dgraph/pull/6981 that was merged by mistake
Fixes SUCCESS-145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7055)

[docs] : rephrase for "--replicas" flag usage (related to PR: #6981)

---

wiki/content/deploy/production-checklist.md
wiki/content/mutations/upsert-block.md

* Fix typos in upsert and deploy docs.
* Update backup policy section to link to docs for backups (enterprise feature) and data exports (open-source feature).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7088)

docs: Fix typos. Update backup policy section.

---

netlify.toml

https://community.netlify.com/t/build-netlify-only-if-base-dir-changes/27694/7
Build was cancelled as we can see in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7091)

build: Ignore build if changes not done in wiki folder

---

t/t.go

fix is to download resources if the requested suite is all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7101)

fix(test): fixing test for all suite

---

graphql/admin/admin.go

* fix: added comment docstring for ExportInput format
(cherry picked from commit 072b03ecb8bed934865444afc0f157b7d78c9fb7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7099)

fix: added comment docstring for ExportInput format (#6991)

---

netlify.toml

https://community.netlify.com/t/build-netlify-only-if-base-dir-changes/27694/7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7093)

build: ignore netlify build if wiki folder is not changed

---

x/x.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7114)

chore(GC): Increase discard ratio from 0.7 to 0.9

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7115)

Update badger to master

---

wiki/content/deploy/_index.md
wiki/content/deploy/dgraph-administration.md
wiki/content/deploy/fast-data-loading/_index.md
wiki/content/deploy/fast-data-loading/bulk-loader.md
wiki/content/deploy/fast-data-loading/live-loader.md
wiki/content/deploy/fast-data-loading/overview.md
wiki/content/deploy/kubernetes.md
wiki/content/deploy/ports-usage.md
wiki/content/mutations/batch-mutations.md

Fixes DGRAPH-2803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7121)

docs (feat): Add live loader upsert predicate example

---

wiki/content/deploy/fast-data-loading/live-loader.md

Fix RDF examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7124)

docs (fix): Update RDF example code in live-loader

---

query/query.go

(cherry picked from commit 2b7722dbd3fcd964598e63039fe35abf15174bb2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7131)

v20.11: chore: Revert the trace format changes (#7129)

---

go.mod
go.sum

This PR is meant to fix the zero vptr issue present in Badger.
See https://github.com/dgraph-io/badger/pull/1620 for more context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7134)

fix: Update badger

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7136)

release/20.11 - fix: Update badger

---

wiki/content/deploy/index.md

added examples on how to turn on query logging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7079)

[docs] rephrase query logging + examples

---

posting/lists.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7140)

fix(race): fixing race condition in localcache

---

CHANGELOG.md

updating changelog for release 20.11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7146)

adding changelog for release 20.11

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7152)

chore(docs): updating docs latest version

---

dgraph/cmd/bulk/reduce.go
dgraph/cmd/bulk/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7155)

fix(bulk): fixing bulk loader when encryption + mtls is enabled (#7154)

---

query/query.go

This PR fixes the race condition in process subgraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7156)

fix(dgraph): fixing race condition in process subgraph

---

graphql/admin/admin.go
graphql/admin/schema.go
graphql/resolve/resolver.go
graphql/subscription/poller.go

Fix race conditions by adding appropriate locks and synchronizing access.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7141)

fix(GraphQL): Fix race conditions found in tests

---

wiki/content/enterprise-features/binary-backups.md

Fixes DGRAPH-2815
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7162)

docs (fix): Add decryption key information to binary-backups.md

---

systest/bulk_live/common/bulk_live_cases.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7175)

chore(systest): add missing variable to RunLiveCases

---

dgraph/cmd/bulk/reduce.go
dgraph/cmd/bulk/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7173)

fix(bulk): fixing bulk loader when tls + encryption is enabled

---

wiki/content/migration/_index.md
wiki/content/migration/dgraph-compared-to-other-databases.md
wiki/content/migration/graphql-dgraph.md
wiki/content/migration/loading-csv-data.md
wiki/content/migration/migrate-dgraph-1-1.md
wiki/content/migration/migrate-dgraph.md

Adding a new section based on @aman-bansal  feedback
Fixes DGRAPH-2598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7172)

docs: Add a Migration section

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7181)

Fix versions

---

netlify.toml
wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7182)

Fix version

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7184)

docs: versioning fix for docs

---

wiki/scripts/build.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7186)

docs: move 20.03 to older versions

---

wiki/content/deploy/log-format.md

- divided the query logging paragraph into two section
- corrected typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7192)

docs : Rephrase of the query logging section

---

wiki/content/deploy/production-checklist.md

- suggested disk IOPS (1k min and 3k for medium-large dataset)
- added info about the new aws [gp3](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/?nc1=h_ls) disk
- changed bare minimum cpu and memory to 8cpu and 16GiB mem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7187)

[docs] Suggestion for disk IOPS 

---

wiki/content/deploy/production-checklist.md

* added suggestion for disk IOPS and changed bare min cpu and memory
(cherry picked from commit b6e243e80cc36462fd00a414f11d82df9b23cae4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7195)

docs: Suggestion for disk IOPS  (#7187)

---

wiki/content/tips/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7183)

Docs: rename gql+- to dql

---

wiki/content/graphql/directives/index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7199)

docs: Fix link to lambda directive.

---

t/t.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7197)

chore(test): increasing timeouts when running with race

---

netlify.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7206)

netlify: add netlify rule for branch deploys

---

wiki/content/_index.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7205)

docs: Remove deprecated Slack link

---

netlify.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7200)

netlify: change host url for netlify preview prod env

---

netlify.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7201)

netlify: change host url for netlify preview

---

wiki/scripts/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7207)

build: make build script similar to master

---

netlify.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7209)

netlify: fix host url for prod env

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7210)

update changelog for v20.03.7

---

netlify.toml
wiki/content/deploy/download.md
wiki/content/deploy/kubernetes.md
wiki/content/enterprise-features/access-control-lists.md
wiki/content/graphql/custom/directive.md
wiki/content/graphql/lambda/overview.md
wiki/content/tutorial-2/index.md
wiki/content/tutorial-6/index.md
wiki/content/tutorials/index.md
wiki/scripts/local.sh

Changes:
* Fix Netlify preview links. Builds now happen for the changes done in the PR using ./scripts/local.sh, which sets up the theme and builds the PR changes.
* Fix typos in docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7215)

docs: Fix Netlify previews.

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7219)

updating changelog for v20.07.3

---

dgraph/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7221)

updating codename for v20.07

---

systest/1million/1million_test.go
systest/21million/common/run_queries.go
testutil/backup.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7224)

fix(test): fixing test cases for race enabled tests

---

edgraph/access_ee.go

(cherry picked from commit 2bf8eed016fa18521a1246ef3e5d08420645e025)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7229)

chore: fixed a typo in password (#7228)

---

wiki/content/deploy/fast-data-loading/bulk-loader.md

Documented how to use bulk loader based on dataset size
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7223)

docs: how to properly bulk load

---

wiki/content/deploy/fast-data-loading/bulk-loader.md

* provided two ways to run bulk loader
(cherry picked from commit 7735d4b805064a7e33b7ccd8477ce754c940eaee)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7231)

docs: how to properly bulk load (#7223)

---

t/t.go
testutil/plugin.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7264)

fix(test): fixing plugin test when build with race

---

dgraph/cmd/zero/raft.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7281)

release/v20.11:  fix(dgraph): fixing unique proposal key error (#7218)

---

graphql/admin/restore.go
worker/online_restore.go
worker/online_restore_ee.go

…7202)
* reset acl accounts once restore is done if necessary
* handling restores with wait group
* making wg to work with each proposal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7280)

release/v20.11:  fix(restore): reset acl accounts once restore is done if necessary

---

wiki/content/deploy/ludicrous-mode.md

Fixes DGRAPH-2887
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7284)

docs (chore):  SEO optimization for Ludicrous mode

---

t/t.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7286)

chore(test): add the option to skip packages

---

worker/executor.go

The following crash is seen in alpha, if we run high load writes in ludicrous mode for a long time. 
```
2021/01/07 00:43:14 Name: Applied watermark doneUntil: 42339870. Index: 42339868
github.com/dgraph-io/badger/v2/y.AssertTruef
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20201214114056-bcfae6104545/y/error.go:62
github.com/dgraph-io/badger/v2/y.(*WaterMark).process.func1
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20201214114056-bcfae6104545/y/watermark.go:165
github.com/dgraph-io/badger/v2/y.(*WaterMark).process
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20201214114056-bcfae6104545/y/watermark.go:232
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1374
```
The error was due to a logical race condition in concurrent execution of mutations in …

fix(ludicrous): Fix logical race condition in concurrent execution of mutations

---

wiki/content/enterprise-features/binary-backups.md

Fixes SUCCESS-263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7296)

docs: Document export_backup command

---

go.mod
go.sum
protos/pb/pb.pb.go

Update `gogo/protobuf` version. 
`v1.3.1` has some security issues, hence upgrading the version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7308)

chore: update gogo/protobuf version

---

go.mod
go.sum
protos/pb/pb.pb.go

gogo/protobuf v1.3.1 has some security issues, hence upgrading the version to v1.4.1
(cherry picked from commit 914f9e4407ab04a0c797af536e100d80111e7b92)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7312)

release/v20.11: chore: update gogo/protobuf version (#7308)

---

wiki/content/enterprise-features/encryption-at-rest.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7239)

Fix markdown link

---

wiki/content/graphql/mutations/deep.md

Corrected typo -> double Deep
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7268)

Correct Typo in deep.md

---

netlify.toml
wiki/content/deploy/download.md
wiki/content/deploy/kubernetes.md
wiki/content/enterprise-features/access-control-lists.md
wiki/content/graphql/custom/directive.md
wiki/content/graphql/lambda/overview.md
wiki/content/tutorial-2/index.md
wiki/content/tutorial-6/index.md
wiki/content/tutorials/index.md
wiki/scripts/local.sh

Changes:
* Fix Netlify preview links. Builds now happen for the changes
done in the PR using ./scripts/local.sh, which sets up the
theme and builds the PR changes.
* Fix typos in docs.
Cherry-pick of #7215.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7217)

docs: Fix Netlify previews and typos.

---

wiki/content/graphql/custom/directive.md

…endpoints (#7290)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7320)

docs (20.11.1): Add docs about how errors are returned from custom

---

README.md
wiki/content/releases/index.md

Changes:
* Update README with latest release info
* Update Releases page with latest release info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7322)

docs: Update latest release info.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7328)

docs(Copyediting): Minor fixes, typos + Oxford commas

---

graphql/e2e/common/query.go

This PR fixes Failing e2e test `inFilterOnFloat` on master. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7346)

fix(GraphQL): fix infilterOnFloat e2e test

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7347)

fix(GRAPHQL):update gqlparser release to v2.1.4

---

go.mod
go.sum

(cherry picked from commit d2ea0e61606c85164bfc8236177cad49d40939fd)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7352)

fix(GRAPHQL):update gqlparser release to v2.1.4 (#7347)

---

posting/list.go
posting/list_test.go

Cherry pick: #7288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7350)

release/20.11 - fix(Dgraph): check for deleteBelowTs in pIterator.valid

---

go.mod
go.sum

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7357)

chore(dgraph): update badger

---

dgraph/cmd/alpha/run.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7367)

fix: /probe/graphql now returns CORS headers too

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7369)

chore(release): changelog for v20.11.1

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7370)

chore: fixing changelog links

---

graphql/e2e/schema/apollo_service_response.graphql
graphql/resolve/auth_query_test.yaml
graphql/resolve/query_test.yaml
graphql/schema/testdata/schemagen/output/apollo-federation.graphql
graphql/schema/testdata/schemagen/output/interface-with-id-directive-and-ID-field.graphql
graphql/schema/wrappers.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7372)

fix(Apollo): fix tests

---

graphql/e2e/common/common.go
graphql/e2e/common/query.go
graphql/e2e/schema/apollo_service_response.graphql
graphql/resolve/auth_query_test.yaml
graphql/resolve/query_test.yaml
graphql/schema/testdata/schemagen/output/apollo-federation.graphql
graphql/schema/testdata/schemagen/output/interface-with-id-directive-and-ID-field.graphql
graphql/schema/wrappers.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7373)

fix(Apollo: Rewrite Apollo entities e2e test

---

dgraph/cmd/alpha/run.go
dgraph/cmd/zero/run.go

* alpha: Update capitalization on `--zero` flag.
* zero: Update `--replicas` flag to mention Dgraph Alpha.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7374)

chore: Update help text for flags in Alpha and Zero.

---

dgraph/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7375)

chore(release): updating code name

---

dgraph/cmd/alpha/run.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7378)

fix: Fixing the content type for /probe/graphql

---

systest/1million/1million_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7379)

chore(test): fixing 1million test import error

---

go.mod
go.sum

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7402)

go.mod fix

---

worker/cdc_ee.go
worker/sink_handler.go

The build got broken by last commit. Fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7416)

Fix Dgraph Build

---

x/x.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7412)

fix(GC): Reduce DiscardRatio from 0.9 to 0.7

---

graphql/authorization/auth.go
graphql/e2e/auth_closed_by_default/auth_closed_by_default_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7422)

fix(GraphQL):This PR fix autClosedByDefault Tests. 

---

systest/queries_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7423)

fix(GraphQL): enable RegexpToggleTrigramIndex test

---

dgraph/cmd/zero/raft.go
worker/draft.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7427)

fix(Raft): Retry Sync indefinitely on failure

---

dgraph/cmd/root.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6694)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0529b2d193-107199.surge.sh)

fix(config): Set glog -v flag correctly from config files.

---

x/x.go

(cherry picked from commit 15bbec3a0abaaae06a1b9dcc0f4f440dd0877bf3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7421)

fix(GC): Reduce DiscardRatio from 0.9 to 0.7 (#7412)

---

contrib/config/backups/s3/README.md
contrib/config/backups/s3/terraform/.gitignore
contrib/config/backups/s3/terraform/README.md
contrib/config/backups/s3/terraform/main.tf

Minor update of terraform scripts and corrections on instructions (README.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7438)

chore(contrib): updated contrib s3 bucket support examples for terraform v0.14

---

dgraph/cmd/zero/http.go

This makes moveTablet namespace aware. 
User needs to pass namespace as a query parameter, else default namespace is assumed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7468)

fix(moveTablet): make move tablet namespace aware

---

CHANGELOG.md
dgraph/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7470)

updating changelog for v20.11.2

---

graphql/admin/http.go

This PR fixes the race conditions that were introduced after the multi-tenancy changes for GraphQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7471)

fix(GraphQL): Fix race conditions (GRAPHQL-1009)

---

edgraph/multi_tenancy_ee.go
systest/backup/multi-tenancy/backup_test.go
systest/multi-tenancy/basic_test.go
testutil/multi_tenancy.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7481)

chore(test): making create namespace in test more robust

---

dgraph/cmd/alpha/run.go
dgraph/cmd/bulk/run.go
dgraph/cmd/zero/run.go
x/flags.go

(This is related to DGRAPH-3026.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7487)

fix(Flags): Small formatting improvements

---

contrib/manual_tests/test.sh
contrib/tlstest/alpha_tls.sh
contrib/tlstest/alpha_tls_auth.sh
contrib/tlstest/server_11.sh
contrib/tlstest/server_nopass.sh
contrib/tlstest/server_nopass_client_auth.sh
contrib/tlstest/server_pass.sh
systest/backup/encryption/backup_test.go
systest/backup/encryption/docker-compose.yml
systest/backup/filesystem/docker-compose.yml
systest/backup/minio-large/docker-compose.yml
systest/backup/minio/docker-compose.yml
systest/loader/docker-compose.yml
systest/loader/loader_test.go
systest/online-restore/docker-compose.yml
tlstest/acl/acl_over_tls_test.go
tlstest/acl/docker-compose.yml
tlstest/certrequest/certrequest_test.go
tlstest/certrequest/docker-compose.yml
tlstest/certrequireandverify/certrequireandverify_test.go
tlstest/certrequireandverify/docker-compose.yml
tlstest/certverifyifgiven/certverifyifgiven_test.go
tlstest/certverifyifgiven/docker-compose.yml
tlstest/mtls_internal/ha_6_node/docker-compose.yml
tlstest/mtls_internal/multi_group/docker-compose.yml
tlstest/mtls_internal/single_node/docker-compose.yml
tlstest/zero_https/all_routes_tls/docker-compose.yml
x/tls_helper.go
x/x.go

(DGRAPH-3026)
TLS SuperFlag options will now look like this:
| Old Name | New Name | Changed |
|--------------:|----------------:|:------------:|
| `cacert`   | `ca-cert`       | :green_circle: |
| `internal-port-enabled`  | `internal-port` | :green_circle: |
| `client-auth` | `client-auth-type`  | :green_circle: |
| `cert`  | `client-cert`  | :green_circle: |
| `key` | `client-key` | :green_circle: |
| `node-cert`  | `server-cert`  | :green_circle: |
| `node-key`  | `server-key`  | :green_circle: |
|  `use-system-ca`  | `use-system-ca`  |  |
| `server-name` | `server-name` | |
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7491)

fix(Flags): Rename ambiguous TLS flags

---

dgraph/cmd/alpha/admin.go
dgraph/cmd/alpha/admin_backup.go
dgraph/cmd/alpha/http.go
dgraph/cmd/alpha/run.go
graphql/schema/validation_rules.go
systest/plugin/plugin_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7501)

chore(graphql): refactoring request handler in alpha

---

dgraph/cmd/alpha/run.go
ee/audit/audit_ee.go
ee/audit/interceptor_ee.go
systest/audit/audit_test.go
x/log_writer.go
x/logger.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7504)

chore(audit): making audit logs to get output over stdout

---

ee/backup/run.go
worker/backup_common.go
worker/backup_handler.go
worker/export.go
worker/file_handler.go
worker/restore.go
worker/s3_handler.go

This PR enables the export_backup to work with S3 backups also.
This also fixes cors to work with multi tenancy. If found they will be appended back to graphql schema
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7450)

chore(export_backup): s3 handler for export backup

---

contrib/standalone/run.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7512)

fix(standalone): Set whitelist flag using superflag.

---

x/init.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7513)

chore(version): Add link to Dgraph Cloud.

---

dgraph/cmd/bulk/reduce.go

This PR removes the stale allocator in the bulk reduce phase. It was previously used by the uidpack encoders. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7510)

fix(Bulk): Remove stale allocator in bulk reduce

---

worker/graphql_schema.go

This PR logs the time a GraphQL schema update has to wait for another ongoing GraphQL schema update, in-case the wait is more than 500ms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7518)

chore(GraphQL): Log the time GraphQL schema update has to wait (GRAPHQL-1063)

---

dgraph/cmd/alpha/mutations_mode/docker-compose.yml
dgraph/cmd/alpha/mutations_mode/mutations_mode_test.go
dgraph/cmd/alpha/run.go
dgraph/cmd/bulk/run.go
dgraph/cmd/zero/run.go
ee/audit/audit_ee.go
ee/enc/flags.go
ee/vault/flags.go
worker/cdc_ee.go
worker/draft.go
worker/server_state.go
x/config.go
x/flags.go
x/sentry_integration.go
x/tls_helper.go

cherry-pick of https://github.com/dgraph-io/dgraph/pull/7544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7560)

cherry-pick: [Breaking] fix(Flags): consolidation and help text improvements (#7544)

---

ee/audit/interceptor_ee.go
ee/audit/run_ee.go
go.sum
t/t.go
x/log_writer.go

This PR fixes two issues in audit logs when encryption is enabled.
1. Decrypt tool crashes if encryption file is empty.
2. Decrypt tool doesn't verify the encryption key. This is done via adding "Hello World" tag in the encrypted file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7548)

chore(audit): fix audits to verify encryption file + check for empty files

---

telemetry/telemetry.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7564)

fix(release/v21.03) - Use worker.GetEEFeatureList instead of ee.GetEEFeatureList

---

go.mod
go.sum
tools.go

This fix updates go tool dependencies for the `xgo` tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7576)

fix(release): update support for xgo tool

---

posting/list.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7578)

chore: Remove debug printf.

---

go.mod
go.sum
tools.go

* update support for xgo tool
(cherry picked from commit 479a7fbab715fb280356358535a569f451d8a8aa)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7586)

fix(release): update support for xgo tool (#7576)

---

dgraph/cmd/bulk/run.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7591)

fix(Flags): remove unused badger.max-retries option from bulk command

---

dgraph/cmd/debuginfo/debugging.go
dgraph/cmd/debuginfo/run.go

- This PR adds 5 new metrics (/jemalloc, /state, /health, /debug/vars, /metrics) to be collected when running  the `debuginfo` 
- the flag `-p` has been changed to `-m` to reflect the change. This new flag will let you pick up one or multiple metrics/pprof to be collected:
```
-m, --metrics strings    List of metrics & profile to dump in the report. (default [jemalloc,state,health,vars,metrics,heap,cpu_profile,trace,goroutine,threadcreate,block,mutex])
```
- default value of `-s` flag is now 30sec since it requires 30s to collect a cpu profile
- when saving the metric/profile - it will log the metric/profile name and the path where it's saving to.
- added new flag for time based profiles that are cpu and trace profiles:
```
-c, --cron_pprof strings   time-based pprof (default …
```

feat(cmd/debuginfo) add new metrics to be collected (#7439)

---

compose/compose.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7539)

chore(compose): Don't mount GOPATH if not used.

---

go.sum

Run `go mod tidy`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7594)

chore: Run go mod tidy.

---

systest/bgindex/count_test.go
systest/bgindex/parallel_test.go
systest/bgindex/reverse_test.go
systest/bgindex/string_test.go
systest/multi-tenancy/basic_test.go
t/t.go
testutil/multi_tenancy.go

* chore(test): fixing flaky tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7596)

chore(test): fixing flaky tests (#7577)

---

contrib/release.sh
contrib/release/xgo.Dockerfile

Fix:
* update release/xgo.Dockerfile FROM clause to match GOVERSION
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7623)

release script update to dynamically change Dockerfile

---

contrib/Dockerfile

Set the image to Ubuntu 20.04 and add tools:
* htop
* jq
* less
* sysstat (iostat)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7622)

build(dockerfile): Use Ubuntu 20.04 and add tools.

---

posting/list.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7633)

chore(readListPart): Print l.minTs in the error

---

Makefile
dgraph/cmd/zero/raft.go
dgraph/cmd/zero/run.go

Cherry-pick for clusterID flag (cloud services thing)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7649)

cherry-picking off e8b78b7aa70357e6f8be4d18049071edebf0e865

---

graphql/resolve/extensions_test.go
graphql/resolve/mutation.go

* Remove unused function
* Add tracing for existence query execution
* Fix tests
(cherry picked from commit ba8f5da5a54254dff830db39ea157f1cbb8ddb53)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7658)

Fix(GraphQL): Fix Execution Trace for Add and Update Mutations 

---

ee/vault/vault_ee.go

Vault doesn't always require a secret ID -- for example, if a bound_cidr_list is configured. This PR removes the requirement for a secret ID to be provided in Dgraph's Vault flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7642)

fix(flags): use Vault without secret ID

---

dgraph/cmd/alpha/run.go
dgraph/cmd/bulk/run.go
worker/draft.go
x/config.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7679)

fix(flags): fix bulk loader flag and remove flag parsing from critical path

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7697)

picking up changelog from 20.11 to master

---

graphql/e2e/auth/auth_test.go
graphql/e2e/auth/delete_mutation_test.go
graphql/e2e/auth/schema.graphql
graphql/e2e/auth/test_data.json
graphql/e2e/auth/update_mutation_test.go
graphql/resolve/auth_query_test.yaml
graphql/resolve/query_rewriter.go

Fixes GRAPHQL-1130.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7695)

fix(GraphQL): fix @cascade with Pagination for @auth queries.

---

worker/draft.go

Fixes DGRAPH-3241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7711)

chore: Remove sensitive information when logging proposal

---

README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7732)

chore(release): fixing readme for dgraph after latest release

---

dgraph/cmd/bulk/mapper.go
dgraph/cmd/bulk/schema.go
worker/mutation.go

(cherry picked from commit a4d74d4c664609f8406a81e1b9eb50c370832efb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7749)

release/v21.03: fix(bulk): throw the error instead of crashing (#7722)

---

query/common_test.go
query/query0_test.go

Add some sanity tests for k-random nodes argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7758)

chore(tests): Add basic test for k-random nodes

---

paper/dgraph.tex

- fixed typo, but did not compile the paper, so please compile and commit before merging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7496)

docs(Dgraph paper): fix typo

---

dgraph/cmd/zero/assign.go
dgraph/cmd/zero/run.go
dgraph/cmd/zero/zero.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7787)

fix(lease): don't do rate limiting when not limit is not specified

---

worker/restore_map.go

We were not freeing the UidPack which was causing a memory leak. This PR fixes this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7786)

fix(backup-map): Free the UidPack after use

---

ee/audit/audit_ee.go

Cherry-pick for fixing audit streaming problem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7804)

bug fix to permit audit streaming to stdout writer(#7803)

---

go.mod
go.sum
graphql/admin/http.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7807)

fix(GraphQL): Pass on HTTP request headers for subscriptions (#7806)

---

worker/restore_map.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7809)

fix(dropdata): use galaxynamespace when restore from old backup

---

gql/parser.go
gql/parser_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7821)

feat(lexer): Expose DQL lexer for usage by visual editor

---

gql/parser_test.go

adding assertions for unit tests for LexQuery
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7823)

refactor: LexQuery unit tests

---

ee/updatemanifest/run.go

We were not updating the manifest version after the updation. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7828)

fix(updatemanifest): update the version of manifest after upgrade

---

dgraph/cmd/zero/run.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7842)

fix(flags): Update Raft help on Zero

---

dgraph/cmd/debug/wal.go

$SUBJECT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7857)

chore(debug): Print proposal key.

---

dgraph/cmd/debug/wal.go

(cherry picked from commit d6d768db97cc796e1e42e1c098ca8217c7b77703)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7858)

release/v20.11: chore(debug): Print proposal key. (#7857)

---

README.md

Updates the [roadmap link to 2021](https://discuss.dgraph.io/t/dgraph-product-roadmap-2021/12284).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7830)

docs(README): Update product roadmap

---

CHANGELOG.md
dgraph/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7901)

chore(Changelog): Update change log for v21.03.1

---

worker/backup_manifest.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7899)

fix(restore): return nil if there is error

---

conn/node.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7910)

chore(raft): Log packets message less frequently.

---

graphql/resolve/query_rewriter.go
graphql/resolve/query_test.yaml

(cherry-pick from commit 314091adb607d69aef451613ac498b593debc1e5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7897)

fix(GraphQL): optimize eq filter queries #7897

---

conn/pool.go

In case the heartbeats in a connection pool stop, try to re-establish the connection via a redial. That's a more robust way than waiting for current connection to become usable again and allows much faster recovery from network partitions.
(cherry picked from commit 947a62bdc0526caa1985f2e39e6a5525118aaaab)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7920)

Reconnect via a redial in case of disconnection. (#7918)

---

graphql/e2e/auth/auth_test.go
graphql/resolve/auth_query_test.yaml
graphql/resolve/query_rewriter.go

Fixes DO-12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7915)

fix(GraphQL): Nested Auth Rules not working properly.

---

dgraph/cmd/debug/run.go

Add --only-summary flag in dgraph debug to show LSM tree and namespace sizes.
(cherry picked from commit cc871539d0ab5c1ff5a767555adb606736ac9d09)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7927)

chore(debug): add summary to show LSM tree and namespace size (#7891)

---

graphql/schema/schemagen.go

(cherry picked from commit 46092682c8ab09ddd5d1222548b7f6d83c5a12e2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7923)

cherrypick(GraphQL): handle extend keyword for Queries and Mutations (#7916)

---

contrib/sbs/sbs.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7979)

fix(sbs): Print final result only after all workers are done

---

dgraph/cmd/live/run.go

Cherry-pick of #7983 into release/v21.03-slash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7985)

fix(live): quote the xid when doing upsert

---

dgraph/cmd/alpha/http.go

Add support for RDF format response for HTTP requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8004)

feat(rdf): Add support for rdf response via http

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8009)

fix: update badger for multiple minor fixes

---

worker/draft.go

Proposal dropped logs are crucial and can prove helpful while debugging some instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8012)

chore(logs): add logs to track dropped proposals

---

dgraph/cmd/zero/raft.go
worker/draft.go
worker/proposal.go

Cherry picks:
- fix(proposals): Incremental proposal key for zero proposals (#8005) …
- chore(logs): add logs to track dropped proposals (#8012) …
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8015)

fix(proposal): cherry pick changes related to dropped proposal

---

codec/codec.go
contrib/sbs/sbs.go
dgraph/cmd/alpha/run.go
go.mod
go.sum
graphql/admin/admin.go
posting/list.go
query/query.go
worker/draft.go
worker/task.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8031)

Merge master to release/v21.09

---

contrib/config/backups/client/backup_helper.sh
contrib/config/backups/client/dgraph-backup.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8035)

fix(contrib): Quote strings in backup script.

---

Makefile
dgraph/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8042)

chore: adding tag name to 2109 release

---

graphql/admin/restore.go
worker/online_restore.go
worker/restore_map.go

Add more logs for restore.
(cherry picked from commit 3950c8f36260a0383e5684bb39595e2d60d03cb6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8052)

cherrypick-cloud: chore(restore): Add more logs for restore request (#8050)

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8054)

updating badger to latest version

---

contrib/sbs/go.mod
contrib/sbs/sbs.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8072)

contrib(sbs): add support for mutations replay in sbs

---

go.mod
go.sum

This update to badger pulls in two badger fixes:
* fix(manifest): fix manifest corruption due to race condition in concurrent compactions
* fix(compact): close vlog after the compaction at L0 has completed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8094)

chore(deps): update badgerdb to latest

---

CHANGELOG.md

This PR cherry-picks the changelog from `release/v21.03` to `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8095)

chore(changelog): update changelog for 21.03

---

worker/backup_manifest.go

(cherry picked from commit d4aeea212ef708f2857363231d13996916475ad5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8098)

cherry: fix(restore): return nil if there is error (#7899)

---

CHANGELOG.md
Makefile
dgraph/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8096)

chore(changelog): adding changelog for 21.12 and adding tagname

---

systest/bgindex/docker-compose.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8104)

fix(test): increase pending query limit

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8105)

fix(deps): update badger to fix race condition with drop operation

---

go.mod
go.sum

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8106)

updating gqlparser version with race fix

---

.gitignore
Makefile
contrib/local-test/Makefile
contrib/local-test/README.md
contrib/local-test/docker-compose-lambda.yml
contrib/local-test/docker-compose.yml
contrib/local-test/scripts/script.js

The README.md documents everything completely

build(test): Add a local image build function with helper for schema mods, data loading and queries

---

.github/CODEOWNERS
.github/workflows/ci-dgraph-tests.yml

wiki tests were skiipped 
Unskipping wiki tests

fix(test):Unskip wiki test suite

---

.github/workflows/ci-dgraph-tests.yml

compose test suite was skipped
remove compose from skip list as it has no tests and hence doesn't need to be skipped
<!-
Please add a description with these things:
1. Explain the solution to make it easier to review the PR.
2. Make it easier for the reviewer by describing complex sections with comments.
-->

fix(test):Unskip compose test suite

---

.github/workflows/ci-dgraph-tests.yml

We were skipping types suite. Tests pass.
Unskip types suite.

chore(test): unskip types test suite

---

.github/workflows/ci-dgraph-tests.yml

We were skipping telemetry suite. Tests pass.
Unskip telemetry suite.

chore(test): unskip telemetry test suite

---

.github/workflows/ci-dgraph-tests.yml

We were skipping schema suite. Tests pass.
Unskip schema suite.

chore(test): unskip schema test suite

---

.github/workflows/ci-dgraph-tests.yml

fix(test): unskip static folder as there are no tests
static suite was skipped
static suite is now skipped

fix(test): unskip static suite

---

.github/workflows/ci-dgraph-tests.yml

GIthub workflow was skipping conn.
Don't skip conn.

chore(test): unskip conn

---

.github/workflows/ci-dgraph-tests.yml

We were skipping algo suite. Tests pass.
Unskip algo suite.

chore(test): unskip algo test suite

---

.github/workflows/ci-dgraph-tests.yml

skipped tests in posting
remove posting from skiplist in ci-dgraph-tests.yml

chore(test:)unskipping posting

---

.github/workflows/ci-dgraph-tests.yml

We were skipping raftwal suite. Tests pass.
Unskip raftwal suite.

chore(test): unskip raftwal test suite

---

.github/workflows/ci-dgraph-tests.yml

Removing licenses from the skip list as this has no tests
licenses directory was in the skip list.
Removing licenses from the skip list.

fix(test): unskip licenses suite

---

.github/workflows/ci-dgraph-tests.yml

skipped tests in testutil
remove testutil from skiplist in ci-dgraph-tests.yml

chore(test): unskipping testutil

---

.github/workflows/ci-dgraph-tests.yml

skipped tests in edgraph
remove edgraph from skiplist in ci-dgraph-tests.yml

chore(test): unskip edgraph

---

.github/workflows/ci-dgraph-tests.yml

skipping task in ci-dgraph-tests.yml
remove from ci-dgraph-tests.yml. there are no tests atm for task directory

chore(test): unskip task

---

.github/workflows/ci-dgraph-tests.yml

gql tests being skipped
remove gql from the ci-dgraph-tests.yml

chore(test): unskip gql 

---

.github/workflows/ci-dgraph-tests.yml

We were skipping x suite.  Tests pass.
Unskip x suite.

chore(test): unskip x

---

.github/workflows/ci-dgraph-tests.yml

skipped tests in query
remove query from skiplist in ci-dgraph-tests.yml

unskip query test suite

---

.github/workflows/ci-dgraph-tests.yml

Chunker was skipped.
Chunker was unskipped.

chore (test): unskip chunker

---

.github/workflows/ci-dgraph-tests.yml

Lex was skipped.
Lex was unskipped.

chore (test): unskip lex suite

---

.github/workflows/ci-dgraph-tests.yml

Paper was skipped.
Paper was unskipped.

chore (test): unskip paper

---

.github/workflows/ci-dgraph-tests.yml

Present was skipped.
Present was unskipped.

Chore (test): unskip present suite

---

.github/workflows/ci-dgraph-tests.yml
graphql/e2e/custom_logic/cmd/Dockerfile

Unskip graphql directory.  Tests work locally, however some tuning may be required in order for tests to run appropriately in CI/CD.
Graphql tests will be run.

chore(test) - unskip graphql

---

.github/workflows/ci-dgraph-tests.yml

Un-skipping filestore suite
filestore suite was skipped
Updating ci-dgraph-tests.yml to unskip filestore

chores(test): Updating ci-dgraph-tests.yml to unskip filestore

---

.github/workflows/ci-dgraph-tests.yml

xidmap tests are being skipped
remove xidmap from skiplist

unskip xidmap, push to run tests

---

.github/workflows/ci-dgraph-tests.yml

`tok` was skipped, but all tests pass
Unskip `tok`

unskip tok test suite

---

.github/workflows/ci-dgraph-tests.yml

contrib & t pig's are skipped 
unskip `contrib` & `t`

fix(test): unskip contrib and t pkg

---

.github/workflows/ci-dgraph-tests.yml

Protos was skipped.
Protos was unskipped.

Chore (test): unskip protos 

---

.github/workflows/ci-dgraph-tests.yml

dgraph/cmd/live/load-json is skipped
unskip dgraph/cmd/live/load-json

unskip dgraph/cmd/live/load-json test suite

---

.github/workflows/ci-dgraph-tests.yml

Worker was skipped.
Worker was unskipped.

Chore (test): unskip worker

---

.github/workflows/ci-dgraph-tests.yml

upgrade is skipped
unskip upgrade

fix(test): unskip upgrade

---

.github/workflows/ci-dgraph-tests.yml

test flakiness
fix tests causing flakiness

fix(test): fix test flakiness

---

go.mod
go.sum

CVE https://github.com/dgraph-io/dgraph/security/code-scanning/68
update yaml version

fix(sec) CVE-2019-11254

---

README.md

Fixes #5347
Updated copy of #5698

docs(Badges): Adds a TODOs Badge to the README

---

contrib/gh-runner/gh-runner.sh

added gh runner shell script

---

contrib/gh-runner/README.md

No Readme steps for the shell script
Adds a readme

fix(doc) gh action runner readme

---

contrib/gh-runner/README.md
contrib/gh-runner/gh-runner.sh

GH Runner reboot doesn't pick up agent config 
temporary solution added to reboot step#5

fix(test): runner reboot issue

---

contrib/gh-runner/README.md
contrib/gh-runner/gh-runner.sh

run.sh is not ideal because its 1-time test run, what we need is this runner to persist
switch to svc.sh

fix(test): runner reboot fix

---

.github/workflows/ci-dgraph-tests.yml
README.md

GH-Hosted Runners have limited resources for our tests. This is causing certain tests to fail because of mem issues.
We are switching to self-hosted runners.

fix(test): to execute on self-hosted runner

---

.github/workflows/ci-dgraph-tests.yml

If a workflow run is forcefully cancelled, the successive run against another PR is also affected. This happens because docker cleanup is not made available as a pre-step.
Adding a pre-step for cleanup

fix(test) add cleanup step

---

README.md

badges are broken
fixing badges to reflect the current state

fix(docs): fix badges 

---

README.md

broken link for CI
update badge hyperlink

fix(doc) badge link update

---

.github/workflows/ci-dgraph-load-tests.yml

no load tests running 
open up the flood gates for load tests

fix(test): open load tests

---

.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests.yml

the cleanups are failing, but the tests are passing - and its marking the job as failed because of it.
after a little research, I am going to disable the cleanup - as its not needed

fix(test) rm cleanup steps, as they are not needed

---

contrib/gh-runner/gh-runner.sh

environment cleanup is not happening correctly, there are crufts by docker - which are  owned by root. This causes the next runner job to get impacted in the cleanup step.
switching to a cron based ownership changer, to handle the issue at infrastructure layer.

fix(ci) load test environment cleanup

---

README.md
contrib/gh-runner/gh-runner.sh

badges don't reflect the true state of our repo
frequency of cruft cleanup could cause issues
update badges
increasing cleanup frequency

fix(test) CI test data fix badges & increase frequency for cruft cleanup

---

.github/workflows/ci-dgraph-tests.yml

systest/backup was skipped, but its tests are passing on local.
unskip systest/backup

fix(test): unskip systest/backup test suite in CI

---

.github/workflows/ci-dgraph-tests.yml

systest/online-restore was skipped, but tests are passing.
unskip systest/online-restore

fix(test): unskip systest/online-restore test suite in CI

---

.github/workflows/ci-dgraph-tests.yml

fix(test) unskip loader

---

.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests.yml

Capture errors around acl, multi tenancy, minio side
Increase run frequency as a safe guard

fix(test): increase CI harness frequency before Release

---

.github/workflows/ci-dgraph-tests.yml

Transient issues running restore/minio/multi-tenancy tests
#skip these tests in full suite run, and then run them individually after

fix(test) segmented tests with transient failures

---

.github/workflows/ci-dgraph-tests.yml
worker/groups.go

need logging for identifying flaky test issue for ee license
super verbose logging

fix(test): adding logging to EnterpriseEnabled function

---

.github/workflows/cd-dgraph.yml

dependencies failures were seen on a test release
adjust the dependencies

fix(cd): adjust dependencies

---

Makefile

we are mv'ing the binary in release pipeline, which is affecting the next build docker step
use cp instead of mv

fix(cd): fix the mv to cp

---

.github/workflows/cd-dgraph.yml

docker cli login fails because of a blocking password request
switch to GH actions login, as its easier & cleaner

fix(cd): dockerhub login issues

---

.github/workflows/cd-dgraph.yml

mistake in docker user key name
fix key name from user to username

fix(cd): fix docker secrets keyname

---

.github/workflows/cd-dgraph.yml

cd pipeline was running with test creds
switch to real creds

fix(cd) switch to non-test creds

---

CHANGELOG.md

GH Webhooks is not taking effect on the PR hyperlinks
force hyperlinks to PRs 
add compare tabs

fix(doc): repoint hyperlinks to pr's

---

CHANGELOG.md

the security tab was a sub-bullet (which is wrong)
fix the security tabbing
bold sub-bullets

fix(doc): adjust tabs & bold text

---

.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests.yml

Our queue is increasing because the test run frequency is high (every 15 mins)
Frequency changed from every 15 mins to every 1 hr

fix(cd): Reduce frequency of test runs

---

.github/workflows/labeler.yml

Chore(Other): Set labeler to main.

---

.golangci.yml

related to https://github.com/dgraph-io/dgraph/actions/runs/3397696352/jobs/5650298207
comment out this because this is a larger fix

fix(ci): comment out gas

---

.github/workflows/cd-dgraph.yml

badger artifacts should be released with dgraph artifacts
update the cd script to use the generated artifacts from badger project with correct version picks

fix(cd) badger artifacts

---

.github/workflows/cd-dgraph.yml

release script is out of sync for badger release
cherry pick https://github.com/dgraph-io/dgraph/pull/8422 & https://github.com/dgraph-io/dgraph/pull/8406

fix(cd): cd changes for badger

---

CHANGELOG.md

v22.0.1 release needs a changelog update
Updating changelog release notes

fix(release): update changelog

---

.github/CODEOWNERS

More reviewers needed
Adding @matthewmcneely @billprovince

fix(chore): Update CODEOWNERS

---

.github/workflows/ci-aqua-security-trivy-tests.yml
.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests-arm64.yml
.github/workflows/ci-dgraph-tests.yml
.github/workflows/ci-golang-lint.yml

draft ci runs need to be enabled because we are closing in for release
fix the ci config to enable runs on draft PRs

fix(cicd): run on draft PRs

---

LICENSE.md
Makefile
compose/Makefile
contrib/scripts/license.py
contrib/scripts/license.sh
contrib/tlstest/Makefile
dgraph/Makefile
protos/Makefile
protos/depcheck.sh
t/Makefile

There are still some Copyright to update
Change remaining Copyright year

fix(chore): Change remaining Copyright year

---

t/t.go

Files download in serial fashion, slowing the test harness.
Download files in parallel

chore: Download LDBC files in parallel

---

.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests-arm64.yml
.github/workflows/ci-dgraph-tests.yml

ci needs draft run trigger to be disabled, cost
disabled in ci yawls

fix(ci): reduce triggers by disabling on draft runs

---

go.mod
go.sum

badger update sync - to support arm
bump version

fix(arm64): bump badger version

---

.github/workflows/cd-dgraph.yml

missing arm cd steps
change to buildx, and introduce arm build & push step

fix(cd): adds arm job

---

CHANGELOG.md

Need a changelog for 22.0.2 release
Update CHANGELOG.md for 22.0.2 release

chore(doc): Update CHANGELOG.md for 22.0.2 release

---

.github/workflows/ci-dgraph-code-coverage.yml
.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests-arm64.yml
.github/workflows/ci-dgraph-tests.yml

we are quite stable now, and we don't want to burn $'s
reduce cron runs

fix(ci): reduce cron runs for self-hosted runners

---

.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/feature_request.yml

The current template is more a bug report and does not ask for references, current workaround and suggested solution.
update the template

chore(github): update feature request issue template

---

edgraph/access_ee.go
edgraph/server.go
ee/audit/audit_ee.go
ee/audit/interceptor.go
ee/audit/interceptor_ee.go
graphql/admin/http.go
x/jwt_helper.go
x/x.go

Fix audit logs for requests over websocket.
(cherry picked from commit 3f8cff957b0ce34673f70ffd8793d0353bf2a910)

fix: fixing audit logs for websocket connections (#8048) (#8053)

---

go.mod
go.sum

Update dep on Badger to include https://github.com/dgraph-io/badger/pull/1745

chore(deps): update badger to include #1745

---

README.md

docker setup docs link needs to point to new docs url
Added new link in readme
Made some small changes to text/grammar

fix(readme): Update docs link

---

.github/workflows/cd-dgraph.yml

related to this https://github.com/dgraph-io/badger/pull/1887
same definition ^

chore(ci): pipeline changes release_pipeline_to_tags 

---

CHANGELOG.md

Changelog updates for v23.0.0-beta

chor(changelog): add changelog for v23.0.0-beta

---

.github/workflows/ci-dgraph-code-coverage.yml

Goveralls was failing on community PR's.  See https://github.com/dgraph-io/badger/pull/1894

chore(ci): resolve community PR goveralls failure

---

.github/workflows/ci-dgraph-load-tests.yml

add release filter for load test

release filter for load test

---

CHANGELOG.md

chore(changelog): fix broken link

---

dql/parser.go
query/query0_test.go
systest/mutations_test.go

fix(dql): fix panic in parsing of regexp

---

dgraphtest/cluster.go
dgraphtest/compose_cluster.go
dgraphtest/config.go
dgraphtest/dcloud_cluster.go
dgraphtest/dgraph.go
dgraphtest/image.go
dgraphtest/local_cluster.go

This commit improves logging in the dgraphtest package. It also improves our health check by waiting until EE features are enabled and login works.

dgraphtest: improve logging and health check

---

go.mod
go.sum

upgrade badger to v4.1.0 before doing dgraph release.

upgrade badger to v4.1.0

---

CHANGELOG.md

need v23 rc1 changelog
added v23 rc1 items

chore(changelog): v23 rc1 changelog

---

CHANGELOG.md

lower case strings for release artifacts
fix str to lower

fix(changelog): lower case naming convention

---

.github/workflows/ci-dgraph-code-coverage.yml
.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests-arm64.yml
.github/workflows/ci-dgraph-tests.yml

higher frequency was enabled to solve flaky tests .. this is more $$'s
reduce frequency because we are done with RC testing

fix(ci): frequency fix

---

.vscode/launch.json

Fixed Jaeger parameters in launch.json

fix(vscode): fixed Jaeger parameters

---

.github/workflows/ci-dgraph-upgrade-tests.yml
dgraphtest/cluster.go
dgraphtest/local_cluster.go
query/query0_test.go
query/upgrade_test.go
systest/audit_encrypted/audit_test.go

This might be incorporated as part of another workflow.  For now, we will test it out here.
JIRA issue: https://dgraph.atlassian.net/browse/DGRAPHCORE-97

chore(ci): add upgrade test workflow

---

CHANGELOG.md

We update changelog in v23 release branch.

chore(changelog): update changelog in release branch

---

README.md

chore(readme): update readme for v23

---

t/t.go

`fix`: Made a change for the ldbc test which will fail the test if file download fails.

`fix`: Made a change for the ldbc test which will fail the test if file download fails.

---

dgraphtest/cluster.go
dgraphtest/config.go
dgraphtest/dgraph.go
dgraphtest/local_cluster.go
query/normalize_feature_flag_test.go
systest/multi-tenancy/basic_test.go

WithFeatureFlags is renamed to WithListInNormalize as well as IsParent is renamed to IsHigherversion. These functions are easier to understand and deal with than previous functions

chore: improve a couple of functions in dgraphtest

---

graphql/admin/restore.go

chore(restore): add log message when restore fails

---

CHANGELOG.md

chore: add changelog for v23.0.1

---

.github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
.github/workflows/ci-dgraph-upgrade-tests.yml

4 hours do not seem enough for the workflow.

chore(upgrade): increase the duration of the CI workflow

---

dgraphtest/config.go
dgraphtest/dgraph.go
go.mod
go.sum
systest/integration2/graphql_schema_auth_test.go

Seems like there was a race condition that was fixed in v2.2.2 from v2.2.1. This change upgrades gqlparser to the fixed version.
CLOSES: DGRAPHCORE-329
CLOSES: DGRAPHCORE-341

chore(graphql): upgrade gqlparser to v2.2.2

---

dgraph/cmd/alpha/run_test.go
dql/parser.go
edgraph/server.go
graphql/admin/current_user.go
graphql/resolve/query_rewriter.go
query/query.go
telemetry/telemetry.go

Description: Small name change to make the code easier to read and understand.
Fixes: NA
Closes: NA
Docs: NA

Chore(DQL and Telemetry): Rename GQLPM to DQL

---

dgraphtest/cluster.go
dgraphtest/local_cluster.go
ee/acl/acl_test.go
ee/acl/upgrade_test.go

Closes: https://dgraph.atlassian.net/browse/DGRAPHCORE-335

test(upgrade): add upgrade tests for v20.11 for ee/acl

---

README.md

Description: This PR updates the version in the README.  (We are also testing out a new webhook that will be triggered on merge).

ci: update version in readme

---

go.mod
go.sum

Reference: https://github.com/99designs/gqlgen/pull/2863

Update go.mod with appdash replacements

---

.github/workflows/ci-aqua-security-trivy-tests.yml
.github/workflows/ci-dgraph-fuzz.yml
.github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
.github/workflows/ci-golang-lint.yml

Description: Fix typo in cron, reduce lint cadence.

chore(ci): typo in cron

---

.github/workflows/ci-dgraph-jepsen-tests.yml

Description: Run basic jepsen test on PR's and on cron schedule (daily).
Closes: DGRAPHCORE-275

chore(ci): add jepsen test workflow

---

.github/workflows/ci-dgraph-load-tests.yml
.github/workflows/ci-dgraph-tests.yml
.github/workflows/ci-dgraph-upgrade-tests.yml
.github/workflows/ci-golang-lint.yml

Optimizing CI workflows to remove redundant runs

Optimize CI Workflows

---

tlstest/certrequest/certrequest_test.go

This particular test seems to fail for this PR https://github.com/dgraph-io/dgraph-private/pull/48 pretty consistently. While we have not completely migrated to use dgraphtest package yet, this is a temporary solution to fix the test.

ci: wait for the cluster to startup in tlstest

---

check_upgrade/check_upgrade.go
dgraph/cmd/root.go
dgraphtest/cluster.go
dgraphtest/compose_cluster.go
dgraphtest/ee.go
dgraphtest/local_cluster.go
dgraphtest/paths.go
testutil/client.go

Title format:
- `Topic(Area): Feature`
- `Topic` must be one of `build|ci|docs|feat|fix|perf|refactor|chore|test`
- `Area` must be one of `acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade|zero`
- * Add [BREAKING] if it is a breaking change
------------------
Body Format:
Description: <add description>
Fixes: <GitHub Issue>
Closes: <JIRA Issue>
Docs: <docs PR>

add script for log duplicate ACL users

---

.github/workflows/ci-aqua-security-trivy-tests.yml

Reintroducing nightly Trivy scans for ongoing security scanning

ci(build): add nightly Trivy scan

---

.github/workflows/codeql.yml

[CodeQL](https://codeql.github.com/) is a code vulnerability scanner made available for free by GitHub for open source projects

ci(build): enable CodeQL scanning

---

.github/workflows/cd-dgraph.yml

Fixing issue with if condition while pushing manifest

Fixing issue with if condition while pushing manifest for the cd pipeline

---

.github/workflows/cd-dgraph.yml

Fixing  cd-dgraph.yml to tag custom build correctly

Fixing  cd-dgraph.yml to tag custom build correctly

---

CHANGELOG.md

Updated changelog for v24.0.0

---

.github/workflows/stale.yml

for more: https://discuss.dgraph.io/t/adding-stale-action-to-our-repos/19414/1

Chore(): create stale.yml

---

CHANGELOG.md

chore(changelog): update changelog for v23.1.1

chore(changelog): update changelog for v23.1.1 

---

CHANGELOG.md

chore(changelog): update changelog for v23.1.1

---

CHANGELOG.md

Adding 24.0.1 to the Changelog

Update CHANGELOG.md to add 24.0.1

---

CHANGELOG.md

Add 24.0.2 to CHANGELOG.md

---

.github/labeler.yml

fix(repo): labeler config

---

graphql/resolve/query_rewriter.go
graphql/schema/dgraph_schemagen_test.yml
graphql/schema/rules.go
graphql/schema/testdata/schemagen/input/embedding-directive-with-similar-queries.graphql
graphql/schema/testdata/schemagen/output/embedding-directive-with-similar-queries.graphql
graphql/schema/wrappers.go
query/common_test.go
query/vector/vector_graphql_test.go
query/vector/vector_test.go
schema/parse_test.go
systest/vector/vector_test.go
tok/hnsw/helper.go
tok/hnsw/persistent_factory.go
tok/hnsw/persistent_hnsw.go
tok/hnsw/persistent_hnsw_test.go
tok/options/README.md
worker/worker_test.go

Fixed spelling of euclidean from euclidian. 
Updated default parameters.

fix(vector): fixed euclidean spelling and a bug in parameters

---

dgraph/Makefile

Following v24 import changes, git version stopped working.

fix(core): Build to show correct version

---

dgraphtest/config.go
graphql/resolve/resolver.go

fix some function names in comment

chore: fix some function names in comment

---

tok/hnsw/persistent_hnsw.go

Title format:
- `Topic(Area): Feature`
- `Topic` must be one of `build|ci|docs|feat|fix|perf|refactor|chore|test`
- `Area` must be one of `acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade|zero`
- * Add [BREAKING] if it is a breaking change
------------------
Body Format:
Description: <add description>
Fixes: <GitHub Issue>
Closes: <JIRA Issue>
Docs: <docs PR>

fix(core): fix visited uids bitset memory

---

dgraph/Makefile

Following v24 import changes, git version stopped working.

fix(core): Build to show correct version (#9192)

---

x/x.go

Fixes a compilation error on Windows, needed for ModusDB.

fix: compile on Windows

---

CHANGELOG.md
algo/benchmarks
chunker/README.txt
contrib/manual_tests/test.sh
graphql/bench/README.md
graphql/testdata/custom_bench/profiling/graphql_profiler.go
paper/dgraph.tex
systest/1million/test-reindex.sh
systest/21million/test-21million.sh
systest/loader-benchmark/loader-benchmark.sh
t/t.go

Update benchmarks paths with recent repo move.
**Checklist**

chore: update benchmark paths

---

.trunk/trunk.yaml
CONTRIBUTING.md
SECURITY.md
go.mod
graphql/e2e/custom_logic/cmd/go.mod
t/Makefile
t/README.md

Bump Go patch version
**Checklist**

chore(deps): bump Go patch version

---

dgraph/cmd/alpha/run.go
posting/lists.go
posting/mvcc.go
worker/server_state.go

fix(core): put new metrics behind a feature flag (#9337)

---

posting/oracle.go
worker/sort_test.go

fix(core): fix read scalar list with rollups
