- graphql/admin/endpoints_ee.go
- graphql/admin/restore.go
- systest/online-restore/online_restore_test.go
The backup ID can now be passed to select a specific series of backups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5208)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-713d7c5795-55297.surge.sh)
> Allow backup ID to be passed to restore endpoint.

- ee/acl/acl_test.go
Added test for -:
* Different groups having different permissions for a predicate and users belong to more than 1 such group.
* New predicate creation. Users can't create new predicate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5083)
> Extend ACL tests

- xidmap/xidmap.go
Small optimization to avoid reading the atomic once again after the
value is successfully updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5224)
> Return immediately if compareandswap updates the maxUidSeen.

- worker/backup_handler.go
- worker/file_handler.go
- worker/restore.go
- worker/s3_handler.go
Removing these log statements as they are not very useful and some of
them look like leftovers from prevoius debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5227)
> Remove unnecessary log lines.

- wiki/content/enterprise-features/index.md
This PR documents the steps for user to create backups to Google Cloud Storage via Minio Gateway. Created a new PR after deleting my fork.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5111)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-119e4fa56f-52531.surge.sh)
> Document backups to Google cloud storage

- graphql/admin/add_group.go
- graphql/admin/admin.go
- graphql/admin/schema.go
- graphql/admin/update_group.go
- graphql/dgraph/execute.go
- graphql/e2e/common/error.go
- graphql/resolve/mutation.go
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/mutation_test.go
- graphql/resolve/query.go
- graphql/resolve/resolver.go
- graphql/resolve/resolver_error_test.go
Refactors the signatures of the Dgraph execution functions.
Because:
* Some of these have gotten out of hand with many inputs and upto 4 return values
* We'll need to expose transaction handling as part of auth, so we need access to the requests and responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5244)
> graphql: execution refactor

- go.mod
- go.sum
Among all improvements, this release reports module dependencies by
reading runtime information. It means standalone Go binaries can report
their build dependencies.
Fixes #5166.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5231)
> Bump sentry-go to v0.6.0

- wiki/content/howto/index.md
This PR is meant to document support for encryption with the debug tool per this ticket: https://dgraph.atlassian.net/browse/DGRAPH-1202?atlOrigin=eyJpIjoiMjk3NGE5YjY2NTc1NDM2MGFmNTMyODViMGVjZDM5OWUiLCJwIjoiaiJ9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5202)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c1411b6795-55996.surge.sh)
> Document support for encryption with debug tool

- dgraph/cmd/live/batch.go
- worker/draft.go
Live loader currently runs x.Fatalf the moment it has a connection interrupt. Instead, it should just retry indefinitely.
Also, remove a `%+v` error print for aborting transactions, which causes the entire error stack trace to be printed, which makes it look like a crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5268)
> Avoid crashing live loader in case the network is interrupted.

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/mutation_test.go
- graphql/resolve/query_test.go
- graphql/resolve/resolver.go
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/remote.go
- graphql/schema/remote_test.go
- graphql/schema/rules.go
- graphql/schema/wrappers.go
- graphql/schema/wrappers_test.go
This PR adds support for mutations on remote GraphQL endpoints through graphql.
```graphql
type Mutation {
// Note - The input/return payload here should be something that the user should
// have defined or we should have.
updateMyFavoriteUsers(input: [User!]): AddUserPayload @custom(input: {
url: "http://api-gateway.com/graphql",
method: "POST"
graphql: "mutation { updateUsers(input: $input) }"
})
}
```
Something like the above is now possible. It is possible to pass the input parameters in the graphql request.
Fixes #GRAPHQL-325
None
\>= 20.07.0
added support for mutations on remote GraphQL endpoints through graphql.
No
No
Yes
No
--- …
> graphql: Support mutations on remote GraphQL endpoints

- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/resolver.go
Append errors encountered while making HTTP requests to resolve fields to the list of errors returned to the client. Addresses the comments on #5176. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5261)
> graphql: Propogate errors encountered from external endpoints back to the client 

- wiki/content/deploy/index.md
Jira - Dgraph-1203
This PR updates documentation about the changes to zero flag added via commit https://github.com/dgraph-io/dgraph/commit/82adb16f0f46fd617ea09bb6f54ce7f236278074.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5262)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4d74df9198-57283.surge.sh)
> wiki: Add info about multiple zeros in HA

- contrib/integration/testtxn/main_test.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/reduce.go
- worker/groups.go
- x/config.go
JIRA- DGRAPH-1132
Currently, alpha supports specifying only a single zero instance
address via the `--zero` flag in `dgraph alpha` command. This commit
adds supports for a comma-separated list of `zero` addresses in
`dgraph alpha` so that any zero address can be used from the list
of zero addresses if one of them is unavailable.
We'll pick zero addresses starting from the first one in the list and
try to establish a connection to it. If it fails, we'll pick
the next zero address.
The `dgraph bulk/live` command accepts only a single zero address.
The comma-separated list is only for `dgraph alpha` command.
(cherry picked from commit 82adb16f0f46fd617ea09bb6f54ce7f236278074)
--- …
> release/v1.2: Support comma separated list of zero addresses in alpha (#5116)

- dgraph/cmd/live/batch.go
- worker/draft.go
Cherry-pick of #5268 onto release/v1.2:
> Live loader currently runs x.Fatalf the moment it has a connection interrupt. Instead, it should just retry indefinitely.
>
> Also, remove a `%+v` error print for aborting transactions, which causes the entire error stack trace to be printed, which makes it look like a crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5276)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cd5a8983bb-57454.surge.sh)
> release/v1.2: Avoid crashing live loader in case the network is interrupted.

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
This PR exposes the `compression_level` flag in `alpha`. The flag can be set as 
```
dgraph alpha --badger.compression_level=xxx
```
A higher value of the compression level is more CPU intensive but offers better compression ratio. The default value is `3`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5278)
> Alpha: Expose compression_level option

- algo/uidlist.go
- algo/uidlist_test.go
- codec/codec.go
- posting/list.go
Rollup was setting the BlockSize of the encoder for multi-part list but not for
normal lists.
This caused ApproxLen to return 0. Then the intersect algorithm exited early in this case.
Existing data will be encoded with the right block size the next time the list is rolled up.
This PR does the following.
1. Set the blocksize.
1. Add an assert in rollup to verify that the blocksize is always the right value.
1. Eliminate the check in the intersect algorithm to not return immediately even if ApproxLen
returns 0. There's no difference if the actual length is zero since the smallest list is picked
to perform the iteration. If the list has data but a block size of zero, removing this check allows
the query to return the right result. Added a test to verify this scenario.
1. Added missing tests …
> Always set BlockSize in encoder.

- worker/draft.go
- worker/online_restore_ee.go
While doing an online restore, queries and mutations should be
disallowed.
Fixes DGRAPH-1231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5265)
> Enable draining mode when doing an online restore.

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
This PR exposes the `compression_level` flag in `alpha`. The flag can be set as
```
dgraph alpha --badger.compression_level=xxx
```
A higher value of the compression level is more CPU intensive but
offers a better compression ratio. The default value is `3`.
`compression_level=0` disables compression.
(cherry picked from commit 7442993fb862d16d1181a2accd860acd9ebbf67d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5279)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-20099d09b1-57550.surge.sh)
> release/v1.2: Alpha: Expose compression_level option (#5278)

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
This PR exposes the `compression_level` flag in `alpha`. The flag can be set as 
```
dgraph alpha --badger.compression_level=xxx
```
A higher value of the compression level is more CPU intensive but 
offers a better compression ratio. The default value is `3`.
`compression_level=0` disables compression.
(cherry picked from commit 7442993fb862d16d1181a2accd860acd9ebbf67d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5280)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0af9c5913c-57556.surge.sh)
> release/v20.03: Alpha: Expose compression_level option (#5278)

- worker/restore.go
Jira - DGRAPH-1281 and DGRAPH-1282
When the restore is started, we open a badger instance with the provided encryption key and then check if the backup file can be opened using the encryption key. If the backup cannot be opened using the encryption key, we return an error to the user but the badger DB stores the encryption key.
When the user tries to restore the same backup to the same badger instance without a key (because backup is unencrypted), badger complaints about the missing key. 
This PR fixes by opening badger after opening the backup file. This ensures we don't open an encrypted badger db for an unencrypted backup file.
--- …
> Restore: Handle incorrect encryption key

- ee/backup/restore.go
Jira - DGRAPH-1281 and DGRAPH-1282
When the restore is started, we open a badger instance with the
provided encryption key and then check if the backup file can be
opened using the encryption key. If the backup cannot be opened
using the encryption key, we return an error to the user but the
badger DB stores the encryption key.
When the user tries to restore the same backup to the same badger
instance without a key (because backup is unencrypted), badger
complaints about the missing key.
This PR fixes by opening badger after opening the backup file.
This ensures we don't open an encrypted badger db for an
unencrypted backup file.
(cherry picked from commit 25c37c823593fe4480ca10e3354336503be3785b)
--- …
> release/v1.2: Restore: Handle incorrect encryption key (#5284)

- worker/restore.go
Jira - DGRAPH-1281 and DGRAPH-1282
When the restore is started, we open a badger instance with the
provided encryption key and then check if the backup file can be
opened using the encryption key. If the backup cannot be opened
using the encryption key, we return an error to the user but the
badger DB stores the encryption key.
When the user tries to restore the same backup to the same badger
instance without a key (because backup is unencrypted), badger
complaints about the missing key.
This PR fixes by opening badger after opening the backup file.
This ensures we don't open an encrypted badger db for an
unencrypted backup file.
(cherry picked from commit 25c37c823593fe4480ca10e3354336503be3785b)
--- …
> release/v20.03:Restore: Handle incorrect encryption key (#5284)

- go.mod
- go.sum
The protobuf version was updated accidentally in https://github.com/dgraph-io/dgraph/commit/7b37ddba6d98a5d5e49ecd1e6d76295fba18ddec.
This PR reverts the version update. This should also suppress the warning _temporarily_ .
```
$ dgraph
2020/04/22 17:19:12 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5290)
> Downgrade protobuf to version v1.3.5

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/e2e/custom_logic/schemas/batch-mode-graphql.graphql
- graphql/e2e/custom_logic/schemas/batch-mode-rest.graphql
- graphql/e2e/custom_logic/schemas/mixed-modes.graphql
- graphql/e2e/custom_logic/schemas/single-mode-graphql.graphql
- graphql/e2e/custom_logic/schemas/single-mode-rest.graphql
- graphql/resolve/resolver.go
- graphql/schema/errors.go
- graphql/schema/remote.go
- graphql/schema/rules.go
- graphql/schema/wrappers.go
- graphql/schema/wrappers_test.go
Fields could earlier be resolved through custom REST endpoints. This change adds support for resolving fields through GraphQL endpoints which could be a query/mutation.
TODO
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5271)
> graphql: Resolve fields through custom GraphQL endpoints

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/e2e/custom_logic/schemas/batch-mode-graphql.graphql
- graphql/e2e/custom_logic/schemas/mixed-modes.graphql
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/remote.go
- graphql/schema/remote_test.go
- graphql/schema/rules.go
- graphql/schema/wrappers.go
This PR adds validations and tests for `@custom` graphql on fields
Fixes #GRAPHQL-392
None
\>= 20.07.0
added validations and tests for `@custom` graphql on fields
No
No
Yes
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5283)
> graphql: add validations and tests for @custom graphql on fields

- dgraph/cmd/live/batch.go
- worker/draft.go
Cherry-pick of #5268 onto release/v20.03.
> Live loader currently runs x.Fatalf the moment it has a connection interrupt. Instead, it should just retry indefinitely.
>
> Also, remove a `%+v` error print for aborting transactions, which causes the entire error stack trace to be printed, which makes it look like a crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5275)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-31c16e2a52-57434.surge.sh)
> release/v20.03: Avoid crashing live loader in case the network is interrupted.

- x/sentry_integration.go
Fixes #DGRAPh-1270
1. Separate dev and release events into its own projects. The DSN (API KEY) determines the project the event goes to.
2. Implement beforeSend() method. This method
- Removes the stacktrace in the event. They are of no use. 
- Sets the event type to the panic's message. 
On the sentry side, I created a new project "dgraph-devtest-playground" where the dev build events will go. The "dgraph-gh" project will now only be used for prod/release events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5288)
> segregate dev and prod into its own projects; handle panic bt and type info for better grouping

- wiki/content/releases/index.md
- wiki/scripts/build.sh
This PR sets v20.03.1 as the latest docs.
Changes
* Update build script to set v20.03.1 as the latest docs.
* Update Releases page with newest release versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5309)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-33fd341f0c-58763.surge.sh)
> docs: Set v20.03.1 as the latest docs.

- wiki/content/deploy/index.md
This adds a section to cover disk compression in Dgraph and the configuration option `--badger.compression_level`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5294)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c67d5044d9-58813.surge.sh)
> docs: Add section about compression level option.

- wiki/content/deploy/index.md
Add a section to the Deploy docs about ludicrous mode.
All the ludicrous mode changes made it in v20.03.1.
* What is it
* How to enable it
* What are the trade offs
* Can it work with HA clusters (yes)
* Can it work with sharded clusters (yes)
Fixes DGRAPH-1187.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5310)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-37c35605f8-58878.surge.sh)
> docs: Add section about ludricrous mode.

- graphql/e2e/common/admin.go
- graphql/e2e/common/common.go
- graphql/resolve/resolver.go
@martinmr pointed as part of https://github.com/dgraph-io/dgraph/pull/5307 that partial backup queries were not working. On inspection, I found out that partial admin queries are broken after the refactoring that happened as part of simplifying how resolver are written. The reason being that `[]interface{}` is different from `[]map[string]interface{}`. We also didn't have any test which did partial queries. I have added a test for the same and have a fix in place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5317)
> graphql: Fix response for partial admin queries.

- graphql/e2e/custom_logic/cmd/main.go
- graphql/resolve/custom_mutation_test.yaml
- graphql/resolve/custom_query_test.yaml
- graphql/resolve/resolver.go
Earlier, we expected the response to be an object with a key that was the same as the key defined in our GraphQL schema as the query/mutation name. We have removed that limitation for now and just take the response as it is. Fixes GRAPHQL-340.
There were also discussions around the `http` arguments inside `@custom` accepting another key called `responseKey` which allows keeping the same functionality we have right now but being more configurable. We are not doing that right now but if we decide to, we should do it for both query/mutation and also fields resolved through custom HTTP endpoints.
For e.g.
```
type Query {
myFavoriteMovies(id: ID!, name: String!, num: Int): [Movie] @custom(http: {
url: "http://mock:8888/favMovies/$id?name=$name&num=$num",
method: "GET",
responseKey: …
```
> Change the expected response structure for queries/mutations that are resolved through HTTP endpoints.

- worker/export.go
- worker/export_test.go
Fixes https://github.com/dgraph-io/dgraph/issues/5053
Fixes DGRAPH-1260
The current implementation of export would add dropped predicates to the exported schema.
This PR fixes it by ignoring the deleted predicates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5302)
> Export: Ignore deleted predicates from schema

- wiki/content/query-language/index.md
Fixes #4399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5306)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c25332894e-59183.surge.sh)
> Adding docs about filtering on list

- gql/parser.go
- gql/parser_test.go
- query/query1_test.go
- worker/task.go
Currently `uid_in` functions checks membership of only one **uid** across a given predicate edge. This PR will extend the support of membership checks to multiple **uids** in a single query fragment. Particularly we can run queries like this which checks for the presense of two uids (0x4e472a and 0x4e472b):
```
q(func: eq(name, "Jane Doe") ){
name
friend @filter( uid_in(memberOf, [0x4e472a, 0x4e472b]) ) {
name
}
}
```
Fixes #JiraIssue [DGRAPH-1292](https://dgraph.atlassian.net/browse/DGRAPH-1292)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5292)
> Add support for multiple uids in uid_in function

- raftwal/storage.go
Somebody reported that an error message is printed in this line (due to
compaction happening at the same time). However, the range in question
goes from zero to zero. We should skip deleting empty ranges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5343)
> Avoid deleting empty ranges from the write-ahead log.

- worker/export.go
- worker/export_test.go
Fixes https://github.com/dgraph-io/dgraph/issues/5053
Fixes DGRAPH-1260
The current implementation of export would add dropped
predicates and deleted types to the exported schema.
This PR fixes it by ignoring the deleted predicates and types.
(cherry picked from commit 23140a9f61116ead3defda05bbade9eeca161aef)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5326)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-34541f2982-59439.surge.sh)
> release/v20.03: Export: Ignore deleted predicates from schema (#5302)

- worker/export.go
- worker/export_test.go
Fixes https://github.com/dgraph-io/dgraph/issues/5053
Fixes DGRAPH-1260
The current implementation of export would add dropped
predicates and deleted types to the exported schema.
This PR fixes it by ignoring the deleted predicates and types.
(cherry picked from commit 23140a9f61116ead3defda05bbade9eeca161aef)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5327)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d5221e4649-59452.surge.sh)
> release/v1.2: Export: Ignore deleted predicates from schema (#5302)

- wiki/content/deploy/index.md
Use relref link to refer to a page in a specific version of the docs. Using relref fixes two things:
* It respects the baseURL for dgraph.io/docs
* It respects the currently selected version of the docs (e.g., latest, master, v20.03.0, etc.).
Fixes #5352, DGRAPH-1325.
This needs to be cherry-picked to the previous doc version pages too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5367)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1e79765b39-60609.surge.sh)
> docs: Fix broken link for versioned page.

- graphql/e2e/common/mutation.go
- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/update_mutation_test.yaml
Fixes https://github.com/dgraph-io/dgraph/issues/5355
Adds testing around the issue.  The tests now represent all the possible cases.  One case ("updt single edge" cases) was the issue and failing.
The fix doesn't change any existing tests, except one that was also incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5356)
> graphql: ensure upserts don't have accidental edge removal

- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_add_test.yaml
- graphql/resolve/auth_update_test.yaml
Adds more testing around authorization given https://github.com/dgraph-io/dgraph/issues/5355.
This will fail testing until the changes from https://github.com/dgraph-io/dgraph/pull/5356 get merged through.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5357)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-dfba003062-60673.surge.sh)
> graphql: more testing around additional deletes and auth

- wiki/config.toml
- wiki/scripts/build.sh
These changes make docs work with Hugo v0.69.2 (the current latest version).
Starting with [Hugo v0.60.0](https://gohugo.io/news/0.60.0-relnotes/) and later, setting `markup.goldmark.renderer.unsafe = true` is required to use inline HTML. Otherwise, inline HTML in Markdown documents is replaced with ``. We use raw HTML in some places of the docs (e.g., on the front page).
Changes
* Set `[markdown.highlight] noClasses = false` to keep the same syntax highlighting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5337) …
> docs: Update Hugo config for latest Hugo version.

- contrib/config/kubernetes/dgraph-ha/README.md
- contrib/config/kubernetes/dgraph-ha/cluster.yaml
- contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml
This PR changes the example `dgraph-ha.yaml` to use `ClusterIP` service type for security best practices.  Previously, the default was to expose the Dgraph cluster to the wilds of public Internet.  
Changes:
* Services `LoadBalancer` to `ClusterIP`
* Removed single node service, as not needed.
* Added example eksctl script for easy provisioning of Amazon EKS
* Added README to add more depth, as well as show options on how to access and secure endpoints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5346)
> DGRAPH-1287 Updated example dgraph-ha.yaml for sec best practices

- query/fastjson_test.go
- query/outputnode.go
- query/outputnode_test.go
This PR further tries to simplify `fastJsonNode` processing. It has following changes:
* Return error response if encoded response is > 4GB in size.
* Replace `idMap` with `idSlice` in `encoder`.
* Refactor `AddListChild` and `AddMapChild` to remove `attr` from their arguments. Both functions
accept parent, child and attr as arguments. This attr is equal to attr field of child, hence sending
it explicitly can be avoided.
* Minimise calls to `idForAttr()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5359)
> Minor changes in fastJsonNode

- contrib/release.sh
This updates the release.sh script to use xgo for Linux, Windows, and Darwin builds. 
This is to fix the panics related to Badger compression which only uses Zstd when Cgo is enabled. See #4995.
Darwin and Windows release builds moving forward (v20.03.0 were already built with this change). Linux builds are working fine.
No.
Fixes #4995
This uses https://github.com/techknowlogick/xgo/, which is a maintained fork of https://github.com/karalabe/xgo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5120)
> contrib: Use xgo to use Cgo in cross-compiled release builds.

- dgraph/cmd/zero/license.go
- dgraph/cmd/zero/license_ee.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- dgraph/cmd/zero/zero.go
Fixes DGRAPH-1341
The enterprise_license option on zero is not applied properly. There were couple issues: 1) It would be over-written by trial license. 2) It generally failed because when the license was applied, Raft was not initialized and the zero was not the leader.
This patch make several fixes and improvements
1. Apply the option `enterprise_license` only after the node's Raft is initialized and it is the leader. 
2. Don't apply the trial license if a license already exists.
3. Disallow the enterprise_license option for OSS build and bail out. 
4. Apply the option even if there is a license from a previous life of the Zero (i.e. Zero is restarted with same the `zw/`
Tests:
1. New Cluster, `dgraph zero` 
Trial license is applied.
2. New Cluster, `dgraph zero …
> EE license fixes.

- query/query.go
Use the GetUids function which handles the case where the pointer is nil
correctly.
Fixes DGRAPH-1342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5377)
> Fix segmentation fault in query.go

- wiki/content/tutorial-3/index.md
I believe this is a typo as `author_name` (ie: not "author{dot}name") is used everywhere else
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/4549)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-40e72f0762-61702.surge.sh)
> Fix typo in Tutorial

- dgraph/cmd/zero/license.go
- dgraph/cmd/zero/license_ee.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- dgraph/cmd/zero/zero.go
( git cherry-pick 4e35cba37f8176f8d3681451d6faa4df021d4130)
Fixes DGRAPH-1341
This patch make several fixes and improvements
-  Apply the option enterprise_license only after the node's Raft is initialized and it is the leader.
- Don't apply the trial license if a license already exists.
- Disallow the enterprise_license option for OSS build and bail out.
- Apply the option even if there is a license from a previous life of the Zero (i.e. Zero is restarted with same the zw/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5384)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.sv …
> Cherry-Pick to v20.03 - EE license fixes. (#5383)

- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- dgraph/cmd/zero/zero.go
- posting/index.go
- query/query.go
There's no need to call the len function when checking for an empty
string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5390)
> Fix empty string checks.

- .github/workflows/label.yml
Make it run only on new PRs. Prevent it from creating multiple events with Branch synchronization.
No issues to fix
No Jira to fix
No Breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5395)
> [Minor] update label.yml

- worker/groups.go
The function processing the oracle delta stream combines multiple deltas
into one to reduce the number of proposal. However, the group checksums
were not being updated, causing some group checksums update to be lost.
gRPC guarantees that the ordering of the deltas coming from the stream
so overwriting the group checksums is safe.
Tested by following the steps in #5368.
Fixes #5368, DGRAPH-1333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5394)
> Update group checksums when combining multiple deltas.

- worker/groups.go
The context created with context.WithCancel should be cancelled before
jumping to the START label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5397)
> Fix warning about issues with the cancel function.

- protos/Makefile
- protos/depcheck.sh
If installed from a package manager, the header files will be at
/usr/include not /usr/local/include.
This change fixes the check by looking at both places and including
them in the call to protoc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5381)
> Fix protobuf headers check.

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/e2e/auth/test_data.json
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/query_rewriter.go
- graphql/schema/auth.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5392)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5b6cd9570f-62461.surge.sh)
> graphql: Added RBAC and related tests

- query/query.go
- worker/task.go
The following output from pprof shows that the `pb.Result{}` takes up a lot of memory. This PR tries to reduce the unnecessary allocation
From https://discuss.dgraph.io/t/optimize-dgraph-memory-usage/6665
```
(pprof) list processTask
.     1.91GB    887:	out, err := qs.helpProcessTask(ctx, q, gid)
.          .    888:	if err != nil {
4.50MB     4.45GB    889:		return &pb.Result{}, err // Create this object once, use it repeatedly.
.          .    890:	}
.     4.97GB    891:	return out, nil
.          .    892:}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5414)
> Worker: Return nil on error

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
Opencensus traces are taking a lot of memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5405)
> Change the default ratio of traces from 1 to 0.01.

- dgraph/cmd/alpha/run.go
Fixes DGRAPH-1359
Sentry init on alpha is not done asap when Run() is called. This results in the monitoring process to have additional state, including the HMAC Secret and the Enc Key, that it should not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5409)
> Sentry should be initialized first on Alpha.Run()

- dgraph/cmd/alpha/run.go
cherry pick from commit c9bc5cab2a521d5c9b6c572023d3a0db572eb48f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5429)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2f8ec0a86f-63059.surge.sh)
> Cherry-Pick v20.03 : Initialize sentry  at the begin of alpha.Run() (#5409)

- .github/CODEOWNERS
This stops everyone from getting tagged on every PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5438)
> Changing the default code owner

- edgraph/access_ee.go
- graphql/admin/current_user.go
- worker/config.go
- x/types.go
- x/x_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5450)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fd81269a7b-64118.surge.sh)
> Cherry-Pick v20.03: Use SensitiveByteSlice type for hmac secret (#5445)

- edgraph/access_ee.go
- worker/config.go
- x/types.go
- x/x_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5451)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-523e83b721-64127.surge.sh)
> Cherry Pick v1.2: Use SensitiveByteSlice type for hmac secret (#5445)

- dgraph/cmd/alpha/http.go
while running queries, we should propagate the request context down the tree. This ensures that if the caller has cancelled the request i.e. not waiting for the response, we stop executing the query too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5418)
> Use request context while handling queries

- graphql/admin/admin.go
- graphql/e2e/common/admin.go
This PR adds support for adding xid to existing gqlschema nodes as it was not taken into consideration in #5054.
Fixes #GRAPHQL-417.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5457)
> graphql: support existing gqlschema nodes without xid

- wiki/content/deploy/index.md
We currently do not have documentation on how to create alarms in response to the change in status of the `/health` endpoint. This PR adds docs towards the same. 
Fixes DGRAPH-1081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5399)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9e60822166-64773.surge.sh)
> Added docs for Cloudwatch monitoring

- query/common_test.go
- query/query3_test.go
This PR edits test cases to remove non-deterministic behavior in shortest path queries when there are more than one paths with identical cost. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5464)
> Edit test cases to remove flaky behavior

- dgraph/cmd/zero/run.go
- worker/server_state.go
- x/x.go
Pstore and WALstore valueGC go routine in v1.2.x use the same timeticker  which would cause gc of p directory would't be apply sometimes. 
The related discuss thread is [here](https://discuss.dgraph.io/t/should-pstore-and-walstore-use-the-same-time-ticker-for-gc/6749/4).
Cherry-pic commit from master to fix this, and test on production env, it works fine and vlog size decreases significantly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5468) …
> Pstore and WALstore use different timeticker for value gc

- graphql/admin/schema.go
- graphql/e2e/common/admin.go
- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/common/query.go
- graphql/resolve/mutation.go
- graphql/resolve/mutation_query_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/query.go
- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
- graphql/resolve/resolver.go
- graphql/resolve/resolver_error_test.go
- graphql/resolve/resolver_error_test.yaml
- graphql/resolve/resolver_test.go
(cherry picked from commit cb01b0d76d6a0ad36c5e88d0a28dbf19493ff757)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5484)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-00d727bba2-65441.surge.sh)
> graphql: move alias to end of graphql pipeline (#5369)

- graphql/admin/schema.go
- graphql/dgraph/execute.go
- graphql/e2e/common/error.go
- graphql/resolve/mutation.go
- graphql/resolve/resolver.go
- graphql/resolve/resolver_error_test.go
Adds transaction system to graphql mutations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5485)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d46bac604a-65468.surge.sh)
> graphql: adds transactions to graphql mutations

- worker/executor.go
Fixes DGRAPH-1332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5479)
> acquire lock in addEdges()

- wiki/content/enterprise-features/index.md
The backup GraphQL interface uses camel case instead of underscores.
This updates the documentation to match the new names.
Fixes DGRAPH-1589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5489)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-11d3b3d91a-65613.surge.sh)
> Update names of graphql variables to match correct capitalization.

- worker/groups.go
`groupi.Tablet()` returns error and empty Tablet when error is returned while querying zero for Tablet
serving info. This results in allocation of space by empty Tablet and it shows up in alloc_space
profile.
```go
.          .    463:func (g *groupi) Tablet(key string) (*pb.Tablet, error) {
16.22GB    16.22GB    464:	emptyTablet := pb.Tablet{}
.          .    465:
.          .    466:	// TODO: Remove all this later, create a membership state and apply it
.          .    467:	g.RLock()
.          .    468:	tablet, ok := g.tablets[key]
.          .    469:	g.RUnlock()
.          .    470:	if ok {
.          .    471:		return tablet, nil
.          .    472:	}
.          .    473:
.          .    474:	// We don't know about this tablet.
.          .    475:	// Check with dgraphzero if we …
```
> Return nil instead of emptyTablet in groupi.Tablet()

- worker/snapshot.go
There could be changes to the schema while the snapshot is being sent.
Therefore, the list of types and predicates that is sent at the end
should be computed before the snapshot is sent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5488)
> Get lists of predicates and types before sending the snapshot.

- dgraph/cmd/zero/run.go
This will prevent trySnapshot from trying to send a range to the index
range channel before it's closed.
Fixes DGRAPH-1574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5476)
> During shutdown, generate snapshot before closing raft node.

- wiki/scripts/local.sh
Fixes DGRAPH-1295
For now, we will only include fixes for the scripts in *wiki* folder.
(WIP) There are 42 other shell scripts in the repository that will need to be included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5505)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-071acb1792-66032.surge.sh)
> added shellcheck fix for preview scripts

- dgraph/cmd/live/run.go
This PR aims to fix a memory leak in live loader. Currently while getting uid for a NQuad
subject/uid object, we call `xidMap.AssignUid()`. This subject/uid object is of string type.
We suspect that these uids(strings) are still holding references to original string, which
we get after reading single lines in `checker.Parse()`. Hence GC is unable to clean these strings.
In this PR, while getting uid for any NQuad subject/uid object, we pass a copy of it to
`xidMap.AssignUid()`.
Original profile:
```
File: dgraph
Build ID: b80d1c50901c66e79b21afb1ed72a92bed950dc9
Type: inuse_space
Time: May 19, 2020 at 3:52pm (IST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 62468.74MB, 100% of 62486.76MB total
Dropped 28 nodes (cum <= …
```
> Fix memory leak in live loader

- systest/21million/test-21million.sh
test-21million.sh can show failures like the following in CI builds:
```
------- Stdout: -------
=== RUN   TestQueries/query-044
--- FAIL: TestQueries/query-044 (4.74s)
run_test.go:86: 
Error Trace:	run_test.go:86
Error:      	Received unexpected error:
rpc error: code = Unknown desc = : rpc error: code = Unavailable desc = transport is closing
Test:       	TestQueries/query-044
```
```
------- Stdout: -------
=== RUN   TestQueries/query-045
--- FAIL: TestQueries/query-045 (0.01s)
run_test.go:86: 
Error Trace:	run_test.go:86
Error:      	Received unexpected error:
rpc error: code = Unknown desc = : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.24.0.4:7182: connect: …
```
> test: Show cluster logs on failure for 21million systest.

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/bulk/run.go
- systest/bulk_live_cases_test.go
- systest/bulk_live_fixture_test.go
Support passing a GraphQL schema file to the bulk loader. The bulk loader will generate
the triples relevant triples expected by Dgraph. 
Related to DGRAPH-1283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5509)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-054f904c0b-66679.surge.sh)
> Support passing GraphQL schema to bulk loader.

- systest/21million/test-21million.sh
Cherry-pick of #5507 onto release/v1.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5520)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7807091e01-66722.surge.sh)
> release/v1.2: test: Show cluster logs on failure for 21million systest.

- systest/loader/loader_test.go
- worker/export.go
- worker/export_test.go
- worker/groups.go
- worker/worker_test.go
The GraphQL schema is all that's needed to restore the graphql layer. Export it to a separate
file and don't export the existing triples.
First part of the fix for DGRAPH-1283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5501)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-376a56b2ca-66753.surge.sh)
> Export GraphQL schema to separate file.

- dgraph/cmd/migrate/README.md
This commit is meant to update the instructions for using `dgraph/cmd/migrate` to work with Dgraph v20.03.x.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5495)
> Update dgraph/cmd/migrate README.md

- systest/loader/loader_test.go
- worker/export.go
- worker/export_test.go
- worker/worker_test.go
The GraphQL schema is all that's needed to restore the graphql layer. Export it to a separate
file and don't export the existing triples.
First part of the fix for DGRAPH-1283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5528)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5260db303f-66937.surge.sh)
> Export GraphQL schema to separate file. (#5501)

- ee/backup/backup.go
- go.mod
- go.sum
- posting/list.go
- worker/backup_ee.go
Backups convert the values stored in disk into an intermediate format
(for backwards compatibility reasons). This creates a lot of
pb.PostingList and pb.BackupPostingList objects that are discarded
almost immediatly. Using preallocated protobufs (one per thread used by
the stream object) should avoid these allocations altogether.
Fixes DGRAPH-1312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5508)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2396d9ce84-66219.surge.sh)
> Use pre-allocated protobufs during backups.

- go.mod
- go.sum
- worker/server_state.go
This PR updates badger and enables storing indices in the cache which was added via dgraph-io/badger#1336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5538)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-906eb1c14c-67246.surge.sh)
> release/v1.2 Update badger to commit e7b6e76f96e8 #5537

- go.mod
- go.sum
- worker/server_state.go
This PR updates badger and enables storing indices in the cache which was added via dgraph-io/badger#1336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5539)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4eafb18242-67261.surge.sh)
> release/v20.03 Update badger to commit e7b6e76f96e8 #5537

- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/schemagen.go
I observed from the logs that this was happening, which is unexpected behavior. Fixes GRAPHQL-482.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5524)
> graphql: Queries or mutations shouldn't be part of generated Dgraph schema

- wiki/content/query-language/index.md
Fixes DGRAPH 1369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5533)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5188d0b741-67075.surge.sh)
> Added details of K-shortest path queries in documentation

- dgraph/cmd/zero/run.go
Fixes: DGRAPH-1368
Exit gracefully and prevent panic in zero if non-positive rebalance interval duration is passed. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5544)
> Add check on rebalance interval

- contrib/scripts/functions.sh
- dgraph/cmd/bulk/systest/test-bulk-schema.sh
Some versions of docker-compose do not recognize the longer version of
this flag. Found this issue when trying to run the test suite in a
virtual machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5549)
> Use -d instead of --detach when invoking docker-compose.

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/query_rewriter.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5497)
> graphql: Apply type filter for get query at root level.

- dgraph/cmd/debug/run.go
- testutil/backup.go
- worker/server_state.go
Badger supports caching of SST bloom filters, this PR enables caching
bloom filters in ristretto.
The bloom filter cache is enabled only for the `p` directory. The bloom filters for the `w` directory will be kept in memory. We can add those later if necessary. 
This PR also removes old state todos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5552)
> Alpha: Enable bloom filter caching

- worker/draft.go
A panic was caused because n.ops map entry was set to nil in some cases. 
Fix is to not set n.ops map entries to nil. Instead, just delete them.
Fixed DGRAPH-1573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5551)
> dont set n.ops map entries to nil. Instead just delete them

- worker/draft.go
dont set n.ops map entries to nil. Instead just delete them (#5551)
A panic was caused because n.ops map entry was set to nil in some cases.
Fix is to not set n.ops map entries to nil. Instead, just delete them.
Fixed DGRAPH-1573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5557)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4549f6a5bd-67946.surge.sh)
> cherry-picked from commit b05c525873c1c007a6ff4340e3d91fc2ceb96865

- ee/acl/acl_test.go
- graphql/e2e/common/mutation.go
- graphql/resolve/mutation.go
This PR changes the delete msg reported for the case when no nodes are deleted to `No nodes were deleted`. In addition, it corrects some tests which were wrong earlier.
Fixes #GRAPHQL-465.
(cherry picked from commit 47f2f51db7d46fd17f29663257c5b26a656478e6)
\# Conflicts:
\#	ee/acl/acl_test.go
\#	graphql/e2e/auth/auth_test.go
\#	graphql/e2e/common/mutation.go
\#	graphql/resolve/mutation.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5564) …
> backport: graphql: Minor delete mutation msg fix (#5316)

- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/schema/response.go
- graphql/web/http.go
This PR adds the `Graphql-TouchedUids` header in the HTTP response sent by GraphQL.
Fixes #GRAPHQL-489.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5572)
> graphql: add Graphql-TouchedUids header in HTTP response

- graphql/admin/schema.go
- graphql/e2e/common/common.go
This PR makes the updateGQLSchema mutation return the updated schema always, instead of relying on async badger update.
Fixes #GRAPHQL-497.
(cherry-picked from commit 265086f98d04e9a2bfddb5e8e40f677d2f426167)
\# Conflicts:
\#	graphql/admin/schema.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5582)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-35dc57ae86-68789.surge.sh)
> graphql: make updateGQLSchema always return the new schema (#5540)

- dgraph/cmd/debug/run.go
- testutil/backup.go
- worker/server_state.go
Badger supports the caching of SST bloom filters. This PR enables
caching bloom filters in ristretto. The bloom filter cache is enabled
only for the p directory. The bloom filters for the w directory will be
kept in memory. We can add caching for it later if necessary.
This PR also removes old stale todos.
(cherry picked from commit 92328a777993769a45a2b084577af62512c0021b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5554)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a06415f649-67886.surge.sh)
> release/v1.2: Alpha: Enable bloom filter caching (#5552)

- dgraph/cmd/debug/run.go
- testutil/backup.go
- worker/server_state.go
Badger supports the caching of SST bloom filters. This PR enables
caching bloom filters in ristretto. The bloom filter cache is enabled
only for the p directory. The bloom filters for the w directory will be
kept in memory. We can add caching for it later if necessary.
This PR also removes old stale todos.
(cherry picked from commit 92328a777993769a45a2b084577af62512c0021b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5555)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3a7653a8ef-67874.surge.sh)
> release/v20.03: Alpha: Enable bloom filter caching (#5552)

- worker/draft.go
Fixes - DGRAPH-1353
When live loader in running on an Alpha in ludicrous mode, alpha will
crash with a segmentation fault error because badger was closed before
ludicrous mode goroutines were stopped. This PR fixed that issue.
The crash can be reproduced by
```
1. dgraph zero --ludicrous_mode
2. dgraph alpha --ludicrous_mode --enable_sentry=false
3. dgraph live -f $GOPATH/src/github.com/dgraph-io/benchmarks/data/21million.rdf.gz \
-s $GOPATH/src/github.com/dgraph-io/benchmarks/data/21million.schema \
-z localhost:5080 -a localhost:9080 --ludicrous_mode
Hit <CTRL+C> while alpha is receiving data from live loader.
```
(cherry picked from commit e326b9e802f2f04eedf8044361ca28573dbff5a8)
--- …
> release/v20.03 - Alpha: Gracefully shutdown ludicrous mode (#5561) 

- worker/mutation.go
The background reindexing starts indexing in the background but we
do not wait for the indexing to complete in case of error while shutting
down alpha. This PR fixes that issue by waiting for the background
indexing to complete before we shutdown alpha. 
The issue can be easily seen by adding a long sleep in the
background indexing and trying to shutdown alpha. It can be seen
that Alpha doesn't wait for the indexing to complete while shutting
down.
Fixes https://github.com/dgraph-io/dgraph/issues/3873
(cherry picked from commit dc75424d576bcda9e170adc24573204b7b822684)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5597) …
> release/v20.03 Alpha Close: Wait for indexing to complete (#5137)

- query/common_test.go
- query/query3_test.go
- query/shortest.go
- wiki/content/query-language/index.md
Fixes #5426, #5410, #4861
Fixes DGRAPH-1258 DGRAPH-794 DGRAPH-1369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5596)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ee679fd82e-69179.surge.sh)
> release/v1.2 K shortest paths queries fix and documentation update

- dgraph/cmd/zero/license_ee.go
Change error message in case of successful license application
(cherry picked from commit dc8b80c93eabf955178b0eb406e6c179cca048f6)
Fixes #4965, Dgraph-1135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5593)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e00cdff8ed-69151.surge.sh)
> release/v1.2 Change error message in case of successful license application (#5230)

- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/zero.go
Currently, zero uses the MaxRaftId to assign RAFT IDs to new nodes. However, the
MaxRaftId value is not immediately updated and the lock is released in between
creating the proposal and sending the proposal to the RAFT node. This can lead
to situations where more than one new node is assigned the same ID.
To solve this, this change introduces a new field to generate the IDs that is
updated immediately, thus preventing multiple nodes from being assigned
the same ID.
Fixes #5436
cherry-picked from c09380549cf5d57895b189c892b9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5604)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159 …
> (release/v20.03) Avoid assigning duplicate RAFT IDs to new nodes

- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/zero.go
Currently, zero uses the MaxRaftId to assign RAFT IDs to new nodes. However, the
MaxRaftId value is not immediately updated and the lock is released in between
creating the proposal and sending the proposal to the RAFT node. This can lead
to situations where more than one new node is assigned the same ID.
To solve this, this change introduces a new field to generate the IDs that is
updated immediately, thus preventing multiple nodes from being assigned
the same ID.
Fixes #5436
cherry-picked from c09380549cf5d57895b189c892b9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5603)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159 …
> (release/v.1.2) Avoid assigning duplicate RAFT IDs to new nodes.

- worker/backup_handler.go
- worker/file_handler.go
- worker/online_restore_ee.go
- worker/restore.go
- worker/s3_handler.go
This change removes the need to convert between int and uint32.
Group IDs are always uint32.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5605)
> Change groupId from int to uint32 in LoadBackup

- wiki/scripts/local.sh
This change fixes errors for the CI check for shellcheck on release/v20.03.
(cherry picked from commit 266a4dd)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5612)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7bd8b2d1ba-69534.surge.sh)
> docs: Add shellcheck fix for preview scripts.

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- worker/groups.go
- x/sentry_integration.go
(cherry picked from commit 9765e3fbf6e0db301a74dd77e171a9088124bda1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5633)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-964ec75433-70079.surge.sh)
> Cherry pick for v20.03 Send CID for sentry events. (#5625)

- wiki/content/enterprise-features/index.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5638)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b6d841f788-70387.surge.sh)
> Document --encryption_key_file option in dgraph restore command.

- posting/list.go
- posting/list_test.go
- worker/backup_processor.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5648)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4e6773dea2-70562.surge.sh)
> (release/v20.03) Use a sync.Pool to allocate KVs during backup.

- wiki/content/enterprise-features/index.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5647)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c4007bb66d-70535.surge.sh)
> (release/v20.03) Document --encryption_key_file option in dgraph restore command.

- wiki/content/enterprise-features/index.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5646)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d74e79af7d-70528.surge.sh)
> (release/v1.2) Document --encryption_key_file option in dgraph restore command.

- posting/mvcc.go
FIXES - DGRAPH-1613
The incremental roll-up uses a `map` to keep track of the keys that should be rolled up.
The current implementation never clears the map which stores the keys. The existing algorithm is
```
If key is present or key was rolled up 10 seconds ago, perform roll up
```
we never clean up the map in the existing algorithm and as a result the map consumed a lot of memory
```
3.77GB 32.51% 32.51%     3.93GB 33.95%  github.com/dgraph-io/dgraph/posting.(*incrRollupi).Process
```
```
(pprof) list Process
Total: 11.59GB
ROUTINE ======================== github.com/dgraph-io/dgraph/posting.(*incrRollupi).Process in src/github.com/dgraph-io/dgraph/posting/mvcc.go
3.77GB     3.93GB (flat, cum) 33.95% of Total
.          .    118:			for _, key := range *batch {
.          .    119: …
```
> Rollup: Reduce memory consumption of the map

- worker/online_restore_ee.go
Requests for other groups are being sent to the leader but the request
for the group the received the request might not be sent to the leader.
Fix that by first checking if the alpha is the leader. If not, the
request is sent to the leader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5657)
> Only process restore request in the current alpha if it's the leader.

- worker/draft.go
In badger, the right key might be a badger specific key that Dgraph
cannot understand. To deal with these keys, a table is included in
the size calculation if the next table starts with the same key.
Related to DGRAPH-1358 and #5408.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5656)
> Fix: Change tablet size calculation to not depend on the right key.

- .dockerignore
- contrib/Dockerfile
- contrib/config/docker/docker-compose-ha.yml
- contrib/embargo/embargo.yml
- dgraph/cmd/alpha/mutations_mode/docker-compose.yml
- dgraph/docker-compose.yml
- systest/bgindex/docker-compose.yml
- worker/docker-compose.yml
This avoids the possibility of Dgraph not knowing where the Zero leader is in the event of a new election.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5653)
> Adds multiple zero addresses to docker-compose files

- worker/task.go
Fixes: DGRAPH-1608
`srcFn.n` should be equal to `len(q.UidList.Uids)` for implementation `DivideAndRule` and
`calculate` to work correctly. But we have seen some panics while forming `DataKey` in
`calculate()`. panic is of the form `"index out of range [4] with length 1"`. We have tried to
reproduce this but couldn't find any edge case which will result in this panic. So for now
we are just logging when `srcFn.n != len(q.UidList.Uids)` and returning error when this
happens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5652)
> Avoid panic in handleValuePostings

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/schema/rules.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers.go
Add support for declaring headers with custom name like -
secretHeaders: ["Authorization:Github-Api-Token"] where "Authorization" is send as the header name to GitHub and "Github-Api-Token" is used internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5600)
> feat(GraphQL): Allow more control over custom logic header names

- worker/draft.go
- worker/executor.go
Cherry pick changes from PR https://github.com/dgraph-io/dgraph/pull/5585 to branch `release/v20.03`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5636)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a7dbdcc8e6-70273.surge.sh)
> Cherrypick PR #5585 to release/v20.03

- go.mod
- go.sum
- worker/server_state.go
This commit brings the following changes from badger
```
c45d966 Fix assert in background compression and encryption. (#1366)
14386ac GC: Consider size of value while rewriting (#1357)
b2267c2 Restore: Account for value size as well (#1358)
b762832 Tests: Do not leave behind state goroutines (#1349)
056d859 Support disabling conflict detection (#1344)
fd89894 Compaction: Expired keys and delete markers are never purged (#1354)
543f353 Fix build on golang tip (#1355)
a7e239e StreamWriter: Close head writer (#1347)
da80eb9 Iterator: Always add key to txn.reads (#1328)
7e19cac Add immudb to the project list (#1341)
079f5ae DefaultOptions: Set KeepL0InMemory to false (#1345)
```
--- …
> chore(badger): Update badger to latest version

- contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml
Discovered issue with `dgraph-ha.yaml` where dgraph cluster may not come back to a healthy state when zero has a  `readinessProbe.httpGet.path` set to `/state`.  Changing this value to `/health`.
Fixes #5583.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5580)
> update zero health check for dgraph-ha.yaml

- wiki/content/enterprise-features/index.md
This adds two example commands to the docs to apply an enterprise license.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5373)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1225d7082a-61070.surge.sh)
> docs: Add example commands to apply enterprise license.

- worker/task.go
Cherry-pick handleValue panic fix to release/v20.03
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5678)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-51ecfa9df3-71487.surge.sh)
> Cherry-pick handleValue panic fix to release/v20.03

- dgraph/cmd/live/load-uids/load_test.go
- dgraph/cmd/live/run.go
- edgraph/server.go
- ee/acl/acl_test.go
- schema/schema.go
- x/keys.go
This PR fixes the issue where live loader was not able to import the schema exported using export request. It does so, by allowing the alter schema request for pre-defined types to go through if the type in the request is same as the initial internal type.
This issue was introduced as a result of #5185.
This PR also disallows a pre-defined type from being dropped.
Fixes #DGRAPH-1694.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5696) …
> fix(Export/Import): Live load exported schema

- dgraph/cmd/alpha/run.go
- graphql/admin/shutdown.go
- worker/server_state.go
- worker/worker.go
Earlier we had `worker.ShutdownCh` which was used to pass information between `alpha/run.go` and `graphql/admin.go` which was causing confusion and was being used to stop the worker itself. We now have a `y.Closer` in `graphql/admin` which manages the WaitGroup and passing of signals between goroutines using channels. 
Fixes DGRAPH-1169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5560)
> Replace shutdownCh and wait groups to a y.Closer for shutting down Alpha

- ee/enc/util_ee_test.go
- ee/enc/vault_ee.go
Fixes DGRAPH-1722
Fixes DGRAPH-1723
This PR adds support for Vault kv v1 in addition to v2. Also, it allows for Base64 encoded or raw keys fetched from vault. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5708)
> feat(vault): support kv v1 and decode base64 key

- posting/size_test.sh
**Description** Currently when running `./test.sh -F` or the `cd posting && ./size_test.sh`, test failures will be reported as passing.  This is because the underlying test script `posting/size_test.sh`, doesn't return an exit code of 1 when the test fails.  
The test script is a shell script wrapper to setup data, instead of using the go test framework.  Unlike the go test framework it returns exit code of 1 when a test fails, and exit code of 0 when test succeeds.  The `size_test.sh` always returns a 0 when the test passes of fails.
**Solution**
* return exit of 1 if any tests fails (2 tests wrapped in this script)
* return exit of 2 setup fails, such as GCS file not available or file not available.
* do not report error if `rm` on file that doesn't exist
* use `/usr/bin/env` to execute …
> ci: fixes systest  - posting/size_test.sh to return fail for failed test

- x/sentry_integration.go
Fixes DGRAPH-1692
(cherry picked from commit 0088d7492a7ac22be1e7b57f80b60b4b5489415b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5728)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3dec27848a-72818.surge.sh)
> Cherry-pick v20.03: feat(sentry): Tag sentry events with additional version details. (#5674)

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
- x/sentry_integration.go
Fixes DGRAPH-1689.
(cherry picked from commit eeb0dcbcad65ec0d73c174328b6b6f880ac7be6a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5729)
> Cherry-pick v20.03: chore(sentry): Sentry opt out banner. (#5672)

- worker/draft.go
In badger, the right key might be a badger specific key that Dgraph
cannot understand. To deal with these keys, a table is included in
the size calculation if the next table starts with the same key.
Related to DGRAPH-1358 and #5408.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5684)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f0813d8c7b-71644.surge.sh)
> release/v20.07: Fix: Change tablet size calculation to not depend on the right key

- posting/list.go
- posting/list_test.go
- worker/backup_processor.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5683)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4551a16d19-71631.surge.sh)
> release/v20.07: Use a sync.Pool to allocate KVs during backup.

- worker/draft.go
In badger, the right key might be a badger specific key that Dgraph
cannot understand. To deal with these keys, a table is included in
the size calculation if the next table starts with the same key.
Related to DGRAPH-1358 and #5408.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5665)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-785ee0ceb9-71149.surge.sh)
> (release/v20.03) Fix: Change tablet size calculation to not depend on the right key

- ee/enc/util_ee_test.go
- ee/enc/vault_ee.go
Fixes DGRAPH-1722
Fixes DGRAPH-1723
This PR adds support for Vault kv v1 in addition to v2. Also, it allows for Base64 encoded or raw keys fetched from vault.
(cherry picked from commit eff3dd9bb0e2fa20d5d20b992bc36f5829245461)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5725)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-486cf25853-72796.surge.sh)
> Cherry-pick v20.07: feat(vault): support kv v1 and decode base64 key (#5708)

- worker/task.go
Fixes DGRAPH-998
Fixes #4689
When we run ./systest/21million/test-21million.sh --loader live, 
This query fails.
```
{                                                                                                                                                                                                                                                                                                                          
directors(func: gt(count(director.film), 5)) {                                                                                                                                                                                                                                                                           
totalDirectors : count(uid) …
```
> fix(dgraph):  Badger iterator key copy in count index query

- testutil/client.go
Some tests down and up alphas so connection issues are expected and the
tests should retry until the alpha comes back up.
Fixes DGRAPH(1618)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5736)
> test: Retry due to connection issues in RetryMutations and RetryQuery.

- systest/online-restore/online_restore_test.go
The tests are flaky because the test waits for the leaders to complete the request. However,
the followers might be behind and the client can be connected to a follower. The fix is
to check that the client has exited draining mode before doing any queries.
Fixes DGRAPH-1740
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5724)
> test(restore): Fix flakiness in online restore tests.

- wiki/content/deploy/index.md
- Added note about memory recommendation and AWS instance sizes. 
- Corrected port quoting/code escaping. 
- Fixed note about the volume being mounted at /tmp/data and not /data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5759)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-15a5249815-73827.surge.sh)
> docs(Deploy): Added note about memory recommendation and AWS instance sizes.

- gql/parser.go
- gql/parser_test.go
- graphql/dgraph/graphquery.go
- graphql/resolve/query_rewriter.go
- graphql/schema/wrappers.go
- query/query.go
- systest/queries_test.go
Fixes DGRAPH-1279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5607)
> feat(graphql+-): Allow parameterized @cascade directive.

- contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
Minor fix to dgraph-single.yaml for security purposes.
Overview:
* changes from service type form `LoadBalancer` to `ClusterIP`. 
* default should be secure, not exposed to public Internet.
Fixes  #5768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5772)
> update dgraph-single.yaml for security

- CHANGELOG.md
The wrong issue was being referenced for the `@cascade` directive. #5179 is for authorization while #5511 is for `@cascade`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5800)
> docs(CHANGELOG): Fixed referenced issue for @cascade

- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/schema/remote.go
Fixes GRAPHQL-503
This PR fixes remote schema introspection for custom logic in GraphQL for a single remote endpoint. Enabling validation for types that are part of custom logic query/mutation/field in our GraphQL schema against the remote schema .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5710)
> fix(GraphQL): Remote schema introspection for single remote endpoint

- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/schemagen.go
Fixes #5311
Fixes GRAPHQL-419
Previously when Dgraph schema was generated the GraphQL interface was getting skipped and hence it was not present in the generated Dgraph schema. This PR fixes that and hence now all the queries/mutations will work as expected.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5738)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-87aa33a2d9-74808.surge.sh)
> fix(GraphQL): Fix case where Dgraph type was not generated for GraphQL interface

- edgraph/server.go
- graphql/admin/admin.go
- graphql/e2e/schema/schema_test.go
- graphql/resolve/resolver.go
- worker/graphql_schema.go
Fixes #GRAPHQL-370.
This PR makes sure that the GraphQL schema is preserved after `drop_data` operation. It also makes sure that the `getGQLSchema` GraphQL admin resolver reports empty schema after `drop_all`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5790)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cd8ca67f67-74641.surge.sh)
> fix(GraphQL): GraphQL schema is preserved after drop_data

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/schema/rules.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers.go
This PR adds a way to have custom names for headers in custom logic. 
(cherry picked from commit bbf49dca743cf2c95d072a1bfc169d7032011947)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5809)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1b39ca2573-75052.surge.sh)
> feat(GraphQL): Allow more control over custom logic header names (#5600)

- contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
- wiki/content/deploy/index.md
This is update to outdated Kubernetes section around `dgraph-ha.yaml` and `dgraph-single.yaml`.
Overview of Changes:
* Update to show examples with both EKS and GKE
* Removed any mention of kops, replaced with eksctl (and gcloud cli)
* Updated remove resources section, as incorrect and slow (10+ min)
* Replace short form options with more description long form options (as best practices for docs since Unix days)
* Corrected example output as was incorrect
* Mentioned that we tested on Kubernetes 1.14 to 1.15 on EKS and GKE.
Fixes #5773 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5771)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c …
> docs: deploy wiki update for Kubernetes

- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/schema/remote.go
Fixes #GRAPHQL-503
This PR fixes remote schema introspection for custom logic in GraphQL for a single remote endpoint. Enabling validation for types that are part of custom logic query/mutation/field in our GraphQL schema against the remote schema .
(cherry picked from commit 55594de574cf67ec4305eba58c9b179b76a80ba3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5824)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0fb4674860-75263.surge.sh)
> fix(GraphQL): Remote schema introspection for single remote endpoint (#5710)

- dgraph/cmd/alpha/run.go
- graphql/admin/admin.go
- graphql/web/http.go
Fixes #GRAPHQL-507.
This PR adds `/probe/graphql` HTTP endpoint which returns HTTP status 200 OK, if the `/graphql` endpoint is up and running otherwise it returns HTTP status 503 Service Unavailable. It also returns a JSON body of the following form:
```
{"status":"init/up/updating schema"}
```
Status `init` is returned for 503, while rest of the two statuses return 200 code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5802)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ee9f26feeb-75202.surge.sh)
> feat(GraphQL): GraphQL health now reported by /probe/graphql

- upgrade/change_list.go
- upgrade/change_v20.03.0.go
- upgrade/change_v20.07.0.go
- upgrade/doc.go
- upgrade/upgrade.go
- upgrade/upgrade_test.go
- upgrade/utils.go
- upgrade/utils_test.go
Fixes #DGRAPH-1617.
This PR adds the capability to upgrade to v20.07.0 from v20.03.0+
It has only considered the breaking changes introduced in #5185.
It also introduces a generic system to handle upgrades.
At present, upgrade tool expects to handle only breaking ACL changes, and does not expect to handle badger data format changes. The way it is supposed to work is by updating the Dgraph binary to new version, start Dgraph cluster with existing data directories (which could also have been restored by enterprise backup/restore), and then running the upgrade tool by specifying the version you want to upgrade from and the version you want to upgrade to.
(cherry picked from commit d5892dc0c233970bab85b2aa39e865df57c45fc5)
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> feat(Upgrade): Users can now upgrade to v20.07.0 (#5634)

- wiki/content/deploy/index.md
Fix sampling rate for tracing in the documentation.
See [default value for --trace](https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/alpha/run.go#L128)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5806)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-aaa05c8b69-75041.surge.sh)
> fix(Documentation): fixes sampling rate in tracing documentation

- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/schemagen.go
Fixes #5311
Fixes #GRAPHQL-419
Previously when Dgraph schema was generated the GraphQL interface was getting skipped and hence it was not present in the generated Dgraph schema. This PR fixes that and hence now all the queries/mutations will work as expected.
(cherry picked from commit c6a0dfa4c6f87ab8d3708701027e2ef5859eb2d4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5828)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1190b0a47c-75336.surge.sh)
> fix(GraphQL): Fix case where Dgraph type was not generated for GraphQL interface (#5738)

- worker/draft.go
Use the GetXXX methods of the generated protobufs to correctly handle
the case where no predicate hints are available.
Fixes DGRAPH-1753.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5798)
> fix(dgraph): Fix segmentation fault in draft.go

- wiki/content/clients/index.md
From #2123. This Spark connector connects to Dgraph over gRPC.
This connector comes from @EnricoMi. Thanks for your contribution!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5859)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1e0c1c5fb9-76024.surge.sh)
> docs(Clients): Add community Apache Spark Connector.

- worker/draft.go
Use the GetXXX methods of the generated protobufs to correctly handle
the case where no predicate hints are available.
Fixes DGRAPH-1753.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5861)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cf21cf7677-76037.surge.sh)
> (release/v20.07) fix(dgraph): Fix segmentation fault in draft.go

- graphql/admin/admin.go
Fixes DGRAPH-1787.
This PR fixes an issue, where if some user accidentally deleted the `dgraph.type` edge for the GraphQL schema node and simultaneously added another GraphQL schema node with `dgraph.type` edge and restarted the alpha, it would end up crashing with a panic saying `panic: interface conversion: interface {} is nil, not string`.
Steps to reproduce:
* Start zero and alpha.
* Run following mutation:
```
{
set {
_:newSchema <dgraph.type> "dgraph.graphql" .
}
delete {
<0x1> <dgraph.type> * .
}
}
```
Note that <0x1> is the uid of existing GraphQL schema node. What we did in this mutation is to remove the `dgraph.type` edge from the existing schema node, and add a new node with just `dgraph.type` edge.
* Restart alpha.
* It will panic, and crash.
The reason it happens is that the …
> fix(GraphQL): fix interface conversion panic in v20.03

- graphql/authorization/auth.go
- graphql/resolve/auth_test.go
#5668 Cherrypicking to release/v20.07 branch
* If JWT custom claim field is string, parse as JSON
Co-authored-by: David Peek <mail@dpeek.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5862)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f3ecf01458-76063.surge.sh)
> fix(GraphQL): Custom Claim will be parsed as JSON if it is encoded as a string

- worker/draft.go
Fixes: https://github.com/dgraph-io/dgraph/issues/5601
Fixes: DGRAPH-1669
Currently we are unable to start alpha server in ludicrous mode, because of reasons explained
below.
Things we do at alpha start:
1. At start we insert `dgraph.type`, `dgraph.graphql.schema` and `dgraph.graphql.xid` predicates as
our initial schema.
2. We also insert `dgraph.graphql` type(having predicates `dgraph.graphql.schema` and
`dgraph.graphql.xid`) as initial types.
3. We also upsert data related to graphql schema(which results in upserts for predicates 
`dgraph.graphql.schema` and `dgraph.graphql.xid`).
While inserting types we verify that predicates used in the types should either already be present
in schema or should be part of same mutation where we are trying to insert this type.
In ludicrous mode we …
> Fix alpha start in ludicrous mode

- graphql/e2e/common/schema.go
- graphql/resolve/resolver.go
- graphql/schema/introspection.go
- graphql/schema/introspection_test.go
- graphql/schema/remote.go
- graphql/schema/testdata/introspection/output/full_query.json
- graphql/schema/wrappers.go
There was a missing `"` in the `__typename` that was filled in for types in schema introspection queries. That resulted in JSON parsing errors, we have fixed it and modified the existing test to test for it. Fixes #5792. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5827)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0aaf3fb33b-76313.surge.sh)
> fix(GraphQL): Typename for types should be filled in query for schema introspection queries

- systest/21million/run_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5820)
> fix(dgraph): add retry mechanism for 21million test

- systest/online-restore/online_restore_test.go
There's still some flakiness in the online restore tests caused by
the server being in draining mode. I suspect this happens when the
follower is behind and the check succeeds only for draining mode to be
enalbed right after. Previously the test checked that the alpha was
not in draining mode once. This change now requires the alpha to
have draining mode disabled three consecutive times before allowing
queries to be sent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5853) …
> test: Fix flakiness in online restore tests.

- wiki/content/deploy/index.md
* doc fixes for mTLS/TLS dgraph live, dgraph cert, curl
(cherry picked from commit cd454e58a45a4020e2a5c90ad822ce7d0244be5e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5871)
> doc: tls doc update fixes

- testutil/client.go
Some tests down and up alphas so connection issues are expected and the
tests should retry until the alpha comes back up.
Fixes DGRAPH-1618
(cherry-picked from 49a3fa97a41c858f6b8bc52a2c30d569b20d9f41)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5748)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fc23e63145-73450.surge.sh)
> (release/v1.2) test: Retry due to connection issues in RetryMutations and RetryQuery

- wiki/content/deploy/index.md
* doc fixes for mTLS/TLS dgraph live, dgraph cert, curl
(cherry picked from commit cd454e58a45a4020e2a5c90ad822ce7d0244be5e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5870)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-92c1b40b89-76168.surge.sh)
> doc: tls update

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_query_test.yaml
- graphql/schema/wrappers.go
Auth rules were not applied on type having @dgraph directive because they were stored in authRules map corresponding to Graphql type name and was fetched with Dgraph type name when rewriting the query.
(cherry picked from commit 8562311a6e70eb7278abcb5c9c0c004196f206dd)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5863)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-69b991e011-76070.surge.sh)
> fix(GraphQL): Apply auth rules on type having @dgraph directive (#5702)

- dgraph/cmd/alpha/upsert_test.go
use new timestamp instead of committed txn timestamp in TestUpsertWithValueVar test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5801)
> fix(dgraph): Fix flaky TestUpsertWithValueVar test

- wiki/content/deploy/index.md
- wiki/content/query-language/index.md
Fixes #GRAPHQL-523.
This PR adds documentation about the required authentications to access the admin endpoints.
Please see this discuss post for more details: https://discuss.dgraph.io/t/authentication-for-admin-endpoints/6786
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5842)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f33f8f5a21-76488.surge.sh)
> docs: add docs for admin endpoint auth

- dgraph/cmd/alpha/run.go
- graphql/admin/admin.go
- graphql/web/http.go
Fixes #GRAPHQL-507.
This PR adds /probe/graphql HTTP endpoint which returns HTTP status 200 OK, if the /graphql endpoint is up and running otherwise it returns HTTP status 503 Service Unavailable. It also returns a JSON body of the following form:
{"status":"init/up/updating schema"}
Status init is returned for 503, while the rest of the two statuses return 200 code.
(cherry picked from commit 072f6b29abd2e0d94a073b08066a49156bfd27eb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5875) …
> feat(GraphQL): GraphQL health now reported by /probe/graphql (#5802)

- wiki/content/deploy/index.md
- wiki/content/query-language/index.md
Fixes #GRAPHQL-523.
This PR adds documentation about the required authentications to access the admin endpoints.
Please see this discuss post for more details: https://discuss.dgraph.io/t/authentication-for-admin-endpoints/6786
(cherry picked from commit a7dece87c9dca475bfa0a0a7c2bead01ecf6d9ff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5904)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a0e13efbdd-77228.surge.sh)
> docs: add docs for admin endpoint auth (#5842)

- dgraph/cmd/live/load-uids/load_test.go
This PR fixes flaky behavior in `TestLiveLoadExportedSchema`. It used to happen because of the export file naming. It was assumed that the exported file is always named `g01.schema.gz`, but it turns out that the initial prefix `g01` is based on group id, on which the request was executed. So, this PR changes the filename to be dynamically read at export time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5903)
> fix(Flaky): TestLiveLoadExportedSchema

- posting/index.go
Fixes #4600
While running dgraph as systemd service, we may not have permissions
to create a folder in the current directory. Now, we instead use /tmp
dir to store the temporary index solving the permission denied error.
(cherry picked from commit 8bf90461f28fcc5683c4edffc12ba70ff711c59e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5730)
> (dgraph/release/v1.2) Use /tmp dir to store temporary index (#4766)

- posting/mvcc.go
We've seen some panics like `proto: illegal wireType 6` on trying to read the posting lists. We haven't found the fix yet. The issue could be because badger is returning incorrect values for the posting list. Since we haven't been able to reproduce it, this is a stop-gap solution to return an error instead of crashing dgraph. This is not the fix, this will return an error instead of causing a panic.
Fixes DGRAPH-1778
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5877)
> fix(readPostingList): Return error instead of panic

- query/outputnode.go
- query/query_facets_test.go
Fixes: #5241 
Fixes: DGRAPH-1670
This PR is related to #5690. It issues with facets response when facets are retrieved with
`@normalize` directive. Below two cases are covered:
1. Fixing facets response with uid/uid list predicates.
2. Fixing facets response with scalard list predicates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5691)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a1433bdd39-71794.surge.sh)
> (release/v20.03) Fix facets response with normalize

- testutil/client.go
TestSnapshot is still flaky due to "broken pipe" errors, this change
makes the tests retry that type of error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5896)
> test: retry "broken pipe" connection issues.

- posting/size_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5899)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f9918b3719-76939.surge.sh)
> (release/20.07) test: Handle kB units in size_test.go

- contrib/jepsen/main.go
This PR does two things:
1. Add an option `--refresh-cluster` to down and up the test cluster before each test. I noticed
that most errors that lead to incomplete tests go away if this is done.
1. Retry incomplete tests. Most incomplete tests fail early so it's not very expensive to retry
the test. The tool now only returns an exit code of 1 if there's a test failure or a test was incomplete
even after retries.
Related to DGRAPH-971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5804) …
> test: Deal with incomplete tests in Jepsen tool

- ee/backup/backup.go
- posting/list.go
- posting/list_test.go
This PR includes related commits to bring up branch release/v1.2 up to
date and introduce the memory savings in master. None of the changes
are breaking.
For simplicity, I am opening a single PR but the commits can be rebased
to the branch when they are approved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5649)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-75bc709625-70578.surge.sh)
> (release/v1.2) Changes to reduce backup memory.

- graphql/e2e/common/error_test.yaml
- graphql/e2e/normal/normal_test.go
- graphql/e2e/normal/schema.graphql
- graphql/schema/wrappers.go
This PR fixes panic error when there is no @withSubscription directive on any type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5874)
> fix(GraphQL): fix panic error when there is no @withSubscription directive on any type.

- graphql/e2e/common/error_test.yaml
- graphql/e2e/normal/normal_test.go
- graphql/e2e/normal/schema.graphql
- graphql/schema/wrappers.go
This PR fixes panic error when there is no @withSubscription directive on any type.
(cherry picked from commit b40c63254cfc3b4a4f3af9cb36d3d4fb2cb18cad)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5921)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5b35e119e8-77619.surge.sh)
> fix(GraphQL): fix panic error when there is no @withSubscription directive on any type. (#5874)

- dgraph/cmd/live/load-uids/load_test.go
This PR fixes flaky behavior in `TestLiveLoadExportedSchema`. It used to happen because of the export file naming. It was assumed that the exported file is always named `g01.schema.gz`, but it turns out that the initial prefix `g01` is based on group id, on which the request was executed. So, this PR changes the filename to be dynamically read at export time.
(cherry picked from commit 74d8a13c343d9e5809ca0604ee0622a58d598179)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5905) …
> fix(Flaky): TestLiveLoadExportedSchema (#5903)

- graphql/e2e/directives/schema.graphql
- graphql/resolve/resolver_error_test.go
- graphql/schema/request.go
- graphql/schema/wrappers.go
We realised that as a result of b40c63254cfc3b4a4f3af9cb36d3d4fb2cb18cad, introspection queries started failing in Insomnia because subscription didn't exist in the types. Instead of adding more hacks there, we add validation for this inside Operation. We already do something similar for Queries/Mutations. If queries/mutations are not defined (say only custom queries/mutation were), we return this error.
```
{
"errors": [
{
"message": "yo was not executed because no suitable resolver could be found - this indicates a resolver or validation bug (Please let us know : https://github.com/dgraph-io/dgraph/issues)"
}]
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5926)
> fix(GraphQL): Validate subscriptions in Operation function

- chunker/json_parser_test.go
- dgraph/cmd/bulk/systest/test-bulk-schema.sh
This PR partially fixes: - DGRAPH-1643 -- It fixes bulk-schema test which displayed flakiness. 
It adds sleep between starting a cluster and querying the relevant schemas in the test.
`test-bulk-schema.sh`
No.
Not required.
Partially
Fixes DGRAPH-1643
Testing flaky behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5826)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f868f660bc-77820.surge.sh)
> fix(bulk-schema flaky test): Add sleep time to wait for clusters before querying for schema in the test

- ee/acl/acl_test.go
Makes Deepsource checks pass for PR #5733
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5929)
> chore: Add deferred cancel in TestExpandQueryWithACLPermissions

- dgraph/cmd/bulk/systest/test-bulk-schema.sh
Add sleep to prevent query on unhealthy cluster
(cherry picked from commit b537eff70da0fe884106f6c00ec49e642d2cda24)
Partially
Fixes DGRAPH-1643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5931)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-929adea24b-77885.surge.sh)
> fix(bulk-schema flaky test): Add sleep time to wait for clusters before querying for schema in the test (#5826)

- worker/draft.go
Fixes: #5601
Fixes: DGRAPH-1669
Currently we are unable to start alpha server in ludicrous mode, because of reasons explained
below.
Things we do at alpha start:
At start we insert dgraph.type, dgraph.graphql.schema and dgraph.graphql.xid predicates as
our initial schema.
We also insert dgraph.graphql type(having predicates dgraph.graphql.schema and
dgraph.graphql.xid) as initial types.
We also upsert data related to graphql schema(which results in upserts for predicates
dgraph.graphql.schema and dgraph.graphql.xid).
While inserting types we verify that predicates used in the types should either already be present
in schema or should be part of same mutation where we are trying to insert this type.
In ludicrous mode we mark any proposal done without error as soon as it is retrieved as …
> (dgraph/fix) (cherrypick-20.07) Fix alpha start in ludicrous mode (#5642)

- posting/index.go
- posting/list.go
- systest/mutations_test.go
Fixes: DGRAPH-890
Currently count index is calculated in the following way:
Calculate length of posting list for which mutation is getting performed.
Perform the actual mutation.
Calculate the length of posting list after mutation is performed.
Add count index for new count and delete count index for old count.
Finding length of posting list:
Length of posting list is calculated by merging mutable and immutable layer. Immutable layer is already sorted. We need to sort mutable layer for merging. This sorting turns out to be a costly function and shows up in CPU profile. Since we are calculating length twice, sorting is happening twice.
Optimization:
This PR avoids calculating length twice. It uses length calculated before and edge(for mutation) information, to calculate length after …
> perf(countindex): (cherrypick-v20.07) Optimize count index (#4666)

- query/outputnode.go
- query/query_facets_test.go
Fixes: #5241
Fixes: DGRAPH-1670
This PR fixes issue with facets when it is retrieved in a query containing @normalize directive.
While forming @normalize response, we flatten a fastJsonNode and make its grand children,
direct children of it. This should be valid in all of cases except when fastJsonNode is parent of
facets nodes. For example consider below data:
<0x1> <name> "Alice" .
<0x1> <friend> "Bob" (from="college") .
<0x1> <friend> "Roman" (from="school") .
Also consider below query:
q(func: uid(0x1)) @normalize {
name: name
friend: friends @facets
}
Expected response is:
{
"data": {
"q": [
{
"name": "Alice",
"friends|from": {
"0": "college",
"1": "school"
},
"friends": [
"Bob",
"Roman"
]
}
]
}
}
But actual response is:
{
"data": {
"q": [
{
"0": "college",
"1": "school",
"friends": …
> (fix/dgraph): (Cherrypick-v20.07) Fix facets response with normalize (#5690)

- worker/task.go
Use a copy of the key of the badger iterator for count index queries.
(cherry picked from commit 7050bfdb5d30191a6967b0f6c68844e225d81db2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5936)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-63b5c7c0ed-78080.surge.sh)
> fix(dgraph):  Badger iterator key copy in count index query (#5689)

- .github/workflows/label.yml
Makes the labeler work with PR releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5944)
> chore: Labeler on PR releases

- edgraph/access_ee.go
- ee/acl/acl_test.go
This PR partially fixes:
- DGRAPH-1711 -- `expand(_all_)` and `value variable` queries do not work with ACL turned on. This PR fixes the issues with `value variable` queries.
For a detailed discussion and repro examples refer [here.](https://github.com/dgraph-io/dgraph/issues/5687)
`value variables` queries when ACL is enabled. 
No.
See `TestValQueryWithACLPermissions` in `acl_test.go`.
Tests include various queries related to `val(variable)` under following circumstances:
1. User has access to no predicate
2. User has access to only one predicate 
3. User has access to all predicates.
Partially
Fixes DGRAPH-1711
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5945)
> fix(Query): Fix val queries when ACL is enabled

- wiki/content/get-started/index.md
- wiki/content/howto/index.md
- wiki/content/tutorial-2/index.md
- wiki/content/tutorial-4/index.md
- wiki/content/tutorial-5/index.md
- wiki/content/tutorial-6/index.md
- wiki/content/tutorials/index.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5965)
> Removed slack references from tutorial pages

- edgraph/server.go
- systest/21million/docker-compose-ludicrous.yml
- systest/21million/test-21million.sh
- worker/draft.go
Fixes out of order commit in ludicrous mode.
DGRAPH-1612
(cherry picked from commit 2a8c17f56660a2b7481f63391dfcd7543faeb14c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5914)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d4372af2b5-77436.surge.sh)
> fix(dgraph): ludicrous mode mutation error (#5701)

- graphql/schema/wrappers.go
- x/x.go
Fixes GraphQL-570.
Earlier, sending a query like this:
```
query ($filter: CountryFilter!){
qc0: queryCountry(filter: $filter) {
id
name
}
qc1: queryCountry(filter: $filter) {
id
name
}
}
```
where $filter is a GraphQL variable as below:
```
{
"filter": {
"id": [
"0x0"
]
}
}
```
would fetch you results like this:
```
"data": {
"qc0": [
{
"id": "0x2711",
"name": "India"
},
{
"id": "0x2712",
"name": "Australia"
},
{
"id": "0x2713",
"name": "US"
}
],
"qc1": []
}
```
While you should have got empty results for both the queries as `0x0` is not a uid that exists.
This PR fixes the above bug by doing a deep-copy of field arguments if variables are provided, so avoiding sharing the same memory address across all the queries in a request. Hence, avoiding any bugs that could be caused as a result …
> fix(GraphQL): multiple queries in a single request should not share the same variables

- posting/mvcc.go
We've seen some panics like "proto: illegal wireType 6" on trying to read the
posting lists. We haven't found the fix yet. The issue could be because badger
is returning incorrect values for the posting list. Since we haven't been able
to reproduce it, this is a stop-gap solution to return an error instead of
crashing dgraph.
This is not the fix, this will return an error instead of
causing a panic.
Fixes DGRAPH-1778
(cherry picked from commit f2773c8eb362881928f3448c8ff109ef51c032ff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5907)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4 …
> release/v20.03: fix(readPostingList): Return error instead of panic (#5877)

- posting/mvcc.go
The original PR https://github.com/dgraph-io/dgraph/pull/5731 was closed because I couldn't start CI on that PR.
FIXES - DGRAPH-1613
The incremental roll-up uses a `map` to keep track of the keys that should be
rolled up. The current implementation never clears the map which stores the
keys. The existing algorithm is
```
If key is present or key was rolled up 10 seconds ago, perform roll up
```
we never clean up the map in the existing algorithm and as a result the map
consumed a lot of memory 
```
3.77GB 32.51% 32.51%     3.93GB 33.95%  github.com/dgraph-io/dgraph/posting.(*incrRollupi).Process
```
The proposed change will clean up the keys every 2 minutes and remove the keys
that have not changed in the last 10 seconds.
(cherry picked from commit …
> release/20.07- Rollup: Reduce memory consumption of the map (#5599)

- go.mod
- go.sum
- worker/server_state.go
Fixes https://github.com/dgraph-io/dgraph/issues/5573
This commit brings the following new changes from badger.
```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh 14386ac9b76...0dfb8b45d4a4
Fix assert in background compression and encryption. (dgraph-io/badger#1366)
Avoid panic in filltables() (dgraph-io/badger#1365)
Force KeepL0InMemory to be true when InMemory is true …
> fix(badger): Update badger to v20.07.0-rc1

- posting/mvcc.go
We've seen some panics like "proto: illegal wireType 6" on trying to read the
posting lists. We haven't found the fix yet. The issue could be because badger
is returning incorrect values for the posting list. Since we haven't been able
to reproduce it, this is a stop-gap solution to return an error instead of
crashing dgraph.
This is not the fix, this will return an error instead of
causing a panic.
Fixes DGRAPH-1778
(cherry picked from commit f2773c8eb362881928f3448c8ff109ef51c032ff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5908)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4 …
> release/v1.2: fix(readPostingList): Return error instead of panic (#5877)

- worker/draft.go
Use the GetXXX methods of the generated protobufs to correctly handle
the case where no predicate hints are available.
Fixes DGRAPH-1753.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5860)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b7791c434d-76030.surge.sh)
> (release/v20.03) fix(dgraph): Fix segmentation fault in draft.go

- go.mod
- go.sum
- worker/server_state.go
This commit brings following new changes from badger
```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh c45d966681d4...0dfb8b45d4a4
Avoid panic in filltables() (dgraph-io/badger#1365)
Force KeepL0InMemory to be true when InMemory is true (dgraph-io/badger#1375)
Tests: Use t.Parallel in TestIteratePrefix tests  (dgraph-io/badger#1377)
Remove second initialization of writech …
> fix(badger): release/v20.07- Update badger to v20.07.0-rc1

- go.mod
- go.sum
- worker/server_state.go
**NOTE** - The diff shown on this PR is incorrect. Please see updated diff at https://github.com/dgraph-io/dgraph/compare/release/v1.2...ibrahim/r1.2-badger-rc 
There are two commits on this branch but this PR shows only one.
---
This commit brings following new changes from badger
```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh 14386ac9b76...0dfb8b45d4a4
Fix assert in …
> fix(badger): release/v1.2 - Update badger to v20.0.7-rc1

- posting/mvcc.go
We've seen some panics like "proto: illegal wireType 6" on trying to read the
posting lists. We haven't found the fix yet. The issue could be because badger
is returning incorrect values for the posting list. Since we haven't been able
to reproduce it, this is a stop-gap solution to return an error instead of
crashing dgraph.
This is not the fix, this will return an error instead of
causing a panic.
Fixes DGRAPH-1778
(cherry picked from commit f2773c8eb362881928f3448c8ff109ef51c032ff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5906)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4 …
> release/v20.07: fix(readPostingList): Return error instead of panic (#5877)

- posting/index.go
- posting/list.go
- systest/mutations_test.go
Fixes: DGRAPH-890
Currently count index is calculated in the following way:
Calculate length of posting list for which mutation is getting performed.
Perform the actual mutation.
Calculate the length of posting list after mutation is performed.
Add count index for new count and delete count index for old count.
Finding length of posting list:
Length of posting list is calculated by merging mutable and immutable layer. Immutable layer is already sorted. We need to sort mutable layer for merging. This sorting turns out to be a costly function and shows up in CPU profile. Since we are calculating length twice, sorting is happening twice.
Optimization:
This PR avoids calculating length twice. It uses length calculated before and edge(for mutation) information, to calculate length after …
> perf(countindex): Optimize count index (#4666)

- graphql/admin/update_group.go
- graphql/e2e/auth/add_mutation_test.go
- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_add_test.yaml
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/auth_update_test.yaml
- graphql/resolve/mutation.go
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/query_rewriter.go
Fixes GRAPHQL-427(Release blocker)
Previously auth queries had type filter for all levels and hence it would fetch all nodes of a particular type. This PR only applies auth on the nodes that are part of the parent query. Hence, touching same/less number of nodes as it would have in the query without auth rules.
(cherry picked from commit 222f42a21fb4d85200101ae6421a0efb08c76746)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5950) …
> perf(GraphQL): Nested auth queries no longer search through all possible records (#5666)

- worker/docker-compose.yml
This PR adds customs cluster label to jaeger container so that it'll be cleaned properly when we restart cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5951)
> test: Add cluster lables to the jaeger containers

- edgraph/access_ee.go
- go.mod
- go.sum
- graphql/authorization/auth.go
- graphql/e2e/auth/auth_test.go
- graphql/resolve/auth_test.go
- graphql/schema/wrappers_test.go
- testutil/graphql.go
Fixes GRAPHQL-565(Release-blocker)
1. Upgrades jwt-go to v4 to support multiple aud claims in JWT
2. Makes JWT token expiry field option in GraphQL.
3. Changes Dgraph.Authorization format.
Co-authored-by: David Peek <mail@dpeek.com>
(cherry picked from commit 5d789f0ed80fc6680bbb1333b999c2fa8895ecdc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5980)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1cad00a827-79275.surge.sh)
> feat(GraphQL): Validate audience in authorization JWT and change `Dgraph.Authorization` format.

- dgraph/cmd/zero/http.go
- edgraph/server.go
1. This PR enhances usability by not omitting default fields in `/state` and `/assign` endpoints.
Earlier:
```json
{
"zeros": {
"1": {
"id": "1",
"addr": "localhost:5080",
"leader": true
},
"2": {
"id": "2",
"addr": "localhost:5081"
}
},
"maxTxnTs": "10000",
"maxRaftId": "2",
"cid": "256a5894-c3d2-4d3c-9879-7c29ae2e9584",
"license": {
"maxNodes": "18446744073709551615",
"expiryTs": "1597232998",
"enabled": true
}
}
```
Now:
```json
{
"zeros": {
"1": {
"id": "1",
"groupId": 0,
"addr": "localhost:5080",
"leader": true,
"amDead": false,
"lastUpdate": "0",
"clusterInfoOnly": false,
"forceGroupId": false
},
"2": {
"id": "2",
"groupId": 0,
"addr": "localhost:5081",
"leader": false,
"amDead": false,
"lastUpdate": "0",
"clusterInfoOnly": false,
"forceGroupId": false
}
},
"maxLeaseId": "0", …
```
> feat(Usability): /state endpoint explicitly show the default values (e.g. leader=false)

- graphql/e2e/common/schema.go
- graphql/resolve/resolver.go
- graphql/schema/introspection.go
- graphql/schema/introspection_test.go
- graphql/schema/testdata/introspection/output/full_query.json
- graphql/schema/wrappers.go
There was a missing " in the __typename that was filled in for types in schema introspection queries. That resulted in JSON parsing errors, we have fixed it and modified the existing test to test for it. Fixes #5792.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5891)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5f8d263489-76705.surge.sh)
> fix(GraphQL): Typename for types should be filled in query for schema introspection queries (#5827)

- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- graphql/schema/testdata/schemagen/input/interface-with-dgraph-pred.graphql
- graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-on-concrete-type-with-interfaces.graphql
- graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-with-interfaces.graphql
- graphql/schema/testdata/schemagen/output/field-with-reverse-predicate-in-dgraph-directive.graphql
- graphql/schema/testdata/schemagen/output/interface-with-dgraph-pred.graphql
Fixes #5744 and GRAPHQL-558
There was another bug where field which map to reverse edges in Dgraph where generated as part of AddTypeInput and TypeRef. They have been excluded now as we can't perform a mutation along them. They would earlier have given an error at runtime while doing mutations in Dgraph about predicate being incorrect because it starts with ~. Apart, from that to fix #5744, we also allow interfaces implemented by the current type in the check.
(cherry picked from commit ecec0714e5a49ca24ef763c132bd4671ac5df46a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5982)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883 …
> fix(GraphQL): Dgraph directive with reverse edge should work smoothly with interfaces (#5911)

- graphql/e2e/directives/schema.graphql
- graphql/resolve/resolver_error_test.go
- graphql/schema/request.go
- graphql/schema/wrappers.go
We realised that as a result of b40c632, introspection queries started failing in Insomnia because subscription didn't exist in the types. Instead of adding more hacks there, we add validation for this inside Operation. We already do something similar for Queries/Mutations.
(cherry picked from commit e33850e1625a0c6e980224fdb862d7f585bcd441)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5983)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6bc865451d-79376.surge.sh)
> fix(graphQL): Validate subscriptions in Operation function (#5926)

- wiki/content/enterprise-features/index.md
The POST request for applying the enterprise license key can only be sent to the leader zero endpoint.
```
$ curl -X POST http://10.0.0.10:6080/enterpriseLicense --upload-file licensekey.txt 
{"errors":[{"message":"while proposing enterprise license state to cluster: Not Zero leader. Aborting proposal: license:\u003cuser:\"User\" maxNodes:6 expiryTs:1594752958 \u003e ","extensions":{"code":"ErrorInvalidRequest"}}]}
$ curl -X POST http://10.0.0.11:6080/enterpriseLicense --upload-file licensekey.txt 
{"code": "Success", "message": "License applied."}
```
Fixed this typo in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5985) …
> docs(Enterprise): fix typo for EE license application to Zero leader

- contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml
This is change to k8s manifest `dgraph-ha.yaml` to support multiple zeros for `dgraph alpha` service and an inline comment for further explanation about the `--zero` option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5973)
> chore: contrib k8s ha support dgraph alpha multiple zero support

- worker/groups.go
Fixes DGRAPH-1935
delta.GroupChecksums is nil at this point in the code, so copying keys to this map causes the code to panic with message:
`assignment to entry in nil map`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5999)
> fix(dgraph): Panic because of nil map in groups.go

- worker/groups.go
Fixes DGRAPH-1935
(cherry picked from commit 3c46878)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6008)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d1638c7d3d-80034.surge.sh)
> Cherry-pick fix(dgraph): Panic because of nil map in groups.go (#5999)

- dgraph/cmd/cert/create.go
- wiki/content/deploy/index.md
Fixes #5799
This changes the `--duration` default value for `dgraph cert` to 365 days (down from 5 years). This fixes `ERR_CERT_VALIDITY_TOO_LONG` errors where certs are valid for too long on platforms that enforce shorter-lived certs like macOS.
Changes:
* docs(Deploy): Document default validity and update ls example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5986)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-198798bde7-79570.surge.sh)
> fix: Set dgraph cert default duration to 1 year.

- contrib/config/marketplace/aws/README.md
- contrib/config/marketplace/aws/dgraph.json
AWS Marketplace Update
* update 16 regional Ubuntu AMI image ids with latest Ubuntu 18.04.
* doc change for usability - aws command to get exact security group id
Testing
* tested this on us-west-2; verified stack comes up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6013)
> chore: refresh aws marketplace cfn template with updated AMIs and docs

- contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml
- contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
This renames the port names used in `dgraph-ha.yaml` and `dgraph-single.yaml` Kubernetes manifests to be consistent with Helm chart port names.  The helm charts port names were changed to support older versions of Itsio naming conventions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5972)
> chore: rename port names for consistency with helm chart

- graphql/authorization/auth.go
- graphql/schema/wrappers_test.go
Fixes #GRAPHQL-574
Currently, we error out if the user specifies the old format for `Dgraph.Authorization`
This PR allows us to parse the old format as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5998)
> fix(GraphQL): Maintain backward compatibility for `Dgraph.Authorization` in schema.

- posting/index.go
- systest/mutations_test.go
When updating a single uid predicate with a reverse index, the existing entry in the
reverse index should be deleted first.
Fixes DGRAPH-1738
(cherry picked from commit 5b70fe8aa2c4dc08f74794b3e9875c8789c11c9f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6005)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-dc7383af73-80005.surge.sh)
> (release/v20.07) fix(Dgraph): update reverse index when updating single UID predicates

- dgraph/cmd/alpha/run.go
This PR updates the usage text for `--whitelist` flag in `alpha` to reflect all the ways in which IP ranges can be provided as input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6016)
> chore: Correct whitelist flag usage text

- worker/task.go
The grpcWorker.ServeTask function is called when a request is received
over the network (sent by a peer). This function doesn't consider the
health of the node before starting the processing of the request. If we
process a request before the node is ready, we might end up seeing
crashes similar to https://dgraph.atlassian.net/browse/DGRAPH-1934
Fixes DGRAPH-1934
I ran jepsen bank test with all nemesis and don't see any panics
```
./jepsen --jepsen-root $GOPATH/src/github.com/dgraph-io/jepsen -w bank -n "kill-alpha,kill-zero,partition-ring,move-tablet"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6019)
> fix(ServeTask): Return error if server is not ready

- worker/task.go
The grpcWorker.ServeTask function is called when a request is received
over the network (sent by a peer). This function doesn't consider the
health of the node before starting the processing of the request. If we
process a request before the node is ready, we might end up seeing
crashes similar to https://dgraph.atlassian.net/browse/DGRAPH-1934
Fixes DGRAPH-1934
This bug was seen when running jepsen bank test with
kill-alpha and kill-zero nemesis.
(cherry picked from commit 9293c97cf8641a6ecbdbe316a312d183065d44c7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6021)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d90 …
> release/v20.03: fix(ServeTask): Return error if server is not ready (#6019)

- worker/task.go
The grpcWorker.ServeTask function is called when a request is received
over the network (sent by a peer). This function doesn't consider the
health of the node before starting the processing of the request. If we
process a request before the node is ready, we might end up seeing
crashes similar to https://dgraph.atlassian.net/browse/DGRAPH-1934
Fixes DGRAPH-1934
This bug was seen when running Jepsen bank test with
kill-alpha and kill-zero nemesis.
(cherry picked from commit 9293c97cf8641a6ecbdbe316a312d183065d44c7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6022)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d90 …
> release/v1.2: fix(ServeTask): Return error if server is not ready (#6019)

- worker/task.go
The grpcWorker.ServeTask function is called when a request is received
over the network (sent by a peer). This function doesn't consider the
health of the node before starting the processing of the request. If we
process a request before the node is ready, we might end up seeing
crashes similar to https://dgraph.atlassian.net/browse/DGRAPH-1934
Fixes DGRAPH-1934
This bug was seen when running jepsen bank test with
kill-alpha and kill-zero nemesis.
(cherry picked from commit 9293c97cf8641a6ecbdbe316a312d183065d44c7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6020)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d90 …
> release/v20.07: fix(ServeTask): Return error if server is not ready (#6019)

- dgraph/cmd/alpha/admin_backup.go
- dgraph/cmd/alpha/run.go
- systest/backup/minio-large/backup_test.go
PR #5802 introduced a bug that caused the adminServer global variable to
never be set, which in turned caused a segmentation fault when the
/admin/backup endpoint was called. This PR fixes the bug and changes the
minio-large test to use the /admin/backup endpoint to act as a
regression test.
Fixes DGRAPH-1938.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6042)
> fix(GraphQL): Fix segmentation fault when calling the /admin/backup endpoint.

- dgraph/cmd/alpha/admin_backup.go
- dgraph/cmd/alpha/run.go
- systest/backup/minio-large/backup_test.go
PR #5802 introduced a bug that caused the adminServer global variable to
never be set, which in turned caused a segmentation fault when the
/admin/backup endpoint was called. This PR fixes the bug and changes the
minio-large test to use the /admin/backup endpoint to act as a
regression test.
Fixes DGRAPH-1938.
(cherry picked from commit 6d014042730fd65bbaec66b7a6d0a4c93a9b58f2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6043) …
> (release/v20.07) fix(GraphQL): Fix segmentation fault when calling the /admin/backup endpoint

- go.mod
- go.sum
```sh
#!/bin/bash
set -e
cat <<EOF
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
EOF
```
Invoked as:
GHORG=dgraph-io GHREPO=badger changes.sh 3ffaf3cd1d4a...37ee16d8ad1c
Various bug fixes: Break up list and run DropAll func (dgraph-io/badger#1439) (dgraph-io/badger#1440)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6040)
> chore(badger): Update badger to 37ee16d

- worker/snapshot.go
When we're done requesting a snapshot the context should be canceled so that the leader stops sending instead of continuing when there are errors.
Fixes DGRAPH-1942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6033)
> fix(worker): Cancel the context when opening connection to leader for streaming snapshot

- worker/snapshot.go
Fixes DGRAPH-1942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6045)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6f3202bae5-81131.surge.sh)
> Cherry-pick v20.07: fix(worker): Cancel the context when opening connection to leader for streaming snapshot

- worker/snapshot.go
Fixes DGRAPH-1942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6044)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-db0e668718-81124.surge.sh)
> Cherry-Pick v20.03 - fix(worker): Cancel the context when opening connection to leader for streaming snapshot

- worker/snapshot.go
Fixes DGRAPH-1942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6046)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-feff8e5dd6-81146.surge.sh)
> Cherry-Pick v1.2 - fix(worker): Cancel the context when opening connection to leader for streaming snapshot

- worker/docker-compose.yml
(cherry picked from commit c9ea2cb208b67dd6dc31bd4177dac4e08585abcb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6010)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-22bcfa987d-80081.surge.sh)
> (release/v20.03) test: add cluster lables to the jaeger containers

- posting/size_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5900)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f95e22ed05-76945.surge.sh)
> (release/v20.03) test: Handle kB units in size_test.go

- wiki/content/deploy/index.md
Update to wiki deploy area for helm chart
* updated `Deleting the Chart` as command did not work
* removed large table under `Configuration` and referred users to chart README.md where this chart is maintained and updated. _less is more_
* use long form for command line options as best practices since Unix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6049)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0d0778b465-81261.surge.sh)
> docs: wiki/deploy helm chart update

- dgraph/cmd/zero/run.go
This is so we can know what the config is set to in Zero.
Example:
`I0721 04:39:20.865338      16 run.go:187] Setting Config to: {bindall:true myAddr:zero1:5180 portOffset:100 nodeId:1 numReplicas:3 peer: w:zw rebalanceInterval:480000000000 LudicrousMode:false}`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6047)
> chore: Print Zero config in logs.

- graphql/e2e/subscription/subscription_test.go
This PR skips the flaky subscriptions tests **TestSubscriptionAuth_SameQueryAndClaimsButDifferentExpiry_ShouldExpireIndependently** 
and **TestSubscriptionAuth_SameQueryDifferentClaimsAndExpiry_ShouldExpireIndependently** .
!--
Your title must be in the following format: topic(Area): Feature
Topic must be one of build|ci|docs|feat|fix|perf|refactor|chore|test
Sample Titles:
feat(Enterprise): Backups can now get credentials from IAM
fix(Query): Skipping floats that cannot be Marshalled in JSON
perf: [Breaking] json encoding is now 35% faster if SIMD is present
chore: all chores/tests will be excluded from the CHANGELOG
Please add a description with these things:
1. A good description explaining the problem and what you changed.
2. If it fixes any GitHub issues, say "Fixes #GitHubIssue".
3. …
> fix(GraphQl): skiping the flaky subscription tests.

- wiki/scripts/build.sh
Update docs's build.sh to set v20.03.4 as the latest docs.
<!-
Your title must be in the following format: topic(Area): Feature
Topic must be one of build|ci|docs|feat|fix|perf|refactor|chore|test
Sample Titles:
feat(Enterprise): Backups can now get credentials from IAM
fix(Query): Skipping floats that cannot be Marshalled in JSON
perf: [Breaking] json encoding is now 35% faster if SIMD is present
chore: all chores/tests will be excluded from the CHANGELOG
Please add a description with these things:
1. A good description explaining the problem and what you changed.
2. If it fixes any GitHub issues, say "Fixes #GitHubIssue".
3. If it corresponds to a Jira issue, say "Fixes DGRAPH-###".
4. If this is a breaking change, please put "[Breaking]" in the title. In the description, please put a …
> docs(build): Update latest docs to v20.03.4.

- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_add_test.yaml
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/auth_tests.yaml
- graphql/resolve/auth_update_test.yaml
- graphql/resolve/query_rewriter.go
Fixes #GRAPHQL-583
**GraphQL query:**
```
query {
queryContact {
id
nickName
tasks {
id
name
occurrances {
due
comp
}
}
}
}
```
If `tasks` and `occurrence` have RBAC rules evaluated to true then we would return early and not rewrite the query properly.
**Previously:** Here `Task4` and `TaskOccurance3` will be reported as undefined variables.
```
query {
queryContact(func: uid(ContactRoot)) {
id : uid
nickName : Contact.nickName
tasks : Contact.tasks @filter(uid(Task4)) {
id : uid
name : Task.name
occurrances : Task.occurrances @filter(uid(TaskOccurance3)) {
due : TaskOccurance.due
comp : TaskOccurance.comp
dgraph.uid : uid
}
}
}
ContactRoot as var(func: uid(Contact5))
Contact5 as var(func: type(Contact))
}
```
**Current:**
```
query {
queryContact(func: uid(ContactRoot)) {
id : uid …
```
> fix(GraphQL): Fix auth rewriting for nested queries when RBAC rule is true.

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/resolve/mutation.go
FIxes GRAPHQL-589.
See [Discuss](https://discuss.dgraph.io/t/panic-when-update-with-filter-but-without-set-remove/8623) for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6073)
> fix(GraphQL): fixes panic in update mutation without set & remove

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/resolver.go
Fixes GRAPHQL-590.
This PR fixes wrong parameter value being supplied in the URL query parameters for `@custom` fields. Earlier, all the nodes used to get the same value for a query parameter, which has been fixed, and now every node gets the value corresponding to its dgraph fields in the `@custom` query parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6074)
> fix(GraphQL): fixes wrong query parameter value for custom field URL

- systest/mutations_test.go
Make sure both the main and reverse edges are deleted when the main
edge is deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6061)
> test: Add extra assesrtions to reverse uid test.

- systest/loader/loader_test.go
This PR fixes DGRAPH-1737
The test is modified to use query instead of exported uids to check xidmap's re-use with live loader. This removes the flakyness from the test.
TestLoaderXidMap
No.
It is a fix to the flaky test. Additional testing not required.
Fixes DGRAPH-1737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6080)
> chore: Modify test to remove flakiness caused by explicit uids

- Makefile
- dgraph/Makefile
- x/init.go
- x/sentry_integration.go
This adds a codename field to the `dgraph version` output. The codename
is set explicitly in the Makefiles for Dgraph. The codename is also
pushed to Sentry.
Additionally, this updates the Makefile to check if the working
directory has any uncommitted changes. If so, the codename is suffixed
with "-mod" to indicate that the binary was created with uncommitted
modified changes.
Changes
* Update dgraph version output with the codename
* Update build Makefiles to include the codename and "-mod" suffix
* Update Sentry reporting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6113)
> chore(version): Add release codename to version output.

- testutil/client.go
TestSnapshot is still flaky due to "broken pipe" errors, this change
makes the tests retry that type of error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5917)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e837ecf3c5-77525.surge.sh)
> (release/v20.07) test: retry "broken pipe" connection issues.

- contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml
* contrib k8s ha support dgraph alpha multiple zero support
(:cherries: :pick: cherry picked  from commit 3ff7d3f52069e9996ce746d3d00e900e8de80766)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5988)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2981c565bf-79613.surge.sh)
> chore: contrib k8s ha support dgraph alpha multiple zero support (#5973)

- dgraph/Makefile
- query/query.go
Fixes DGRAPH-1734
Use next release version as the dgraph version number for dgraph build on master branch. Refer: https://discuss.dgraph.io/t/health-endpoint-doesnt-show-a-version-when-built-from-master/8566/ for discussion about this.
Earlier `git describe` was being used to get the recent tag which is yielding `v2.0.0-rc1-503-g144685a84` on master. `git describe` finds the last ancestor commit which is shared with any tag and yield that tag. It's unclear why it's yielding an old tag on master. May be something wrong with the commit history somewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5956) …
> fix(dgraph): Dgraph version picked from git tags on master

- systest/loader/loader_test.go
DGRAPH-1737
(cherry picked from commit a5c469d56741a4a6e2c668b5053dba17bbfa5860)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6085)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0541873cc1-82701.surge.sh)
> chore: Modify test to remove flakiness caused by explicit uids (#6080) 

- systest/loader/loader_test.go
Fixes DGRAPH-1737
(cherry picked from commit a5c469d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6086)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-513039c01a-82711.surge.sh)
> chore: Modify test to remove flakiness caused by explicit uids (#6080)

- dgraph/cmd/debug/run.go
- worker/snapshot.go
Calculating min and max versions upfront requires iterating over the entire Badger DB. For larger DBs, this can take up significant amount of time and compute power. And it is not useful outside of Jepsen testing which calculates min-max anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6031)
> fix(Debug): Do not calculate min max versions upfront

- graphql/e2e/custom_logic/custom_logic_test.go
The order in which the query responses were returned, was not fixed earlier, so the test was flaky. Fixed the query to return the responses in sorted order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6120)
> fix(GraphQL): fixes flaky TestCustomDQL

- dgraph/cmd/live/run.go
- x/tls_helper.go
- x/x.go
Live Loader can now support Slash GraphQL
Here is an example: 
```
./dgraph live --slash_grpc_endpoint=defiant-curve-2926.grpc.us-east-1.aws.thegaas.com:443 -f /path/to/file.json.gz -t api-token
```
Why introduce a new flag, `--slash_grpc_endpoint`?
* Connections to zero didn't support TLS, so we'd need a new flag to indicate this
* There was no way to start TLS, but use the system CA pool (--tls_ca_cert had to be a valid path). This is not needed for public auth
* Passing in the --alpha --zero and --tls_server_name with the same value felt clunky
* In Slash GraphQL, the GRPC authentication is passed in via `Authentication` metadata to all endpoints, as opposed to only passing in `X-Dgraph-AuthToken` to alter alone
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> feat: Live Loader Now Supports Slash GraphQL

- dgraph/cmd/bulk/count_index.go
- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
Split keys for indexes can cause out-of-order issues due to the variable length of the term inside the key.
To fix the issue, the split keys are written to a temporary DB first (using the writebatch to avoid the out
of order issues) and then copied to the main p directory.
Related to DGRAPH-1897
(cherry picked from commit 2a3b85c9cc9bf6bcb62564bb6bf12669967ed7da)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6124)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-687c631305-83892.surge.sh)
> (release/v20.07) fix(dgraph): Fix out of order issues with split keys in bulk loader.

- dgraph/cmd/bulk/count_index.go
- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
Split keys for indexes can cause out-of-order issues due to the variable length of the term inside the key.
To fix the issue, the split keys are written to a temporary DB first (using the writebatch to avoid the out
of order issues) and then copied to the main p directory.
Related to DGRAPH-1897
(cherry picked from commit 2a3b85c9cc9bf6bcb62564bb6bf12669967ed7da)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6125)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5b35690f76-83893.surge.sh)
> (release/v20.03) fix(dgraph): Fix out of order issues with split keys in bulk loader.

- ee/backup/backup.go
- ee/backup/tests/filesystem/backup_test.go
- ee/backup/tests/minio/backup_test.go
- testutil/backup.go
- x/keys.go
The full schema should be backed up during incremental backups.
During restore, the schema should be cleared before processing each backup
to end up with only the final schema.
(cherry picked from commit f8beadded98bfce094fc7d0065e159914b4fbf5c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6126)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0c7b8485f3-83948.surge.sh)
> (release/v1.1) Backup schema keys in incremental backups.

- contrib/integration/acctupsert/main.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6100)
> fix v1.1 fix(dgraph): ignore minTs warning in bank upsert test. (#5821)

- dgraph/cmd/alpha/upsert_test.go
TestUpsertWithValueVar test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6106)
> fix v1.1 use new timestamp instead of commited txn timestamp in (#5801)

- wiki/scripts/build.sh
This updates the build script to publish v20.07 docs from the release/v20.07 branch.
Needs #6131 to be merged first into release/v20.07 to build the new split-page structure for the docs.
Now docs are built for v20.07 release series only, NOT for every patch release (e.g., v20.07.0, v20.07.1, and so on).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6132)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f1e8e8311f-84122.surge.sh)
> docs(build): Set v20.07 docs as latest.

- dgraph/cmd/debug/run.go
- posting/list.go
Clear out the start_ts field in the postings of deltas before they are
marshalled to avoid storing that field in disk. This field is only meant
to be used during in-memory processing.
Related to https://discuss.dgraph.io/t/start-ts-not-being-cleared-before-postings-are-written-to-disk/9146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6127)
> fix(Dgraph): Don't store start_ts in postings.

- posting/mvcc.go
- posting/mvcc_test.go
fix(rollup): rollup a batch every 2 seconds or 64 keys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6118)
> fix(rollups): rollup a batch if more than 2 seconds elapsed since last batch

- posting/mvcc.go
(cherry picked from commit aca09216f0cfa5a125a81235127285d45e2fe546)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6137)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7747ab1cbd-84207.surge.sh)
> Cherry pick v20.07: fix(rollups): rollup a batch if more than 2 seconds elapsed since last batch (#6118)

- graphql/resolve/query_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/wrappers.go
For the schema
```
type Tweets {
id: String! @id
score: Int
}
```
getTweets query was not being properly re-written. This is because we were using the name `id` to signify that a field is of type `ID` instead of the type `ID` itself. That has been fixed now. So `getTweets` would work if the field was named anything.
```
query MyQuery {
getTweets(id: "1286891968727982081") {
score
id
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6130)
> fix(GraphQL): Fix getType queries when id was used as a name for types other than ID

- dgraph/cmd/bulk/reduce.go
The compression level is set in the `setBadgerOptions` function and setting `compressionLevel` before calling that function is a no-op since we will overwrite the value in the `setBadgerOptions` function.
https://github.com/dgraph-io/dgraph/blob/5e39c8aa8b4091d7fffcf8b2f18a98d712544539/dgraph/cmd/bulk/reduce.go#L135-L142
This PR removes the redundant setting of the option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6119)
> fix(bulk loader): Remove redundant compressionLevel option set

- posting/list.go
- posting/list_test.go
Currently the code keeps tracks of the split startUids and updates them
as the posting lists are split or empty parts are removed. Instead,
update the list of startUids at the end of each step based on the
contents of the map of startUids to posting list. This removes the need
of keeping track of the same piece of information in two different ways.
Also, fix a bug where the empty parts were removed from the list of
splits but not from the map. This caused empty posting lists to be
written to disk although it didn't affect normal execution because those
parts were not accessible from the main posting list.
(cherry picked from commit c51d007e7d53a0d313bab3e73e8536ff1fc455c0)
--- …
> (release/v20.03) refactor: Simplify how list splits are tracked.

- posting/mvcc.go
- Reduce batch size to 16.
- Force a rollup to happen every 500ms instead of 2s.
Related to DGRAPH-2202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6143)
> fix(Dgraph): Perform rollups more aggressively.

- posting/list.go
Right now, keys are only added for rollups during queries. Keys that
only receive queries will not be rolled up until they are queried, which
can cause issues and slowness.
Fixes DGRAPH-2202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6145)
> fix(Dgraph): Queue keys for rollup during mutation.

- contrib/integration/acctupsert/main.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6102)
> fix v20.07 fix(dgraph): ignore minTs warning in bank upsert test. (#5821)

- contrib/integration/acctupsert/main.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6101)
> fix 20.03 fix(dgraph): ignore minTs warning in bank upsert test. (#5821)

- dgraph/cmd/alpha/upsert_test.go
- dgraph/cmd/bulk/systest/test-bulk-schema.sh
TestUpsertWithValueVar test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6108)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6bfc00c88f-84317.surge.sh)
> fix 20.7 use new timestamp instead of commited txn timestamp in (#5801)

- dgraph/cmd/alpha/upsert_test.go
TestUpsertWithValueVar test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6107)
> fix 20.03 use new timestamp instead of commited txn timestamp in (#5801)

- posting/list.go
Right now, keys are only added for rollups during queries. Keys that
only receive queries will not be rolled up until they are queried, which
can cause issues and slowness.
Fixes DGRAPH-2202
(cherry picked from commit 3ea5efe5bd94936fcbcc402a330b49e4a6870a2a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6151)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c77038a5ba-84722.surge.sh)
> (releave/v20.07) Queue keys for rollup during mutation.

- posting/list.go
Right now, keys are only added for rollups during queries. Keys that
only receive queries will not be rolled up until they are queried, which
can cause issues and slowness.
Fixes DGRAPH-2202
(cherry picked from commit 3ea5efe5bd94936fcbcc402a330b49e4a6870a2a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6150)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d09a06df6a-84721.surge.sh)
> (release/v20.03) Queue keys for rollup during mutation.

- posting/mvcc.go
- Reduce batch size to 16.
- Force a rollup to happen every 500ms instead of 2s.
Related to DGRAPH-2202
(cherry picked from commit fa013db935cdc64ca5eb31139057528d83751a3b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6147)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e45e2c6291-84547.surge.sh)
> (release/v20.03) fix(Dgraph): Perform rollups more aggressively

- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/http_test.go
- edgraph/server.go
- x/x.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6148)
> feat: add metrics cost to grpc and http header

- dgraph/cmd/alpha/run.go
Fixes GRAPHQL-577.
This PR updates the usage text for `--whitelist` flag in `alpha` to reflect all the ways in which IP ranges can be provided as input.
(cherry picked from commit b300f298f4a6f503faa50529093095eaf14111b3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6018)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-842a01b886-80261.surge.sh)
> chore: Correct whitelist flag usage text v20.07 (#6016)

- graphql/schema/wrappers.go
- x/x.go
Fixes GraphQL-570.
Earlier, sending a query like this:
```
query ($filter: CountryFilter!){
qc0: queryCountry(filter: $filter) {
id
name
}
qc1: queryCountry(filter: $filter) {
id
name
}
}
```
where $filter is a GraphQL variable as below:
```
{
"filter": {
"id": [
"0x0"
]
}
}
```
would fetch you results like this:
```
"data": {
"qc0": [
{
"id": "0x2711",
"name": "India"
},
{
"id": "0x2712",
"name": "Australia"
},
{
"id": "0x2713",
"name": "US"
}
],
"qc1": []
}
```
While you should have got empty results for both the queries as `0x0` is not a uid that exists.
This PR fixes the above bug by doing a deep-copy of field arguments if variables are provided, so avoiding sharing the same memory address across all the queries in a request. Hence, avoiding any bugs that could be caused as a result …
> fix(GraphQL): multiple queries in a single request should not share the same variables (#5953)

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/resolve/mutation.go
FIxes GRAPHQL-589.
See [Discuss](https://discuss.dgraph.io/t/panic-when-update-with-filter-but-without-set-remove/8623) for more details.
(cherry picked from commit d82ecb4426c3119a970c12211c407a868a1bba33)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6160)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1dce3a8667-85134.surge.sh)
> fix(GraphQL): fixes panic in update mutation without set & remove (#6073)

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/resolver.go
Fixes GRAPHQL-590.
This PR fixes wrong parameter value being supplied in the URL query parameters for `@custom` fields. Earlier, all the nodes used to get the same value for a query parameter, which has been fixed, and now every node gets the value corresponding to its dgraph fields in the `@custom` query parameters.
(cherry picked from commit 3f91f2976615cb80ef8338808f9817ec684d3ef4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6161) …
>  fix(GraphQL): fixes wrong query parameter value for custom field URL (#6074)

- wiki/content/deploy/dgraph-administration.md
- wiki/content/query-language/schema.md
- wiki/content/query-language/type-system.md
Fixes DGRAPH-1714.
This PR adds documentation for upgrading from `v20.03.x` to `v20.07.0`. It also adds documentation for the reserved `dgraph.` namespace for internal types and predicates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6149)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-eaf7d05835-85181.surge.sh)
> docs: document upgrade and internal type/predicate namespace

- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/resolver.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- graphql/schema/wrappers.go
- graphql/schema/wrappers_test.go
Fixes #5641
Fixes GRAPHQL-508
Fixes [Discuss Issue](https://discuss.dgraph.io/t/custom-mutation-underscores-within-post-body/8622)
This PR adds support for parsing hardcoded scalar values in `@custom` HTTP body.
This also adds support for allowing `_` in key names in the body template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6157)
> feat(GraphQL): @custom HTTP body now supports hardcoded scalars

- wiki/content/deploy/dgraph-administration.md
- wiki/content/query-language/schema.md
- wiki/content/query-language/type-system.md
Fixes DGRAPH-1714.
This PR adds documentation for upgrading from `v20.03.x` to `v20.07.0`. It also adds documentation for the reserved `dgraph.` namespace for internal types and predicates.
(cherry picked from commit 0b4cd73c09c586fe643e4d54caa1424eb3178aaf)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6164)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fe96eb2c55-85365.surge.sh)
> Cherry pick v20.07: docs: document upgrade and internal type/predicate namespace (#6149)

- go.mod
- go.sum
- graphql/authorization/auth.go
- graphql/e2e/auth/auth_test.go
- graphql/e2e/common/query.go
- graphql/e2e/common/subscription.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/e2e/subscription/subscription_test.go
- graphql/resolve/auth_test.go
- graphql/resolve/mutation.go
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/query_rewriter.go
- graphql/subscription/poller.go
- graphql/web/http.go
- testutil/graphql.go
Co-authored-by: Pawan Rawal <pawan0201@gmail.com>
Co-authored-by: JatinDevDG <jatin@dgraphh.io>
(cherry picked from commit 5f81aac3d4c5bc0e1ef114c3f288caf177e99d20)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6165)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-065f20d492-85372.surge.sh)
> feat(GraphQL): Adds auth for subscriptions (#5984)

- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
This PR disallow Subscription typename so that it doesn't conflict with Subscriptions generated.
(cherry picked from commit 601e837e39d6e796db8f5c46921413f63e02b3c2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6173)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-05faf22c4b-85645.surge.sh)
> fix(GraphQL):  Disallow  Subscription typename. (#6077)

- graphql/e2e/subscription/subscription_test.go
- graphql/web/http.go
- testutil/graphql.go
This PR fixes panic error when expiry is not given in jwt for subscriptions using authorization.
(cherry picked from commit 37823e9153506f244a89630071253a55b6d4305b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6175)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1aa107c4f0-85683.surge.sh)
> fix(GraphQl): Panic fix when subscription expiry is not present in jwt.

- dgraph/cmd/zero/run.go
**Fixes DGRAPH-2185**
The panic mentioned in the bug is caused when idx is set to 0. The raft library we are using [etcd/raft](https://github.com/etcd-io/etcd/tree/master/raft) doesn't allow ID in the raft config to be 0 as it is reserved [to denote None i.e. no leader](https://github.com/etcd-io/etcd/blob/master/raft/raft.go#L34).
This change just adds this check to gracefully exit if idx is set to 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6156) …
> fix: Don't allow idx flag to be set to 0 on dgraph zero

- graphql/admin/admin.go
- graphql/api/panics.go
- graphql/e2e/common/error.go
- graphql/resolve/resolver.go
- graphql/schema/introspection.go
- systest/export/docker-compose.yml
- worker/graphql_schema.go
Since we don't use GitHub issues anymore, error messages should not link to them. Updating the error messages to say so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6183)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-777cd253ad-85809.surge.sh)
> fix(GraphQL): Remove github issues link from the error messages. (#6036)

- graphql/resolve/query_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/wrappers.go
For the schema
type Tweets {
id: String! @id
score: Int
}
getTweets query was not being properly re-written. This is because we were using the name id to signify that a field is of type ID instead of the type ID itself. That has been fixed now. So getTweets would work if the field was named anything.
query MyQuery {
getTweets(id: "1286891968727982081") {
score
id
}
}
(cherry picked from commit bb8e4b9d5456cc05a1abd15933b95881ca8e156b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6180) …
> fix(GraphQL): Fix getType queries when id was used as a name for types other than ID (#6130)

- graphql/e2e/subscription/subscription_test.go
- graphql/web/http.go
This PR allows case insensitive auth header for graphql subscriptions.
(cherry picked from commit d807eb7d00f61b62c4cd67e8dbaa1f7d45512135)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6179)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-778017d341-85750.surge.sh)
> fix(GraphQl): Allow case insensitive auth header for graphql subscriptions. (#6141)

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/update_mutation_test.yaml
- graphql/schema/wrappers.go
Fixes GRAPHQL-458
Schema:
```
type Post {
id: ID!
title: String! @id
text: String!
}
```
Mutation:
```
mutation AP {
addPost(input: [{title: "", text: "TextHello" }]) {
post{
id
title
text
}
numUids
}
}
```
This PR errors out on the following mutation which was previously allowed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6177)
> fix(GraphQL): Prevent empty values in fields having `id` directive.

- dgraph/cmd/zero/run.go
**Cherry pick**
* Fix DGRAPH-2185
* Update the help message for idx flag in dgraph zero
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6192)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-113a4aed52-86157.surge.sh)
> fix: Don't allow idx flag to be set to 0 on dgraph zero (#6156)

- contrib/config/monitoring/grafana/dgraph-kubernetes-grafana-dashboard.json
- contrib/config/monitoring/prometheus/README.md
- contrib/config/monitoring/prometheus/chart-values/README.md
- contrib/config/monitoring/prometheus/chart-values/dgraph-prometheus-operator.yaml
This updates the Prometheus section in contribution.  The following items were added:
* Docs for existing Prometheseus manifests
* Helm Chart Values for prometheus-operator including Grafana install.
* Grafana dashboard adjusted for Kubernetes, e.g. using pods instead of instances.
Additionally, tested the usability of the Grafana dashboard on GKE and EKS using 21million data set to generate some traffic.  
Not included in this PR:
* Add alert rules
* Add dgraph grafana dash board automatically
* Documentation for in deploy wiki for new helm chart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6128)
> chore: Prometheus helm chart values

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/update_mutation_test.yaml
- graphql/schema/wrappers.go
Fixes GRAPHQL-458
Schema:
```
type Post {
id: ID!
title: String! @id
text: String!
}
```
Mutation:
```
mutation AP {
addPost(input: [{title: "", text: "TextHello" }]) {
post{
id
title
text
}
numUids
}
}
```
This PR errors out on the following mutation which was previously allowed.
(cherry picked from commit d6975fd1060a3c372b3362ac064c55d8d95fcef4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6196)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3b29ad867c-86271.surge.sh)
> Prevent empty values in fields having `id` directive. (#6177)

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/schema.graphql
For nested add mutations, the linking of nodes for xids wasn't working properly. Level 1 and 2 are linked properly but level 2 and beyond were not. This PR aims to fix that.
See https://discuss.dgraph.io/t/grandchild-is-not-attached-to-child-when-using-addtype/9224 for more details.
(cherry picked from commit 806a8dfb51818d6baa63129df4cf34788f41b59e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6203)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-17a344b48d-86482.surge.sh)
> fix(GraphQL): Linking of xids for deep mutations (#6172)

- posting/list.go
Clear out the start_ts field in the postings of deltas before they are
marshalled to avoid storing that field in disk. This field is only meant
to be used during in-memory processing.
Related to https://discuss.dgraph.io/t/start-ts-not-being-cleared-before-postings-are-written-to-disk/9146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6206)
> fix(Dgraph): Don't store start_ts in postings

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
Fix First and offset on auth queries due to incorrect query rewriting.
https://discuss.dgraph.io/t/unexpected-output-when-adding-first-filter-on-nested-graph/8702/6
Fixes GRAPHQL-591
GraphQL Query:
```
query {
queryMovie(filter: { content: { eq: "MovieXYZ" } },  order: { asc: content }, first: 1) @cascade  {
content
regionsAvailable(filter: { name: { eq: "Region123" } },  order: { asc: name }, first: 1) {
name
global
}
}
}
```
Example Data after applying auth:
```
{
"queryMovie": [
{
"id": "0x276c", // Movie with one region
"regionsAvailable": [
{
"id": "0x2772", // Region
}
]
},
{
"id": "0x276d", // Movie with no region
},
{
"id": "0x276e", // Movie with two region
"regionsAvailable": [
{
"id": "0x2771", // Region
},
{
"id": "0x2773", // Region
}
]
}
]
}
```
According to the above data …
> fix(GraphQL): Fix order and offset in auth queries.

- posting/mvcc.go
- Reduce batch size to 16.
- Force a rollup to happen every 500ms instead of 2s.
Related to DGRAPH-2202
(cherry picked from commit fa013db935cdc64ca5eb31139057528d83751a3b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6146)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d28a35d5a7-84545.surge.sh)
> (release/v20.07) fix(Dgraph): Perform rollups more aggresively.

- worker/backup_ee.go
- worker/draft.go
Backups should be added to the list of tasks (rollups, snapshots, etc)
that are managed by Dgraph so that rollups and other tasks are paused
during the backup.
Fixes DGRAPH-2203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6152)
> fix(Dgraph): make backups cancel other tasks

- wiki/content/mutations/delete.md
Fixes DGRAPH-2261
Minor update in the docs of delete.
* Add information about the behaviour of `S * *` delete pattern.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6257)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-781e870a24-87642.surge.sh)
> docs: Improve the docs of delete mutation

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
This change also adds a way to set the table and value log loading modes for the w directory
independently of the values for the p directory.
Fixes DGRAPH-1898.
(cherry picked from commit 5f5aa9c1ab7505122b6e394a8af24ce0d52d9823)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6260)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cae470757a-87713.surge.sh)
> (release/v20.03) fix(Dgraph): Stop forcing RAM mode for the write-ahead log.

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
This change also adds a way to set the table and value log loading modes for the w directory
independently of the values for the p directory.
Fixes DGRAPH-1898.
(cherry picked from commit 5f5aa9c1ab7505122b6e394a8af24ce0d52d9823)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6259)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0ab83ca1b4-87706.surge.sh)
> (release/v20.07) fix(Dgraph): Stop forcing RAM mode for the write-ahead log.

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
This change also adds a way to set the table and value log loading modes for the w directory
independently of the values for the p directory.
Fixes DGRAPH-1898.
(cherry picked from commit 5f5aa9c1ab7505122b6e394a8af24ce0d52d9823)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6261)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-22e3aac5a0-87721.surge.sh)
> (release/v1.2) fix(Dgraph): Stop forcing RAM mode for the write-ahead log.

- wiki/content/deploy/kubernetes.md
Kubernetes Update
* Kubernetes
* reconciled missing or lost content from prior PRs due to split
* adjustment for clarity
* Helm Chart
* reconciled missing or lost content from prior PRs due to split
* From Previous PR: removed harm chart config values (redundant) and an incorrect command
* added section on dgraph config
* expanded load balancer to loadbalancer public and private and ingress.
* warning about `latest` and `master` tags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6254) …
> docs: update kubernetes section

- query/query3_test.go
- query/recurse.go
Currently a node is marked as visited if it's been visited before AND
has been visited from the same source UID. In dense graphs, the second
condition leads to exponential growth of the data and to other issues
such as responses that are too big to encode.  Removing this condition
fixes the issue.
Fixed tests and verified the new output makes sense.
Fixes DGRAPH-2337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6272)
> Fix(Dgraph): Fix how visited nodes are detected in recurse queries.

- query/query3_test.go
- query/recurse.go
Currently a node is marked as visited if it's been visited before AND
has been visited from the same source UID. In dense graphs, the second
condition leads to exponential growth of the data and to other issues
such as responses that are too big to encode.  Removing this condition
fixes the issue.
Fixed tests and verified the new output makes sense.
Fixes DGRAPH-2337
(cherry picked from commit 3638c12c1b755e7478c40a5142cb9cb3701c4ed5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6276) …
> (release/v20.07) Fix(Dgraph): Fix how visited nodes are detected in recurse queries.

- query/query3_test.go
- query/recurse.go
Currently a node is marked as visited if it's been visited before AND
has been visited from the same source UID. In dense graphs, the second
condition leads to exponential growth of the data and to other issues
such as responses that are too big to encode.  Removing this condition
fixes the issue.
Fixed tests and verified the new output makes sense.
Fixes DGRAPH-2337
(cherry picked from commit 3638c12c1b755e7478c40a5142cb9cb3701c4ed5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6277) …
> (release/v20.03) Fix(Dgraph): Fix how visited nodes are detected in recurse queries.

- query/query3_test.go
- query/recurse.go
Currently a node is marked as visited if it's been visited before AND
has been visited from the same source UID. In dense graphs, the second
condition leads to exponential growth of the data and to other issues
such as responses that are too big to encode.  Removing this condition
fixes the issue.
Fixed tests and verified the new output makes sense.
Fixes DGRAPH-2337
(cherry picked from commit 3638c12c1b755e7478c40a5142cb9cb3701c4ed5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6278) …
> (release/v1.2) Fix(Dgraph): Fix how visited nodes are detected in recurse queries.

- worker/file_handler.go
This was being done in the S3 handler but not in the file handler.
By default the paths are sorted by the filename but sorting by backup
number is more robust.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6263)
> fix(Dgraph): Sort manifests by BackupNum in file handler.

- graphql/admin/admin.go
- graphql/e2e/schema/schema_test.go
This PR fixes the "Internal error" response when querying the GraphQL schema after performing drop_all operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6268)
> fix(GraphQL): fix internal error when doing GraphQL schema introspection after drop all

- query/query.go
- systest/queries_test.go
Fixes DGRAPH-1279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6283)
> feat(dgraph): Allow parent's cascade (with or w/o param) to trickle to child until overridden explicitly

- edgraph/access_ee.go
- ee/acl/acl_test.go
This PR fixes: DGRAPH-2354
ACL enabled queries
No.
Added following tests in `acl_test.go`:
1. Use variable at the top level without using variable inside the first query. Below test case fails without this change.
```
f as q1(func: has(name), orderasc: name) {
name
age
}
q2(func: uid(f), orderasc: name) {
name
age
}
```
Fixes DGRAPH-2354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6290)
> fix(ACL Query): Fixes queries which use variable at the top level

- worker/backup_handler.go
- worker/online_restore_ee.go
- worker/restore.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6295)
> fix: Allowing you to pass credentials to online restore

- x/sentry_integration.go
(cherry picked from commit 52e136fb4871434e67dd79106286452ab34df2c3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6300)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e69be90848-89191.surge.sh)
> fix panicwrap parent check (#6264)

- worker/file_handler.go
- worker/s3_handler.go
Original change was not cherry-picked because the change was
made during the addition of online restores, which is a new feature in
the 20.07 version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6280)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7eca1192ae-88696.surge.sh)
> (release/v20.03) fix(Dgraph): Sort manifests by backup number.

- worker/file_handler.go
This was being done in the S3 handler but not in the file handler.
By default the paths are sorted by the filename but sorting by backup
number is more robust.
(cherry picked from commit df63d6ca2076f059961892b9a6f192cb05f88e31)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6279)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5dcbfe6016-88687.surge.sh)
> (release/v20.07) fix(Dgraph): Sort manifests by BackupNum in file handler.

- posting/list.go
Clear out the start_ts field in the postings of deltas before they are
marshalled to avoid storing that field in disk. This field is only meant
to be used during in-memory processing.
Related to https://discuss.dgraph.io/t/start-ts-not-being-cleared-before-postings-are-written-to-disk/9146
(cherry picked from commit fbbd7315b8bf76609ede13a3fe4abbee5c4bde41)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6214)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-dd0f1f7da9-86725.surge.sh)
> (release/v20.03) fix(Dgraph): Don't store start_ts in postings.

- posting/index.go
- systest/mutations_test.go
When updating a single uid predicate with a reverse index, the existing entry in the
reverse index should be deleted first.
Fixes DGRAPH-1738
(cherry picked from commit 5b70fe8aa2c4dc08f74794b3e9875c8789c11c9f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6006)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a00e100e3e-80012.surge.sh)
> (release/v20.03) fix(Dgraph): update reverse index when updating single UID predicates

- query/query3_test.go
- query/recurse.go
This reverts commit 3638c12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6307)
> Revert "Fix(Dgraph): Fix how visited nodes are detected in recurse queries"

- posting/list.go
Clear out the start_ts field in the postings of deltas before they are
marshalled to avoid storing that field in disk. This field is only meant
to be used during in-memory processing.
Related to https://discuss.dgraph.io/t/start-ts-not-being-cleared-before-postings-are-written-to-disk/9146
(cherry picked from commit fbbd7315b8bf76609ede13a3fe4abbee5c4bde41)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6213)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d02df9623c-86718.surge.sh)
> (release/v20.07) fix(Dgraph): Don't store start_ts in postings.

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
- edgraph/access.go
- edgraph/access_ee.go
- edgraph/server.go
- go.mod
- go.sum
- worker/groups.go
- worker/server_state.go
This PR removes the usage of context.Background() in groups.go and ensures that all the various goroutines exit as intended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6313)
> Fix(Alpha): MASA: Make Alpha Shutdown Again

- wiki/content/graphql/custom/graphqlpm.md
Reference: [Discuss Post](https://discuss.dgraph.io/t/custom-dql-typename-bug-strange-behaviour/9341)
(cherry picked from commit 0faae407a9ee74244734d97e757a284972f95ad2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6273)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-532d968164-88434.surge.sh)
> cherry-pick v20.07: docs: add info about __typename in custom DQL (#6248)

- posting/mvcc.go
Fixes DGRAPH-2181
The queries in dgraph are processed in separate goroutines. The pstore badger DB
could be closed while the query was being processed. This causes panics such as
```
panic: runtime error: invalid memory address or nil pointer dereference
panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11d2311]
goroutine 19298 [running]:
github.com/dgraph-io/badger/v2.(*Txn).Discard(0xc05586bc20)
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200718033852-37ee16d8ad1c/txn.go:517 +0xc1
panic(0x19e26a0, 0x2988560)
/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
```
This PR attempts to reduce the number of such crashes. This PR doesn't fix the actual
issue but …
> release/v20.03 - fix(task): Return error on closed DB (#6075)

- posting/mvcc.go
Fixes DGRAPH-2181
The queries in dgraph are processed in separate goroutines. The pstore badger DB
could be closed while the query was being processed. This causes panics such as
```
panic: runtime error: invalid memory address or nil pointer dereference
panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11d2311]
goroutine 19298 [running]:
github.com/dgraph-io/badger/v2.(*Txn).Discard(0xc05586bc20)
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200718033852-37ee16d8ad1c/txn.go:517 +0xc1
panic(0x19e26a0, 0x2988560)
/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
```
This PR attempts to reduce the number of such crashes. This PR doesn't fix the actual
issue but …
> release/20.07 - fix(task): Return error on closed DB (#6075)

- worker/backup_ee.go
- worker/draft.go
Backups should be added to the list of tasks (rollups, snapshots, etc)
that are managed by Dgraph so that rollups and other tasks are paused
during the backup.
(cherry picked from commit ea15b664aa8659c0722e31a499c598698377215f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6244)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f84dfa78b7-89642.surge.sh)
> (release/v20.03) fix(Dgraph): make backups cancel other tasks

- go.mod
- go.sum
This badger update brings the following changes from badger.
```
b41e77a Fix(cleanup): Avoid truncating in value.Open on error (#1465) (#1489)
a0d4903 fix(cleanup): Do not close cache before compaction (#1464) (#1488)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6293)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2dfb1f9b0e-89042.surge.sh)
> release/v20.03 - Update badger to v2.2007.2

- go.mod
- go.sum
This badger update brings the following changes from badger.
```
b41e77a Fix(cleanup): Avoid truncating in value.Open on error (#1465) (#1489)
a0d4903 fix(cleanup): Do not close cache before compaction (#1464) (#1488)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6294)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-98f059cd42-89043.surge.sh)
> release/v20.07 - Update badger to v2.2007.2

- posting/mvcc.go
Fixes DGRAPH-2181
The queries in dgraph are processed in separate goroutines. The pstore badger DB
could be closed while the query was being processed. This causes panics such as
```
panic: runtime error: invalid memory address or nil pointer dereference
panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11d2311]
goroutine 19298 [running]:
github.com/dgraph-io/badger/v2.(*Txn).Discard(0xc05586bc20)
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200718033852-37ee16d8ad1c/txn.go:517 +0xc1
panic(0x19e26a0, 0x2988560)
/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
```
This PR attempts to reduce the number of such crashes. This PR doesn't fix the actual
issue but …
> release/v1.2 - fix(task): Return error on closed DB (#6075)

- edgraph/access_ee.go
- ee/acl/acl_test.go
- gql/mutation.go
- protos/pb/pb.pb.go
- query/mutation.go
Using below query with ACL turned on fails because the code treats `STAR_ALL` as a separate predicate which should not be the case. This is somewhat similar to `expand(_all_)` bug which was fixed in #5733 
```
{
delete {
<0x6> * * .
}
}
```
This PR fixes: DGRAPH 2361
STAR_ALL delete queries when ACL is enabled.
No
Added following tests in:
1.
Fixes DGRAPH 2361
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6331)
> fix(Query) Fix Star_All delete query when used with ACL enabled

- ee/backup/backup.go
Version 1.2 returns a nil list from ReadPostingList. The backup was
trying to call the method SingleListRollup. The fix is to ignore those
lists. They will be backed up when the main key is accessed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6314)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2f08db6222-89552.surge.sh)
> fix(Dgraph): skip backing up nil lists.

- graphql/e2e/custom_logic/cmd/graphqlresponse.yaml
- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
Fixes DGRAPH-2357.
Fixes GRAPHQL-562.
(cherry picked from commit 91e28d53c356312956230dad94dfb0d5e9f04135)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6347)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0164447e07-90326.surge.sh)
> cherry-pick v20.07: chore(GraphQL): remove skipped tests (#6078)

- contrib/scripts/functions.sh
Fixes DGRAPH-2356
This PR fixes random GraphQL custom logic e2e test failures in TeamCity by requiring docker-compose to always build images before starting the containers, as the mock server in custom logic tests can change any time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6348)
> test: add --build option for docker-compose up in test script

- wiki/content/graphql/authorization/directive.md
- wiki/content/graphql/authorization/mutations.md
This PR fix errors from authorization examples given in docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6330)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7997c5b7af-90396.surge.sh)
> fix(GraphQl): fix errors from authorization examples given in docs.

- dgraph/cmd/alpha/dashboard.go
- dgraph/cmd/alpha/http_test.go
**Motivation**
Currently, making an API call to a non-existent path on alpha HTTP server such as "/admin/test" returns status as 200 (OK). As the path does not exist, status should be 404.
Related discuss issue: https://discuss.dgraph.io/t/dgraph-should-return-404-on-non-existent-api-paths/9574
**Components affected by this PR**
Dgraph alpha http server
**Does this PR break backwards compatibility?**:
No
**Testing**
Added two unit tests in dgraph/cmd/alpha/http_test.go .
This Pull Request fixes this.
**Fixes**
DGRAPH-2335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6296)
> fix: Return 404 status on non-existent API calls

- contrib/scripts/functions.sh
Fixes DGRAPH-2356
This PR fixes random GraphQL custom logic e2e test failures in TeamCity by requiring docker-compose to always build images before starting the containers, as the mock server in custom logic tests can change any time.
(cherry picked from commit 536b3176fec9600045d5ca2d4e60ae3a055fa1ef)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6352)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-91310e1c83-90418.surge.sh)
> cherry-pick v20.07: test: add --build option for docker-compose up in test script (#6348)

- graphql/admin/schema.go
- graphql/e2e/custom_logic/docker-compose.yml
- graphql/e2e/schema/generatedSchema.graphql
- graphql/e2e/schema/schema_test.go
This PR fixes the behaviour where Dgraph schema was being given as `generatedSchema` field in `updateGQLSchema` request. Now, the newly generated complete GraphQL schema is given as `generatedSchema`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6349)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a820345247-90521.surge.sh)
> fix(GraphQL): incorrect generatedSchema in updateGQLSchema

- graphql/admin/schema.go
- graphql/e2e/schema/generatedSchema.graphql
- graphql/e2e/schema/schema_test.go
This PR fixes the behaviour where Dgraph schema was being given as generatedSchema field in updateGQLSchema request. Now, the newly generated complete GraphQL schema is given as generatedSchema.
(cherry picked from commit 0b8681cdca27b1032aa645ee6c0e6851ae82b154)
\# Conflicts:
\#	graphql/e2e/schema/schema_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6354)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ca5294b185-90549.surge.sh)
> cherry-pick v20.07: fix(GraphQL): incorrect generatedSchema in updateGQLSchema (#6349)

- dgraph/cmd/zero/run.go
(cherry picked from commit 254bd2904fa236ef4527d8744f2246af27b61d9a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6355)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c8bdabbed7-90583.surge.sh)
> (release/v20.07) fix(Dgraph): add flag to set up compression in zero.

- dgraph/cmd/zero/run.go
(cherry picked from commit 254bd2904fa236ef4527d8744f2246af27b61d9a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6357)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a9eaa8132b-90591.surge.sh)
> (release/v1.2) fix(Dgraph): add flag to set up compression in zero.

- dgraph/cmd/zero/run.go
(cherry picked from commit 254bd2904fa236ef4527d8744f2246af27b61d9a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6356)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-319193662d-90590.surge.sh)
> (release/v20.03) fix(Dgraph): add flag to set up compression in zero.

- query/query.go
- query/query1_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6058)
1. Pagination param "after" does not work when using func: uid(v). For ex:
for query
```
{
var(func: has(name@en), first: 50) {
test as uid
}
ss(func: uid(test), first: 2, after: 0x6) {
uid
}
}
```
before the result was
```
{
"data": {
"ss": [
{
"uid": "0x4"
},
{
"uid": "0x6"
}
]
}
}
```
now the result is
```
{
"data": {
"ss": [
{
"uid": "0x7"
},
{
"uid": "0x8"
}
]
}
}
```
2. Fixes #5242.
3. Fixes [DGRAPH-1273](https://dgraph.atlassian.net/browse/DGRAPH-1273).
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" …
> Pagination param "after" does not work when using func: uid(v)

- graphql/admin/schema.go
- graphql/e2e/schema/generatedSchema.graphql
- graphql/e2e/schema/schema_test.go
This PR fixes the behaviour where Dgraph schema was being given as generatedSchema field in updateGQLSchema request. Now, the newly generated complete GraphQL schema is given as generatedSchema.
(cherry picked from commit 0b8681cdca27b1032aa645ee6c0e6851ae82b154)
\# Conflicts:
\#	graphql/e2e/schema/schema_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6368)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9a56f1a2f4-90807.surge.sh)
> cherry-pick v20.07-slash: fix(GraphQL): incorrect generatedSchema in updateGQLSchema (#6349)

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/delete_mutation_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/mutation_rewriter.go
Fixes GRAPHQL-596
```
mutation {
deleteTweets(
filter: {
text: {anyoftext: "abc"}
}) {
tweets {
text
}
}
}
```
The above mutation was previously rewritten as:
```
dgmutations:
- deletejson: |
[
{ "uid": "uid(x)" },
{
"User.tweets" : [{"uid":"uid(x)"}],
"uid" : "uid(User2)"
}
]
dgquery: |-
query {
x as deleteTweets() {
User1 as Tweets.user
}
tweets(func: uid(Tweets2)) {
text : Tweets.text
dgraph.uid : uid
}
Tweets2 as var(func: uid(Tweets3))
Tweets3 as var(func: uid(x))
}
```
Since the RBAC rule failed for `Tweets` it should not contain any fields inside the query and also it should not try to delete its inverse reference if it has any field with `@hasInverse`
After this PR if RBAC rules fails the mutation is rewritten as follows:
```
dgmutations:
- deletejson: |
[
{ "uid": "uid(x)" }
] …
```
> fix(GraphQL): Fix query rewriting for auth delete when deleting types with inverse field.

- edgraph/server.go
Fixes DGRAPH-2391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6372)
> fix(dgraph): sentry nil pointer check

- dgraph/cmd/zero/raft.go
because, raft ready already proposing enterprise license. So, avoiding
the race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6367)
> don't propose trail license if the licences is provided by the user.

- wiki/content/graphql/schema/graph-links.md
remove duplicate word "doesn't" from description of two-way edges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6378)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5c80007d4e-91182.surge.sh)
> chore(Docs): Update graph-links.md to remove a duplicate word

- dgraph/cmd/alpha/run.go
Forcefully kill alpha if CTRL-C is caught before node initialization
has completed.
Fixes DGRAPH-2377
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6359)
> fix(shutdown): Force exit if CTRL-C is caught before initialization

- wiki/content/get-started/index.md
Current schema fails with the error: `"message": "Schema does not contain a matching predicate for field starring in type Film",
`
This PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6390)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-938d122813-91672.surge.sh)
> docs: add missing predicates in alter schema

- conn/node.go
- conn/pool.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/zero/license.go
- dgraph/cmd/zero/license_ee.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- dgraph/cmd/zero/zero.go
- edgraph/access.go
- edgraph/access_ee.go
- edgraph/server.go
- go.mod
- go.sum
- graphql/admin/admin.go
- graphql/admin/shutdown.go
- posting/lists.go
- posting/mvcc.go
- raftwal/storage.go
- worker/draft.go
- worker/executor.go
- worker/groups.go
- worker/mutation.go
- worker/server_state.go
- x/x.go
The closer type was moved from badger/y to ristretto/z in https://github.com/dgraph-io/ristretto/pull/191 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6394)
> Use z.Closer instead of y.Closer

- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/output/searchables.graphql
Fixes GRAPHQL-650.
For this user schema:
```
type Starship {
id: ID!
name: String! @search(by: [term])
length: Int64
tags: [String]
createdAt: DateTime
}
```
we were generating complete GraphQL schema with StarshipOrderable as:
```
enum StarshipOrderable {
name
length
tags
createdAt
}
```
that would cause a DQL query to be formed which errors out, see this GraphQL query:
```
query {
queryStarship(order: {asc: tags}) {
id
name
length
tags
}
}
```
It gives back:
```
{
"errors": [
{
"message": "Dgraph query failed because Dgraph execution failed because : Sorting not supported on attr: Starship.tags of type: [scalar]"
}
],
"data": {
"queryStarship": []
}
}
```
which means we should not allow even list of scalar along with object types in orderable. Only scalar field should be allowed in …
> fix(GraphQL): don't generate orderable enum value for list fields

- conn/node.go
- conn/pool.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/zero/license.go
- dgraph/cmd/zero/license_ee.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- dgraph/cmd/zero/zero.go
- edgraph/access.go
- edgraph/access_ee.go
- go.mod
- go.sum
- graphql/admin/admin.go
- graphql/admin/shutdown.go
- posting/lists.go
- posting/mvcc.go
- raftwal/storage.go
- worker/draft.go
- worker/executor.go
- worker/groups.go
- worker/mutation.go
- worker/server_state.go
- x/x.go
The closer type was moved from badger/y to ristretto/z in https://github.com/dgraph-io/ristretto/pull/191
(cherry picked from commit 028783889501fe5c514df9270242e9264e476ca8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6399)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6087eef2ed-91834.surge.sh)
> release/v20.07 - Use z.Closer instead of y.Closer (#6394)

- conn/node.go
- conn/pool.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/zero/license.go
- dgraph/cmd/zero/license_ee.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- dgraph/cmd/zero/zero.go
- edgraph/access.go
- edgraph/access_ee.go
- go.mod
- go.sum
- graphql/admin/admin.go
- posting/lists.go
- posting/mvcc.go
- raftwal/storage.go
- worker/draft.go
- worker/executor.go
- worker/groups.go
- worker/mutation.go
- worker/server_state.go
- x/x.go
The closer type was moved from badger/y to ristretto/z in https://github.com/dgraph-io/ristretto/pull/191
(cherry picked from commit 028783889501fe5c514df9270242e9264e476ca8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6398)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ec120c14b5-91827.surge.sh)
> release/v20.03 - Use z.Closer instead of y.Closer (#6394)

- conn/node.go
- conn/pool.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/zero/license.go
- dgraph/cmd/zero/license_ee.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- dgraph/cmd/zero/zero.go
- edgraph/access.go
- edgraph/access_ee.go
- go.mod
- go.sum
- posting/lists.go
- raftwal/storage.go
- worker/draft.go
- worker/groups.go
- worker/mutation.go
- worker/server_state.go
- x/x.go
The closer type was moved from badger/y to ristretto/z in https://github.com/dgraph-io/ristretto/pull/191
(cherry picked from commit 028783889501fe5c514df9270242e9264e476ca8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6396)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1665bb8ffb-91813.surge.sh)
> release/v1.2 - Use z.Closer instead of y.Closer (#6394)

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
- edgraph/access.go
- edgraph/access_ee.go
- edgraph/server.go
- go.mod
- go.sum
- graphql/admin/admin.go
- worker/groups.go
- worker/server_state.go
This PR removes the usage of context.Background() in groups.go and ensures that all the various goroutines exit as intended.
Changes:
* Shutdown SubscribeForUpdates correctly.
* Fix up all the closing conditions.
* Consolidate updaters into one closer
* Update Badger to master
* fix(build): Update ResetAcl args for OSS build.
* chore: Remove TODO comment.
(cherry picked from commit f1941b3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6406) …
> release/v1.2 - Fix(Alpha): MASA: Make Alpha Shutdown Again (#6313)

- tok/tok.go
- tok/tok_test.go
- tok/tokens.go
The current tokenization method breaks the use of `anyofterms` and `allofterms` for languages like Chinese or Japanese. The issue was first raised [here](https://discuss.dgraph.io/t/anyofterms-doesn-t-work-as-expected-with-chinese-characters/9373), where tokenization in a language where the space character isn't used to delimit words (e.g. Chinese). 
This PR fixes that as a first step to removing Bleve in term tokenization.
Additional language support to the `TermTokenizer` is added, so that `GetTokenizerByLang` works when `TermTokenizer` gets passed in. If it's a language in which we know doesn't use space to delimit words, then a simple `strings.Split` is called.
Currently no attempt is made to clean up punctuations and symbols. The reason for this is that it gets quite complicated with …
> feat(querylang): language support for term tokenization

- graphql/resolve/delete_mutation_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/wrappers.go
Fixes GRAPHQL-655.
For this user schema (interface have no non-Id field):
```
interface A {
name: String! @id
}
type B implements A {
age: Int!
}
```
the following delete mutation 
```
mutation{
deleteA(filter:{name:{eq: "xyz"}}){
a{
name
}
}
}
```
was resulting in the following error:
```
{
"errors": [
{
"message": "Internal Server Error - a panic was trapped.  This indicates a bug in the GraphQL server.  A stack trace was logged.  Please let us know by filing an issue with the stack trace."
}
]
}
```
This PR fixes this bug and now deleting can be performed successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6387)
> fix(GraphQL): fix for deletion on interfaces with no non Id field

- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/http_test.go
Fixes DGRAPH-2227.
A request sent to a query or mutation handler with the header `Content-Type: application/json; charset=utf-8` fails even though it is perfectly valid. This PR fixes parsing of the `Content-Type` header.
Currently, I've added a check - `charset`, if defined, must be `utf-8`. We may or may not want to remove that check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6370)
> fix(Dgraph): Parse Content-Type in headers properly

- graphql/admin/restore_status.go
- graphql/admin/restore_status_test.go
Fixes GRAPHQL-642.
For this restoreStatus query using variable
```
query restoreStatus($restoreId: Int!) {
restoreStatus(restoreId: $restoreId) {
status
errors
}
}
```
was giving this panic
```
panic: interface conversion: interface {} is json.Number, not int64.
```
Whereas expected result should be
```
{
"data": {
"restoreStatus": {
"status": "UNKNOWN",
"errors": []
}
},
"extensions": {}
}
```
This PR fixes this panic, Now `resolveStatus` with or without variable works fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6414)
> fix(GraphQL): fix  restoreStatus query with query variables

- dgraph/cmd/zero/raft.go
The Checkquorum() function is used by the leader to determine if it is
still a leader and not behind a network partition (split-head situation).
The current code would checkquorum even for followers which isn't necessary.
This PR removes the quorum check for followers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6323)
> fix(raft): Only leader should check the quorum

- wiki/content/deploy/troubleshooting.md
Fixes DGRAPH-2317. Issue is with v20.07 we restrict the admin operations from alpha instances only. But this hasn't been mentioned during the deployment process in any examples. Hence community is running into issues like Unauthorized IP address X.X.X.X. This doc addition in troubleshoot page will help the community members if they run into this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6422)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cbcd6b45a4-92572.surge.sh)
> docs: add whitelisting issue error in troubleshoot page to help the community

- wiki/content/_index.md
The current absolute link doesn't work on master, so making it an absolute link for the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6429)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a148921d4c-92859.surge.sh)
> chore(docs): Make the link for badger on docs an absolute link

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/schema.graphql
While creating the add mutation, we weren't squashing different bits correctly which led to the incorrect mutation being sent to Dgraph. This change modifies the set to append for `[]interface{}` to fix that.
Fixes GRAPHQL-679
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6416)
> fix(GraphQL): Fix squashIntoObject so that results are correctly merged

- wiki/content/clients/raw-http.md
- wiki/content/deploy/cluster-checklist.md
- wiki/content/deploy/dgraph-administration.md
- wiki/content/deploy/dgraph-alpha.md
- wiki/content/deploy/fast-data-loading.md
- wiki/content/deploy/kubernetes.md
- wiki/content/deploy/multi-host-setup.md
- wiki/content/deploy/ports-usage.md
- wiki/content/deploy/production-checklist.md
- wiki/content/deploy/single-host-setup.md
- wiki/content/design-concepts/concepts.md
- wiki/content/dgraph-compared-to-other-databases/index.md
- wiki/content/mutations/batch-mutations.md
- wiki/content/mutations/json-mutation-format.md
- wiki/content/mutations/language-rdf-types.md
- wiki/content/mutations/upsert-block.md
- wiki/content/query-language/aggregation.md
- wiki/content/query-language/count.md
- wiki/content/query-language/expand-predicates.md
- wiki/content/query-language/facets.md
- wiki/content/query-language/functions.md
- wiki/content/query-language/graphql-fundamentals.md
- wiki/content/query-language/kshortest-path-quries.md
- wiki/content/query-language/pagination.md
- wiki/content/query-language/schema.md
- wiki/content/query-language/sorting.md
- wiki/content/query-language/type-system.md
- wiki/content/query-language/value-variables.md
Motivation:
With the splitting of docs into multiple pages work carried out in this PR: https://github.com/dgraph-io/dgraph/pull/6079 , many subsections had moved to different pages causing references to not redirect to the desired page.
This PR fixes those referencing bugs.
Tested locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6439)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3f6e3e6873-93047.surge.sh)
> Fix(docs): Fix subsection references in docs

- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/query.go
Fixes GRAPHQL-680
Fixes [Discuss Issue](https://discuss.dgraph.io/t/int-type-parameter-of-custom-dql-is-wrong/10142)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6433)
> fix(GraphQL): correct GraphQL variable propagation to custom-dql

- query/shortest.go
Fixes DGRAPH-2381
The k-shortest path query sometimes returns a wrong response. The cause
of this issue is inappropriate use of sync.pools. Whenever a valid path 
is found a new variable is assigned with this route and that variable is  
appended in the kroutes (which is then parsed to produce response). 
But the route is also put in the sync.pool. Since the route is a 
structure containing a pointer to slice along with other fields, when
it is fetched back from the pool in future then any mutation on this fetched 
route causes modification in the kroutes, resulting in garbage response. 
This issue is fixed by making a deep copy of the route struct rather
than just assigning it to a variable, which causes a shallow copy.
--- …
> fix(Query): Fix wrong path response for k-shortest paths

- posting/list.go
- systest/mutations_test.go
the iterate method does not account for delete postings in the same transaction
so they have to be preserved manually. Otherwise, if a deletion and an add operation
to the same uid happen in the same predicate, the deletion operation is not
applied.
Fixes DGRAPH-1309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6431)
> fix(Dgraph): fix bug when deleting and adding to a single UID predicate in the same transaction.

- worker/draft.go
This PR would cause the Alpha leader to immediately trigger a snapshot creation if it doesn't already have one.
This is useful when you bring a new cluster from bulk loader. If you remove an Alpha instance and add a new Alpha instance, the new follower won't get a snapshot if the leader doesn't have one. This PR avoids that by causing the leader to get a snapshot asap.
Fixes DGRAPH-2445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6458)
> fix(Alpha): Immediately take a snapshot if we don't have one

- dgraph/cmd/zero/tablet.go
DGraph zero always times out when it tries to rebalance across alpha nodes for very large nodes. This PR increases the timeout from 20 minutes to 2 hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6388)
> fix(DGraph): Increased timeout for rebalancing alpha nodes from 20m to 2h

- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/input/type-without-orderables.graphql
- graphql/schema/testdata/schemagen/output/type-without-orderables.graphql
Fixes GRAPHQL-650
It was introduced after #6392.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6456)
> fix(GraphQL): Generate correct schema when no orderable field in a type

- go.mod
- go.sum
Fixes GRAPHQL-681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6462)
> fix(GraphQL): Fix subscriptions not getting terminated on client disconnect by updating graphql-transport-ws-library.

- x/x.go
Fixes DGRAPH-1675
To test out this fix just start a Dgraph cluster and load some dummy data then run a query with curl:
e.g
```
curl  -v -H "Content-Type: application/graphql+-" localhost:8080/query -XPOST -d '
{
result(func: has(director.film), first: 10) {
uid
}
}' | jq
```
The content length will be reported as follows:
<pre>
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /query HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/graphql+-
> Content-Length: 64
>
} [64 bytes data]
* upload completely sent off: 64 out of 64 bytes
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: X-Dgraph-AccessToken, Content-Type, Content-Length, …
> Return content length header for queries

- x/debug.go
Importing dgo/x will try to add version 1.0 of dgo to the go.mod file.
Instead, just use the x package inside dgraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6486)
> chore: replace dgo/x package with dgraph/x

- CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6489)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-66e8c2e52f-94455.surge.sh)
> Changelog for v20.03.5

- graphql/e2e/schema/schema_test.go
- graphql/schema/introspection_test.go
- graphql/schema/testdata/introspection/input/full_query.graphql
- graphql/schema/wrappers.go
Fixes GRAPHQL-673.
This PR fixes the issue where introspection queries would break if there were two types implementing same interface and having fields with same name in those two types and that repeating field is also a field in introspection query.
This was introduced after #6228.
(cherry picked from commit 243a336d17c8a27ddd6a59ffec894fdbc68f6480)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6389)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e77cca26cc-91647.surge.sh)
> cherry-pick v20.07: fix(GraphQL): fix introspection completion bug (#6385)

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
- x/x.go
Motivation
Currently, badger.compression_level flag is used to set compression level for Postings directory. Compression Level for WAL directory is set to None by default.
This PR adds functionality to set compression levels of each directory separately using a comma separated badger.compression_level flag.
Related discuss issue: https://discuss.dgraph.io/t/separate-dgraph-compression-level-config-for-p-and-w-directories/9938
Components affected by this PR:
Dgraph alpha
Does this PR break backwards compatibility?:
No
Fixes DGRAPH-2380
(cherry picked from commit 601cc3b39ab018c3ac751d955f2508d7eebfc880)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6420)
Docs Preview: …
> release/v20.03 - Feat(Dgraph): Add separate compression flag for z and wal dirs (#6401)

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
- x/x.go
Motivation
Currently, badger.compression_level flag is used to set compression level for Postings directory. Compression Level for WAL directory is set to None by default.
This PR adds functionality to set compression levels of each directory separately using a comma separated badger.compression_level flag.
Related discuss issue: https://discuss.dgraph.io/t/separate-dgraph-compression-level-config-for-p-and-w-directories/9938
Components affected by this PR:
Dgraph alpha
Does this PR break backwards compatibility?:
No
Fixes DGRAPH-2380
(cherry picked from commit 601cc3b39ab018c3ac751d955f2508d7eebfc880)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6421)
Docs Preview: …
> release/v20.07 - Feat(Dgraph): Add separate compression flag for z and wal dirs (#6401)

- wiki/content/graphql/schema/types.md
- wiki/content/query-language/schema.md
Fixes GRAPHQL-657
Fixes [Discuss Issue](https://discuss.dgraph.io/t/documentation-that-arrays-work-as-a-set-not-storing-duplicates/9590)
(cherry picked from commit 07cff6f56303bce07828e6829b92f3ad7195b80b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6461)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b658e3314b-93842.surge.sh)
> cherry-pick v20.07: docs: Update list documentation (#6455)

- systest/group-delete/group_delete_test.go
(cherry picked from commit 512c69bf7ebd94b3e2a970b520f8794c72afa92a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6482)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7413258aa6-94335.surge.sh)
> (release/v20.07) test: retry getting client in TestNodes.

- wiki/content/clients/raw-http.md
- wiki/content/deploy/cluster-checklist.md
- wiki/content/deploy/dgraph-administration.md
- wiki/content/deploy/dgraph-alpha.md
- wiki/content/deploy/fast-data-loading.md
- wiki/content/deploy/kubernetes.md
- wiki/content/deploy/multi-host-setup.md
- wiki/content/deploy/ports-usage.md
- wiki/content/deploy/production-checklist.md
- wiki/content/deploy/single-host-setup.md
- wiki/content/design-concepts/concepts.md
- wiki/content/dgraph-compared-to-other-databases/index.md
- wiki/content/mutations/batch-mutations.md
- wiki/content/mutations/json-mutation-format.md
- wiki/content/mutations/language-rdf-types.md
- wiki/content/mutations/upsert-block.md
- wiki/content/query-language/aggregation.md
- wiki/content/query-language/count.md
- wiki/content/query-language/expand-predicates.md
- wiki/content/query-language/facets.md
- wiki/content/query-language/functions.md
- wiki/content/query-language/graphql-fundamentals.md
- wiki/content/query-language/kshortest-path-quries.md
- wiki/content/query-language/pagination.md
- wiki/content/query-language/schema.md
- wiki/content/query-language/sorting.md
- wiki/content/query-language/type-system.md
- wiki/content/query-language/value-variables.md
Motivation:
With the splitting of docs into multiple pages work carried out in this PR: #6079 , many subsections had moved to different pages causing references to not redirect to the desired page.
This PR fixes those referencing bugs.
Tested locally.
(cherry picked from commit 027db53875b5b8d16edd35fab7741e708bfa8610)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6516)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a9f6305bb3-94719.surge.sh)
> release/v20.07 - Fix(docs): Fix subsection references in docs (#6439)

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
Fixes GRAPHQL-591.
#6221 
* Fix order and offset in auth queries.
* Remove order from top-level auth filter.
(cherry picked from commit a5bfd4a9ce87a36fb6e4fc073cd651b81f9299e8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6366)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ed19da219d-90741.surge.sh)
> fix(GraphQL): Fix order and offset in auth queries. (#6221)

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/delete_mutation_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/mutation_rewriter.go
#6350 
* Fix query rewriting for auth delete when deleting types with inverse field.
(cherry picked from commit be9ebd0586e29b8edbe12b2783faf3422ca4bd40)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6524)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-482d88d4ad-94873.surge.sh)
> fix(GraphQL): Fix query rewriting for auth delete when deleting types with inverse field. (#6350)

- graphql/admin/restore_status.go
- graphql/admin/restore_status_test.go
Fixes GRAPHQL-642.
For this restoreStatus query using variable
```
query restoreStatus($restoreId: Int!) {
restoreStatus(restoreId: $restoreId) {
status
errors
}
}
```
was giving this panic
```
panic: interface conversion: interface {} is json.Number, not int64.
```
Whereas the expected result should be
```
{
"data": {
"restoreStatus": {
"status": "UNKNOWN",
"errors": []
}
},
"extensions": {}
}
```
This PR fixes this panic, Now `resolveStatus` with or without variable works fine.
(cherry picked from commit 45afae9)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6424)
> release/v20.07: fix(GRAPHQL): fix restoreStatusQuery

- wiki/content/graphql/authorization/directive.md
- wiki/content/graphql/authorization/mutations.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6522)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-cea3c2bfb6-94856.surge.sh)
> fix(docs): fix errors from authorization examples given in docs.

- wiki/content/clients/go.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6492)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-60e2822d39-94687.surge.sh)
> docs for RDF response. 

- graphql/admin/schema.go
- graphql/schema/gqlschema.go
- graphql/schema/schemagen.go
- graphql/schema/schemagen_test.go
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-all-empty.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-circular.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-custom-mutation.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-directLink.graphql
- graphql/schema/testdata/schemagen/input/hasInverse-with-interface-having-directive.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
Fixes GRAPHQL-572
This PR adds schema cleaning in GraphQL which will remove empty links and types from generated GraphQL schema recursively.
(cherry picked from commit bec53225d09c255345ad625ef3880c4e09a19de5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6523)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5d82a56056-94863.surge.sh)
> fix(GraphQL): This PR add schema cleaning in GraphQL.

- graphql/e2e/auth/auth_test.go
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
* Fix cascade with auth query.
* Added additional E2E test.
(cherry picked from commit 8c518d4976cd54e3c5dd0954c9aedf2dcd5ae3e2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6535)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2831c29351-95059.surge.sh)
> fix(GraphQL): Fix cascade with auth query when RBAC is false (#6444)

- graphql/e2e/auth/add_mutation_test.go
- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/debug_off/debug_off_test.go
- graphql/e2e/auth/delete_mutation_test.go
- graphql/e2e/auth/schema.graphql
- graphql/e2e/common/common.go
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/query_rewriter.go
- graphql/schema/response.go
* Hide info when performing mutation on id field with auth rule.
(cherry picked from commit 5c33428fc9adc973590c7f5eb1f8ccd55eeb26f9)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6534)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5a3266d5af-95045.surge.sh)
> fix(GraphQL): Hide info when performing mutation on id field with auth rule. (#6391)

- conn/node_test.go
- dgraph/cmd/zero/run.go
- go.mod
- go.sum
- raftwal/storage.go
- raftwal/storage_test.go
- worker/draft_test.go
- worker/server_state.go
This PR changes how we use badger in the wal store. Currently we run
badger in normal mode for `w` and `zw` store. We've seen up to 900K
entries for the same hard state (hs) key in `zw` store. These duplicate
keys cause spikes in read latencies in `zw`. The `w` store has more
compactions compared to `zw` store and so it has lesser stale data and
thus lesser spikes in read latencies.
The fix here is to open the `w` and `zw` directories in managed mode and
perform all writes on the same timestamp (max version in the db). This
leads to close to 0 duplicates in the store.
This PR also fixes the raft leader election issue which is a result of high
read latencies.
(cherry picked from commit 6882e377d24f8c89c9a426b1011c24334d2e7c3a)
--- …
> release/v20.03 - perf(raft): Use raft storage in managedmode (#6457)

- wiki/content/enterprise-features/encryption-at-rest.md
Currently, docs state the following about turning of encryption:
> If you wish to turn off encryption from an existing Alpha, then you can export your data and import it into a new Dgraph instance without encryption enabled.
This is not enough clear, therefore this doc PR to clarify that in this case, one has to load data with live loader and pass the `--encryption_key_file` + example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6548) …
> docs: clarify how to turn off encryption with live loader

- conn/node.go
- dgraph/cmd/zero/raft.go
- raftwal/storage.go
When logging in v=3, the Zero heartbeat logs would show 0 heartbeats even when the quorum is healthy:
RaftComm: [0x1] Heartbeats out: 0, in: 0
This change fixes the reporting for Zero instances by calling ReportRaftComms in Zero:
RaftComm: [0x1] Heartbeats out: 28, in: 28
Also, this adds a log for read index to check for healthiness for read index calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6538)
> fix: Report Raft heartbeat metrics for Zero v=3 logs and log read index.

- dgraph/cmd/alpha/run.go
- worker/config.go
- worker/server_state.go
- x/x.go
Motivation
Currently, badger.compression_level flag is used to set compression level for Postings directory. Compression Level for WAL directory is set to None by default.
This PR adds functionality to set compression levels of each directory separately using a comma separated badger.compression_level flag.
Related discuss issue: https://discuss.dgraph.io/t/separate-dgraph-compression-level-config-for-p-and-w-directories/9938
Components affected by this PR:
Dgraph alpha
Does this PR break backwards compatibility?:
No
Fixes DGRAPH-2380
(cherry picked from commit 601cc3b39ab018c3ac751d955f2508d7eebfc880)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6419)
Docs Preview: …
> release/v1.2 - Feat(Dgraph): Add separate compression flag for z and wal dirs (#6401)

- worker/groups.go
Fixes DGRAPH-2466
We were calling closer.Done() twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6551)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b524e3fdc5-95420.surge.sh)
> fix(shutdown): Fix negative waitgroup error

- wiki/content/enterprise-features/binary-backups.md
Binary Backup Update
* Cleaned up MinIO GCS gateway area
* Added new MinIO Azure gateway area
* Added notes about AWS credentials not needed starting with `v20.07.0`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6520)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-86275a4930-95517.surge.sh)
> Doc: binary backup update for gcs, azure, aws

- wiki/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6477)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-37dd329db8-94267.surge.sh)
> fix(docs): Allow more levels for right toc

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6498)
Docs …
> docs: Update Hugo config for v1.0.6 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6500)
Docs …
> docs: Update Hugo config for v1.0.7 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6501)
Docs …
> docs: Update Hugo config for v1.0.8 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6502)
Docs …
> docs: Update Hugo config for v1.0.9 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6496)
Docs …
> docs: Update Hugo config for v1.2.2. (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6515)
Docs …
> docs: Update Hugo config for v1.2.1 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6514)
Docs …
> docs: Update Hugo config for v1.2.0 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6513)
Docs …
> docs: Update Hugo config for v1.1.1 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6512)
Docs …
> docs: Update Hugo config for v1.1.0 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6511)
Docs …
> docs: Update Hugo config for v1.0.18 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6510)
Docs …
> docs: Update Hugo config for v1.0.17 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6509)
Docs …
> docs: Update Hugo config for v1.0.16 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6508)
> docs: Update Hugo config for v1.0.15 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6507)
Docs …
> docs: Update Hugo config for v1.0.14 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6506)
Docs …
> docs: Update Hugo config for v1.0.13 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6505)
Docs …
> docs: Update Hugo config for v1.0.12 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6504)
Docs …
> docs: Update Hugo config for v1.0.11 (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6495)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-78156635b1-94575.surge.sh)
> docs: Update Hugo config for v20.03

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6494)
Docs …
> docs: Update Hugo config for v20.03.0. (#5337)

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6493)
Docs …
> docs: Cherry pick hugo config upgrade 20.03.3

- wiki/config.toml
- wiki/scripts/build.sh
Changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6503)
Docs …
> docs: Update Hugo config for v1.0.10 (#5337)

- posting/list.go
If `deleteBelowTs` is not zero `it.uidPosting` won't be intialized in `pitr.init()`. This could cause panic when we are doing `pitr.posting()`. Our assumption was that `piter.valid()` would return false in such cases. This assumption might not always be true. If `it.uids` is empty, we try to move to next valid part of the list. In the function `moveToNextPart` we are intitializing many components of pIterator but not `uidPosting`. If `it.uids` is filled here, `piter.valid()` would become true and we
would end up into a panic at `pitr.posting()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6560)
> Initialize posting list in moveToNextPart

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/bulk/run.go
Fixes DGRAPH-2135
All UT pass.
This adds a new flag `--encrypted_out` to bulk loader. Now, when bulk loading with encryption input or output, you must set both the `--encrypted` and `--encrypted_out` flags along with the encryption key. Otherwise, it's an error.
For example, to bulk load encrypted input data and output unencrypted data:
dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file ./enc-key --encrypted=true --encrypted_out=false
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6541)
> feat(bulk): Allow encrypted input with unencrypted output in bulk.

- wiki/content/howto/concurrent-modification-java-multithreaded.md
This PR adds a how-to article on concurrent modifications using Java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6438)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-bfbe2101f0-93791.surge.sh)
> docs: How-to article on concurrent modifications and txn aborts.

- dgraph/cmd/debug/run.go
- dgraph/cmd/debug/wal.go
- dgraph/cmd/raft-migrate/run.go
- dgraph/cmd/raft-migrate/storage.go
- dgraph/cmd/root.go
This PR also fixes the debug tool to support old and new raft format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6575)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0b4a98e598-96501.surge.sh)
> feat(raftmigrate): Add tool to migrate from old raft format to new one

- dgraph/cmd/alpha/run.go
- edgraph/server.go
- x/config.go
Currently we don't have any limitation on number of NQuads that can be present in single mutations request.
This is creating OOM issues in some case. Specially in case of upserts, where we combine results from queries and use them
in mutations. In some case we have seen numbers of NQuads after expansion to be as large as 1 billion.
This PR introduces as way to limit those via option called `mutations_nquad_limit`. Default value for it is 1M.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6561)
> feat(mutations): Introducte mutatoinsNquadLimit

- wiki/content/tutorial-4/index.md
In the language tags examples, the "comment" column has been erroneously listed as "name".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6064)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e3141a36e6-82003.surge.sh)
> fix(docs): Fix error in language tags example table

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
Fixes GRAPHQL-335.
This PR fixes incorrect linking of objects with `hasInverse`. For example
For this schema, `type Country` has field `state` with `hasInverse` predicate.
```
type Country {
id: ID!
name: String! @search(by: [trigram, hash])
states: [State] @hasInverse(field: country)
}
type State {
id: ID!
xcode: String! @id @search(by: [regexp])
name: String!
capital: String
country: Country
}
```
And for the following mutation
```
mutation addCountry($input: [AddCountryInput!]!) {
addCountry(input: $input) {
country {
name
states{
xcode
name
country{
name
}
}
}
}
}
```
with `input`:
```
{
"input": {
"name": "A Country",
"states": [
{
"xcode": "abc",
"name": "Alphabet"
},
{
"xcode": "def",
"name": "Vowel",
"country": {
"name": "B country"
}
}
]
}
}
``` 
should result in 
```
{ …
```
> Fix(GraphQL): fix object Linking with `hasInverse`

- schema/schema.go
Fixes DGRAPH-2370
If index building fails for some reason after starting building indexes, no new schema mutations 
can take place. It throws out `errIndexingInProgress` error. This is because though the schema 
update has failed, the predicate remains in the `mutSchema`. It should be deleted from the map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6583)
> fix ErrIndexingInProgress if schema update fails

- graphql/admin/admin.go
- graphql/resolve/middlewares.go
Fixes GRAPHQL-352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6562)
> feat(graphql): GQL Logging MW for admin query/mutation

- conn/node_test.go
- dgraph/cmd/zero/run.go
- go.mod
- go.sum
- raftwal/storage.go
- raftwal/storage_test.go
- worker/draft_test.go
- worker/server_state.go
This PR changes how we use badger in the wal store. Currently we run
badger in normal mode for `w` and `zw` store. We've seen up to 900K
entries for the same hard state (hs) key in `zw` store. These duplicate
keys cause spikes in read latencies in `zw`. The `w` store has more
compactions compared to `zw` store and so it has lesser stale data and
thus lesser spikes in read latencies.
The fix here is to open the `w` and `zw` directories in managed mode and
perform all writes on the same timestamp (max version in the db). This
leads to close to 0 duplicates in the store.
This PR also fixes the raft leader election issue which is a result of high
read latencies.
(cherry picked from commit 6882e377d24f8c89c9a426b1011c24334d2e7c3a)
--- …
> release/v1.2 - perf(raft): Use raft storage in managedmode (#6457)

- x/x.go
This PR adds `Content-Length` header to the response of queries sent via HTTP.
Fixes DGRAPH-1675
(cherry picked from commit ed63786522c9539059d2131750327fa1bfcfee6c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6480)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a12f6c239c-94309.surge.sh)
> release/v20.07 - chore(query): Return content length header for queries (#6469)

- x/x.go
This PR adds `Content-Length` header to the response of queries sent via HTTP.
Fixes DGRAPH-1675
(cherry picked from commit ed63786522c9539059d2131750327fa1bfcfee6c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6479)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-54a3bbfca3-94302.surge.sh)
> release/v20.03 - chore(query): Return content length header for queries (#6469)

- dgraph/cmd/alpha/http.go
This PR adds `Content-Length` header to the response of queries sent via HTTP.
Fixes DGRAPH-1675
(cherry picked from commit ed63786522c9539059d2131750327fa1bfcfee6c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6478)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d9836ff78a-94295.surge.sh)
> release/v1.2 - chore(query): Return content length header for queries (#6469)

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/bulk/run.go
Bulk loader uses caches in compression and this PR adds flags to make it
configurable.
Bulk loader was setting compressionLevel but not the compression option.
As a result of this, badger wasn't compressing any data. This PR fixes
this setting compression if compressionLevel is greater than 0.
(cherry picked from commit 99341dc9f707e76b04006321acefaec4d869a000)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6467)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-8ef4b49ae4-94005.surge.sh)
> release/v20.07 - fix(bulkLoader): Use flags for cache (#6322)

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/bulk/run.go
Bulk loader uses caches in compression and this PR adds flags to make it
configurable.
Bulk loader was setting compressionLevel but not the compression option.
As a result of this, badger wasn't compressing any data. This PR fixes
this setting compression if compressionLevel is greater than 0.
(cherry picked from commit 99341dc9f707e76b04006321acefaec4d869a000)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6466)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5ff3e7ee52-93998.surge.sh)
> release/v20.03 - fix(bulkLoader): Use flags for cache (#6322)

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/bulk/run.go
Bulk loader uses caches in compression and this PR adds flags to make it
configurable.
Bulk loader was setting compressionLevel but not the compression option.
As a result of this, badger wasn't compressing any data. This PR fixes
this setting compression if compressionLevel is greater than 0.
(cherry picked from commit 99341dc9f707e76b04006321acefaec4d869a000)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6465)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-db5140a500-93985.surge.sh)
> release/v1.2 - fix(bulkLoader): Use flags for cache (#6322)

- systest/group-delete/docker-compose.yml
Related to DGRAPH-2455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6586)
> test: Update docker-compose file for group delete test.

- graphql/admin/endpoints_ee.go
- wiki/content/enterprise-features/binary-backups.md
Related to DGRAPH-1648.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6471)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-dbd9403eb8-94131.surge.sh)
> docs: Document backupNum field in restore endpoint.

- contrib/integration/bank/main.go
This exposes an HTTP port for pprof information in the bank test. This is configurable via the `-http` config option. By default, it is set to localhost:6060.
When the bank test starts, it will first log the address/port for pprof:
```
2020/09/23 14:25:06 Listening for /debug HTTP requests at address: localhost:6060
```
Using `go tool pprof`, you can collect pprof information during the bank test.
CPU profile for 10 seconds (save to file and spit out `-text` output):
```text
$ go tool pprof -text 'localhost:6060/debug/pprof/profile?seconds=10s'       
Fetching profile over HTTP from http://localhost:6060/debug/pprof/profile?seconds=10s
Saved profile in /home/dmai/pprof/pprof.bank.samples.cpu.002.pb.gz
File: bank
Build ID: f273cd7e6dbe3988ad3ec0c578ea5a2ca0d22640
Type: cpu
Time: Sep 23, …
```
> chore(contrib): Expose pprof in bank test.

- wiki/content/deploy/monitoring.md
The following flag `-config.file` should have double hyphen (`--`) instead of one. The correct flag is `--config.file`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6301)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d84e63bf74-89216.surge.sh)
> docs: promethus command typo fix

- wiki/content/deploy/metrics.md
added `dgraph_max_assigned_ts` metric to the list of metrics availalbe in `prometheus_metrics` endpoint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6140)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-93b8a6b991-84382.surge.sh)
> docs: added alpha ts metric

- wiki/content/tips/index.md
`checkpwd` boolean becomes a `0` or `1` when used with `val()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5631)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-472648e9ee-70031.surge.sh)
> docs: checkpwd using val()

- wiki/content/tutorial-5/index.md
fixed typo in `term` index description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5496)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4117c361ae-65834.surge.sh)
> docs: fix typo in term index description

- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- wiki/content/graphql/schema/reserved.md
This is related to GRAPHQL-564. as is Dgraph reserved keyword. It's being used by DQL to identify variables. This PR is to restrict the naming for fields with the name as.
Though interesting things have been found while working on this. There is a difference in how we check as keyword while query parsing. For example, in normal DQL queries, the parser uses this strings.ToLower(peekIt[0].Val) == "as" (dgraph/gql/parser.go:2552) this means as, As, AS, aS all are the same.
But while parsing facets, its been treated like this !trySkipItemVal(it, "as") (dgraph/gql/parser.go:1984).
Though having a different use case, keyword significance is the same. Would love to hear thoughts about these implementations.
--- …
> fix (graphql): disallowing field names with as

- dgraph/cmd/zero/zero.go
If we don't do that, the next node that starts with an ID of zero
(auto-assign) will be assigned an existing ID.
DGRAPH-2496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6576)
> Update nextRaftId when starting a node with a raftId > 0.

- worker/server_state.go
This is related to DGRAPH-2225. While exploring one issue, a crash was reported and it's been logged without log level. To have better clarity this has been fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6585)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c301ac7858-97395.surge.sh)
> fix(dgraph): correcting crash log level

- x/x_test.go
Second argument for ToHex was missing in the test.
INFO: Running test for github.com/dgraph-io/dgraph/x
...
x/x_test.go:163:41: not enough arguments in call to ToHex
have (number)
want (uint64, bool)
x/x_test.go:164:41: not enough arguments in call to ToHex
have (number)
want (uint64, bool)
x/x_test.go:165:42: not enough arguments in call to ToHex
have (number)
want (uint64, bool)
x/x_test.go:166:42: not enough arguments in call to ToHex
FAIL	github.com/dgraph-io/dgraph/x [build failed]
have (number)
want (uint64, bool)
x/x_test.go:167:56: not enough arguments in call to ToHex
have (number)
want (uint64, bool)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6600)
> test: Fix ToHex test.

- dgraph/cmd/alpha/metrics_test.go
- x/metrics.go
This PR renames the metric `txn_aborts` to `txn_aborts_total` to be compliant with naming guidelines from Prometheus (ref. https://prometheus.io/docs/practices/naming/).
```bash
SRC_PATH=${GOPATH}/src/github.com/dgraph-io/dgraph/
cd $SRC_PATH
git checkout joaquin/txn-abort-metric-rename
make 
cd dgraph/
docker-compose up --detach
cd cmd/alpha
go test -v -run TestMetricTxnAborts
```
```
Using z.Allocator with starting ref: a3f5000000000000
=== RUN   TestMetricTxnAborts
--- PASS: TestMetricTxnAborts (0.07s)
PASS
ok  	github.com/dgraph-io/dgraph/dgraph/cmd/alpha	0.181s
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6606)
> Fix(metric): rename txn_aborts to txn_aborts_total

- graphql/e2e/common/fragment.go
- graphql/resolve/resolver.go
- graphql/schema/wrappers.go
For queries like 
```
queryCharacter {
name
... on Human {
name
totalCredits
}
... on Droid {
name
primaryFunction
}
}
```
Dgraph response includes the field `name` multiple times. This change fixes that by keeping a `map` of the fields already seen and removing them from the response.
This PR fixes: GRAPHQL-638
Query response for query on fragments in GraphQL
Yes
Added following tests in:
In `fragments.go` tests are added to check that repeated fields are not present in the response and order is preserved.
Fixes GRAPHQL-638
https://github.com/99designs/gqlgen/issues/1300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6596)
> fix(GraphQL Query): Remove extra fields when querying interfaces

- graphql/e2e/custom_logic/docker-compose.yml
Running `./test.sh -C graphql` in the `dgraph` repository leaves `dgraph_mock_1` container dangling. This PR fixes that.
Related to GRAPHQL-560.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6595)
> fix(GraphQL): fix dangling containers in Custom Cluster tests related to GraphQL

- worker/snapshot.go
Possible fix for DGRAPH-2349. I think rollups happening in the leader while the snapshot
streaming is happening might be causing issues. Rollups cause previous versions to be
marked as discarded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6282)
> Pause rollups during snapshot streaming.

- worker/draft_test.go
These tests weren't compiling.
$ go test -c
./draft_test.go:61:20: too many arguments in call to raftwal.Init
have (*badger.DB, number, number)
want (string)
./draft_test.go:61:20: cannot use db (type *badger.DB) as type string in argument to raftwal.Init
./draft_test.go:62:10: ds.Closer undefined (type *raftwal.DiskStorage has no field or method Closer)
`TestCalculateSnapshot` now runs and passes:
```
$ go test -v . -run=TestCalculateSnapshot
Using z.Allocator with starting ref: e502000000000000
badger 2020/10/01 02:41:53 INFO: All 0 tables opened in 0s
badger 2020/10/01 02:41:53 INFO: No head keys found
=== RUN   TestCalculateSnapshot
--- PASS: TestCalculateSnapshot (0.03s)
PASS
ok  	github.com/dgraph-io/dgraph/worker	0.107s
```
Not really …
> test: Fix raftwal tests.

- wiki/content/slash-graphql/admin/clone.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6622)
> docs: add documentation for clone backend

- dgraph/cmd/alpha/run.go
This flag is not needed anymore since we have changed Dgraph to
subscribe to ACL updates instead of polling for updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6614)
> fix(Dgraph): Remove acl_cache_ttl flag.

- posting/writer_test.go
`i` is of type `int`, but is being converted to a string using `string(i)` - which is incorrect. I've changed this to `fmt.Sprint(i)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6619)
> test: Fix integer to string conversion in writer_test

- go.mod
- go.sum
Updates the version of Badger so that the stream framework has
parallelism even when there's only one table.
Fixes DGRAPH-2509
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6589)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-07de6a5bd1-98376.surge.sh)
> fix(Dgraph): Generate more than one split in stream framework.

- systest/group-delete/group_delete_test.go
- testutil/zero.go
The test and utility were assuming that node 1 was in group 1, node 2 in
group 2, and so on. This is not true all the time, hence the flakiness.
Fixing the code to not make this assumptions as well as retrying the
DropAll in NodesSetup to ensure all the nodes are up before proceeding
with the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6624)
> test: Fix flakiness in group_delete_test.go

- dgraph/cmd/root_ee.go
- ee/backup/run.go
- worker/export.go
- worker/file_handler.go
This utility allows to take a single backup (full or incremental) and export the data
and the schema inside it to RDF. Encrypted backups are supported.
Fixes DGRAPH-2465
(cherry picked from commit 369a5c11d5ce0d8e8ac4e29f085baf5f016c4993)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6590)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-75586b752e-97145.surge.sh)
> (release/v20.07): feat(Dgraph): add utility to export backup data.

- contrib/docker-build/Makefile
- contrib/docker-build/README.md
- contrib/docker-build/build.sh
- contrib/docker-build/docker-compose.yml
The script is useful for situations in which the host system creates a
binary that's incompatible with the docker container (e.g different
versions of glibc).
(cherry picked from commit c7897381637dc898ce694aa2060116e6bfedb3ee)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6601)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4c0c912c26-97523.surge.sh)
> (release/v20.07) build: Makefile to build Dgraph inside docker container

- worker/snapshot.go
(cherry picked from commit b777913c05e2b3eae05a2d2db392961edc812acd)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6610)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-58013f8935-97963.surge.sh)
> (release/v20.03) Pause rollups during snapshot streaming.

- worker/snapshot.go
(cherry picked from commit b777913c05e2b3eae05a2d2db392961edc812acd)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6611)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ef895d351b-97970.surge.sh)
> (release/v20.07) Pause rollups during snapshot streaming.

- systest/group-delete/group_delete_test.go
- testutil/zero.go
The test and utility were assuming that node 1 was in group 1, node 2 in
group 2, and so on. This is not true all the time, hence the flakiness.
Fixing the code to not make this assumptions as well as retrying the
DropAll in NodesSetup to ensure all the nodes are up before proceeding
with the test.
(cherry picked from commit 36638a79143c1c318be47d3fd1dcfabd797a941b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6626)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c9e68ddef8-98428.surge.sh)
> (release/v20.07) test: Fix flakiness in group_delete_test.go

- systest/group-delete/group_delete_test.go
- testutil/zero.go
The test and utility were assuming that node 1 was in group 1, node 2 in
group 2, and so on. This is not true all the time, hence the flakiness.
Fixing the code to not make this assumptions as well as retrying the
DropAll in NodesSetup to ensure all the nodes are up before proceeding
with the test.
(cherry picked from commit 36638a79143c1c318be47d3fd1dcfabd797a941b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6627)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e5c9113e84-98434.surge.sh)
> (release/v1.2) test: Fix flakiness in group_delete_test.go

- contrib/docker-build/Makefile
- contrib/docker-build/README.md
- contrib/docker-build/build.sh
- contrib/docker-build/docker-compose.yml
The script is useful for situations in which the host system creates a
binary that's incompatible with the docker container (e.g different
versions of glibc).
(cherry picked from commit c7897381637dc898ce694aa2060116e6bfedb3ee)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6603)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-990263c7d3-97538.surge.sh)
> (release/v1.2) build: Makefile to build Dgraph inside docker container.

- contrib/docker-build/Makefile
- contrib/docker-build/README.md
- contrib/docker-build/build.sh
- contrib/docker-build/docker-compose.yml
The script is useful for situations in which the host system creates a
binary that's incompatible with the docker container (e.g different
versions of glibc).
(cherry picked from commit c7897381637dc898ce694aa2060116e6bfedb3ee)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6602)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-49800ba573-97530.surge.sh)
> (release/v20.03) build: Makefile to build Dgraph inside docker container

- dgraph/cmd/root_ee.go
- ee/backup/run.go
- worker/export.go
- worker/file_handler.go
This utility allows to take a single backup (full or incremental) and export the data
and the schema inside it to RDF. Encrypted backups are supported.
Fixes DGRAPH-2465
(cherry picked from commit 75586b752e47efb4a3af9b41de9dcf3b2b7f7225)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6591)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-42b600b9e9-97157.surge.sh)
> (release/v20.03): feat(Dgraph): add utility to export backup data.

- dgraph/cmd/zero/raft.go
* created common function for proposing a new cid
* checking for CID in entries
* checking for CID in entries and proposing a new one if not found
* changed a comment
* proposing CID until there is no CID is assigned to it instead of proposing CID infinitely (useful in the case when a restarted node is joining a cluster)
(cherry picked from commit 09ef988fa53e84c75455dec0dac43284ba89ed59)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6637) …
> CID never created if Zero stops early after first init (#5719)

- systest/group-delete/group_delete_test.go
- testutil/zero.go
The test and utility were assuming that node 1 was in group 1, node 2 in
group 2, and so on. This is not true all the time, hence the flakiness.
Fixing the code to not make this assumptions as well as retrying the
DropAll in NodesSetup to ensure all the nodes are up before proceeding
with the test.
(cherry picked from commit 36638a79143c1c318be47d3fd1dcfabd797a941b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6625)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-76872d8cb7-98420.surge.sh)
> (release/v20.03) test: Fix flakiness in group_delete_test.go

- dgraph/cmd/zero/zero.go
If we don't do that, the next node that starts with an ID of zero
(auto-assign) will be assigned an existing ID.
DGRAPH-2496
(cherry picked from commit a4f21f45b2cc06c6816b09bfcd26e9dcb3a8aa55)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6599)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e1fa48a1b4-97433.surge.sh)
> (release/v1.2) Update nextRaftId when starting a node with a raftId > 0.

- systest/license/docker-compose.yml
- systest/license/license_test.go
Created a file for testing if the license is applied correctly. It contains 3 tests.
1. Applying expired license, this will get applied but it should not be enabled and user information should be extracted
2. Applying invalid license, this won't get applied
3. Applying empty license, this also won't get applied
Co-authored-by: Ibrahim Jarif <ibrahim@dgraph.io>
(cherry picked from commit 61363d1837b929d04fe988af40b888e9f82370ea)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6641) …
> test: Enterprise License tests (#5822)

- query/query.go
- query/query1_test.go
Pagination param "after" does not work when using func: uid(v)
for query
```
{
var(func: has(name@en), first: 50) {
test as uid
}
ss(func: uid(test), first: 2, after: 0x6) {
uid
}
}
```
the response was
```
{
"data": {
"ss": [
{
"uid": "0x4"
},
{
"uid": "0x6"
}
]
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6631)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-70fd76f0af-98614.surge.sh)
> Pagination param "after" does not work when using func: uid(v) (#6365)

- dgraph/cmd/zero/zero.go
If we don't do that, the next node that starts with an ID of zero
(auto-assign) will be assigned an existing ID.
DGRAPH-2496
(cherry picked from commit a4f21f45b2cc06c6816b09bfcd26e9dcb3a8aa55)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6598)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-976fdab4bf-97421.surge.sh)
> (release/v20.03) Update nextRaftId when starting a node with a raftId > 0

- dgraph/cmd/zero/zero.go
If we don't do that, the next node that starts with an ID of zero
(auto-assign) will be assigned an existing ID.
DGRAPH-2496
(cherry picked from commit a4f21f45b2cc06c6816b09bfcd26e9dcb3a8aa55)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6597)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-af79b88085-97418.surge.sh)
> (release/v20.07) Update nextRaftId when starting a node with a raftId > 0

- go.mod
- go.sum
- graphql/e2e/common/fragment.go
- graphql/schema/schemagen_test.go
Motivation:
gqlgen is an external module used by Dgraph for parsing graphql queries. It had the following issue: 99designs/gqlgen#1299 .
The issue was fixed with 99designs/gqlgen#1341 .
Changing the gqlgen version in go.mod .
Also added a test to verify if the issue is solved in gqlgen.
Fixes GRAPHQL-637
(cherry picked from commit f19d882368ad9fbdb357ff0ac5a20d721a1f9a7e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6646)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-500a02f369-99032.surge.sh)
> release/v20.07 - fix(gqlgen): Update gqlgen in go.mod (#6594)

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6648)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a904c6093c-99099.surge.sh)
> release/20.07: Fix(GraphQL): fix object Linking with `hasInverse`

- wiki/content/enterprise-features/binary-backups.md
- wiki/content/graphql/admin/index.md
This PR updates documentation for the `/admin` endpoint operation and  `restore` operation.
(cherry picked from commit 288eafbe97e125de96feca8f75d3d15cc158af36)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6527)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-fa94154509-94912.surge.sh)
> cherry-pick v20.07: doc: update /admin endpoint documentation. (#6415)

- graphql/e2e/common/fragment.go
GRAPHQL-654 has been fixed in https://github.com/dgraph-io/dgraph/pull/6596, this PR simply adds a test for it. The problem occurring was that using multiple fragments containing the same field would cause that field to appear multiple times in the output. Example:
Query:
```graphql
fragment TaskID on Task {
remoteId: id
remoteType: __typename
}
fragment Task on Task {
title
remoteId: id
completed
}
query {
queryTask {
...TaskID
...Task
}
}
```
Schema:
```graphql
type Task {
id: ID!
title: String!
completed: Boolean!
}
```
The resultant JSON listed `remoteId` twice, which was a bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6623)
> test: Duplicate fields in queries with fragments

- graphql/e2e/common/fragment.go
- graphql/resolve/resolver.go
(cherry picked from commit cec55674cb343c1c7f3e96dd9c5fe7867a42f5b8)
This PR fixes: GRAPHQL-638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6647)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-215f7c95aa-99056.surge.sh)
> fix(GraphQL Query): Remove extra fields when querying interfaces (#6596)

- go.mod
- graphql/authorization/auth.go
- graphql/authorization/utils.go
- graphql/resolve/auth_test.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers_test.go
- testutil/graphql.go
Fixes GRAPHQL-693.
This PR extends support for authorization with `jwk_url`. Now users can give `jwkUrl` for their project in the `Dgraph.Authorization` JSON in their schema.
```
#Dgraph.Authorization 
{"VerificationKey":"",
"Header":"header",
"Namespace":"your-namespace",
"jwkurl": "your-jwk-url-",
"Algo":"",
"Audience":["your-audience"]
}
```
When `jwkurl` is provided, keep `VerificationKey` and `Algo` empty as they are not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6564)
> feat(GraphQL): Support authorization with jwk_url

- wiki/content/enterprise-features/binary-backups.md
- Explicitly differentiate between online and offline restores.
- Add more details about the online restores.
(cherry picked from commit 014ee10447cd81e47a35f36120fe470def9572d1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6653)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-4006cceac4-99382.surge.sh)
> (release/v20.07) docs: Update restore documentation.

- query/shortest.go
The k-shortest path query sometimes returns a wrong response. The cause
of this issue is inappropriate use of sync.pools. Whenever a valid path
is found a new variable is assigned with this route and that variable is
appended in the kroutes (which is then parsed to produce response).
But the route is also put in the sync.pool. Since the route is a
structure containing a pointer to slice along with other fields, when
it is fetched back from the pool in future then any mutation on this fetched
route causes modification in the kroutes, resulting in garbage response.
This issue is fixed by making a copy of the route struct rather
than just assigning it to a variable, which causes a shallow copy.
(cherry picked from commit 4792d8b1c4391a08ce2627f9615ed12699f2885f)
--- …
> fix(Query): Fix wrong path response for k-shortest paths (#6437)

- systest/cluster_setup_test.go
TestPlugins is flaky in because it sometimes tries to connect to the cluster while the cluster is still not up. 
This PR fixes: DGRAPH-1637
TestPlugins, Systest
No
N/A
Fixes DGRAPH-1637
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6652)
> fix(TestPlugins) Increase sleep timer to prevent connection retries on sleeping cluster

- gql/parser.go
- gql/parser_test.go
ParseID function would panic if the input consists of only whitespace characters. This PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6615)
> fix(gqlParser): Handle strings with only whitespace in parseID

- graphql/admin/schema.go
- graphql/schema/gqlschema.go
- graphql/schema/schemagen.go
- graphql/schema/schemagen_test.go
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-all-empty.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-circular.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-custom-mutation.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-directLink.graphql
- graphql/schema/testdata/schemagen/input/hasInverse-with-interface-having-directive.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
Fixes GRAPHQL-714
Reverts dgraph-io/dgraph#6587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6666)
> Feat(GraphQL): This PR add enable schema cleaning in GraphQL and reduce schema update time.

- worker/groups.go
Fixes DGRAPH-2523
(cherry picked from commit a8a47af407ce51c39d15777fb942829e5e80f537)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6676)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b12cea7675-100038.surge.sh)
> release/v20.03 - Break out if g.Ctx is done

- worker/groups.go
Fixes DGRAPH-2523
(cherry picked from commit a8a47af407ce51c39d15777fb942829e5e80f537)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6675)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-7b20092536-100032.surge.sh)
> release/v20.07 - Break out if g.Ctx is done

- worker/groups.go
Fixes DGRAPH-2523
(cherry picked from commit a8a47af407ce51c39d15777fb942829e5e80f537)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6677)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5bd111b00c-100046.surge.sh)
> release/v1.2 - Break out if g.Ctx is done

- systest/export/export_test.go
- worker/export.go
If they are not surrounded by brackets, type names with special
characters will not be able to be imported to a new DB.
Fixes DGRAPH-2462.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6656)
> Fix(Dgraph): Type names in exported schema are sorrounded by brackets.

- dgraph/cmd/root.go
This fixes setting glog's `v` config option when set via a [config file](https://dgraph.io/docs/deploy/config) (e.g., YAML).
This change reads all glog config values as strings and then sets them accordingly. Before, we were only setting values that could correctly be cast as a string (`conf.Get(gflag).(string)`). Any non-string values were _ignored_.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6678)
> fix(config): Set glog -v flag correctly from config files.

- wiki/content/enterprise-features/binary-backups.md
Fixes DGRAPH-2547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6663)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-114987b630-99640.surge.sh)
> docs: Document listBackups GraphQL endpoint.

- dgraph/cmd/alpha/admin.go
- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/login_ee.go
- dgraph/cmd/alpha/run.go
- dgraph/docker-compose.yml
- edgraph/server.go
- graphql/e2e/admin_auth/admin_auth_test.go
- graphql/e2e/admin_auth/docker-compose.yml
- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/web/http.go
- x/x.go
Fixes DGRAPH-2419
Fixes [Discuss Issue](https://discuss.dgraph.io/t/acl-login-will-fail-if-auth-token-enabled-in-v20-07-0/10044)
This PR fixes Poor-man's auth for following endpoints:
* `/login`
* `/admin`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6660)
> fix(Auth): fix Poor-man's auth for admin operations

- dgraph/cmd/alpha/admin.go
- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/login_ee.go
- dgraph/cmd/alpha/run.go
- edgraph/server.go
- graphql/e2e/admin_auth/admin_auth_test.go
- graphql/e2e/admin_auth/docker-compose.yml
- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/web/http.go
- x/x.go
Fixes DGRAPH-2419
Fixes [Discuss Issue](https://discuss.dgraph.io/t/acl-login-will-fail-if-auth-token-enabled-in-v20-07-0/10044)
This PR fixes Poor-man's auth for following endpoints:
* `/login`
* `/admin`
(cherry picked from commit 4fc328d7c4fcd3264f7bcf2330a01cd6882cbd72)
\# Conflicts:
\#	graphql/e2e/common/common.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6686)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-edf0eea3ac-100314.surge.sh)
> cherry-pick v20.07: fix(Auth): fix Poor-man's auth for admin operations (#6660)

- graphql/e2e/common/query.go
This PR slightly modifies `e2e` test for in filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6702)
> fix(GraphQL): fix e2e test for in filter

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/bulk/run.go
Like #6616, add a `--badger.compression` flag to `dgraph bulk` which allows changing
the compression algorithm.
This changes the default from Zstd (level 1) to Snappy.
$ dgraph bulk --help
...
Flags:
...
--badger.compression string        [none, zstd:level, snappy] Specifies the compression algorithm and the compressionlevel (if applicable) for the postings directory. none would disable compression, while zstd:1 would set zstd compression at level 1. (default "snappy")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6697)
> [BREAKING/cli-flags] feat(bulk): Use snappy compression by default.

- wiki/content/deploy/kubernetes.md
Fix a link from the "Removing a Dgraph Pod" Kubernetes section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6705)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0a3ee51f08-100873.surge.sh)
> docs: Fix link to More about Dgraph Zero page.

- dgraph/cmd/bulk/reduce.go
We should close the stream after we're done in the bulk loader, so we're not holding onto those tables. Otherwise, these tables are kept around and use up a lot of memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6710)
> opt(bulk): Close the stream after done

- graphql/resolve/auth_test.go
This PR modifies the` jwkUrl` test case as the `kid` of the minted token used in the test case is not available anymore at hosted`jwkurl`, so the expected error should be different now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6712)
> fix(GraphQL): modify jwkUrl test case

- wiki/content/query-language/functions.md
Updates to functions.md to document the `between` function:
- Noted the usage and types supported
- Provided a syntax example that should be correct (but that causes errors on the site in the "runnable" context because `between` is not yet available in production)
@pawanrawal and @minhaj-shakeel , please let me know if we need to add any caveats or other notes.
fixes DGRAPH-2538
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6711) …
> Docs(DQL)Document the `between` function

- wiki/content/deploy/dgraph-administration.md
- wiki/content/query-language/schema.md
* https://dgraph.io/docs/deploy/dgraph-administration/ now has missing content from PR 5842 (wiki/content/deploy/index.md) 
* https://dgraph.io/docs/query-language/schema/ now has missing content from PR 5842 (wiki/content/query-language/index.md)
Fixes DGRAPH-2235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6709)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d90fe5bc19-101047.surge.sh)
> Docs (Authentication):Fix for DGRAPH-2235 to restore missing admin authentication docs deleted by split-pages Docs PR

- query/query0_test.go
- types/compare.go
- worker/task.go
Fixes DGRAPH-2528.
Fixes DGRAPH-2544.
This PR extends the support for `between` filter on non-indexed predicates so that it could be used outside the root also. For example, for the given schema
```
type CarModel {
make
model
year
}
model                          : string @index(term) @lang .
make                           : string @index(term) .
year                           : int .
```
The below query uses between filter on `year` predicate which is non-indexed, should be valid.
```
queryCareModel(func: type(CarModel)) @filter(between(year,2009,2010)){
make
model
year
}
```
This PR also fixes the `eq` filter for more than one argument on the non-indexed predicate which earlier used to compare with just the first of the given arguments for `eq` filter. For eg the below query was not …
> fix(worker): fix between filter for non indexed predicates

- edgraph/access_ee.go
- ee/acl/acl_test.go
- x/x.go
In case of invalid login request we don't reveal info about user. So make error message more generic
Fixes DGRAPH-2468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6716)
> Make ACL login error message more generic

- compose/compose.go
This was the previous behavior of the compose tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6720)
> chore(compose): Set container names by default.

- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
This PR fix panic error when we give null value in filter connectives. Null values corresponding to connective are skipped now.
For example in the below filter, not connective gets skipped.
```
filter:{
id:{eq:"123"},
not:null
},
```
(cherry picked from commit 345b6d1e7e04bf660e3c65b9e63a16266d3e9678)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6736)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-9ab5b0adfd-101906.surge.sh)
> fix(GraphQL): This PR fix panic error when we give null value in filter connectives. (#6707)

- dgraph/Makefile
This sets the flag --with-malloc-conf when installing jemalloc to set the default conf values at runtime. In our case, we're setting:
* background_thread:true
* metadata_thp:auto
Example:
* `sudo rm /usr/local/lib/libjemalloc.a && make install` (install jemalloc)
* `dgraph bulk -f 1million.rdf.gz -s 1million.schema -z localhost:5080`
```
___ Begin jemalloc statistics ___
Version: "5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756"
...
Run-time option settings
...
opt.metadata_thp: "auto"
opt.background_thread: true (background_thread: true)
...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6721)
> build(linux): Set --with-malloc-conf when installing jemalloc.

- wiki/content/slash-graphql/security.md
Fixes GQLSAAS-794
This PR fixes an incomplete note on https://dgraph.io/docs/master/slash-graphql/security/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6730)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-225efbe0eb-101788.surge.sh)
> docs (fix): fixing incomplete Slash security note

- edgraph/access_ee.go
- ee/acl/acl_test.go
- query/mutation.go
- systest/bgindex/count_test.go
- systest/online-restore/online_restore_test.go
- x/x.go
Motivation
Currently, it is possible to delete guardians user group and groot user using a simple graphql query. 
This behaviour causes bad user experience as guardians is the admin group and groot user is the primary admin user. 
Once, the group has been deleted, to get back access to groot user, the user has to restart dgraph alpha again. 
This PR adds fixes this. This PR makes it impossible to delete groot user and guardians group.
Related discuss issue: https://discuss.dgraph.io/t/customers-can-delete-guardians-group-and-lose-access/9614
Components affected by this PR:
Dgraph ACL
Does this PR break backwards compatibility?:
No
Fixes DGRAPH-2454
--- …
> Fix(ACL) : Disallow deleting of groot user and guardians group

- systest/online-restore/online_restore_test.go
Motivation:
Recently, it was observed that the tests TestBasicRestore and TestMoveTablets were failing in TeamCity. This is a temporary fix to unblock users by increasing duration between statusRestore requests.
Fixes DGRAPH-2576, DGRAPH-1740
(cherry picked from commit 7a75b15ad615291d367a15633cd74b54415c44a7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6747)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d3f466bb77-102306.surge.sh)
> Fix(Tests): Fixes failing tests TestBasicRestore and TestMoveTablets

- systest/ludicrous/upsert_test.go
- worker/draft.go
Fixes DGRAPH-2446
We were not updating startTs for upsert mutations properly in ludicrous mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6754)
> fix(Ludicrous): Upserts on list type in Dgraph

- query/common_test.go
- query/query.go
- query/query3_test.go
- query/query4_test.go
Enable queries that can declare filters on predicates while using `expand(_all_)` directive. 
Example: 
```
q(func: eq(name, "Michonne")) {
expand(_all_)
friend @filter(eq(alive, true)){
expand(_all_)
}
}
```
Note: Queries that explicitly ask for scalar predicates while using `expand(_all_)` will continue to throw. 
This PR fixes: DGRAPH-2524
Further discussion: https://discuss.dgraph.io/t/expand-with-predicate-filters/10611
Query Package particularly queries involving `expand(_all_)` directive.
No
Added following tests in:
1. TestFilterAtSameLevelOnUIDWithExpand
Fixes DGRAPH-2524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6752)
> feat(Query): Allow filters in expand(_all_) queries on predicates pointing to nodes

- systest/ludicrous/docker-compose.yml
- systest/ludicrous/upsert_test.go
ludicrous test have been failing in master because --ludicrous_mode option has been removed from the zero initialization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6767)
> fix(test): removing ludicrous mode from the zero init

- systest/ludicrous/upsert_test.go
The tests are currently failing with following  in the CI:
```
Error Trace:	client.go:160
upsert_test.go:47
upsert_test.go:76
Error:      	Received unexpected error:
rpc error: code = Unknown desc = Please retry again, server is not ready to accept requests
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6766)
> fix(test): Add sleep before running ludicrous mode tests

- dgraph/cmd/zero/http.go
- dgraph/cmd/zero/run.go
- go.mod
- go.sum
- tlstest/zero_https/all_routes_tls/all_routes_tls_test.go
- tlstest/zero_https/all_routes_tls/docker-compose.yml
- tlstest/zero_https/custom_routes_tls/custom_routes_tls_test.go
- tlstest/zero_https/custom_routes_tls/docker-compose.yml
- tlstest/zero_https/no_tls/docker-compose.yml
- tlstest/zero_https/no_tls/no_tls_test.go
Enabling TLS based encryption in Dgraph zero. 
Fixes https://dgraph.atlassian.net/browse/DGRAPH-1366. Based on discussion here https://discuss.dgraph.io/t/enabling-tls-configuration-for-internal-ports-making-dgraph-more-secure/10860/2
The same variables are used which needs to be defined for alpha tls configuration
Things to consider:
1. With TLS enabled, tls_enabled_route has to be defined.
2. If defined all routes will be accessible with TLS. But ones mentioned in --tls_enabled_route will not be accessible via HTTP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6691)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588 …
> feat(dgraph): enabling TLS config in http zero

- wiki/content/query-language/schema.md
The PR which provides lists of the predicates which are being indexed has been merged. https://github.com/dgraph-io/dgraph/pull/4961
This PR updates the docs related to that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6448)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-6320a4a8e9-103433.surge.sh)
> update(docs): information regarding merged PR for background indexing

- compose/compose.go
Zero no longer has the `--ludicrous_mode` flag but the compose tool was generating it with this flag. This PR fixes the compose tool so that it doesn't generate `--ludicrous_mode` for zeros.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6772)
> fix(compose): Don't add ludicrous_mode flag to zero

- dgraph/cmd/alpha/run.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6784)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2b6f3a728a-103661.surge.sh)
> release/v20.03 - fix(defaults): Set --cache_mb to 2048 by default

- dgraph/cmd/alpha/run.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6785)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-df1d121bfc-103669.surge.sh)
> release/v20.07 - fix(defaults): Set --cache_mb to 2048 by default

- dgraph/cmd/alpha/run.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6783)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c27e8f2427-103654.surge.sh)
> release/v1.2 - fix(defaults): Set --cache_mb to 2048 by default

- dgraph/cmd/alpha/run_test.go
- dgraph/cmd/bulk/systest/test-bulk-schema.sh
- edgraph/graphql.go
- ee/acl/acl_test.go
- graphql/admin/admin.go
- graphql/e2e/common/admin.go
- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema_response.json
- graphql/e2e/schema/schema_test.go
- graphql/schema/request.go
- graphql/web/http.go
- schema/schema.go
- systest/backup/encryption/backup_test.go
- systest/backup/filesystem/backup_test.go
- systest/backup/minio/backup_test.go
- systest/export/export_test.go
- systest/mutations_test.go
- systest/queries_test.go
- worker/export.go
- x/keys.go
- x/x.go
Enable persistent queries as discussed in [RFC on discuss.](https://discuss.dgraph.io/t/rfc-persistent-queries-and-cached-results/10636)
This PR fixes: GRAPHQL-721
This feature works out-of-the-box with Apollo client for GraphQL
Query package
No
Added following tests in:
-  `persistedQuery` in `common.go`. It is an end-to-end test which checks following cases:
1. If incorrect sha is given throw with `provided sha doesn't match the query`
2. If only sha is given and it is not present in dgraph throw with `PersistedQueryNotFound`
3. If both query and sha are given and they match, then execute query and persis the query-sha pair. Check for no error.
4. Use sha provided in `step iii` to execute the query and check that it throws no error.
5. Do `step iv` via a `GET` request
Fixes GRAPHQL-721 …
> feat(Query): Enable persistent queries in dgraph

- dgraph/cmd/alpha/reindex_test.go
- posting/index.go
Fixes the test OverwriteUidPredicatesReverse added in the previous PR #6746.
When updating a single uid predicate with a reverse index, the existing entry in the
reverse index should be deleted first.
Fixes DGRAPH-1738
(cherry picked from commit 5b70fe8aa2c4dc08f74794b3e9875c8789c11c9f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6748)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-219b04a84c-102333.surge.sh)
> fix(Dgraph): update reverse index when updating single UID predicates.

- wiki/content/query-language/schema.md
- wiki/content/tutorial-3/index.md
Clarified how it's the exact order for both `trigram` and `term` index when specified together in the schema.
Order has to look like:
```
<predicate>: string @index(term, trigram) . 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6800)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d51c41b35b-104613.surge.sh)
> docs: clarify exact order for trigram and term indexes when specified together 

- dgraph/cmd/zero/oracle.go
- dgraph/cmd/zero/run.go
- go.mod
- go.sum
- systest/ludicrous/upsert_test.go
Fixes DGRAPH-2456
This PR uses the mmaped keyCommit map instead of golang map. This map can grow very large if the mutations are very big and `--snapshot-after` flag is large. This can make things slow. Using mmaped B+ tree should fix that.
See [this](https://discuss.dgraph.io/t/seems-to-be-a-memory-leak/10354)
When 21m was live loaded on my machine. On `master` it took 15m18s, while on this branch it took 15m12s. i.e. almost the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6804)
> stability(zero): add mmaped keyCommit map

- wiki/content/query-language/index.md
Clarified how it's the exact order for both trigram and term index when specified together in the schema.
Order has to look like:
```
<predicate>: string @index(term, trigram) . 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6809)
> docs:v20.03 docs trigram term order

- wiki/content/query-language/schema.md
Clarified how it's the exact order for both trigram and term index when specified together in the schema.
Order has to look like:
```
<predicate>: string @index(term, trigram) .
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6808)
> docs:v20.07 docs trigram term order

- gql/parser.go
- gql/parser_test.go
ParseID function would panic if the input consists of only whitespace characters. This PR fixes it.
Fixes GRAPHQL-720
(cherry picked from commit d994cb3d638ba521b0299a8f4ed66155c5ab3ff0)
Conflicts:
gql/parser_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6674)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-3e669a4ce1-100023.surge.sh)
> release/v20.07 - fix(gqlParser): Handle strings with only whitespace in parseID (#6615)

- gql/parser.go
- gql/parser_test.go
ParseID function would panic if the input consists of only whitespace characters. This PR fixes it.
Fixes GRAPHQL-720
(cherry picked from commit d994cb3d638ba521b0299a8f4ed66155c5ab3ff0)
Conflicts:
gql/parser_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6673)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-21da995e7c-100016.surge.sh)
> release/v20.03 - fix(gqlParser): Handle strings with only whitespace in parseID (#6615)

- gql/parser.go
- gql/parser_test.go
ParseID function would panic if the input consists of only whitespace characters. This PR fixes it.
Fixes GRAPHQL-720
(cherry picked from commit d994cb3d638ba521b0299a8f4ed66155c5ab3ff0)
Conflicts:
gql/parser_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6672)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-80cccbfc0d-100008.surge.sh)
> release/v1.2 - fix(gqlParser): Handle strings with only whitespace in parseID (#6615)

- x/tls_helper.go
Fixes DGRAPH-2469.
Currently Dgraph supports both tls v1.1 and tls v1.2 which introduces security concerns. This PR limits the min version to v1.2 and also enables only selected cipher suites which are more secure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6819)
> fix(security): changing min version to v1.2 with some secure cipher suites only

- wiki/content/graphql/queries/search-filtering.md
- wiki/content/query-language/functions.md
Adding documentation for the `between` filter for GraphQL, also minor wording changes to the rest of this page.
Updates to search-filtering.md to document the `between` function in GraphQL:
- Added coverage of the `between` keyword in GraphQL, along with syntax examples from the related code PR (https://github.com/dgraph-io/dgraph/pull/6651)
- Minor rewording throughout
Minor updates to functions.md (DQL) to note that `between` searches in an inclusive range.
@minhaj-shakeel , please let me know if we need to add any caveats or other notes.
Fixes DGRAPH-2607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6813) …
> Docs(GraphQL)Document the `between` function 

- graphql/resolve/mutation_rewriter.go
- graphql/resolve/mutation_test.go
- graphql/resolve/schema.graphql
- graphql/resolve/update_mutation_test.yaml
Fixes GRAPHQL-745.
While doing an updateMutation, when the linked object didn't have an `id` or `xid` our code was panicking. This change fixes that behavior by returning an error instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6810)
> fix(GraphQL): Fix panic caused when trying to delete a nested object which doesn't have id/xid

- graphql/e2e/subscription/subscription_test.go
(cherry picked from commit b4c6a7314fa01fff18f8f190a2cf3078401d54f6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6724)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-45824387da-101664.surge.sh)
> fix(GraphQL): fixes flaky test  for subscriptions.

- graphql/admin/schema.go
- graphql/schema/gqlschema.go
- graphql/schema/schemagen.go
- graphql/schema/schemagen_test.go
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-all-empty.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-circular.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-custom-mutation.graphql
- graphql/schema/testdata/schemagen/input/filter-cleanSchema-directLink.graphql
- graphql/schema/testdata/schemagen/input/hasInverse-with-interface-having-directive.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
(cherry picked from commit 5ab44c453b28a32bb853819f85381b4cbe0c6dd0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6725)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-2dc9b0e9ec-101670.surge.sh)
> Fix(GraphQL): This PR add enable schema cleaning in GraphQL and reduce schema update time.

- edgraph/server.go
- query/mutation.go
- systest/ludicrous/upsert_test.go
- worker/draft.go
In ludicrous mode, we were trying to fetch the list of types (and their
predicates) using a timestamp of 0. This would cause deletes to be
ineffective and the actual data won't be deleted. This PR fixes it.
Co-authored-by: Manish R Jain <manish@dgraph.io>
Fixes - DGRAPH-2593
(cherry picked from commit a0cc3a50d90064919f275d2e30ffc46b58baf7d5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6832)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b3d8514027-106076.surge.sh)
> release/v20.07 - fix(ludicrous mode): Handle deletes correctly (#6773)

- edgraph/server.go
- query/mutation.go
- systest/ludicrous/upsert_test.go
- worker/draft.go
In ludicrous mode, we were trying to fetch the list of types (and their
predicates) using a timestamp of 0. This would cause deletes to be
ineffective and the actual data won't be deleted. This PR fixes it.
Co-authored-by: Manish R Jain <manish@dgraph.io>
Fixes - DGRAPH-2593
(cherry picked from commit a0cc3a50d90064919f275d2e30ffc46b58baf7d5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6831)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-18d952d9ec-106069.surge.sh)
> release/v20.03 - fix(ludicrous mode): Handle deletes correctly (#6773)

- graphql/e2e/schema/schema_test.go
- worker/export.go
FIxes GRAPHQL-747
Fixes [Discuss Issue](https://discuss.dgraph.io/t/multiple-values-for-the-graphql-schema/10881)
This PR fixes the issue where you would get an error, if you first add a GraphQL schema, then delete the GraphQL schema using `<uid> * *` delete mutation and try to export the DB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6815)
> fix(export): don't return an error if there was no GraphQL schema

- edgraph/access_ee.go
- ee/acl/acl_test.go
- x/x.go
(cherry picked from commit c269de85e0c5351290b9af5e1a1d3a6ede94bfd5)
In case of invalid login request we don't reveal info about user. So make error message more generic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6843)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0e64f25d60-106622.surge.sh)
> Make ACL login error message more generic (#6716)

- x/x.go
- x/x_test.go
This fixes a panic that happens when the --my flag has a terminating dot which is
still a hostname we can still technically connect to:
2020/11/04 05:22:12 dgraph-alpha-0.dgraph-alpha-headless.default.svc.:7080 is not valid address
github.com/dgraph-io/dgraph/x.AssertTruef
/ext-go/1/src/github.com/dgraph-io/dgraph/x/error.go:101
github.com/dgraph-io/dgraph/worker.StartRaftNodes
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/groups.go:78
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run.func4
/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:772
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1373
This change updates the ValidHostnameRegex to conform to valid DNS names
as defined in RFC 1035. The exact hostname syntax is covered in Section
[2.3.1. Preferred name …
> fix(x.ValidateAddress): Fix hostname regex check for --my config.

- wiki/content/graphql/schema/types.md
The feature requested here will be ready in 20.11: https://discuss.dgraph.io/t/error-coercing-value-to-type-int/9353/10
Fixes GRAPHQL-782
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6829)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d90b6a5168-106706.surge.sh)
> Docs (GraphQL) Note the addition of Int64 support in 20.11, mention JSON limitations for this type

- contrib/scripts/goldendata-queries.sh
- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/http_test.go
- dgraph/cmd/alpha/reindex_test.go
- dgraph/cmd/alpha/run_test.go
- dgraph/cmd/alpha/upsert_test.go
- dgraph/cmd/bulk/systest/run.sh
- dgraph/cmd/bulk/systest/test-bulk-schema.sh
- ee/acl/acl_curl_test.go
- graphql/admin/add_group.go
- graphql/admin/update_group.go
- graphql/dgraph/graphquery.go
- graphql/resolve/mutation_rewriter.go
- systest/queries_test.go
- wiki/content/clients/raw-http.md
Fixes GRAPHQL-706
This PR Add support for below header in query endpoint
`curl -H "Content-Type: application/dql" "localhost:8080/query"`
We are also keeping support for the old header.
`curl -H "Content-Type: application/graphql+-" "localhost:8080/query"`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6849)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-d4b996c791-106781.surge.sh)
> fix(GraphQL): This PR adds support for "application/dql" in content header. 

- edgraph/access_ee.go
In case of an invalid login request, we don't reveal info about user. So made the error message more generic in alpha logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6848)
> Generic alpha log error message for failed ACL login 

- edgraph/access_ee.go
* In case of an invalid login request, a generic error message will be printed in alpha logs
(cherry picked from commit 7088d59f41f2e176f743a6cc828b21fa8179ba70)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6851)
> Generic alpha log error message for failed ACL login  (#6848)

- wiki/content/howto/migrate-dgraph-1-1.md
Fixed typo: `locahost` --> `localhost`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6855)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c6668afe73-106944.surge.sh)
> docs: fixed localhost typo

- wiki/content/graphql/queries/count.md
- wiki/content/graphql/schema/reserved.md
Motivation:
There were certain changes to how count queries were implemented then what was mentioned in RFC. Specifically the following:
1. Name of Aggregate Fields has been changed to `<name>Aggregate` rather than `aggregate_<name>`
This PR reflects the same. It also adds two types to Reserved Names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6854)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e852dbbb7a-106963.surge.sh)
> Update docs for count queries

- wiki/content/howto/migrate-dgraph-1-1.md
(cherry picked from commit 3d1e3805b163691158dcd48c27b8a9278a49079c)
fixed typo `locahost` --> `localhost`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6856)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0f19d31b53-106952.surge.sh)
> docs: fixed localhost typo (#6855)

- wiki/content/howto/index.md
fixed typo `locahost` --> `localhost`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6857)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-aebaefde41-106962.surge.sh)
> docs: fix localhost typo

- dgraph/cmd/zero/oracle.go
This PR adds `occupancy` of keyCommit B+ tree to the logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6869)
> chore(logs): add occupancy stats of keycommit to logs

- wiki/content/graphql/directives/index.md
The Password Type link from https://dgraph.io/docs/master/graphql/directives/#secret isn't useful. It links to https://dgraph.io/docs/master/graphql/schema/#password-type which provides the sub-menu with no docs for the password type.
This PR fixes this issue, pointing readers to the right location in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6872)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-e9ccf4d62f-107827.surge.sh)
> Docs (chore) fix link to password types from GraphQL Directives page

- graphql/authorization/auth.go
- graphql/resolve/auth_test.go
- testutil/graphql.go
Fixes GRAPHQL-795.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6866)
> fix(GraphQL): make `audience` necessary if `JWKUrl` is provided

- wiki/content/graphql/authorization/authorization-overview.md
- wiki/content/graphql/authorization/directive.md
- wiki/content/graphql/mutations/mutations-overview.md
- wiki/content/graphql/schema/search.md
- wiki/content/graphql/schema/types.md
This PR adds documentation for the GraphQL Union type feature (20.11)
Fixes GRAPHQL-725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6873)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-5ce384719c-107833.surge.sh)
> docs (feature): Add Union type documentation

- worker/export.go
If they are not surrounded by brackets, type names with special
characters will not be able to be imported to a new DB.
Fixes DGRAPH-2462.
(cherry picked from commit 51821f30f9e6b7acd824a96faeca60bcc80d175e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6679)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-0315c625b7-100081.surge.sh)
> (release/v20.07) Fix(Dgraph): Type names in exported schema are surrounded by brackets.

- worker/export.go
If they are not surrounded by brackets, type names with special
characters will not be able to be imported to a new DB.
Fixes DGRAPH-2462.
(cherry picked from commit 51821f30f9e6b7acd824a96faeca60bcc80d175e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6680)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-40fe99ab04-100089.surge.sh)
> (release/v20.03) Fix(Dgraph): Type names in exported schema are surrounded by brackets.

- worker/export.go
If they are not surrounded by brackets, type names with special
characters will not be able to be imported to a new DB.
Fixes DGRAPH-2462.
(cherry picked from commit 51821f30f9e6b7acd824a96faeca60bcc80d175e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6681)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-8014aceabd-100096.surge.sh)
> (release/v1.2) Fix(Dgraph): Type names in exported schema are surrounded by brackets.

- wiki/content/get-started/index.md
Because of the end of life of python2, I think it would be better if we use `python3` as default in the examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6874)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b81bc4ad35-107903.surge.sh)
> docs(getting-started): use python3 to pretty print response

- graphql/e2e/subscription/subscription_test.go
- graphql/subscription/poller.go
Fixes GRAPHQL-764
If we start and Terminate multiple subscriptions and at the end start a new subscription with a 1-second duration between each terminate and start then for any update we were getting multiple responses for the last running subscription whereas we should be getting the only one response. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6868)
> fix(GraphQL): This PR fixes issue of multiple responses in a subscription for an update.

- graphql/e2e/subscription/subscription_test.go
- graphql/subscription/poller.go
Fixes GRAPHQL-764
If we start and Terminate multiple subscriptions and at the end start a new subscription with a 1-second duration between each terminate and start then for any update we were getting multiple responses for the last running subscription whereas we should be getting the only one response.
Co-authored-by: Pawan Rawal <pawan0201@gmail.com>
(cherry picked from commit 734bbe151ea94b6c2d3ab4c51f969c26288eaec6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6879)
> fix(GraphQL): This PR fixes issue of multiple responses in a subscrption for an update. (#6868)

- dgraph/cmd/zero/oracle.go
- go.mod
- go.sum
This PR brings in the memory improvements in B+ tree. This fixes the size of the B+ tree becoming too big.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6875)
> chore(btree): update ristretto to bring in improvements in b+ tree

- dgraph/cmd/alpha/run.go
- dgraph/cmd/live/load-json/load_test.go
- worker/zero_proxy.go
Alpha now forwards /pb.Zero/AssignUids to the zero leader. This allows
live loader to only talk to alpha (with alpha internally dispatching
this API call to zero).
This is useful to Slash GraphQL as we no longer need to look at
FullMethodName in order to forward GRPC requests to alpha or zero
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6878)
> feat: Liveloader can use Alpha for assigning uids

- wiki/content/graphql/queries/cascade.md
Fixes GRAPHQL-781
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6888)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-952022ad1b-108662.surge.sh)
> docs (Update): Documentation for Parameterized cascade

- wiki/content/graphql/queries/count.md
Motivation:
While testing of Count Queries feature, it was felt that the current documentation does not clearly mention the type of fields for whom aggregate Fields are generated. This PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6886)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-a7ddf77562-108492.surge.sh)
> Chore(Docs): Fix documentation for GraphQL count query

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
- worker/worker.go
- x/config.go
- x/tls_helper.go
Fixes DGRAPH-2469 for patch release 20.07.
Currently Dgraph supports both tls v1.1 and tls v1.2 which introduces security concerns. This PR limits the min version to v1.2 and also enables only selected cipher suites which are more secure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6820)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-98b2fbbe99-108815.surge.sh)
> fix(dgraph): giving users the option to control tls versions

- wiki/content/graphql/queries/search-filtering.md
Updating 20.11 documentation to cover the availability of these keywords
Fixes GRAPHQL-778
Fixes GRAPHQL-674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6898)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-f3edd4d1a5-109174.surge.sh)
> Docs (GraphQL): Document the `in` and `has` keywords for 20.11

- graphql/e2e/common/query.go
- graphql/resolve/query_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/input/searchables.graphql
- graphql/schema/testdata/schemagen/output/interfaces-with-types-and-password.graphql
- graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
- graphql/schema/testdata/schemagen/output/searchables.graphql
- graphql/schema/testdata/schemagen/output/union.graphql
Fixes GRAPHQL-817.
This PR is a breaking change for the `eq` filter on the List of `enum` Types.
This PR fixes bugs in the filter generated for enum types. For the given schema:-
```
enum Status {
ACTIVE
DEACTIVATED
}
type VerificationFilter {
status: [Status]! @search
}
```
the `hash` filter generated for `status` was:
```
input Status_hash {
eq: [Status]!
in: [Status]
}
```
whereas, it should be:
```
input Status_hash {
eq: Status
in: [Status]
}
```
This PR also fixes incorrect filter generated for `exact` index in List of enum types. 
Earlier it was being generated like:
```
input Status_exact {
eq: [Status]
in: [Status]
le: [Status]
lt: [Status]
ge: [Status]
gt: [Status]
between: Status
}
```
but it should be like:
```
input Status_exact {
eq: Status
in: [Status]
le: Status
lt: Status …
```
> fix(GraphQL): handle filters for enum properly

- wiki/content/graphql/schema/search.md
Fix an error in the Geolocation`contains` example
Fixes GRAPHQL-837
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6892)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-c26b70254b-108886.surge.sh)
> docs (fix): Fix Geolocation feature example 

- wiki/content/graphql/queries/cached-results.md
This PR adds the "Cached results" feature documentation  (https://github.com/dgraph-io/dgraph/pull/6799)
Fixes GRAPHQL-703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6890)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b006a1d3d4-108762.surge.sh)
> docs (20.11): add documentation for Cached Results

- wiki/content/deploy/fast-data-loading.md
This PR adds docs for Batch upserts in Live loader
Fixes DGRAPH-2586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6897)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-13877a4fce-109235.surge.sh)
> docs (20.11): add documentation for Upserts in Live Loader

- wiki/content/graphql/authorization/directive.md
This PR adds the documentation for `@auth` on interfaces
Fixes GRAPHQL-750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6894)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-1358cfe3bc-109507.surge.sh)
> docs (feature): add documentation for auth on interfaces

- graphql/resolve/query_test.yaml
- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
- graphql/schema/testdata/schemagen/output/deprecated.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
- graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
- graphql/schema/testdata/schemagen/output/hasfilter.graphql
- graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
- graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
- graphql/schema/testdata/schemagen/output/no-id-field.graphql
- graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
- graphql/schema/wrappers_test.go
Fixes GRAPHQL-787.
This PR fixes the Bug in query and mutations generation in case of types that have just `has` filter and not any other kind of filter. For example for the given type: 
```
type Student {
name: String
age: Int
}
```
the corresponding query generated was 
```
queryStudent(order: StudentOrder, first: Int, offset: Int): [Student]
```
and only `add` mutation was being generated.
Whereas, the correct query should be: 
```
queryStudent(filter: StudentFilter, order: StudentOrder, first: Int, offset: Int): [Student]
```
and corresponding update and delete mutation should be:
```
updateStudent(input: UpdateStudentInput!): UpdateStudentPayload
deleteStudent(filter: StudentFilter!): DeleteStudentPayload
```
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> fix(GraphQL): fix exclusion of filters in Query generation in case of just Has Filters.

- graphql/resolve/query_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/output/searchables.graphql
Fixes GRAPHQL-785.
This PR fixes incorrect Schema being generated for the `IN` filter on `enum` types.
for eg: For the given schema:-
```
type Verification {
status: Status! @search
}
enum Status {
ACTIVE
DEACTIVATED
}
```
The filter generated was:-
```
type Status_hash {
eq: Status!
in: Status!
}
```
whereas It should be
```
{
eq: Status!
in: [Status!]
}
```
This PR fixes that.
(cherry picked from commit ecace57b1d2eddd004cd9c2d7b4ed3907cae627a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6906)
> bug(GraphQL): fix IN filter for `enum` types. (#6865)

- graphql/e2e/common/query.go
- graphql/resolve/query_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/input/searchables.graphql
- graphql/schema/testdata/schemagen/output/interfaces-with-types-and-password.graphql
- graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
- graphql/schema/testdata/schemagen/output/searchables.graphql
- graphql/schema/testdata/schemagen/output/union.graphql
This PR is a breaking change for the `eq` filter on the List of `enum` Types.
This PR fixes bugs in the filter generated for enum types. For the given schema:-
```
enum Status {
ACTIVE
DEACTIVATED
}
type VerificationFilter {
status: [Status]! @search
}
```
the `hash` filter generated for `status` was:
```
input Status_hash {
eq: [Status]!
in: [Status]
}
```
whereas, it should be:
```
input Status_hash {
eq: Status
in: [Status]
}
```
This PR also fixes incorrect filter generated for `exact` index in List of enum types.
Earlier it was being generated like:
```
input Status_exact {
eq: [Status]
in: [Status]
le: [Status]
lt: [Status]
ge: [Status]
gt: [Status]
between: Status
}
```
but it should be like:
```
input Status_exact {
eq: Status
in: [Status]
le: Status
lt: Status
ge: Status
gt: …
```
> fix(GraphQL): handle filters for enum properly (#6887)

- schema/schema.go
If index building fails for some reason after starting building indexes, no new schema mutations
can take place. It throws out errIndexingInProgress error. This is because though the schema
update has failed, the predicate remains in the mutSchema. It should be deleted from the map.
(cherry picked from commit 1c7429d75eb79478cd76c8070e594909ba9bac2a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6912)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-ed2ef08c8f-109602.surge.sh)
> fix ErrIndexingInProgress if schema update fails (#6583)

- graphql/e2e/auth/add_mutation_test.go
- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/delete_mutation_test.go
Motivation:
Recently, the PR, https://github.com/dgraph-io/dgraph/pull/6907 was pushed to master which resulted in failure of auth tests. This PR fixes those failing tests.
Testing:
Tested Manually.
rajas@rajas-ThinkPad-T490:~/Github/dgraph/graphql/e2e/auth|master⚡ ⇒  go test
testutil: "" localhost:9080 localhost:5080
PASS
PASS
ok  	github.com/dgraph-io/dgraph/graphql/e2e/auth	43.578s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6923)
> Fix(GraphQL): Fix failing auth tests

- graphql/authorization/auth.go
- graphql/resolve/auth_test.go
- testutil/graphql.go
Fixes GRAPHQL-795.
(cherry picked from commit d3bec85ca832c719486a6094dc41a51ab4855322)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6905)
> fix(GraphQL): make audience mandatory if JWKUrl is provided

- wiki/content/graphql/authorization/authorization-overview.md
- wiki/content/graphql/authorization/directive.md
Fixes GRAPHQL-736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6913)
> docs (20.11): Add documentation for JWK URL auth

- wiki/content/graphql/admin/index.md
Documentation for the new `updateSchemaHistory` syntax. Includes some minor rewording.
Fixes GQLSAAS-863
**Still blocked by CLA Assistant, no matter what I change on my client or how many times I try to sign the CLA**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6925)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-b24179ee7b-110408.surge.sh)
> docs(graphql): Syntax and use case for `updateSchemaHistory`

- wiki/content/deploy/metrics.md
**Still blocked by CLA Assistant, no matter what I change on my client or how many times I try to sign the CLA**
Document the new dgraph_txn_aborts_total metric that counts transaction aborts for a Dgraph server cluster.
Also:
* Added an introduction sentence
* Shifted headers to sentence-case,
* Minor rewording for usage and style 
Fixes DGRAPH-2606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6927)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" align="absmiddle" alt="Dgraph Preview"/>](https://dgraph-298412bd30-110406.surge.sh)
> docs(metrics): Document dgraph_txn_aborts_total metric

- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
- graphql/resolve/resolver.go
- graphql/schema/wrappers.go
Fixes GRAPHQL-806.
Fixes GRAPHQL-793.
This PR extends support for multiple aliases for the same field (except those which are inbuilt) in one query.
For eg:
For the Given Schema:
```
type Author {
id: ID!
posts: [Post!] @hasInverse(field: author)
}
type Post {
postID: ID!
title: String! @search(by: [term])
text: String @search(by: [fulltext])
isPublished: Boolean @search
author: Author!
}
```
The given query:
```
queryAuthor {
name
p1: posts(filter: {isPublished: true}){
title
text
}
p2: posts(filter: {isPublished: false}){
title
text
}
}
```
Earlier the results we picked up only for the first alias for `posts` i.e `p1` and the results into `p2` were copied from the `p1`. This PR fixes that. 
Now, `p1` should contain all those posts which have `isPublished: true` and `p2` will contain all …
> fix(GraphQL): fix multiple alias in query

- t/main.go
The earlier implementation would have caused bugs in the case of any whitespace in the input. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6947)
> Avoid splitting commands by whitespace in test script

- graphql/e2e/subscription/subscription_test.go
- graphql/subscription/poller.go
Fixes GRAPHQL-764
If we start and Terminate multiple subscriptions and at the end start a new subscription with a 1-second duration between each terminate and start then for any update we were getting multiple responses for the last running subscription whereas we should be getting the only one response.
Co-authored-by: Pawan Rawal <pawan0201@gmail.com>
(cherry picked from commit 734bbe151ea94b6c2d3ab4c51f969c26288eaec6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6935) …
> fix(GraphQL): This PR fixes issue of multiple responses in a subscription for an update. (#6868)

- xidmap/xidmap.go
Use B+ tree with the hash of xid in xidmap.
(cherry picked from commit 6a18d849909cdf6c93cff3e61e76a6ce20a53ce8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6926)
> perf(xidmap): Use btree with hash of keys for xidmap (#6902)

- wiki/content/deploy/ludicrous-mode.md
Documentation for https://github.com/dgraph-io/dgraph/pull/6060
- Noted new `--ludicrous_concurrency` configuration setting.
- Some rewording for usage and style.
Fixes DGRAPH-2758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6939)
> Document new concurrency support in Ludicrous mode

- conn/node.go
This log is noisy alongside -v=3 Raft heartbeat logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6952)
> chore(log): Log "Request readctx" in -v=4.

- dgraph/cmd/alpha/reindex_test.go
- edgraph/server.go
- ee/acl/acl_test.go
- graphql/e2e/common/common.go
- systest/online-restore/docker-compose.yml
- systest/online-restore/online_restore_test.go
- t/main.go
- worker/backup_ee.go
- worker/file_handler.go
- Make error checking in TestGuardianOnlyAccessForAdminEndpoints to be more robust.
- Make addSchemaAndData handle temporary server errors better.
- Make online-restore not leave behind directories created by root in Docker by using docker volume for backup tests.
- Remove docker volumes left behind by tests.
- Create backup path if it doesn't exist during backup (not needed to fix any tests, but useful in general).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6958)
> Fix a bunch of flaky tests

- contrib/Dockerfile
Set GODEBUG=madvdontneed=1 to lower Go RSS memory usage.
MADV_DONTNEED is the default behavior in the upcoming Go 1.16:
https://go-review.googlesource.com/c/go/+/267100/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6953)
> build(dockerfile): Set GODEBUG=madvdontneed=1.

- t/main.go
Added a `--rebuild-binary` flag to the `t` package that, when disabled, avoids building Dgraph before running tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6962)
> chore: Add flag to test script to avoid building Dgraph

- contrib/manual_tests/test.sh
Currently, when a manual start of Dgraph is tested, a healthcheck is used to see if the start was successful. This PR also performs an increment operation on each started Alpha, as part of the test.
I've also added a manual start test for Dgraph with both internal and external TLS enabled:
```sh
./test.sh test::manual_start_tls2
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6928)
> chore: add increment to manual_tests

- worker/draft.go
This PR would cause the Alpha leader to immediately trigger a snapshot creation if it doesn't already have one.
This is useful when you bring a new cluster from bulk loader. If you remove an Alpha instance and add a new Alpha instance, the new follower won't get a snapshot if the leader doesn't have one. This PR avoids that by causing the leader to get a snapshot asap.
(cherry picked from commit 6bd7f8e7d96d48108b4b524bdd8a2ea80fd077a0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6969)
> fix(Alpha): Immediately take a snapshot if we don't have one (#6458)

- wiki/content/deploy/data-compression.md
- wiki/content/deploy/fast-data-loading.md
Fixes GraphQL-876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6965)
> Docs (GraphQL): Disk Compression breaking change in 20.11 ( `--badger.compression` replaces `--badger.compression_level`)

- graphql/e2e/common/admin.go
This PR fixes the flaky behavior of the test which verifies that the response of `/state` should be the same as the response of GraphQL admin state request. Previously it used to compare the counter returned in the state response, which can change between two consecutive state calls. The counter in state response is set based on the index of the last RAFT entry applied by Zero. If Zero has applied a RAFT entry between the two consecutive state calls, then the counter would have changed. So, let's not compare this in the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6967)
> test: don't compare counter in successive state calls (GRAPHQL-873)

- raftwal/encryption_test.go
- raftwal/log.go
We need to keep a copy of baseIV in raftwal because if we grow, then the underlying buffer will change. Holding reference will cause segmentation fault. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6977)
> Fix(raftwal): Copy baseIV instead of holding reference

- wiki/content/graphql/queries/cascade.md
Per customer feedback, a typo fix.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6957)
> Docs (chore): typo fix: @casecade -> @cascade

- raftwal/encryption_test.go
- raftwal/log.go
Cherry-pick of #6977.
We need to keep a copy of baseIV in raftwal because if the wal-file grow, then 
the underlying buffer will change. Holding reference will cause segmentation fault.
Extend the TestLogGrow to also test with encryption enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6979)
> fix(raftwal): Keep copy of baseIV instead of holding reference

- wiki/content/graphql/authorization/directive.md
Motivation:
A feature which now supports auth with secret directive was recently added over here, https://github.com/dgraph-io/dgraph/pull/6907 . This PR adds documentation for the feature.
Fixes GRAPHQL-875
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6972)
> Feat(Docs): Add documentation for auth with secret directive

- query/query0_test.go
- types/compare.go
- worker/task.go
Fixes DGRAPH-1781.
This PR backport the fix of `eq filter on non-indexed predicate`, which was fixed by #6715 earlier.
This PR  fixes the `eq` filter for more than one argument on the non-indexed predicate which earlier used to compare with just the first of the given arguments for the `eq` filter. For eg for the given schema:
```
type CarModel {
make
model
year
}
model                          : string @index(term) @lang .
make                           : string @index(term) .
year                           : int .
```
the below query was not giving proper results earlier.
```
queryCarModel(func: type(CarModel)) @filter(eq(year,2008,2009)){
make
model
year
}
```
--- …
> fix(worker): fix eq filter for non-index predicates.

- wiki/content/releases/index.md
Customers are sometimes confused about why we don't have versions 2-19. This PR aims to clarify this by linking from our versioning page to our blog post on this topic
Fixes Success-171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6973)
> Docs (clarification): Clarify switch from semantic to calendar versioning

- query/query0_test.go
- worker/task.go
* fix eq function with non indexed predicate
* remove tests for between function
(cherry picked from commit 54ef639ae160bc2bdd313853bc1c37efed98bed2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6988)
> fix(worker): fix eq filter for non-index predicates. (#6986)

- graphql/admin/admin.go
Small fix to change comment from backups to export, as this is in the context of exports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6990)
> fix: ExportInput destination doc-string comment

- graphql/e2e/common/fragment.go
- graphql/resolve/query_test.yaml
- graphql/schema/request.go
Fixes GRAPHQL-863
Consider the below schema, Human implements both character and Employee interfaces.
interface Employee { ... }
interface Character { ... }
type Human implements Character & Employee { ... }
type Droid implements Character { ... }
While Querying Character interfaces which can return an object of Droid or Human, we will be able to use fragment on Employee interface if the returned object is of type Human and ignores it if the returned object is of type Droid.
(cherry picked from commit f810e4ec0267bd4d69241e6774c70e8bcc22ea43)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6966)
> fix(GraphQL):This PR allows to use fragments on interfaces while querying other interface.  (#6964)

- systest/queries_test.go
- wiki/content/query-language/functions.md
- worker/tokens.go
Fixes DGRAPH-2601
Previously, the following schema:
```
name: string @index(trigram, term) .
```
with some added data, and the following query:
```
query {
q(func: eq(name, "Alice", "Bob")) {
uid
name
}
}
```
would error out saying it doesn't have a valid tokenizer:
```
{
"errors": [
{
"message": ": Attribute name does not have a valid tokenizer.",
"extensions": {
"code": "ErrorInvalidRequest"
}
}
],
"data": null
}
```
even though `term` index is present on the predicate.
On the other hand, if you reversed the order of indexes:
```
name: string @index(term, trigram) .
```
It would give correct results:
```
{
"data": {
"q": [
{
"uid": "0x2",
"name": "Alice",
"age": 20
},
{
"uid": "0x3",
"name": "Bob",
"age": 25
}
]
}
}
```
This PR fixes the above issue.
--- …
> fix(DQL): ignore ordering of indexes in schema with eq function (DGRAPH-2601)

- dgraph/cmd/bulk/reduce.go
The function `( *Buffer) Slice(int)` now returns `-1` for invalid offset. This PR incorporates this change in bulk-loader.
This also fixes a memory leak in bulk-loader, which is caused because we didn't free the `kvBuf`.
**Note: This PR needs some testing**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6999)
> fix(bulk): Fix reduce phase crash and memory leak in bulk-loader

- worker/proposal.go
This is useful to know when a proposal is retried in the trace logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7003)
> chore(trace): Add trace log for proposal limiter.

- graphql/e2e/common/common.go
- graphql/e2e/schema/schema_test.go
- t/t.go
- worker/groups.go
- worker/schema.go
Also make the t.go check for health of the cluster before running tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7006)
> Fix(health): Update health only after upserting schema and types

- tlstest/acl/acl_over_tls_test.go
This PR fixes the ACL test which was failing over TLS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7004)
> chore(test): fixing acl test over tls

- t/t.go
- testutil/client.go
When TLS is enabled, we won't be able to login without the certificates. This PR skips the login if
TLS is enabled. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7010)
> fix(flaky): Fix login error for TLS clusters

- graphql/e2e/common/query.go
- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
Motivation:
Related Discuss post: https://discuss.dgraph.io/t/panics-on-checkpassword-with-alias/11629
Testing:
Added e2e test and a test to query_test.yaml
Fixes GRAPHQL-884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7011)
> Fix(GraphQL): Fix bug with password query rewriting

- gql/fuzzit.sh
Fixes some issues with the fuzz test script:
- Assuming the Dgraph folder is present in `$GOPATH`. This is not necessarily true, I've changed this to only run tests in the current (`gql`) directory.
- The Docker image being used for clang doesn't seem to be updated any more, and was causing problems with the latest builds. I've replaced it with the most popular clang image on Docker Hub. Note that I had to use `clang-10`, because the `clang-11` image is based on Ubuntu Bionic (glibc 2.39), which causes issues in our CI. This can be changed once we upgrade.
- Bash quoting/whitespace nits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7015)
> chore: Fix gql fuzz tests

- dgraph/cmd/bulk/run.go
- ee/backup/run.go
- systest/backup/encryption/backup_test.go
- systest/backup/filesystem/backup_test.go
- systest/backup/minio-large/backup_test.go
- systest/backup/minio/backup_test.go
- worker/restore.go
`dgraph restore` does not currently use any form of compression. This PR adds a `--badger.compression` flag (similar to other Dgraph subcommands) and defaults all compression to `snappy`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6987)
> feat(Dgraph): Add badger.compression to Dgraph restore

- dgraph/cmd/bulk/run.go
- worker/restore.go
Changes the default compression levels in `bulk` and `store` to `zstd:3` for consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6995)
> release/v20.07 - fix: change default compression on 20.07 to zstd:3

- wiki/content/deploy/dgraph-administration.md
Clarified in the docs how to specify a custom path when sending the export request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7000)
> [docs] added example to export to a custom path within the graphql mutation

- dgraph/cmd/root.go
- dgraph/cmd/version/version_test.go
The recent `--kebab-case` PR included a normalization function that messed with `glog` flags. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6998)
> fix: Undo normalization of glog files

- graphql/e2e/auth/auth_test.go
- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
- graphql/resolve/resolver.go
- graphql/schema/gqlschema.go
Motivation:
This PR adds Aggregation Queries at child level. Aggregation Queries handle Avg,Max,Min,Sum functions for scalar fields.
Related RFC: https://discuss.dgraph.io/t/count-queries-in-graphql/10714/9
This PR contains the following changes:
1. Support for aggregation queries at child levels in query_rewriter.go
2. Changes to resolver.go to handle response of aggregation queries at child level.
3. Tests to query_test.yaml and auth_query_test.yaml
4. e2e tests for aggregation queries at child level.
Fixes GRAPHQL-773
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7022)
> Feat(GraphQL): Add Aggregation Queries at Child Level

- graphql/e2e/common/admin.go
- graphql/e2e/common/query.go
- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
Fixes GRAPHQL-884
* Fix bug with password query rewriting
* Remove query.ResponseName() from query_rewriter.go
(cherry picked from commit 46a39c660f6c41ab3dc6a184983644c30dd6d4b1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7012)
> Fix(GraphQL): Fix password query rewriting in release/v20.11

- README.md
Add macOS details
Fixes DGRAPH-2602
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7020)
> docs (chore): Add build/install instructions for macOS

- dgraph/cmd/root.go
- dgraph/cmd/version/version_test.go
The recent `--kebab-case` PR included a normalization function that messed with `glog` flags. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7025)
> release/20.11 - fix: Undo normalization of glog files

- dgraph/cmd/alpha/run.go
- go.mod
- go.sum
- graphql/e2e/admin_auth/poorman_auth/admin_auth_test.go
- graphql/e2e/admin_auth/poorman_auth_with_acl/admin_auth_test.go
- graphql/e2e/auth/add_mutation_test.go
- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/debug_off/debugoff_test.go
- graphql/e2e/auth/delete_mutation_test.go
- graphql/e2e/auth/update_mutation_test.go
- graphql/e2e/common/admin.go
- graphql/e2e/common/common.go
- graphql/e2e/common/error.go
- graphql/e2e/common/mutation.go
- graphql/e2e/common/schema.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/e2e/schema/schema_test.go
- graphql/e2e/subscription/subscription_test.go
- testutil/client.go
- testutil/graphql.go
- testutil/schema.go
This PR does the following things:
* adds a counter in `/probe/graphql` response which indicate how many time the GraphQL schema has been updated.
* adds some common test methods to update the GQL schema which ensure schema update using the counter.
* Refactors existing tests to use those methods in order to update the GQL schema.
* adds the best practice of using `common.RequireNoGQLErrors` instead of `require.Nil` for verifying that the `GraphQLResponse` has no errors.
* enables some skipped tests in `graphql/e2e/admin_auth`.
With this PR, all the flakiness around GraphQL schema updates should no longer be there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7016)
> chore(test): Refactor GraphQL tests to use best practices (GRAPHQL-885)

- wiki/content/deploy/kubernetes.md
Fixes bug DGRAPH-2581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7049)
> docs (fix): Update kubernetes links to match 20.07 config files

- go.mod
- go.sum
Fixes DGRAPH-2808
This PR brings in the change of an increasing number of buffers from 32 to 64 in z.Allocator.
Related discuss issue: https://discuss.dgraph.io/t/panic-allocator-can-not-allocate-more-than-32-buffers/11650
See https://github.com/dgraph-io/ristretto/pull/234 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7046)
> fix(allocator): bring in increased buffers for allocator from ristretto

- systest/queries_test.go
- wiki/content/query-language/functions.md
- worker/tokens.go
Previously, the following schema:
```
name: string @index(trigram, term) .
```
with some added data, and the following query:
```
query {
q(func: eq(name, "Alice", "Bob")) {
uid
name
}
}
```
would error out saying it doesn't have a valid tokenizer:
```
{
"errors": [
{
"message": ": Attribute name does not have a valid tokenizer.",
"extensions": {
"code": "ErrorInvalidRequest"
}
}
],
"data": null
}
```
even though `term` index is present on the predicate.
On the other hand, if you reversed the order of indexes:
```
name: string @index(term, trigram) .
```
It would give correct results:
```
{
"data": {
"q": [
{
"uid": "0x2",
"name": "Alice",
"age": 20
},
{
"uid": "0x3",
"name": "Bob",
"age": 25
}
]
}
}
```
This PR fixes the above issue.
(cherry picked from commit …
> fix(DQL): ignore ordering of indexes in schema with eq function

- wiki/content/query-language/schema.md
adjusted doc to reflect the fixed behavior by https://github.com/dgraph-io/dgraph/pull/6996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7036)
> [docs] removed note about order for term and trigram 

- wiki/content/query-language/schema.md
adjusted doc to reflect the fixed behavior by #6996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7037)
> [docs] removed note about order for term and trigram since it has been fixed

- wiki/content/deploy/cluster-setup.md
Updates to: 
https://dgraph.io/docs/deploy/cluster-setup/#consistent-replication specify that the --replicas flag has to be passed to Dgraph Zero, and that it has to be passed only once (for the first Dgraph Zero node launched).
Also includes some rewording.
Fixes SUCCESS-245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6981)
> Docs (clarification) Note proper use and meaning of --replicas flag

- wiki/content/graphql/mutations/add.md
fix(Wiki): Fix typo in  "Variables" of query: "Example: Add mutation on single type using variables".
In the last section, "Example: Add mutation on single type using variables",
we use "$author" variable in GraphQL.
`mutation addAuthor($author: [AddAuthorInput!]!) {
addAuthor(input: $author) {
author {
id
name
}
}
}`
However, in the query variables, we have "auth" key.
` 
{ "auth":
{ "name": "A.N. Author",
"dob": "2000-01-01",
"posts": []
}
}
`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6723)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" height="34" …
> fix(Wiki): Fix typo in add.md in wiki.

- wiki/content/graphql/todo-app-tutorial/todo-auth0-jwt.md
When I followed the tutorial for the todo app with auth, I got stuck on this page (https://dgraph.io/docs/graphql/todo-app-tutorial/todo-auth0-jwt/) and asked for help in the forums (https://discuss.dgraph.io/t/auth-rule-restricting-tasks-to-be-queried-only-by-logged-in-users-prevents-any-tasks-to-be-queried-by-anyone/10125).
Arijit Das showed me that the schema authorization format was outdated in the tutorial.
So I proposed these changes to fix the tutorial.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6442)
Docs Preview: [<img src="https://bl.ocks.org/prashant-shahi/raw/3a9f99bec84231cfe3c0e82cf883f159/0e588d908ad8c8b10958b87ebdd2ba68779ccf4f/dgraph.svg" …
> docs(GraphQL): Update Dgraph authorization format in Todo tutorial

- dgraph/cmd/alpha/metrics_test.go
- x/metrics.go
This adds a new metric called `dgraph_memory_alloc_bytes` that tracks the jemalloc memory reported by `z.NumAllocBytes()`. 
Changes
* Add `dgraph_memory_alloc_bytes` Prometheus metric.
* Add comment about runtime.ReadMemStats stopping the world.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7051)
> feat(metric): Add dgraph_memory_alloc_bytes to track jemalloc memory.

- wiki/content/deploy/log-format.md
- rephrased title
- rephrased `-v=3` paragraph
- added "note" box to highlight the fact that these flags require a restart
- added example for query logging output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7032)
> [docs] : rephrase + added example to query logging section

- dgraph/cmd/debug/run.go
The debug tool was using normal iterators which are very slow. This PR use the stream framework in debug tool instead of the iterators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7060)
> Use stream framework in debug tool

- x/metrics.go
These metrics should be using LastCount to get the measured metric, not just the
number of counted events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7005)
> fix(metrics): Use LastCount for RaftAppliedIndex and MaxAssignedTs.

- dgraph/cmd/debug/run.go
Add `--rollup` flag in debug tool which allows key rollup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7066)
> feat(debug): Support rollup in debug tool

- worker/draft.go
- x/metrics.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7069)
> feat(metrics): Add metrics for size of applyCh and proposal size.
