- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
- go.mod
- go.sum
- x/metrics.go
Accessible via /jemalloc at Zero's HTTP port.
http:localhost:6080/jemalloc
```
Num Allocated Bytes: 0 B [0]
Allocators:
NO leaks found.
```
Also, update to the latest Badger to fix OOMs during compaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7070)
> feat(zero): Bring in jemalloc debugging to Zero.

- posting/list.go
- query/query.go
- worker/match.go
- worker/sort.go
- worker/task.go
- worker/trigram.go
When retrieving Uids, if we are not doing any filtering or ordering, then we should respect the first: N argument and only retrieve what's being asked for. This really speeds up the query execution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7072)
> Opt(query): Respect the first N argument

- dgraph/cmd/alpha/run.go
The shutdown handler was attempting to signal a possible nil `ServerCloser`, causing panics on early Ctrl-C. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7048)
> fix: Check for nil ServerCloser in shutdown handler

- query/outputrdf.go
- query/rdf_result_test.go
Fixes DGRAPH-2781.
Fixes DGRAPH-2552.
This PR fixes Some of the bugs in the RDF response.
For the given schema:
```
name: string @index(exact) .
friend: [uid] .
type Person {
name
friend
}
```
1) For a query:
```
query(func: type(Person)){
uid
name
}
```
The output was:
```
<0x5573a> <uid> <0x5573a> .
<0x5573c> <uid> <0x5573c> .
<0x5573d> <uid> <0x5573d> .
<0x5573a> <name> "Charlie" .
<0x5573c> <name> "Alice" .
<0x5573d> <name> "Bob" .
```
The redundant `<X> <uid> <X>` triplets should be removed from the RDF output. This PR fixes that.
2) For the given query: 
```
query(func: type(Person)){
name
friend
}
```
The RDF response is:
```
<0x5573a> <name> "Charlie" .
<0x5573c> <name> "Alice" .
<0x5573d> <name> "Bob" .
<0x5573c> <friend> <0x5573a> .
<0x5573c> <friend> <0x5573d> .
```
The `<X> …
> fix(Query): Fix incorrect RDF response.

- wiki/content/deploy/log-format.md
* rephrase + added expample to query logging
* rephrase + typos
(cherry picked from commit bc41f5116ec456d2d0450ff3a439bddb22ba4c0c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7078)
> [docs] : rephrase + added example to query logging section (#7032)

- xidmap/xidmap.go
We should only log "Writing to DB" when it is actually being written.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7082)
> fix(logs): Fix logs in xidmap flush

- wiki/content/deploy/production-checklist.md
Suggested to implement and use a backup policy in our prod checklist. Also provided some recommendations
Fixes SUCCESS-189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7084)
> [docs] added backup policy

- graphql/admin/add_group.go
- graphql/admin/current_user.go
- graphql/admin/schema.go
- graphql/admin/update_group.go
- graphql/dgraph/graphquery.go
- graphql/resolve/mutation.go
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/query.go
- graphql/resolve/query_rewriter.go
Motivation:
Currently, a GraphQL query/mutation is rewritten to DQL query. This is done in query_rewriter.go and mutation_rewriter.go . The GraphQL query/mutation is first converted into *gql.GraphQuery and then finally rewritten to DQL query. 
As the DQL query is not a single query, but a list of queries (involving a query and multiple functions), currently to store such multiple queries, *gql.GraphQuery is kept empty and its children (*gql.GraphQuery.Children[]) are used to store them. This is problematic as at many places one needs to iterate over Children and also to have different cases to handle case in which the top level *gql.GraphQuery is empty.
This PR fixes this and replaces *gql.GraphQuery as output of query rewriting with []*gql.GraphQuery .
Testing:
Tested locally all tests …
> Fix(GraphQL): Refactor output of query/mutation rewriting

- graphql/admin/admin.go
(cherry picked from commit 80bbf0a576e525b8af2962d10634919e71596f68)
This fixes doc-string for ExportInput { destination } that references backup and not export.  Change to reflect the context of export.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6992)
> fix: ExportInput destination doc-string comment (#6990)

- graphql/admin/admin.go
Added docstring comment for ExportInput { format }.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/6991)
> fix: added comment docstring for ExportInput format

- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
- query/query.go
This PR moves the pagination parameters for root user query to root auth query. This greatly optimizes the number of nodes that need to be processed by child auth queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7100)
> perf(GraphQL): Part-1: Pagination for root user query is applied at root auth query (GRAPHQL-854)

- edgraph/server.go
- graphql/admin/admin.go
- graphql/admin/config.go
- worker/worker.go
- x/config.go
(cherry picked from commit 449c06b552f2deeda064d3754825dc0168b5fee3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7085)
> Add LogRequest variable to config input (#5197)

- graphql/resolve/auth_add_test.yaml
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/auth_update_test.yaml
- graphql/resolve/query_rewriter.go
We don't need to query `uid` for auth queries, as they always have at least one field in their selection set. This optimizes the number of `touched_uids` greatly, while time is not much improved here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7105)
> perf(GraphQL): Part-2: Remove unnecessary `dgraph.uid : uid` selections for auth queries (GRAPHQL-854)

- wiki/content/clients/go.md
Fixes DGRAPH-2341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7108)
> docs (chore):  Add missing Discard(ctx) to Dgo client

- graphql/admin/admin.go
* fix: added comment docstring for ExportInput format
(cherry picked from commit 072b03ecb8bed934865444afc0f157b7d78c9fb7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7097)
> fix: added comment docstring for ExportInput format (#6991)

- wiki/content/clients/go.md
fixes DGRAPH-2355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7113)
> docs (chore): add note regarding RDF queries

- graphql/e2e/auth/auth_test.go
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
This PR fixes the issue introduced by #7100. As pagination is moved to root auth query, so order also needs to be applied at root auth query, in addition to being applied at the root user query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7117)
> fix(GraphQL): Correctly apply order for root auth query (GRAPHQL-854)

- go.mod
- go.sum
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7122)
> Update ristretto to bring in jemalloc-stats fix

- dgraph/cmd/alpha/metrics_test.go
This PR aims to fix the flaky behaviour of TestMetricTxnAborts. Thing is prometheus metrics are eventually consistent. This adds retryable function that will wait upto the 10th iteration for the metrics to match
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7126)
> chore(test): fixing flakyness in  TestMetricTxnAborts

- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
This PR modifies how the internal graph aliases are generated in case of multiple aliases of same field in the query.
For the given graphql query:
```
query {
queryAuthor {
name
p1: posts(filter: {isPublished: true}){
title
text
}
p2: posts(filter: {isPublished: true}){
title
text
}
}
}
```
earlier it was rewritten into:
```
query {
queryAuthor(func: type(Author)) {
name : Author.name
posts : Author.posts @filter(eq(Post.isPublished, true)) {
title : Post.title
text : Post.text
dgraph.uid : uid
}
posts1 : Author.posts @filter(eq(Post.isPublished, true)) {
title : Post.title
text : Post.text
dgraph.uid : uid
}
dgraph.uid : uid
}
}
```
Now it is changed to:
```
query {
queryAuthor(func: type(Author)) {
name : Author.name
posts : Author.posts @filter(eq(Post.isPublished, true)) {
title : …
```
> fix(GraphQL): fix internal Aliases name generation

- dgraph/cmd/debug/wal.go
- dgraph/cmd/zero/raft.go
We were unmarshalling into incorrect type (`MembershipState`) the snapshot which contained data marshalled from `ZeroSnapshot`. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7125)
> fix: unmarshal snapshot onto zerosnapshot instead of membershipState

- dgraph/cmd/debug/wal.go
- dgraph/cmd/zero/raft.go
We were unmarshalling into incorrect type (MembershipState) the snapshot which contained data marshalled from ZeroSnapshot. This PR fixes that.
(cherry picked from commit 55dd455394da0fc5b2d1c4afa5b14e7a572f940c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7128)
> release(v20.11): unmarshal snapshot onto zerosnapshot instead of membershipState (#7125)

- graphql/resolve/query_test.yaml
The test broke after merging #7009 in master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7130)
> chore: fix a broken test

- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
This PR modifies how the internal graph aliases are generated in case of multiple aliases of same field in the query.
For the given graphql query:
```
query {
queryAuthor {
name
p1: posts(filter: {isPublished: true}){
title
text
}
p2: posts(filter: {isPublished: true}){
title
text
}
}
}
```
earlier it was rewritten into:
```
query {
queryAuthor(func: type(Author)) {
name : Author.name
posts : Author.posts @filter(eq(Post.isPublished, true)) {
title : Post.title
text : Post.text
dgraph.uid : uid
}
posts1 : Author.posts @filter(eq(Post.isPublished, true)) {
title : Post.title
text : Post.text
dgraph.uid : uid
}
dgraph.uid : uid
}
}
```
Now it is changed to:
```
query {
queryAuthor(func: type(Author)) {
name : Author.name
posts : Author.posts @filter(eq(Post.isPublished, true)) {
title : …
```
> fix(GraphQL): fix internal Aliases name generation (#7009)

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/e2e/auth/test_data.json
- graphql/e2e/common/common.go
- graphql/schema/auth.go
- graphql/schema/auth_schemas_test.yaml
This PR aims to fix GRAPHQL-808. This enables multiple things.
1. support for regex matching in custom claims.
2. support for array in custom claims.
3. Claims match based on float, int64, int, structs, bool, string
4. in based custom claim match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7039)
> feat(graphql):  adding auth token support for regexp, in and arrays

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/common/query.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/directives/test_data.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/e2e/normal/test_data.json
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers.go
This PR fixes GRAPHQL-762. Earlier we only can define String! datatypes with @id directive. This enables user to define @id directive with Int, Int64, Float datatypes too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7019)
> fix(graphql): adding support for @id with type other than strings

- wiki/content/graphql/mutations/deep.md
Updated the language and examples to correctly document the behavior of deep mutations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7144)
> Docs(GraphQL): Correct Deep Mutations Docs

- posting/list.go
- t/t.go
This PR reverts https://github.com/dgraph-io/dgraph/pull/6206/files. That PR added the race condition. Also, it was not a bug. If needed we will fix this in a different way.
This also fixes one log line with race in t.go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7149)
> fixing race in pick postings + fixing race log in t.go

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/bulk/run.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7154)
> fix(bulk): fixing bulk loader when encryption + mtls is enabled

- wiki/content/graphql/schema/types.md
Fixes GRAPHQL-893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7142)
> docs: Update GraphQL interface implementation reference

- dgraph/cmd/debug/wal.go
- dgraph/cmd/zero/raft.go
In zero's raftwal meta, we used to store `MembershipState` only. The changes in https://github.com/dgraph-io/dgraph/pull/7096 made it store `ZeroSnapshot`. `Index` and `CheckpointTs` actually need not be stored. 
This PR makes raftwal meta store only `MembershipState`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7143)
> [BREAKING] opt(raftwal):  store only membership state to disk in the zero snapshot

- dgraph/cmd/debug/run.go
- dgraph/cmd/debug/wal.go
- dgraph/cmd/raft-migrate/run.go
- dgraph/cmd/zero/raft.go
Cherry picked from https://github.com/dgraph-io/dgraph/commit/ab0f3ea898f02221c1726ab4ad21f4ecf4492f11
This PR updates the raftmigrate tool. We recently updated raft proposal format for alpha and zero, see #7059 .
The tool now can migrate raftwal from old proposal format to new proposal format wherein we are encoding the proposal.Key within the entry.Data.
This change will help to migrate raftwal from [RC-2,RC-3] to RC-4 onwards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7157)
> release(v20.11): [cherry-pick]  Update Raft migrate tool to handle new proposal format

- xidmap/xidmap.go
This issue was observed earlier as well and there was a PR fixing it. This PR brings that change back.
https://github.com/dgraph-io/dgraph/pull/4738
We still need to find the exact cause of why the tree is not GCed without explicitly setting it to nil, despite the parent struct set to nil. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7161)
> fix(bulk): Fix memory held by tree in reduce phase

- wiki/content/graphql/lambda/overview.md
The /graphql/lambda/directive page doesn't exist. The correct link goes to /graphql/lambda/field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7163)
> docs(graphql): Fix link to lambda fields.

- wiki/content/graphql/lambda/overview.md
The /graphql/lambda/directive page doesn't exist. The correct link goes
to /graphql/lambda/field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7164)
> docs(graphql): Fix link to lambda fields. (#7163)

- dgraph/cmd/bulk/run.go
This exposes the /jemalloc endpoint to bulk loader's HTTP port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7165)
> feat(bulk): Add /jemalloc HTTP endpoint.

- go.mod
- go.sum
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7169)
> Update ristretto to bring in capped b+tree growth

- wiki/content/graphql/mutations/deep.md
PR to fix a typo in https://github.com/dgraph-io/dgraph/pull/7144, also some rewording for style
Fixes GRAPHQL-858
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7145)
> Docs(GraphQL): Correct Deep Mutations Docs (follow-up rewording / typo fix)

- wiki/content/tutorial-1/index.md
- wiki/content/tutorial-2/index.md
- wiki/content/tutorial-3/index.md
- wiki/content/tutorial-4/index.md
- wiki/content/tutorial-5/index.md
- wiki/content/tutorial-6/index.md
- wiki/content/tutorial-7/index.md
- wiki/content/tutorial-8/index.md
- wiki/content/tutorials/index.md
This PR removes the links to https://github.com/dgraph-io/dgraph/issues since it's usage is deprecated, see https://github.com/dgraph-io/dgraph/issues/5947. Instead [discuss.dgraph.io](https://discuss.dgraph.io/c/issues/dgraph/38) should be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7160)
> topic(Docs): Remove link to github issues for issues related to dgraph 

- wiki/content/deploy/log-format.md
explained with examples how to turn on/off query logging via graphql mutation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7077)
> [docs]example on how to turn on/off query logging dynamically

- wiki/content/deploy/log-format.md
added command to turn on/off query logging via graphql mutation
(cherry picked from commit a1f661a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7191)
> [docs] example on how to turn on/off query logging dynamically 

- wiki/content/deploy/index.md
Starting from Dgraph v20.03.7 it will be possible to turn on/off query logging dynamically (without the need of restarting an alpha node).
This PR give example and instruction on how to achieve that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7178)
> [docs] added example on how to turn on/off query logging dynamically

- wiki/content/deploy/log-format.md
* added command to turn on/off query logging via graphql mutation
(cherry picked from commit a1f661ab109aeffd8c75fce1219bc3d26b79c66f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7177)
> [docs]example on how to turn on/off query logging dynamically (#7077)

- wiki/content/migration/migrate-dgraph-1-1.md
Refactor "Migrate to Dgraph v1.1" to a more generic "Migrate from Dgraph v1.0" topic that we can cherry-pick back to 20.07 and 20.03 docs when complete (so, no references to newer features).
Fixes GRAPHQL-804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7179)
> Docs(Migration): "Migrate from Dgraph v1.0 to Newer Versions"

- worker/executor.go
The operations on `inDeg` field of `mutation` struct should be done atomically because it is being used to check if a mutation in dependent on any other mutation. And the mutations are run concurrently, so this update in `inDeg` should be protected. This change fixes the data race which results in alpha crash due to calling `Done` on watermark which is lesser than `doneUntil` 
Fixes: [DGRAPH-2805](https://dgraph.atlassian.net/browse/DGRAPH-2805)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7203)
> fix(ludicrous): Fix data race in executor

- dgraph/cmd/raft-migrate/run.go
Slash wants the raft-migrate to be a no-op if it is already on the newer version. We currently don't store any version (like we store `magic number` in badger). So, we need to check the encoding of protobuf data.
This PR makes raft-migrate a No-op if the raftwal is already at new format.
Reference: [Protobuf encoding format](https://developers.google.com/protocol-buffers/docs/encoding#structure)
In the new format, we prepend Key in the first 8 bytes of the Marshalled proposal. 
https://github.com/dgraph-io/dgraph/blob/6884b151c355669d1387f30696566f458d0a905f/dgraph/cmd/zero/raft.go#L77-L79
So, the first byte will be 0 if the node ID is less than 1<<24, which is a valid assumption for a reasonable cluster.
If we were on older cluster, then the entry.Data[0] would be storing the `wireType` …
> chore(raft-migrate): make raft-migrate a no-op if already migrated

- wiki/content/graphql/queries/cascade.md
Fixes DGRAPH-2886
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7216)
> docs (chore): Fix code indentation in cascade.md

- dgraph/cmd/alpha/http_test.go
- dgraph/cmd/alpha/metrics_test.go
- dgraph/cmd/alpha/run_test.go
- systest/mutations_test.go
- worker/proposal_test.go
HTTP tests have race in terms of how they use a token variable. being a global variable it's being rewritten and read by multiple goroutines and thus leading to errors like "Token expired etc.". This PR is to make them more resilient and fix race Also fixes a few in other test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7167)
> fix(test) : http test to be more resilient and fix race

- edgraph/access_ee.go
- made even more generic the alpha log when failing the auth
- fixed typo in `password`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7228)
> acl: fixed a typo + more generic message for failed acl auth

- wiki/content/mutations/json-mutation-format.md
Fixes DGRAPH-2868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7234)
> docs: add notes regarding restricted JSON values

- query/outputnode.go
- systest/mutations_test.go
This PR fixes the empty string response for a zero-datetime value. The "0001-01-01T00:00:00Z" datetime is considered to be a zero value. Before we used to allow empty string for datetime mutation and internally stored empty string as zero datetime  so we returned empty string for it but now empty string mutation is not allowed. So, we should return "0001-01-01T00:00:00Z" instead of empty string if the mutation contains "0001-01-01T00:00:00Z".
(cherry picked from commit 386665f95ab538cd6c5aab4516c0cb63e4a1e04c)
Fixes DGRAPH-2859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7236)
> fix(dgraph): Fix empty string response for zero datetime (#6067)

- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- graphql/schema/schemagen.go
- graphql/schema/testdata/schemagen/input/apollo-federation.graphql
- graphql/schema/testdata/schemagen/output/apollo-federation.graphql
- graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
- graphql/schema/wrappers.go
Fix GRAPHQL-905.
This PR implements [Federation Schema Specification](https://www.apollographql.com/docs/federation/federation-spec/#federation-schema-specification) in order to support apollo federation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7159)
> feat(GraphQL): Add Schema support for federation

- dgraph/cmd/alpha/http.go
- graphql/e2e/admin_auth/poorman_auth/admin_auth_test.go
Fixes [Discuss Issue](https://discuss.dgraph.io/t/alpha-problems-with-auth-token/12136).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7245)
> fix(GraphQL): Fix auth-token propagation for HTTP endpoints resolved through GraphQL (GRAPHQL-946)

- graphql/admin/restore.go
- worker/online_restore.go
- worker/online_restore_ee.go
This PR reset the ACL accounts once the restore is complete. When we start the restore, it apply DROP_ALL mutation and thus deleting ACL accounts. It's a common across all the alter operation, where we reset ACL accounts once we have the DROP_ALL operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7202)
> fix(restore): reset acl accounts once restore is done if necessary

- dgraph/cmd/debug/run.go
- dgraph/cmd/debug/wal.go
- raftwal/log.go
- raftwal/storage.go
- raftwal/storage_test.go
- raftwal/wal.go
This is an alternate implementation of https://github.com/dgraph-io/dgraph/pull/7168. This should be much faster, but leaves us with a fragmented logFile (entry data is not stored contiguously).
This should not break anything, as we never directly iterate through data fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7196)
> fix: Migrate debug tool to new DiskStorage (more efficient)

- dgraph/cmd/zero/raft.go
We recently made a change to how we store snapshots and it looks like we
forgot to change that in one place.
Fixes DGRAPH-2897
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7244)
> fix(raft): Unmarshal zero snapshot into pb.ZeroSnaphot

- dgraph/cmd/debug/wal.go
- dgraph/cmd/zero/raft.go
We introduced a change in https://github.com/dgraph-io/dgraph/pull/7143 that would have been breaking for the next release v21.03. That change should have been a part of `release/v20.11` but was mistakenly missed. We are doing a revert so that `release/v21.03` is not breaking due to that change. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7249)
> [UNDO-BREAKING] fix(zero-snapshot): Do not break the raftwal format due to ZeroSnapshot

- dgraph/Makefile
- go.mod
- go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7247)
> fix(dgraph): making jemalloc to work with dgraph on macos

- posting/list.go
- posting/list_test.go
- x/debug.go
- x/nodebug.go
Fixes DGRAPH-2840
This PR adds checks for verification of plist's uidpack when dgraph is run in debug mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7250)
> debug(uidpack): add checks for uid pack in debug mode

- raftwal/storage.go
This PR fix following race condition
```
Write at 0x00c000306e00 by goroutine 242:
github.com/dgraph-io/ristretto/z.(*MmapFile).Truncate()
/home/agent/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20201218073023-6a5070bff779/z/file_linux.go:35 +0x479
github.com/dgraph-io/ristretto/z.(*MmapFile).AllocateSlice()
/home/agent/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.4-0.20201218073023-6a5070bff779/z/file.go:148 +0x279
github.com/dgraph-io/dgraph/raftwal.(*wal).AddEntries()
/home/agent/work/4c273890c7f2d4e2/raftwal/wal.go:184 +0x8fa
github.com/dgraph-io/dgraph/raftwal.(*DiskStorage).Save()
/home/agent/work/4c273890c7f2d4e2/raftwal/storage.go:332 +0xf8
github.com/dgraph-io/dgraph/conn.(*Node).SaveToStorage()
/home/agent/work/4c273890c7f2d4e2/conn/node.go:288 +0xf7 …
```
> fix(dgraph): fixing race condition in disk storage sync and save

- dgraph/cmd/zero/raft.go
We recently made a change to how we store snapshots and it looks like we
forgot to change that at one place.
(cherry picked from commit 842bb3d8858f0045b2a1f46d0d60d974850fb0ee)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7259)
> release/20.11-slash: fix(raft): Unmarshal zero snapshot into pb.ZeroSnaphot (#7244)

- ee/backup/run.go
At the end of the restore operation, we update the MaxUid in zero. This
MaxUid can be zero if the backup was created from an empty DB.
Fixes DGRAPH-2804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7258)
> fix(restore): Handle MaxUid=0 appropriately

- dgraph/cmd/root.go
- dgraph/cmd/tool/decrypt/decrypt.go
- dgraph/cmd/tool/run.go
- ee/enc/util_ee.go
Create a tool `dgraph tool decrypt` to decrypt encrypted export data.
e.g.
```
$ dgraph tool -h
A suite of Dgraph tools
Usage:
dgraph tool [command]
Available Commands:
decrypt     Run Decrypt tool
```
```
$ dgraph tool decrypt -h
A tool to decrypt an export file created by an encrypted Dgraph cluster
Usage:
dgraph tool decrypt [flags]
Flags:
--encryption_key_file string   The file that stores the symmetric key of length 16, 24, or 32 bytes. The key size determines the chosen AES cipher (AES-128, AES-192, and AES-256 respectively). Enterprise feature.
-f, --file string                  Path to file to decrypt.
-h, --help                         help for decrypt
-o, --out string                   Path …
```
> feat(tool/decrypt): Add dgraph decrypt tool (#7248)

- wiki/content/deploy/ports-usage.md
- wiki/content/deploy/tls-configuration.md
Updates 20.07 docs to note the addition of mTLS and port encryption. This is not a cherry-pick of https://github.com/dgraph-io/dgraph/pull/6893 because in 20.07 we did not split the `tls_dir` option into  `tls_cacert`, `tls_node_key`, and `tls_node_cert`.
Fixes DGRAPH-2692
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7243)
> Docs (update to v20.07) - Port encryption and use of mTLS for all internal gRPC communications

- ee/backup/run.go
At the end of the restore operation we update the MaxUid in zero. This
MaxUid can be zero if the backup was created from an empty DB.
(cherry picked from commit b05fb930ffdbbb2f849d73a1e57bc8bd7575255d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7265)
> release/20.11 - fix(restore): Handle MaxUid=0 appropriately (#7258)

- wiki/content/query-language/functions.md
Fixes the example query for the `between` function in DQL to return a smaller data set and run in seconds, rather than minutes (the current query functions, but is larger than it should be ).
Staged here: https://deploy-preview-7262--dgraph-docs.netlify.app/query-language/functions/#between
Fixes GRAPHQL-811
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7262)
> Docs (Chore) Change example query for between function to run more quickly

- dgraph/Makefile
- go.mod
- go.sum
* making jemalloc to work with dgraph on macos
* updating ristretto to latest version
* running it tidy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7282)
> release/v20.11:  fix(dgraph): making jemalloc to work with dgraph on macos (#7247)

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/resolve/resolver.go
Fixes GRAPHQL-921
The first mutation below will now return the "Mutation" type, which previously was giving an error.
`Mutation`:
```
mutation {
__typename
addpost1(input: [{title: "Dgraph", numLikes: 92233720 }]) {
post1 {
title
numLikes
}
}
}
`Response:`
{
"__typename":"Mutation",
"addpost1": {
"post1": [{
"title": "Dgraph",
"numLikes": 92233720
}]
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7285)
> fix(GraphQL): This PR allow to use __typename in mutation.

- posting/index.go
Fixes DGRAPH-2894
By default `/tmp` directory was used as a temporary directory for rebuilding indexes. This might lead to out of disk out of space error if `/tmp` is not spacious enough.
This PR provides makes it use directory passed through `--tmp` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7289)
> fix(index): use --tmp directory for building indexes

- go.mod
- query/common_test.go
- query/query1_test.go
- query/query2_test.go
- query/rdf_result_test.go
- worker/sort.go
This PR makes the result of sort consistent for predicate with and without index. There was an issue that for predicate with index, we used to drop the nodes which doesn't contain the predicate used for sorting, while we retained them for that of without index. 
The nulls were dropped in thee case of `sortWithIndex` because in this case to calculate the result, we used to take intersection of the given list for sorting with the index of the predicate used for sorting, hence other predicates were dropped. In this change, we keep track of nodes which have null sort predicates and append them to the result as required.
Some benchmarks:
The dataset contain 1million UIDs, with half of them containing the predicate used for sorting. The time taken are in nano seconds.
```
No Index:
Query …
```
> fix(sort): Make sort consistent for indexed and without indexed predicates

- wiki/content/graphql/custom/directive.md
Fixes GRAPHQL-813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7290)
> docs (20.11.1): Add docs about how errors are returned from custom endpoints

- wiki/content/deploy/fast-data-loading/bulk-loader.md
The `--shufflers` flag (for bulk loader) has been removed with this [commit](https://github.com/dgraph-io/dgraph/commit/d336e41dea7aed518204b11acc5d655d74a575b6) on Jun 11, 2019 
Our docs are still reporting this flag, hence removing it with this PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7294)
> docs: remove "--shufflers" flag reference in bulk loader docs

- contrib/jepsen/main.go
- dgraph/cmd/cert/create.go
- dgraph/cmd/live/load-json/load_test.go
- dgraph/cmd/live/load-uids/load_test.go
- go.mod
- go.sum
- graphql/testdata/datagen/cmd/root.go
- graphql/testdata/datagen/cmd/run.go
- raftwal/log.go
- systest/1million/1million_test.go
- systest/21million/bulk/run_test.go
- systest/21million/common/run_queries.go
- systest/21million/live/run_test.go
- systest/21million/ludicrous/run_test.go
- systest/ludicrous/run_test.go
- systest/online-restore/online_restore_test.go
- t/t.go
- testutil/client.go
- testutil/json.go
- testutil/plugin.go
- worker/export.go
There were two issues on windows
1. We were trying to delete a file with open file descriptors. This
doesn't work on windows. The PR dgraph-io/ristretto#242 in ristretto fixes this.
2. We were using path.Join instead of filepath.Join. The path package is
supposed to be used only on Unix systems. In windows the "" is the path
separator instead of "/".
(cherry picked from commit 5aec24394570706ee0b0bb49586119959ed6dd72)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7299)
> release/v20.11 - fix(dgraph): Fix dgraph crash on windows (#7261)

- posting/index.go
Makes reindexing use directory passed through --tmp flag of alpha.
(cherry picked from commit 1707ecfa8cb44cfccc20675d22929904e1cf7bde)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7300)
> release/v20.11: fix(indexing): use --tmp directory for building indexes (#7289)

- query/common_test.go
- query/query1_test.go
- query/query2_test.go
- query/rdf_result_test.go
- worker/sort.go
Make the result of sort consistent for predicate with and without index.
After this change, the predicates with null values will appear at the
last of the sort result for both ascending and descending sort, for both
index/no-index case. Before this change the result for predicate with index
didn't contain the null predicates and the one without index treated nulls as
infinite value - they appeared at the beginning for descending while at the
end for the ascending sort case.
**NOTE: This is a breaking change for the response of sort.**
Co-authored-by: Rajas Vanjape <rajas@dgraph.io>
(cherry picked from commit 85278f8aeb826a5e83c1de18310ab615572a62bf)
--- …
> release/v20.11 - fix(sort): Make sort consistent for indexed and without indexed predicates (#7241)

- posting/list.go
- posting/mvcc.go
ISSUE:
In a load that has a lot of updations to a key, a lot of deltas accumulate over time. These keys are added to the batch for a rollup. Due to the lossy behavior of rollups, they get dropped while the dgraph is busy rolling up keys (that might have much smaller delta count).
FIX:
We now add keys to rollupBatch just after pushing the deltas over to badger.
We now have a priority inside the keys that we rollup. The keys for which the deltas have increased up to a certain limit (hard-coded 500), we add it to high priority rollupKeyPool so that it has high chances to get rolled up and does not get dropped due to lossy behavior of rollups.
Co-authored-by: Manish R Jain <manish@dgraph.io>
Co-authored-by: NamanJain8 <jnaman806@gmail.com>
(cherry picked from commit …
> release/v20.11: opt(rollup): change the way rollups are done

- worker/executor.go
The operations on inDeg field of mutation struct should be done atomically because
it is being used to check if a mutation in dependent on any other mutation. And the
mutations are run concurrently, so this update/read on inDeg should be protected.
(cherry picked from commit 49fd1f466a07808d46f8047f19c51fb357072217)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7307)
> Release/v20.11 - fix(ludicrous): Fix data race in executor (#7203)

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/resolve/resolver.go
Fixes GRAPHQL-921
The first mutation below will now return the "Mutation" type, which previously was giving an error.
Mutation:
```
mutation {
__typename
addpost1(input: [{title: "Dgraph", numLikes: 92233720 }]) {
post1 {
title
numLikes
}
}
}
`Response:`
{
"__typename":"Mutation",
"addpost1": {
"post1": [{
"title": "Dgraph",
"numLikes": 92233720
}]
}
}
```
(cherry picked from commit b6edc7e0de203241f8f205e1b6ed6517dc3e149b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7303)
> fix(GraphQL): This PR allow to use __typename in mutation. (#7285)

- dgraph/cmd/alpha/run.go
- edgraph/graphql.go
- edgraph/server.go
- ee/acl/acl_test.go
- graphql/admin/cors.go
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema_response.json
- schema/schema.go
- systest/backup/encryption/backup_test.go
- systest/backup/filesystem/backup_test.go
- systest/backup/minio/backup_test.go
- systest/export/export_test.go
- testutil/schema.go
- worker/graphql_schema.go
- x/keys.go
Fixes GRAPHQL-948
We already fixed the issue which causes dgraph to have multiple schema or cores nodes. But there are some cases in which this bug can occur again, for example, someone restored a backup that was taken before the fix. This bug continuously fill the logs on alpha and blocks graphql layer. Then we can't do mutate/query or add schema.
Now, we are changing this behavior, if we have multiple schema or cores nodes then we will select the one which was added last.
In addition to it, we are adding dgraph.type.cors type to to the dgraph.cors node, which allow us to use delete (S * *) type mutation on it, in case we want to delete extra node manually.
(cherry picked from commit fde103177002cb0965b3163ebfcab010e6399e94)
--- …
> Fix(GraphQL): This PR fix multi cors and multi schema nodes issue by selecting one of the latest added nodes, and add dgraph type to cors. (#7270)

- x/x.go
Fixes GRAPHQL-928
This would allow the user to do schema alter operations from the browser when they have Poor Man's auth enabled on Alpha.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7310)
> fix(dgraph): Add X-Dgraph-AuthToken to list of access control allowed headers

- wiki/content/howto/load-balancing-nginx.md
Our current documentation is focused on showing how to set up nginx lb with docker-compose. 
This documentation PR will be useful for users what to set up nginx lb and are starting their Dgraph Cluster using a different deployment method (like systemd)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7291)
> docs: nginx lb for Dgraph Cluster that are not started with docker-compose

- wiki/content/graphql/directives/index.md
Fixes SUCCESS-130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7314)
> docs (chore): Add @include and @skip to the Directives article

- graphql/admin/admin.go
Remove redundant type from `admin.go`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7321)
> chore: Remove persistent types from admin.go

- ee/acl/acl_test.go
- graphql/admin/admin.go
- graphql/admin/backup.go
- graphql/admin/config.go
- graphql/admin/cors.go
- graphql/admin/draining.go
- graphql/admin/export.go
- graphql/admin/health.go
- graphql/admin/list_backups.go
- graphql/admin/login.go
- graphql/admin/restore.go
- graphql/admin/schema.go
- graphql/admin/shutdown.go
- graphql/admin/state.go
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/custom_mutation_test.yaml
- graphql/resolve/custom_query_test.yaml
- graphql/resolve/mutation.go
- graphql/resolve/mutation_test.go
- graphql/resolve/query.go
- graphql/resolve/query_test.go
- graphql/resolve/resolver.go
- graphql/schema/introspection.go
- graphql/schema/response.go
- graphql/schema/wrappers.go
- query/outputnode.go
- query/outputnode_graphql.go
This PR:
* makes the admin server on `/admin` and `@custom(http: {...})` Query/Mutation work through a common pipeline separate from the queries/mutations resolved through Dgraph
* adds scalar coercion to queries resolved through Dgraph
* and, removes completion as a step from resolvers, as it is not needed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7317)
> perf(GraphQL): JSON Part-6: Admin Server and custom HTTP query/mutation are now resolved separately (GRAPHQL-937)

- protos/Makefile
- protos/depcheck.sh
- protos/protos_test.go
If the proto dependencies change, then they need to be fetched first before the
protos can be regenerated. For example, when Badger protos change then this
error can happen:
$ make regenerate
cp: cannot stat '/pb/badgerpb3.proto': No such file or directory
make: *** [Makefile:46: copy-protos] Error 1
Calling `go get` or `go mod tidy` fixes this issue:
$ go mod tidy
...
go: downloading github.com/dgraph-io/badger/v3 v3.0.0-20210113052537-b69163b5c21b
The dependencies need to be fetched in order to pick up the correct proto files
from the `$GOMODCACHE` directory using `go list -m -f "{{.Dir}}"`.
Changes:
* Fetch dependencies (tidy-deps) before regenerating protos.
* Refactor Makefile with `BADGER_PB_VERSION` variable to make it
easier to update Badger version
* Add Go tests to regenerate …
> chore: Fetch dependencies before regenerating protos.

- wiki/content/deploy/decrypt.md
- wiki/content/deploy/dgraph-administration.md
- wiki/content/deploy/production-checklist.md
- wiki/content/deploy/troubleshooting.md
Fixes SUCCESS-262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7297)
> Docs (Admin): Documentation for the "dgraph decrypt" command

- go.mod
- go.sum
This PR brings in fixes from badger:
- 578db8d (HEAD -> release/v3.2011, origin/release/v3.2011) debug(iterator): Add debug logs for iterator crash (#1629) (#1648)
- 8766a64 debug(tableIndex): add debug info for initIndex (#1626) (#1647)
- 84125fa fix(build): fix 32-bit build (#1627) (#1646)
- 1a3dffe fix(table): always sync SST to disk (#1625) (#1645)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7330)
> release/20.11: fix: update badger to bring in latest fixes

- dgraph/cmd/bulk/run.go
This exposes the /jemalloc endpoint to bulk loader's HTTP port.
(cherry picked from commit bec7deaf411bb67e8b0efeeae8a235bf0e9d3014)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7331)
> feat(bulk): Add /jemalloc HTTP endpoint. (#7165)

- posting/list.go
- posting/list_test.go
- x/debug.go
- x/nodebug.go
This PR adds checks for verification of plist's uidpack when dgraph is run in debug mode.
(cherry picked from commit d42f881e43d2aa393cd4ed52b26274eadf28de28)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7332)
> release/v20.11: debug(uidpack): add checks for uid pack in debug mode (#7250)

- xidmap/xidmap.go
Fix memory held by b+ tree even in the reduce phase of bulk loader by bringing
back the change #4738.
(cherry picked from commit cc3dbfa41bc87edb21714c68ba23a00ef4ec593a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7333)
> release/v20.11: fix(bulk): Fix memory held by b+ tree in reduce phase (#7161)

- worker/draft.go
- worker/groups.go
All internal predicates belong to group 1. Set the initial schemas/types directly on all the nodes which belong to group 1 rather than making a raft proposal for them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7324)
> chore(worker): Set initial schema and types directly to group-1 nodes.

- compose/compose.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
- protos/pb/pb.pb.go
- worker/docker-compose.yml
- worker/draft.go
- worker/groups.go
- x/config.go
- x/flags.go
- x/flags_test.go
This PR introduces a new SuperFlag struct, which makes flag handling easier. The setting of the default values for the raft flag is moved within the worker package, so Alpha doesn't need to know about it.
The breaking change here is the move of snapshot_after flag to within raft, considering they are logically together.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7337)
> [Breaking] snapshot_after flag moved inside --raft

- dgraph/cmd/alpha/run.go
- graphql/admin/admin.go
we have changed in Dgraph the way rollups are done in this PR. https://github.com/dgraph-io/dgraph/pull/7253
As a result of it, we were having below unexpected behavior in graphql while updating the schema.
**issue:**
suppose we send below schema requests,
```
1.schema1
2.schema2
```
Badger is supposed to return the following updates to graphql
1.schema1
1.schema1
1.schema1
2.schema2
2.schema2
2.schema2
If we get a schema update that is same as our previous schema then we are already ignoring that 
in graphql.For example, below multiple updates for schema1,schema2 from badger  gets ignored
```
1.schema1  //accepted,new update
2.schema1  //discarded,same as previous
3.schema1  //discarded,same as previous
4.schema1  //discared,same as previous
5.schema2  //accepted,new update 
6.schema2 …
```
> fix(GraphQL):This PR will fix the graphl tests that were failing because of recent change in dgraph. 

- graphql/admin/admin.go
Don't update GraphQL schema if an older version of schema key is received.
(cherry picked from commit cc506cc24e77e5c9cde72e420211a42ab8f53d6d)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7348)
> fix(GraphQL): Fix graphql flaky tests which were caused by receiving extra schema updates  (#7329)

- graphql/dgraph/graphquery.go
- graphql/e2e/auth/schema.graphql
- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/normal/schema.graphql
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
- graphql/resolve/resolver.go
- graphql/resolve/schema.graphql
- graphql/schema/wrappers.go
Fixes GRAPHQL-922.
This PR adds `entity` resolver which resolves `_entities(representation: [Any]!)` queries which are sent by the gateway to the graphql service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7334)
> feat(Apollo): Add "_entities" resolver.

- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/schema/validation_rules.go
The following query was giving panic because here we passed ID as an int which is expected to be a string.
```
query allStories {
queryUser(filter: {
id: 22
}) {
stories {
id
text
}
}
}
```
We now added input coercion so that the ID type value will be coerced to string type. And if we give a slice of integer values
to ID type variable then that will be coerced to slice of integer values.
(cherry picked from commit 5fa67969890d05a4a069ca25f5216f14dcb8ae36)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7353)
> fix(GraphQl):This PR fix a panic when we pass a single ID as a integer and expected type is [ID].We now coerce that to type array of string.  (#7325)

- dgraph/cmd/alpha/run.go
- edgraph/access_ee.go
- graphql/admin/admin.go
- x/x.go
**Issue:**
The last KV from the list received from subscription need not be the latest update. This is because of the KVs written at the top due to value log rewrites or due to rollups. 
We were using the last KV from the updates received via subscription.
**Fix:**
Iterate over the KVs to get the KV with the latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7349)
> fix(subscriptions): fix subscription to use the kv with the max version

- dgraph/cmd/alpha/run.go
- edgraph/access_ee.go
- graphql/admin/admin.go
- x/x.go
Issue:
The last KV from the list received from subscription need not be the latest update. This is because of the KVs written at the top due to value log rewrites or due to rollups.
We were using the last KV from the updates received via subscription.
Fix:
Iterate over the KVs to get the KV with the latest version.
(cherry picked from commit 4a2bc363c70e7f0ef8d09d2b6464746ca904a0b0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7355)
> release/v20.11: fix(subscriptions): fix subscription to use the kv with the max version

- codec/codec.go
- dgraph/cmd/bulk/count_index.go
- dgraph/cmd/bulk/reduce.go
- t/t.go
Instead of creating a new z.Allocator for every encoder, this PR reuses the allocator. On a 21M dataset, bulk loader takes 2m22s on master, and only 1m35s on this PR. That's a major 35% performance improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7360)
> Opt(bulk): Reuse z.Allocator

- worker/mutation.go
- x/metrics.go
This PR is a follow-up to https://github.com/dgraph-io/dgraph/pull/7339 to update the way `dgraph_txn_discards_total` and `dgraph_txn_aborts_total` are tracked. When the client calls Discard, only the `dgraph_txn_discards_total` metric is incremented, not `dgraph_txn_aborts_total`. This makes it easy to see:
1. If the client is calling Discard
2. If the server is aborting transactions (e.g., because of transaction conflicts)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7365)
> fix: Calling Discard only adds to txn_discards metric, not txn_aborts.

- graphql/e2e/common/mutation.go
- graphql/e2e/common/query.go
- graphql/resolve/query_rewriter.go
- graphql/schema/testdata/apolloservice/output/auth-directive.graphql
- graphql/schema/testdata/apolloservice/output/custom-directive.graphql
- graphql/schema/testdata/apolloservice/output/extended-types.graphql
- graphql/schema/testdata/apolloservice/output/generate-directive.graphql
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7366)
> fix(Apollo federation): code refractor

- edgraph/server.go
- graphql/dgraph/execute.go
- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/common/query.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/mutation.go
- graphql/resolve/query.go
- graphql/resolve/resolver.go
- graphql/resolve/resolver_error_test.go
- graphql/resolve/resolver_error_test.yaml
- graphql/resolve/resolver_test.go
- graphql/schema/completion.go
- graphql/schema/wrappers.go
- graphql/testdata/custom_bench/profiling/graphql_profiler.go
- query/outputnode.go
- query/outputnode_graphql.go
- x/x.go
This is a cleanup PR for the JSON changes. It is mostly about nit-picks, making some old tests work, skipping some tests to be ported later to e2e and making the CI green overall. It also fixes a [Discuss Issue](https://discuss.dgraph.io/t/custom-field-resolvers-are-not-always-called/12489) (GRAPHQL-989).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7376)
> perf(GraphQL): JSON part-8:  Cleanup and comments (GRAPHQL-947)

- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/http_test.go
Discuss issue: https://discuss.dgraph.io/t/http-api-error-with-drop-operation-with-unexpected/12571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7382)
> fix(jsonpb): use gogo/jsonpb for unmarshalling string

- graphql/e2e/common/error_test.yaml
- graphql/schema/rules.go
- graphql/schema/validation_rules.go
we were having indeterministic behavior in the filter when we have multiple filter functions as below .
```
query {
queryFoo(filter:{value:{eq:2 le:2}})
{
value
}
}
```
It was because we were selecting the first filter function from the list of functions whose order is not guaranteed.
Now we are returning an error for this.
(cherry picked from commit de2f4ab197b45f7cd8ac303f32b62e25f10f2634)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7384)
> fix(GraphQL): Added error for case when multiple filter functions are  used in filter. (#7368)

- contrib/config/monitoring/prometheus/chart-values/dgraph-prometheus-operator.yaml
This is a small update to allow prometheus installed in `monitoring` namespace to find Dgraph in different namespaces.  Before, Dgraph could only be scraped for metrics if it was in the same namespace as prometheus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7394)
> chore: update prometheus operator to work across namespaces

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/e2e/auth/test_data.json
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
cherry picked from commit 8b29efc513cc8c88177b5208fb3892db5602546c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7408)
> cherrypick(GraphQL): fix interface query with auth rules

- dgraph/cmd/zero/run.go
- worker/backup_ee.go
- worker/server_state.go
- x/disk_metrics_linux.go
- x/disk_metrics_others.go
- x/metrics.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7404)
> feat(Monitoring): Adding Monitoring for Disk Space and Number of Backups

- graphql/authorization/auth.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers_test.go
- testutil/graphql.go
Fixes GRAPHQ-960.
This PR ignores the spacing between `#` and `Dgraph.Authorization` in the GraphQL schema. Now the user can give any number of spaces or no space between it. For example, the header `#Dgraph.Authorization.....` will also be valid which was earlier not the case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7410)
> feat(GraphQL): Dgraph.Authorization should with irrespective of number of spaces after #

- go.mod
- go.sum
- graphql/e2e/common/common.go
- graphql/e2e/common/error_test.yaml
- graphql/e2e/common/mutation.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/schema/request.go
Fixes-GRAPHQl-1006
We have moved some of the input coercion code to the library as part of the commit. I have also added tests to verify the fix.
(cherry picked from commit a26993aa18228177f5524cb4f147fa6f9b1454c2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7428)
> fix(GraphQL): Fix panic caused by incorrect input coercion of scalar to list (#7405)

- query/common_test.go
- query/query1_test.go
- systest/mutations_test.go
- types/sort.go
- worker/sort.go
Multi-sort with some predicates with null values was broken ([Discuss post](https://discuss.dgraph.io/t/sorting-on-multiple-predicates-broken-on-20-11-1/12724)). This PR fixes it. 
Tests are also added for multi-sort with null values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7432)
> fix(sort): Fix multi-sort with nils

- query/common_test.go
- query/query1_test.go
- systest/mutations_test.go
- types/sort.go
- worker/sort.go
Fix the behavior of multi-sort. All the nil values are appended at the end of
the result irrespective of ascending or descending sort. This change also
fixes a bug due to not appending the nil values in the values list,
corresponding to the UIDs appended in the UID list with nil predicates.
(cherry picked from commit 2c7de573090f700841b2d9bda2779c48349fedc5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7444)
> fix(sort): Fix multi-sort with nils (#7432)

- edgraph/server.go
- x/jwt_helper.go
This enables user to see state of only its namespace. A; the guardians can see the rest of the fields. Only predicates are filtered out.
Guardian of Galaxy see all namespaces:
```
"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002person_name": {
"groupId": 1,
"predicate": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002person_name",
"force": false,
"onDiskBytes": "0",
"remove": false,
"readOnly": false,
"moveTs": "0",
"uncompressedBytes": "0"
},
```
Non-Galaxy
```
"person_name": {
"groupId": 1,
"predicate": "person_name",
"force": false,
"onDiskBytes": "0",
"remove": false,
"readOnly": false,
"moveTs": "0",
"uncompressedBytes": "0"
}
```
--- …
> fix(state):  make state endpoint return the predicates of requestor's namespace

- edgraph/server.go
- graphql/e2e/common/common.go
- graphql/resolve/resolver.go
- query/outputnode_graphql.go
This PR fixes the following race conditions with GraphQL:
* JSON encoding of `@custom` GraphQL fields: There was one write-write race and two write-read races.
* attaching namespace to context: one write-write race.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7443)
> fix(GraphQL): fix the race conditions in GraphQL (GRAPHQL-1009)

- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/resolve/query.go
- graphql/resolve/resolver.go
This PR makes `@custom(dql: ...)` work again after the GraphQL response JSON generation changes went in and broke it in #7371.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7449)
> fix(GraphQL): fix custom DQL (GRAPHQL-1020)

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/schema.graphql
Currently, in `rewriteObject` function, the fields inside given Add / Update Mutations are sorted before iterating on them and recursively calling `rewriteObject` function. This behaviour ensures that the fields are considered in  the same order in rewriteObject and `existenceQueries` function.
The drawback this as is follows,
1. If a there is a node which is created and referenced in the same mutation, depending on the order in which the nodes (creation and reference) get visited, an error may be thrown.
This issue has been present even before the refactoring. This PR fixes this.
Testing:
Added unit test in .yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7448)
> Feat(GraphQL): Make XID node referencing invariant of order in which XIDs are referenced in Mutation Rewriting

- worker/export.go
- worker/file_handler.go
Fixes DGRAPH-3054
There was a memory leak because the program exits before DB close. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7452)
> fix(export-backup): fix memory leak in export backup

- dgraph/cmd/debug/run.go
- edgraph/access_ee.go
- edgraph/multi_tenancy.go
- edgraph/multi_tenancy_ee.go
- ee/acl/run_ee.go
- ee/acl/utils.go
- graphql/admin/admin.go
- graphql/admin/endpoints_ee.go
- graphql/admin/namespace.go
- x/keys.go
- Fix dgraph debug tool
- Fix `dgraph acl` tool. TODO: Test it.
- Creation of a namespace requires a password to be set for groot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7446)
> feat(acl): allow setting a password at the time of creation of namespace

- worker/backup_processor.go
The recent change https://github.com/dgraph-io/dgraph/pull/7392 improved
the incremental backups but degraded the performance of full backups.
This PR fixes that.
With this PR, we use the thread local iterator only for the incremental
backups. Using the thread local iterator for full backups causes a 10x
slowdown in performance.
Fixes - DGRAPH-3039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7434)
> fix(backup): Fix perf issues with full backups

- worker/file_handler.go
There was a memory leak because the program exits before DB close.
(cherry picked from commit 2eb7bc8772db7a384289ee85fe28e52cf0ea3404)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7453)
> [release/v20.11] fix(export-backup): fix memory leak in backup export (#7452)

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
- ee/audit/audit.go
- ee/audit/audit_ee.go
- ee/audit/interceptor_ee.go
- worker/cdc_ee.go
- worker/config.go
- worker/sink_handler.go
- x/log_writer.go
- x/logger.go
This PR add the support of namespaces in CDC and audits. For audit logs, namespaces will be logged along with all requests. For cdc namespaces will be used as key that will define partitions for the kafka.
This pr also change audit flag to include days and size
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7447)
> chore(enterprise): making cdc and audit to work with multi tenancy + audit flag change with days and size

- worker/backup_handler.go
- worker/file_handler.go
- worker/online_restore_ee.go
- worker/restore.go
- worker/s3_handler.go
Type update expects that the fields of schema key contains the predicate with namespace appended.
When restoring a backup from the old version (say 20.11), we need to do that while restoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7456)
> fix(restore): fix restoring of type keys from old version (20.11)

- ee/audit/run_ee.go
Currently the audit command is not shown when calling the help command (`dgraph -h`). Also we calling the help output for the audit command, the output is messed up:
```
dgraph audit -h 
Usage:
dgraph audit [command] 
Generic:  
Available Commands:
Dgraph Core:  
Data Loading:  
Dgraph Security:  
Dgraph Debug:  
Dgraph Tools:  
Flags:
-h, --help   help for audit
Use "dgraph audit [command] --help" for more information about a command.
```
This PR adds the audit command to the Dgraph Security section in the help output also it also fixes the help output when calling the help command for audit
```
dgraph -h
...
Dgraph Security:  
acl           Run the Dgraph Enterprise Edition ACL tool  
audit         Dgraph audit tool  
cert          Dgraph TLS certificate management           
...
``` …
> dgraph audit commad fix help output

- chunker/json_parser.go
- chunker/json_parser_test.go
- go.mod
- go.sum
Between v20.03 and v20.11 (with https://github.com/dgraph-io/dgraph/pull/5424), dgraph lost the ability to handle deeply-nested uid facets. A JSON mutation with non-nested uid facets looks like this:
```json
{
"set": [{
"title": "parent",
"children": [{
"title": "child",
"children|position": 1
}]
}]
}
```
A mutation with deeply-nested uid facets looks like this:
```json
{
"set": [{
"title": "parent",
"children": [{
"title": "child",
"children|position": 1,
"children": [{
"title": "grandchild",
"children|position": 1
}]
}]
}]
}
```
There's something about trying to set both `children` and `children|position` on the same JSON object that's causing it to error. The equivalent mutation in RDF succeeds:
```
{
set {
<_:parent> <title> "parent" .
<_:parent> <children> <_:child> (position=1) . …
```
> fix(Mutation): Deeply-nested uid facets

- worker/backup_handler.go
- worker/backup_handler_test.go
- worker/s3_handler.go
The list backups function was reading manifest files sequentially and
this is expensive. This PR improves the latency by parallelizing the
list backup calls.
For 10 backups stored in a single s3 bucket, list backups takes 31 seconds on master
```
dgraph lsbackup -l "s3:///amanbansal-test-bucket"  0.90s user 0.20s system 3% cpu 31.356 total
```
On this PR, it takes ~4.5 seconds
```
dgraph lsbackup -l "s3:///amanbansal-test-bucket"  0.74s user 0.08s system 18% cpu 4.566 total
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7435)
> perf(backups): Reduce latency of list backups

- systest/backup/multi-tenancy/backup_test.go
https://github.com/dgraph-io/dgraph/pull/7451 removed `dgraph.graphql.p_sha256hash` predicate.
This PR removes it from the backup test as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7460)
> fix(test): remove `dgraph.graphql.p_sha256hash` predicate from backup test

- graphql/resolve/mutation_rewriter.go
- graphql/schema/testdata/schemagen/output/custom-dql-query-with-subscription.graphql
Fix master build. Master was failing after merging https://github.com/dgraph-io/dgraph/pull/7433 . This fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7462)
> Fix(GraphQL): Fix master build

- ee/backup/run.go
Let `lsbackup` command print the type of the backup.
e.g.
```
dgraph lsbackup -l ~/bkp/dgraph.20210208.123320.782                                  
Page Size: 4096
Listing backups from: /home/omar/Desktop/in_memory/bkp/dgraph.20210208.123320.782
Name	Since	Groups	Encrypted
/home/omar/Desktop/in_memory/bkp/dgraph.20210208.123320.782/manifest.json	5	map[1:[dgraph.graphql.xid dgraph.graphql.schema dgraph.graphql.p_sha256hash dgraph.graphql.schema_history dgraph.graphql.p_query dgraph.drop.op dgraph.graphql.schema_created_at dgraph.type dgraph.cors]]	false	full
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7425)
> added type of backup (full/incremental) for lsbackup

- graphql/admin/admin.go
- graphql/resolve/middlewares.go
APIs like create/delete namespace and reset password should honour ACL.
Fixes DGRAPH-3051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7464)
> fix(acl): make create and delete namespace available only if ACL is enabled

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/license_ee.go
- dgraph/cmd/zero/zero.go
- graphql/admin/shutdown.go
- worker/groups.go
- x/server.go
- x/x.go
A read replica will not be able to connect to zero until zero has a
valid license. If the license expires when the replica is running, the
replica will crash eventually.
Fixes DGRAPH-3000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7454)
> fix(dgraph): Make Read Replica enterprise only feature

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/schema.graphql
After the refactoring of mutation rewriting, references to inverse objects were not ignored in existenceQueries function. This PR fixes this.
This PR fixes https://discuss.dgraph.io/t/bug-not-sure-how-to-name-this-bug-please-help-out/12845 
Testing:
1. Basic yaml tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7469)
> Fix(GraphQL): Ignore redundant references to inverse object in mutation rewriting

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
Currently, if a node with one of the supplied XIDs does not exist also gets updated during Add with Upsert. This should not happen. Value of any of the XIDs should not change during an Upsert Mutation. This PR fixes this.
Testing:
1. yaml test added in add_mutation_test.yaml .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7472)
> Fix(GraphQL): Fix Upsert with Multiple IDs

- graphql/admin/admin.go
If we have multiple alpha groups then sometimes it was happening that some alpha groups start a bit late compared to others.
If we send schema update to cluster it's received through badger subscription in the alpha's which has already started and we update the schema counter for those alphas.
But the alpha's which will start late get it from the DB while starting and in that case, we weren't incrementing the counter and tests were failing.
Now we fixed it by always incrementing the counter for `namespace 0` while starting alpha if there is already schema in DB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7479)
> fix(GraphQL):fix TestSchemaSubscribe test by always incrementing schema counter value on initialization if there is schema in DB.

- graphql/authorization/auth.go
- graphql/e2e/auth/auth_test.go
- graphql/resolve/resolver.go
- graphql/subscription/poller.go
Fixes: [Discuss Issue](https://discuss.dgraph.io/t/authorization-bearer-token/9133).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7490)
> feat(GraphQL): Add support for passing OAuth Bearer token as authorization JWT

- testutil/multi_tenancy.go
ResetAck() runs in a separate go routine on alpha start. https://github.com/dgraph-io/dgraph/blob/c1d74c752092661d1c1af6c6d1d2f9cb413fab88/dgraph/cmd/alpha/run.go#L876-L884
The server is accepting the request even before complete initialization. This leads to the failure of login.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7497)
> chore(tests): retry on login into namespace

- schema/schema.go
- worker/tokens.go
This PR fixes alpha panic when drop operation and the query is run concurrently.
This may happen when some query that needs indexing over this predicate is executing while the predicate is dropped from the state (using drop operation).
```
I0226 23:00:24.621458      20 server.go:406] ALTER op: drop_all:true  done
I0226 23:00:24.623637      20 http.go:586] Got alter request via HTTP from 192.168.64.1:34114
I0226 23:00:24.623778      20 server.go:362] Received ALTER op: drop_all:true 
I0226 23:00:24.623808      20 server.go:1513] Got Alter request from: "192.168.64.1:34114"
I0226 23:00:24.625026      20 access_ee.go:1079] Successfully authorised the guardian of the galaxy
I0226 23:00:24.627030      20 log.go:34] DropAll called. Blocking writes...
I0226 23:00:24.627076      20 log.go:34] …
```
> fix(schema): log error instead of panic if schema not found for predicate

- dgraph/cmd/alpha/metrics_test.go
- x/metrics.go
Expose the Badger metrics for the lsm tree size and vlog size.
* badger_v3_lsm_size_bytes
* badger_v3_vlog_size_bytes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7488)
> fix(metrics): Expose Badger LSM and vlog size bytes.

- dgraph/cmd/alpha/admin.go
- edgraph/access_ee.go
A few admin endpoints such as `/admin/shutdown`, `/admin/drain`, `admin/config` sends a success response even if the server rejects the request. This PR fixes the issue. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7511)
> Fix(admin-endpoints): Error out if the request is rejected by the server

- dgraph/cmd/alpha/metrics_test.go
- x/metrics.go
This renames the Badger metrics in the /metrics endpoint to remove the
Badger version in the metric names. This allows the metric name to
remain the same across Badger major versions.
| Previous Name                   | New Name                     |
| ------------------------------- | ---------------------------- |
| badger_v3_disk_reads_total      | badger_disk_reads_total      |
| badger_v3_disk_writes_total     | badger_disk_writes_total     |
| badger_v3_read_bytes            | badger_read_bytes            |
| badger_v3_written_bytes         | badger_written_bytes         |
| badger_v3_lsm_bloom_hits_total  | badger_lsm_bloom_hits_total  |
| badger_v3_gets_total            | badger_gets_total            |
| badger_v3_puts_total            | badger_puts_total            |
| …
> breaking(metrics): Rename Badger metrics.

- graphql/admin/update_group.go
- graphql/e2e/common/mutation.go
- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/auth_add_test.yaml
- graphql/resolve/mutation_rewriter.go
Fixes GRAPHQL-1052
Testing:
1. Modified yaml tests.
2. Added e2e test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7515)
> Fix(GraphQL): Fix Upsert mutations in case of multiple upserts

- dgraph/cmd/live/batch.go
- dgraph/cmd/live/run.go
- systest/multi-tenancy/basic_test.go
- testutil/bulk.go
Fixes DGRAPH-3075
Earlier, when live-loading data through Guardians of Galaxy, the NQuads make their way to the DB even if the namespace does not exist for them. This might lead to very interesting bugs.
This PR fixes it by extracting the namespaces by querying the schema. If we encounter a Nquad or schema for which namespace does not exist, we error out and live loader stops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7505)
> fix(multi-tenancy): fix live loader for case when namespace does not exist for data

- graphql/e2e/common/mutation.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- graphql/schema/schemagen.go
- graphql/schema/testdata/apolloservice/input/extended-types.graphql
- graphql/schema/testdata/apolloservice/output/extended-types.graphql
- graphql/schema/testdata/schemagen/input/apollo-federation.graphql
- graphql/schema/testdata/schemagen/output/apollo-federation.graphql
- graphql/schema/wrappers.go
Fixes GRAPHQL-1053.
This PR adds support for @provides and @requires directive for Apollo federation according to the [federation specs](https://www.apollographql.com/docs/federation/federation-spec/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7503)
> feat(Apollo): Add support for @provides and @requires directive. 

- schema/schema.go
- worker/tokens.go
This PR fixes alpha panic when drop operation and the query is run concurrently.
This may happen when some query that needs indexing over this predicate is executing while the predicate is dropped from the state (using drop operation).
(cherry picked from commit 96073fcf52c527fa16addf3bc08b6c57100ee73e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7509)
> release/v20.11: fix(schema): log error instead of panic if schema not found for predicate (#7502)

- graphql/e2e/common/common.go
- graphql/e2e/schema/schema_test.go
Motivatoin:
TestLargeSchemaUpdate test was failing when race flag is set to true in "Periodic Test All" tests. This PR reduce the size of large schema from 1000 to 250 fields. It also changes the time out of update gql schema request from 50 seconds to 200 seconds.
It took around 80 seconds for the test to run locally with race = true. The timeout has been set to 200 seconds to keep a buffe on slower machinesr.
Testing:
1. Tested locally with race flag set to true.
2. Tested without the throttling of indexing code (the test fails in this case as expected)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7522)
> Chore(GraphQL): Fix flaky behaviour of TestLargeSchemaUpdate

- dgraph/cmd/live/run.go
- systest/multi-tenancy/basic_test.go
- testutil/bulk.go
This PR fixes the behaviour of `--force-namespace` flag in live loader.
Earlier, we used to silently ignore this flag when passed by the non-galaxy user. Now, we throw an error if the force-namespace flag is used by the non-galaxy user. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7526)
> fix(live): fix usage of force-namespace parameter in live loader

- graphql/admin/admin.go
- graphql/admin/export.go
This PR fixes the `namespace` parameter in export mutation. 
Current behaviour:
- Guardian of galaxy: 
If nothing is passed, exports Galaxy Namespace. If negative value is passed, exports all namespaces, else exports the specified namespace.
- Guardian of other namespace(ns):
If nothing is passed, exports `ns`. If a negative value is passed or the value passed `nsPassed != ns`, error is returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7524)
> fix(export): fix namespace parameter in export

- graphql/dgraph/graphquery.go
- graphql/resolve/query_test.yaml
We were not adding the `, ` in-between multiple orders in query rewriting for the nested field.
For example the order given in this filter 
posts(filter: { title: { anyofterms: "GraphQL" } }, `order: { asc: numLikes, then: { desc: title } }`, first: 10, offset: 10) got written to below dgraph statement
Author.posts : Author.posts @filter(anyofterms(Post.title, "GraphQL")) (`orderasc: Post.numLikesorderdesc: Post.title`, first: 10, offset: 10)
where there is no comma between two orders. We have fixed it in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7523)
> fix(GRAPHQL): fix query rewriting for multiple order on nested field.

- posting/list.go
- posting/list_test.go
This PR fixes the issue of rollups getting hung. it happened because there was no check on the cardinality of the posting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7525)
> Fix(Rollups): Don't try splitting a posting list with cardinality less than 2.

- contrib/release.sh
This is an update to the release.sh to modularize some of the process so that it can be repeated across different GOARCH environments, e.g. `arm64`.
Changes: 
* `build_docker_image()` to encapsulate building docker images
* `build_darwin()`, `build_windows()`, `build_linux()` to encapsulate process for building target platforms
* `build_artifacts()` to encapsulate building binaries on all target, checksum, archive, and docker image.
* added support for `$GOARCH` var for building archives, checksum, docker image, and building binaries with `xgo`
Not Goals:
* command line options for all of these
* updated makefiles and other build scripts outside of release + xgo
* support for arm64 with multi-platform docker images
Issues Found:
* `xgo` can build `amd64`, but has problem with `zstd` on …
> chores(release) - modularized release.sh

- worker/cdc_ee.go
This PR fixes the cdc events in case of drop type or drop predicate.
In case of drop type, there is a nil pointer exception
in case of drop predicate, if there are some pending txns for that predicate, the mutation fails but cdc event was sent. This PR fixes that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7531)
> chore(cdc): fix cdc events for drop type and drop predicate

- graphql/authorization/auth.go
- graphql/resolve/auth_test.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers_test.go
- testutil/graphql.go
Fixes GRAPHQL-1048.
This PR adds support for Passing multiple JWKUrls in the authorization header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7528)
> feat(GraphQL): Allow Multiple JWKUrls for auth.

- graphql/dgraph/graphquery.go
- graphql/resolve/query_test.yaml
We were not adding the , in-between multiple orders in query rewriting for the nested field.
For example the order given in this filter
posts(filter: { title: { anyofterms: "GraphQL" } }, order: { asc: numLikes, then: { desc: title } }, first: 10, offset: 10) got written to below dgraph statement
Author.posts : Author.posts @filter(anyofterms(Post.title, "GraphQL")) (orderasc: Post.numLikesorderdesc: Post.title, first: 10, offset: 10)
where there is no comma between two orders. We have fixed it in this PR.
(cherry picked from commit 8e835f111d0fb5edf24ffde8b8456ed46bd82c08)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7536)
> fix(GRAPHQL): fix query rewriting for multiple order on nested field (#7523)

- gql/parser.go
This PR fixes a wrong error message in DQL query. Consider the following query
```
query {
foo(func: uid("0x1")) {
x: val(math(1))
}
}
```
Before this change:
```
"message": "line 3 column 16: Expected a variable but got comma"
```
After this change:
```
"message": "line 3 column 16: Expected a variable but got 1"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7543)
> Fix(dql): Fix error message in case of wrong argument to val()

- ee/audit/audit_ee.go
- ee/utils_ee.go
- ee/vault/vault_ee.go
- go.mod
- go.sum
- worker/sink_handler.go
- x/tls_helper.go
Use `Getpath()` method for path arguments in the super-flags.
`GetPath()` handles the path in a right way. It does two things more than what `GetString()` does.
1. It resolves `~` to `/home/user`
2. It cleans up the path to shortest absolute path.
Flags affected by this PR
**Zero**
- `--audit`
- `--tls`
**Alpha**
- `--acl`
- `--audit`
- `--cdc`
- `--tls`
- `--vault`
**Bulk, Live and Restore**
- `--tls`
- `--vault`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7541)
> fix(super-flags): Use GetPath for path arguments in superflags

- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/schemagen.go
- graphql/schema/testdata/schemagen/input/field-with-id-directive.graphql
- graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
Currently we add hash index on a field of type String! @id by default. And as index exact and hash are not compatible , user can't add exact index on such field and can't take advantage of comparator functions like lt,le,gt,ge.
To allow this we now changing that behavior, i.e. for a field of type String! @id @search(by:[exact]) , we don't generate default hash index and only generate exact index.
(cherry picked from commit 195f247)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7550)
> fix(GRAPHQL): Added support for exact index on field having @id directive.#7534

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/schema.graphql
We were getting duplicate xid error for the multiple xid fields if `typeName+xidName+xidValue `is same for those fields. The reason for this is that we need to  generate unique query variables for the xids field while doing mutation rewriting and for that we use a map to variable names. 
we were using below key for that map 
`key = typ.FieldOriginatedFrom(xidName)  + xidName + xidVal`
This was generating same key for different xid fields. For example in below type we have two fields with id fields
```
type ABC {
ab: String! @id
abc: String! @id
}
```
And below mutation try to set them such that `key = typ.FieldOriginatedFrom(xidName)  + xidName + xidVal` will be same for both of them i.e. `ABC+ab+cd=ABC+abc+d=ABCabcd`
```
mutation {
addABC(input: [{ ab: "cd", abc: "d" }]) {
aBC {
ab
abc
} …
```
> fix(GRAPHQL): fix duplicate xid error for multiple xid fields.

- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/schemagen.go
- graphql/schema/testdata/schemagen/input/field-with-id-directive.graphql
- graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
Currently we add hash index on a field of type String! @id by default. And as index exact and hash are not compatible , user can't add exact index on such field and can't take advantage of comparator functions like lt,le,gt,ge.
To allow this we now changing that behavior, i.e. for a field of type String! @id @search(by:[exact]) , we don't generate default hash index and only generate exact index.
(cherry picked from commit 195f2474cca437027fe1ad6868f7bcb7b645eb0f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7551)
> fix(GRAPHQL): Added support for exact index on field having @id directive. (#7534)

- dgraph/cmd/live/run.go
- systest/multi-tenancy/basic_test.go
This PR fixes the issue of multiple txn aborts while live loading data with force-namespace enabled. The problem was if it's a galaxy operation, the schema will already have predicates with a namespace prefix. But we were appending it again in the schema.init function thus causing two namespaces in the predicate Name. This results in the wrong generation of conflict keys and thus txn aborts later
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7553)
> chore(live): fixing live loader abort errors when using force-namespace

- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/auth_add_test.yaml
- graphql/resolve/auth_delete_test.yaml
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/auth_update_test.yaml
- graphql/resolve/delete_mutation_test.yaml
- graphql/resolve/extensions_test.go
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/mutation_test.go
- graphql/resolve/query_rewriter.go
- graphql/resolve/resolver_error_test.go
- graphql/resolve/resolver_test.go
- graphql/resolve/schema.graphql
- graphql/resolve/update_mutation_test.yaml
Motivation:
While rewriting GraphQL queries and mutations to DQL, different variable names are used to generate query names, blank node names. Exam ple: While rewriting `addProject` mutation, the variable `Project1` is used while writing existence queries. This is problematic as same variable name could get generated for two different nodes like `Person1` + `1` and `Person` + `11`, both generating `Person11`. 
To avoid this, this PR adds `_` in variable generation between type name and number. 
Testing:
Added test to add_mutation_test.yaml
Fixes GRAPHQL-1079
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7556)
> Fix(GraphQL): Change variable name generation from Type<Num> to Type_<Num>

- dgraph/cmd/alpha/mutations_mode/docker-compose.yml
- dgraph/cmd/alpha/mutations_mode/mutations_mode_test.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/run.go
- dgraph/cmd/zero/run.go
- ee/audit/audit_ee.go
- ee/enc/flags.go
- ee/vault/flags.go
- go.mod
- go.sum
- worker/cdc_ee.go
- worker/draft.go
- worker/server_state.go
- x/config.go
- x/flags.go
- x/sentry_integration.go
- x/tls_helper.go
DGRAPH-3172
| Old Name | New Name | Type | Subcommands |
|--------------:|----------------:|:-------:|:--------------------|
| | **`--telemetry`** | | | |
| `telemetry` | `reports` | bool | alpha, zero |
| `enable_sentry` | `sentry` | bool | alpha, zero |
| | **`--limit`** | | |
| `mutations` | `mutations` | string | alpha |
| | **`--badger`** | | |
| `max_retries` | `max-retries` | int | alpha |
These are the only flag names changed. They've all been moved into their respective SuperFlags, and only `--telemetry` is new. 
**Note**: In DGRAPH-3172 it says to move `max_retries` into `--badger` "only after verifying if that flag is used only in commitToDisk." I made sure the only time the flag is used is [here](https://github.com/dgraph-io/dgraph/blob/8de50d65b99aa6a498b8fe7471ae0864dd3db6e8/ …
> [Breaking] fix(Flags): consolidation and help text improvements

- dgraph/cmd/debuginfo/debugging.go
- dgraph/cmd/debuginfo/run.go
- This PR adds 5 new metrics (/jemalloc, /state, /health, /debug/vars, /metrics) to be collected when running  the `debuginfo` 
- the flag `-p` has been changed to `-m` to reflect the change. This new flag will let you pick up one or multiple metrics/pprof to be collected:
```
-m, --metrics strings    List of metrics & profile to dump in the report. (default [jemalloc,state,health,vars,metrics,heap,cpu_profile,trace,goroutine,threadcreate,block,mutex])
```
- default value of `-s` flag is now 30sec since it requires 30s to collect a cpu profile
- when saving the metric/profile - it will log the metric/profile name and the path where it's saving to.
- added new flag for time based profiles that are cpu and trace profiles:
```
-c, --cron_pprof strings   time-based pprof (default …
```
> feat(cmd/debuginfo) add new metrics to be collected

- dgraph/cmd/debuginfo/debugging.go
- dgraph/cmd/debuginfo/run.go
- This PR adds 5 new metrics (/jemalloc, /state, /health, /debug/vars, /metrics) to be collected when running  the `debuginfo` 
- the flag `-p` has been changed to `-m` to reflect the change. This new flag will let you pick up one or multiple metrics/pprof to be collected:
```
-m, --metrics strings    List of metrics & profile to dump in the report. (default [jemalloc,state,health,vars,metrics,heap,cpu_profile,trace,goroutine,threadcreate,block,mutex])
```
- default value of `-s` flag is now 30sec since it requires 30s to collect a cpu profile
- when saving the metric/profile - it will log the metric/profile name and the path where it's saving to.
- added new flag for time based profiles that are cpu and trace profiles:
```
-c, --cron_pprof strings   time-based pprof (default …
```
> [cherry-pick] feat(cmd/debuginfo) add new metrics to be collected

- dgraph/cmd/alpha/run.go
- edgraph/server.go
- worker/server_state.go
- x/config.go
`disallow-dropall` flag can be used to disallow the drop all operations in the server. If set to true, all the drop-all requests
will be rejected.
To use this option you can start alpha as:
`dgraph alpha --limit="disallow-dropall=true" `
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7549)
> Chore(flags): Add disallow-dropall flag

- telemetry/telemetry.go
Fixes - DGRAPH-2997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7495)
> fix(telemetry): Track enterprise feature usage

- worker/draft.go
When an alpha would restart, it wasn't reconnecting to the learner
nodes. This PR fixes that.
Fixes DGRAPH-3125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7554)
> fix(learner nodes): Reconnect to learner nodes after restart

- edgraph/server.go
- posting/index.go
- worker/groups.go
- x/keys.go
This PR changes the logs to print namespace in human-readable form. This change doesn't fix all of them. 
We have left the cases where we print a struct and the fields in the struct contains predicate with namespace. 
We have also skipped logs of `SubscribeForUpdates` because we can't assume the prefix being logged will always contain namespace. 
This is not exhaustive, it fixes the things which are apparent on basic usage of dgraph. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7552)
> Fix(multi-tenancy): Format namespace to human readable form

- dgraph/cmd/alpha/run.go
- edgraph/server.go
- worker/server_state.go
- x/config.go
Add `disallow-drop` flag which if set to true, then drop-all and drop-data will not be allowed in the alpha node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7566)
> chore(flag): Change disallow-dropall flag to also block drop data operation

- graphql/e2e/common/common.go
- graphql/e2e/common/lambda.go
- graphql/e2e/custom_logic/cmd/main.go
- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/directives/script.js
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/e2e/normal/script.js
- graphql/e2e/schema/apollo_service_response.graphql
- graphql/resolve/query_rewriter.go
- graphql/resolve/resolver.go
- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/schemagen.go
- graphql/schema/testdata/apolloservice/output/auth-directive.graphql
- graphql/schema/testdata/apolloservice/output/custom-directive.graphql
- graphql/schema/testdata/apolloservice/output/extended-types.graphql
- graphql/schema/testdata/apolloservice/output/generate-directive.graphql
- graphql/schema/testdata/apolloservice/output/single-extended-type.graphql
- graphql/schema/wrappers.go
- query/outputnode_graphql.go
This PR makes the `@requires` directive work with `@custom/@lambda` directives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7558)
> fix(GraphQL): Apollo federation now works with lambda (GRAPHQL-1084)

- graphql/e2e/custom_logic/custom_logic_test.go
- graphql/schema/completion.go
This PR fixes the working of `@custom(dql: ...)` with `__typename` and fragments.
Bug Description:
1. Apply GraphQL schema:
```
interface Node {
id: ID!
}
type User implements Node {
name: String
}
type Token implements Node {
key: String
}
type Query {
queryNodeR: [Node] @custom(dql: """
query {
queryNodeR(func: type(Node)) {
dgraph.type
id: uid
name: User.name
key: Token.key
}
} """)
}
```
2. Add data:
```
mutation {
addUser(input: [{name: "User1"}]) {numUids}
addToken(input: [{key: "Token1"}]) {numUids}
}
```
3. Query with both the auto-generated and the custom query and see the difference:
```
query {
queryNode {
id
__typename
... UserFrag
... TokenFrag
}
queryNodeR {
id
__typename
... UserFrag
... TokenFrag
}
}
fragment UserFrag on User {
name
}
fragment TokenFrag on Token {
key
} …
```
> fix(GraphQL): Fix custom(dql: ...) with __typename (GRAPHQL-1098)

- ee/audit/audit_ee.go
- x/keys.go
- x/log_writer.go
- x/logger.go
Fixes DGRAPH-3139.
There were two bugs fixed here:
- The wrong parameter was being passed to `processOldLogFiles` (`l.MaxSize` instead of `l.MaxAge`).
- When formatting the closing timestamp of an audit log file, we use the local timezone. However, when parsing it back, we were assuming a UTC timezone. I changed this to assume local timezone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7567)
> fix(audit): logs not getting deleted after N days

- telemetry/telemetry.go
We are seeing a crash in zero. This PR fixes this.
```
panic: runtime error: integer divide by zero
goroutine 194 [running]:
github.com/dgraph-io/dgraph/worker.(*groupi).connToZeroLeader(0x31c07a0, 0x205af60)
/home/ash/go/src/github.com/dgraph-io/dgraph-release/worker/groups.go:681 +0x452
github.com/dgraph-io/dgraph/worker.(*groupi).askZeroForEE.func1(0xc000136000)
/home/ash/go/src/github.com/dgraph-io/dgraph-release/worker/groups.go:1100 +0x75
github.com/dgraph-io/dgraph/worker.(*groupi).askZeroForEE(0x31c07a0, 0xc0000e6000)
/home/ash/go/src/github.com/dgraph-io/dgraph-release/worker/groups.go:1123 +0xa9
github.com/dgraph-io/dgraph/worker.EnterpriseEnabled(0x12e)
/home/ash/go/src/github.com/dgraph-io/dgraph-release/worker/groups.go:1090 +0x63 …
```
> fix(telemetry): fix crash due to telemetry

- go.mod
- go.sum
- graphql/e2e/common/error_test.yaml
- graphql/schema/validation_rules.go
GraphQL spec doesn't allow any value apart from `integer` to be passed to a variable of type `Int`. So we are disallowing strings to be passed as `Int` variables. Int64 is our own scalar data type, so we continue to accept `string` and `Integer` values for it.
This PR allows passing `strings` to `Int64` values when given directly in query/mutations and disallows `string` to be passed to `Int` in variables.
`So we will have below final behavior: `
```
`Int32` will accept only `Integer` values, and otherwise will give a coercion error.
`Int64` will accept `Integer` as well as `String` value and will return an error if any other value. And if we can only pass Integer in a string like "1234" otherwise it will give a coercion error.
```
`Int coercion rules in GraphQL spec:` …
> [Breaking] fix(GRAPHQL): fix input coercing for integers and make them GraphQL spec complaint.

- graphql/authorization/auth.go
- graphql/resolve/auth_test.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers_test.go
- testutil/graphql.go
(cherry picked from commit f4c857b8eb565e4820405506b2c8e97acc547d28)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7581)
> feat(GraphQL): Allow Multiple JWKUrls for auth. (#7528)

- worker/draft.go
When an alpha would restart, it wasn't reconnecting to the learner
nodes. This PR fixes that.
Fixes DGRAPH-3125
(cherry picked from commit 586181f57abfe719e4e766b4f4be7b99cc55b8e5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7585)
> release/v21.03 - fix(learner nodes): Reconnect to learner nodes after restart (#7554)

- graphql/e2e/common/mutation.go
- graphql/resolve/mutation_rewriter.go
Fixes GRAPHQL-1094.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7565)
> fix(GraphQL): Fix mutation with Int Xid variables.

- worker/graphql_schema.go
we were generating below error message when there is difference in GraphQL and Dgraph schema. It is caused when we are able to change GraphQL schema and there is error from dgraph , and Dgraph schema wasn't changed.
`
resolving updateGQLSchema failed because succeeded in saving GraphQL schema but failed to alter Dgraph schema - this indicates a bug in Dgraph schema generation. Please let us know by filing an issue. Don't forget to post your old and new schemas in the issue description.: Schema change not allowed from scalar to uid or vice versa while there is data for pred: State.country (Locations: [{Line: 3, Column: 4}])`
We now changed this message to below, which removes the bug part because it's not a bug and also added a comment to  prevent this issue.
`
"resolving updateGQLSchema …
> fix(GRAPHQL): fix error message when dgraph and graphql schema differ.

- graphql/e2e/common/mutation.go
- graphql/resolve/mutation_rewriter.go
(cherry picked from commit eb6e27bc02f66d904da9b45c090037065c6da726)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7588)
> fix(GraphQL): Fix mutation with Int Xid variables. (#7565)

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/common/query.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/directives/test_data.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/e2e/normal/test_data.json
- graphql/resolve/mutation_rewriter.go
- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- graphql/schema/schemagen.go
- graphql/schema/wrappers.go
Fixes GRAPHQL-1075.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7583)
> fix(GraphQL): remove support of @id directive on Float

- Makefile
- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/run.go
cluster ID flag for providing the same via flag -- reason for dgraph/cmd/zero/run.go changes
provided cluster ID should be set to alphas from Zero.Conf -- reason for dgraph/cmd/zero/raft.go changes
(images aren't made if dir linux already exists, adding -p takes care of it -- reason for Makefile changes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7580)
> clusterID flag added for alpha sentry reports (gql-services)

- edgraph/access.go
- edgraph/graphql.go
- systest/multi-tenancy/basic_test.go
This PR makes Persistent query namespace-aware. Also, there was a bug in a persistent query where an unauthorized user can add persistent queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7570)
> fix(persistent): make persistent query namespace aware

- dgraph/cmd/bulk/run.go
(#7591)
"max-retries=-1" was showing up in the default string for badger in Bulk --help output, despite not being used / applied in Bulk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7592)
> fix(Flags): remove unused badger.max-retries option from bulk command

- x/x.go
This updates the subcommand --help template so that flags like `--config` show
up in the --help output under the "Global Flags:" section.
Example:
$ dgraph alpha --help
...
Global Flags:
--alsologtostderr                  log to standard error as well as files
--bindall                          Use 0.0.0.0 instead of localhost to bind to all addresses on local machine. (default true)
--block_rate int                   Block profiling rate. Must be used along with block profile_mode
--config string                    Configuration file. Takes precedence over default values, but is overridden to values set with environment variables and flags.
--cwd string                       Change working directory to the path specified. The parent must exist.
--expose_trace                     Allow …
> fix(flags): Expose global flags to dgraph subcommands.

- systest/bgindex/count_test.go
- systest/bgindex/parallel_test.go
- systest/bgindex/reverse_test.go
- systest/bgindex/string_test.go
- systest/multi-tenancy/basic_test.go
- t/t.go
- testutil/multi_tenancy.go
This PR fixes multiple test cases like TestLiveLoadMultiTenancy, Error in CreateNamespace, TestCountIndex, TestParallelIndex generally in case of tests when enabled with race flag. 
This also fixes one error in t.go where we are printing dgraph logs whenever a test fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7577)
> chore(test): fixing flaky tests

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/raft.go
- ee/audit/audit.go
- ee/audit/audit_ee.go
- systest/audit/audit_test.go
- systest/audit/docker-compose.yml
- testutil/zero.go
- worker/groups.go
- x/log_writer.go
this PR aims to put exclusive locks on files the alpha or zero opens to add audit logs. each logwriter keeps track of data it adds to the file and thus sharing the same file will break rollup and compression logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7561)
> chore(audit): making audit files unique for each alpha/zero node in a dgraph cluster

- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/input/custom-mutation.graphql
- graphql/schema/testdata/schemagen/output/custom-mutation.graphql
Motivation:
A user had reported panic on schema update. The reason was that `cleanupInput` function cleared any input types which had name of the form, `UpdateTInput` and contained exactly one field. This PR adds extra conditions to ensure that the input type is removed only when its generated by dgraph and contains a field by name, `filter`.
Testing:
Added unit test in graphql/schema/testdata/schemagen
Fixes GRAPHQL-1102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7595)
> Fix(GraphQL): Add extra checks for deleting UpdateTypeInput

- graphql/schema/gqlschema.go
- graphql/schema/testdata/schemagen/input/custom-mutation.graphql
- graphql/schema/testdata/schemagen/output/custom-mutation.graphql
* Add extra checks for deleting UpdateTypeInput
* Address Abhimanyu's comment
(cherry picked from commit ce9f4f553861e384fbbc32d6b0bd767a6b50f968)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7600)
> Fix(GraphQL): Add extra checks for deleting UpdateTypeInput (20.11 cherry-pick)

- worker/draft.go
When a learner node starts and there is no alpha peer then it promotes itself to a normal mode.
This PR makes it crash itself in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7582)
> Don't start a learner node with no peers

- dgraph/cmd/alpha/run.go
- dgraph/cmd/increment/increment.go
- edgraph/server.go
- worker/server_state.go
- x/config.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7603)
> Add mechanism to have a limit on number of pending queries

- ee/vault/vault_ee.go
A recent commit erroneously changed Vault's `flagPath` from `GetString` to `GetPath`. This PR changes it back - Vault paths != UNIX paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7605)
> fix(flags): use GetString for vault path

- ee/backup/run.go
- upgrade/change_list.go
- upgrade/change_v20.03.0.go
- upgrade/change_v20.07.0.go
- upgrade/change_v21.03.0.go
- upgrade/upgrade.go
- upgrade/utils.go
- worker/online_restore_ee.go
- worker/restore.go
- worker/s3_handler.go
Some of the internal predicates have been removed in #7431 and #7451.
When restoring from a backup taken on a version older than 21.03, we should skip restoring them.
Also, its export will fail in data loading(bulk/live load).
Instead of polluting the backup code with the restore fixation logic, we will use the dgraph upgrade tool to do the migration.
When upgrading from version 20.11 to 21.03, the changes of this PR will be applied. It will update the graphql schema with CORS information and drop the depreciated predicates/types. It will also update the persisted query.
This PR also fixes the restored backup when a --upgrade is set to true in the export_backup command. Note that persisted query is not fixed in export_backup.
(cherry picked from commit …
> chore(upgrade): update the upgrade tool for deprecated predicates change (#7486)

- dgraph/cmd/bulk/reduce.go
- go.mod
- go.sum
- worker/file_handler.go
- worker/restore.go
- worker/server_state.go
Cherry-pick of #7415 to release/v20.11.
The write amplification of using value log has been unpredictably high. With this change, we'd use 1MB as ValueThreshold to push as many things as possible into the LSM tree. Previously it was 1KB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7474)
> Use Badger's value log threshold of 1MB (#7415)

- t/t.go
The `--build` flag was missing from the `docker-compose up` command. That flag is required for tests in `graphql/e2e/custom_logic` package.
(cherry picked from commit 1d6e633a6b85286fc2b173bc11790bc802384b59)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7618)
> cherry-pick (master): fix(test): Fix test flakiness (GRAPHQL-1125) (#7615)

- graphql/e2e/common/common.go
- graphql/e2e/common/lambda.go
- query/outputnode_graphql.go
Fixes GRAPHQL-1077.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7610)
> fix(GraphQL): fix lambda querying a lambda field in case of no data.

- dgraph/cmd/bulk/reduce.go
- go.mod
- go.sum
- worker/file_handler.go
- worker/restore.go
- worker/server_state.go
The write amplification of using value log has been unpredictably high. With this change, we'd use 1MB as ValueThreshold to push as many things as possible into the LSM tree. Previously it was 1KB.
Co-authored-by: Manish R Jain <manish@dgraph.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7619)
> Use Badger's value log threshold of 1MB (#7415). (#7474)

- contrib/release.sh
Fix:
* xgo docker image for 1.16.x now uses GOVERSION (before it was statically setting this to 1.16.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7620)
> Chore(release): fix for xgo version to use

- contrib/release.sh
- contrib/release/xgo.Dockerfile
- tools.go
* GOVERSION=1.16.2
* updated release/xgo.Dockerfile and release.sh to support buildarg with GOVERSION
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7624)
> chore(release) - release script update to support GOVERSION for xgo

- graphql/admin/admin.go
- graphql/e2e/multi_tenancy/schema_test.go
- graphql/e2e/schema/schema_test.go
This PR fixes the issue where if you create a new namespace and run a GraphQL query for the newly created namespace without first applying any GraphQL schema, then you would get a `panic` in alpha.
Now, such a query will not result in `panic`, but instead will give back a similar response:
```
{
"errors": [
{
"message": "Not resolving getAuthor. There's no GraphQL schema in Dgraph.  Use the /admin API to add a GraphQL schema"
}
]
}
``` 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7630)
> fix(GraphQL): Fix panic when no schema exists for a new namespace

- go.mod
- go.sum
- graphql/resolve/mutation_rewriter.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
DGRAPH PR Message:
1. Added error handling in gqlparser (https://github.com/dgraph-io/gqlparser/pull/16) and bumped the version of gqlparser used in dgraph. 
2. Removed stray printing of typeName which was polluting the logs
This PR fixes: GRAPHQL 1076, 1122
GQL Parser
No
Fixes 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7612)
> fix(GRAPHQL): Add error handling for unrecognized args to generate directive.

- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/run.go
- edgraph/server.go
- worker/server_state.go
- x/config.go
In the case of a multi-tenant environment, long-running queries by tenants can consume all the resources, starving the request from other tenants. The change adds query-timeout as a config which will be applied to all the query requests sent without timeout param.
Fixes DGRAPH-3184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7599)
> feat(flags): Add query timeout as a limit config

- query/query.go
- query/query0_test.go
Fixes DGRAPH-3211.
This PR fixes 2 bugs related to the @cascade directive.
1- Pagination was not working with `Offset = 0`.
2- @cascade directive not working with sort queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7636)
> fix(Query): Fix cascade pagination with 0 offset.

- edgraph/access_ee.go
- ee/acl/utils.go
- systest/multi-tenancy/basic_test.go
We were fetching the namespace from the `api.LoginRequest.Namespace` even if the user has sent the refresh token. We should not do that and extract the namespace from the refresh token itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7637)
> fix(login): fix login based on refresh token logic

- posting/list.go
- posting/list_test.go
There was an issue with split creation in roll-up. When a part `p` is split 
into two parts say `p1` and `p2` then the first UID of `p2` should be greater
than the last UID of p1. This was being violated because of removing UIDs 
until `maxInt64` instead of `maxUint64` from `p` in order to create `p1`. 
This PR fixes this issue and also removes some unwanted codes. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7609)
> Fix(rollups): Fix splits in roll-up

- dgraph/cmd/alpha/run.go
- dgraph/cmd/debuginfo/run.go
- dgraph/cmd/zero/run.go
- ee/audit/interceptor_ee.go
This PR moves the `/z` and `/jemalloc` endpoints in zero and alpha to 
`/debug/z` and `/debug/jemalloc` respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7641)
> fix(endpoints): Move z and jemalloc endpoints to /debug

- graphql/admin/http.go
- graphql/api/panics.go
- graphql/resolve/resolver.go
This PR adds functionality to log the query and mutations which cause panic in PanicHandler.
Testing:
Tested locally. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7638)
> Fix(GraphQL): Log query along with the panic

- worker/backup_processor.go
- worker/export.go
The export and backup code were using BestCompression and Default
gzip compression levels respectively. We see a 4x speed improvement when
switch from BestCompression to BestSpeed compression level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7643)
> release/v20.11-slash: perf(compression): Use gzip with BestSpeed in export and backup

- systest/online-restore/online_restore_test.go
The switch to an async backup API made the online restore tests flaky, this PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7644)
> chore(test): fix flaky tests for online restore

- graphql/resolve/resolver.go
This adds logging for mutations in case of panic.
Testing:
Tested Locally
```
=== RUN   TestRunAll_Normal/panic_catcher/mutation
E0324 18:20:07.423360  955317 panics.go:34] panic: 
****
this test should trap this panic.
It's working as expected if this message is logged with a stack trace
****.
query: mutation {
addCountry(input: [{ name: "A Country" }]) { country { id } }
}
trace: goroutine 5272 [running]:
```
Fixes GRAPHQL-1062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7646)
> Chore(GraphQL): Fix query logging for mutations in case of panic

- graphql/api/panics.go
- graphql/resolve/resolver.go
- graphql/web/http.go
* Log query along with panic
* Log mutations using panic handler
* Address Abhimanyu's comments
Also logs query for mutation.
(cherry picked from commit 071d5de9da51ec41fe164820829641e219ba4a5c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7645)
> Fix(GraphQL): Log query along with the panic (#7638)

- worker/executor.go
This PR aims to solve the crashes we have seen in ludicrous mode due to type inversion error. One such crash is 
```
I0315 18:37:10.987252      18 log.go:34] 2 [logterm: 45, index: 1734160, vote: 2] rejected MsgPreVote from 1 [logterm: 44, index: 1734158] at term 45
panic: interface conversion: interface {} is string, not time.Time
goroutine 3766 [running]:
github.com/dgraph-io/dgraph/tok.DayTokenizer.Tokens(0x1b661e0, 0xc01646c470, 0x1e, 0x1e, 0xdb1ac1f11fa1c8e2, 0x7f1300000000, 0x1b661e0)
/ext-go/1/src/github.com/dgraph-io/dgraph/tok/tok.go:249 +0x2f8
github.com/dgraph-io/dgraph/tok.BuildTokens(0x1b661e0, 0xc01646c470, 0x1fb6c20, 0x2e2ff78, 0x1fb6c20, 0x2e2ff78, 0xc01646c470, 0x0, 0x0)
/ext-go/1/src/github.com/dgraph-io/dgraph/tok/tok.go:108 +0x63 …
```
> fix(ludicrous_mode): fixing type inversion in ludicrous mode

- worker/task.go
This PR fixes an error returned if there are no uids for geo query.
Query:
```
{
tourist(func: near(loc, [-122.469829, 37.771935], 1000) ) {
name
}
}
```
Expected result:
```json
"data": {
"tourist": []
},
```
Actual result:
```json
"errors": [
{
"message": ": can't find 0th integer in a bitmap with only 0 items",
"extensions": {
"code": "ErrorInvalidRequest"
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7651)
> fix(query): return empty result if nothing found for geo queries

- graphql/resolve/mutation_rewriter.go
Motivation:
After the large refactor of mutation_rewriter.go carried out as part of https://github.com/dgraph-io/dgraph/pull/7409, this PR does some more minor refactoring to Add and Update mutations.
1. Some small functions have been removed.
2. At a few places, arrays were unnecessarily used. They have been replaced with a single element.
3. Added comments.
4. Some repetitive variables have been removed.
This is meant to make code more readable and maintainable.
Testing:
Existing unit tests, e2e tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7653)
> Chore(GraphQL): Minor refactoring of mutation_rewriter.go

- graphql/resolve/extensions_test.go
- graphql/resolve/mutation.go
- graphql/resolve/mutation_rewriter.go
Motivation:
After the recent refactor of Mutation Rewriting, now there is an extra execution of existenceQuery made in case of Add and Update Mutations. These also need to be accounted for in Execution Trace. This PR accomplishes this. It also makes a minor refactoring of a function in mutation_rewriter.go
Testing:
Existing Unit and e2e tests. No tests added.
Fixes GRAPHQL-1129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7656)
> Fix(GraphQL): Fix Execution Trace for Add and Update Mutations

- contrib/config/vault/docker/.env
- contrib/config/vault/docker/README.md
- contrib/config/vault/docker/docker-compose.yaml
* update VAULT_VERSION=latest for vault docker image.
* add instructions for using `bound_cidr_list` role where `sercret-id` is no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7661)
> Chore(vault) - Update with instructions for cidr_bound_list

- posting/mvcc.go
The GetNew function may fetch the posting list from the cache. This
cached copy of the posting list might be still in use at other places
and so we need to acquire a lock on it before we read it.
Fixes DGRAPH-3200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7632)
> fix(postingList): Acquire lock before reading the cached posting list

- worker/backup_handler.go
The directory prefix was not being appended for rename operation. This PR fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7669)
> Fix(backup): Fix rename operation in s3 handler

- query/common_test.go
- query/query.go
- query/query0_test.go
Due to narrowing down the query to only fetch N results from the
postings, some of the queries got broken. Some queries like 
`allofterms` requires fetching all the uids/postings from the posting list 
corresponding to each term relevant to the queries. And then do an
intersection of the results corresponding to each token. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7668)
> fix(query): Fix pagination with match functions

- query/common_test.go
- query/query.go
- query/query0_test.go
Fix queries involving `regexp`, `allofterms`, `alloftext` and `match`
function with pagination. These functions relies on indexes and
needs to fetch postings/uids for each relevant index key to generate
the final result. Remove early pagination for these cases.
(cherry picked from commit e00ed676674eaa53672ddf760e6ddeeab74d10de)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7672)
> cherry-pick v20.11: fix(query): Fix pagination with match functions (#7668)

- CHANGELOG.md
- dgraph/Makefile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7673)
> chore(release): Update CHANGELOG for v20.11.3

- query/aggregator.go
- query/math.go
- query/math_test.go
If an operand is passed to math operations like log (ln, logbase), sqrt, pow  which might result in illegal operation (resulting in NaN) we return 0 instead of an error. This PR fixes that.
Fixes DGRAPH-3150
Operation | Data type | Current behavior | New behavior
-- | -- | -- | -- 
Add | Int64 | Overflow/Underflow | Return error
Sub | Int64 | Overflow/Underflow | Return error
Multiply | Int64 | Overflow/Underflow | Return error | Return error
Pow | Float64 | Fractional power of -ve number returns 0 | Return error
Logbase | Int64 | -ve number returns 0 | Return error
Logbase | Int64 | Log with base 1 returns large float | Return error
Logbase | Float64 | -ve number return 0 | Return error
Logbase | Float64 | Log with base 1 returns large float | Return error
Ln | Int64 | -ve number returns …
> fix(Query): [Breaking] Return error for illegal math operations.

- upgrade/change_v21.03.0.go
- upgrade/upgrade.go
- upgrade/utils.go
For the upgrade in versions <= 20.07, `dgraph upgrade` tool updates the acl relates data. Hence, it had `--acl` flag. With the update of the upgrade tool for 21.03, it should work without ACL as well. This PR adds that support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7674)
> fix(upgrade): make upgrade tool to work with non-acl cluster

- query/common_test.go
- query/query.go
- query/query0_test.go
Fix queries involving `regexp`, `allofterms`, `alloftext` and `match`
function with pagination. These functions relies on indexes and
needs to fetch postings/uids for each relevant index key to generate
the final result. Remove early pagination for these cases.
(cherry picked from commit e00ed676674eaa53672ddf760e6ddeeab74d10de)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7678)
> cherry-pick v20.11/slash: Fix(query): Fix pagination with match functions

- compose/run.sh
Update compose/run.sh wrapper script:
* modularize and handle more error scenarios
* check for requirements (env var, binaries)
* support $GOPATH/bin/linux_amd64/dgraph as well as older path
* support running on darwin (build darwin compose, and build linux dgraph)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7676)
> chore(compose) - update run.sh wrapper script

- compose/compose.go
- dgraph/cmd/alpha/run.go
- worker/docker-compose.yml
- worker/draft.go
- worker/server_state.go
Add a new flag snapshot-after-duration, which will take duration as a value. Raft snapshots will now be taken based on time since the last snapshot or the number of new raft entries. Also, rename snapshot-after to snapshot-after-entries for distinction.
Fixes DGRAPH-3213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7675)
> feat(Flags): [Breaking] Add flag for snapshot duration frequency

- dgraph/cmd/alpha/admin.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/run.go
- worker/config.go
- worker/server_state.go
- worker/worker.go
- x/flags.go
This change introduces **cache** as a superflag, with **size-mb** and **percentage** as subflags for dgraph alphas.
Fixes DGRAPH-3212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7652)
> feat(flags): [Breaking] Add cache superflag for alpha

- codec/codec.go
- dgraph/cmd/increment/increment.go
- dgraph/main.go
- go.mod
- go.sum
- graphql/e2e/common/common.go
- posting/list.go
- posting/list_test.go
- worker/backup.go
- worker/backup_ee.go
- worker/draft.go
- worker/export.go
- worker/restore_map.go
- Gzip compression is slow. For backups, I've switched to using snappy for compression. This change is backwards compatible.
- Refactor how backup reader is generated to deal with the compression that's used for creating backup.
- Avoid creating a z.Buffer for every call to marshal uid list. Instead, reuse the same one over and over.
With these changes, we can backup 150GB of data in ~50 mins on my workstation, using 8 goroutines and under 1.5GB of jemalloc memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7680)
> Opt(Backup): Make backups faster

- compose/compose.go
- contrib/config/backups/client/compose-setup.sh
- contrib/manual_tests/test.sh
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/run.go
- dgraph/cmd/decrypt/decrypt.go
- dgraph/cmd/live/load-uids/load_test.go
- dgraph/cmd/zero/run.go
- dgraph/docker-compose.yml
- edgraph/server.go
- ee/enc/flags.go
- ee/utils.go
- ee/utils_ee.go
- systest/backup/encryption/backup_test.go
- systest/backup/encryption/docker-compose.yml
- systest/online-restore/docker-compose.yml
- testutil/backup.go
- worker/online_restore_ee.go
- worker/server_state.go
- Moves `encryption_key_file` under NEW `encryption` super flag.
- Moves `abort_older_than` flag in alpha as `txn-abort-after` under `--limit` flag.
- Moves `disable_admin_http` flag in zero as `disable-admin-http` under `--limit` flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7681)
> [BREAKING] chore(flags): move encryption_key_file and 2 other flags under superflag

- worker/backup_processor.go
- worker/export.go
The export and backup code were using BestCompression and Default
gzip compression levels respectively. We see a 4x speed improvement when
switching from BestCompression to BestSpeed compression level.
(cherry picked from commit 5676462f3601c641e75576acc45e491bddb06dac)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7683)
> release/v21.03 - perf(compression): Use gzip with BestSpeed in export and backup (#7643)

- worker/backup_processor.go
- worker/export.go
The export and backup code were using BestCompression and Default
gzip compression levels respectively. We see a 4x speed improvement when
switching from BestCompression to BestSpeed compression level.
(cherry picked from commit 5676462f3601c641e75576acc45e491bddb06dac)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7682)
> release/v20.11 - perf(compression): Use gzip with BestSpeed in export and backup (#7643)

- worker/s3_handler.go
The restore fails on S3 when the object is nested (`s3://s3.us-east-1.amazonaws.com/dgraphbucket/abc/xyz`). This PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7686)
> fix(restore): append the object path prefix while reading backup

- query/outputnode.go
- query/query2_test.go
We are generating incorrect order of the fields in a result of the @normalize directive when there are multiple fields with same Alias at nested levels. As a result of that in resulting JSON, the nodes with the same Alias were not converted to list.
For example, if we have below data in dgraph .
```
{
"_id": "Process",
"Name": "Process",
"Extends": {
"_id": "Core/Namespace",
"Name": "Namespace"        
}
}
```
And if we do below query with @recurse and @normalize directive
```
{
item as var(func:eq(_id,"Process"))
b2(func:uid(item))@normalize@recurse {
Name:Name id:_id  Extends
}
}
```
We will get this response from Dgraph where fields with same alias are not together and while converting response to JSON  , we are not able to combine fields with same Alias in a list.
```
"b2": [
{ …
```
> fix(DGRAPH): fix @normalize response when multiple fields at different levels with same alias are selected. (#7639)

- graphql/e2e/common/query.go
- graphql/resolve/resolver.go
Motivation:
Related Discuss Post: https://discuss.dgraph.io/t/dgraph-returns-empty-string-for-typename-when-coupled-with-aggregate-edge/13548 
The PR uses different name for ok variable. The bug occurred because the same variable was used twice. At the time of getting dgraph type from result and getting count result. 
Fixes GRAPHQL-1142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7687)
> Fix(GraphQL): Fix __typename result along with aggregate fields

- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
Fixes GRAPHQL-1140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7689)
> Fix(GraphQL): Fix Schema gen in case of GraphQL fields mapping to reverse Dgraph predicates

- ee/backup/run.go
- worker/backup_manifest.go
- worker/export.go
- x/error.go
Use UriHandler for Export and ExportBackup. This way, we can have unified logic for handling local filesystems, Minio, etc. across backups and exports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7690)
> fix(export): use UriHandler for exports

- x/handlers.go
Our current behaviour of checking if `DirExists` and `FileExists` is inaccurate. This PR fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7704)
> Improve DirExists and FileExists functions

- dgraph/cmd/root.go
- dgraph/cmd/root_test.go
Large JSON integers are not being printed correctly (since JSON doesn't have an actual integer type). This PR provides a best-effort way to convert from JSON floats to SuperFlag integers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7712)
> fix(flags): Convert numbers correctly in SuperFlags

- edgraph/server.go
- query/mutation.go
Multiple entries for the same predicate can lead to inconsistent state, hence adding an error for it instead.
Fixes DGRAPH-3225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7715)
> fix(query): Prevent multiple entries for same predicate in mutations.

- query/query1_test.go
- query/query2_test.go
- query/query3_test.go
- worker/match.go
- worker/task.go
- worker/trigram.go
This change fixes the pagination functioning that used "after" to specify a UID as offset.
Fixes DGRAPH-3222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7700)
> fix(pagination): Fix after for regexp, match functions

- systest/online-restore/online_restore_test.go
- worker/draft.go
- worker/online_restore.go
- worker/online_restore_oss.go
Fixes DGRAPH-3202
We should propose a snapshot immediately after the restore to prevent the restore from being replayed.
Earlier we were trying to that too. Snapshot happens after the restore but that does not actually include the restore proposal as it has not been applied yet (`n.Applied.Done()` is not yet called for that proposal). 
Now, we will first wait for the raft entries to be marked as done and then try to propose the snapshot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7719)
> fix(raftwal): take snapshot after restore

- compose/compose.go
The compose tool now has flags for `--cdc` and `--cdc_consumer`.
* `--cdc` runs Zookeeper and Kafka containers and configures every Alpha to push
CDC events to Kafka
* `--cdc_consumer` runs `kafka-console-consumer.sh` to print out the CDC
events of the dgraph-cdc topic in Kafka. You can skip setting this
flag if you don't need to print out the CDC events.
Example:
cd compose && ./run.sh --cdc --cdc_consumer
dgraph increment --alpha localhost:9180 --num=3
docker logs kafka-consumer
...
{"meta":{"commit_ts":4},"type":"mutation","event":{"operation":"set","uid":1,"attr":"counter.val","value":1,"value_type":"int"}}
{"meta":{"commit_ts":6},"type":"mutation","event":{"operation":"set","uid":1,"attr":"counter.val","value":2,"value_type":"int"}} …
> feat(compose): Add setup for CDC with Kafka.

- compose/compose.go
Add a flag `--hostname` in the compose tool to make the tool generate compose file
with alpha and zero's host using the given hostname. This will allow us to use compose
tool to run a cluster which uses public IP addresses. If `--hostname` is set then the 
internal grpc port (7080) is also exposed.
For example, to connect a learner node running on a different machine:
Step-1: Run a cluster on a public IP with ports exposed.
`go run compose.go -a 1 -z 1 -w --hostname=dgin-foxtrot.corp.dgraph.io`
`docker-compose up`
Step-2: Connect a learner node running on other machine:
`dgraph alpha --raft "learner=true; idx=4; group=1" --my=publicHostname:7080 --zero=dgin-foxtrot.corp.dgraph.io:5080`
--- …
> chore(compose): Add a flag to specify hostname

- worker/cdc_ee.go
- worker/sink_handler.go
This PR sets the namespace in the cdc event metadata.
I've also changed the type of key from `[]byte` to `uint64` because it didn't need to be a `[]byte`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7721)
> fix(cdc): Show namespace info in event meta

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- query/outputnode_graphql.go
Motivation:
Current GraphQL encoding had a bug which led to timing out in case there is an empty list in dataset and it is queried before any non-null field. This fixes this behaviour.
Fixes DGRAPH-3257
Testing:
1. The test times out (as expected) without the change to outputnode_graphql.go
2. The test passes with the change to outputnode_graphql.go 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7726)
> Fix(GraphQL): Fix GraphQL encoding in case of empty list

- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/run.go
- dgraph/cmd/debug/run.go
- dgraph/cmd/decrypt/decrypt.go
- dgraph/cmd/live/run.go
- ee/backup/run.go
- ee/flags.go
- ee/keys.go
- ee/keys_ee.go
- ee/utils_ee.go
- testutil/backup.go
- worker/restore_map.go
Currently, `GetKeys` exits immediately upon error. While this works for most uses, it ends up shutting down the Alpha when a restore request is made with bad input. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7713)
> fix(ee): GetKeys should return an error

- dgraph/cmd/bulk/mapper.go
- dgraph/cmd/bulk/schema.go
- worker/mutation.go
The bulk loader crashes before printing out the correct error message.
See https://discuss.dgraph.io/t/how-to-solve-mutation-conflict/13591/13?u=naman
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7722)
> fix(bulk): throw the error instead of crashing

- ee/backup/run.go
Before lsBackup was using wrong conf for starting profiling. This PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7729)
> fix(lsBackup): Fix profiler conf in lsBackup

- dgraph/cmd/zero/assign.go
- dgraph/cmd/zero/zero_test.go
- testutil/client.go
- xidmap/xidmap.go
Fixes DGRAPH-3262
This PR adds checks to prevent integer overflow in ID lease.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7724)
> fix(lease): prevent ID lease overflow

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- query/outputnode_graphql.go
Fix encoding of graphql results.
Fixes DGRAPH-3257
(cherry picked from commit 9e8ab992b2c38e18f89f40bdb698e272a9c402ce)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7730)
> Fix(GraphQL): Fix GraphQL encoding in case of empty list (#7726)

- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
Motivation:
This adds support for having two GraphQL fields linking to the same reverse edge. This also adds corresponding changes to query_rewriter to filter out only the wanted nodes.
Testing:
1. Add yaml test in query_test.yaml
Fixes GRAPHQL-1140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7728)
> Fix(GraphQL): Add filter in DQL query in case of reverse predicate

- chunker/json_parser.go
- chunker/json_parser_test.go
This is a fix for [this issue found on Friday](https://discuss.dgraph.io/t/critical-bug-node-gets-deleted-completely-if-a-non-existend-facet-is-removed/13741).
**Postmortem**
* With #7171, we [moved facet keys](https://github.com/dgraph-io/dgraph/blob/master/chunker/json_parser.go#L400-L407) from the main `map[string]interface{}` to a separate map for a performance boost. 
* However, in our `buf.checkForDeletion` function we [don't account for facet keys removed from the main map](https://github.com/dgraph-io/dgraph/blob/master/chunker/json_parser.go#L265-L267). 
* For example, this JSON: `{"uid":1000,"doesnt|exist":null}` essentially gets turned into `{"uid":1000}` before it reaches `buf.checkForDeletion`, and since it's a `DeleteNquads` operation, it deletes the entire node.
**Fix**
* …
> fix(Chunker): don't delete node with empty facet in mutation

- dgraph/cmd/zero/assign.go
- xidmap/xidmap.go
Relates to https://github.com/dgraph-io/dgraph/pull/7724
This PR fixes the following case:
If we have a cluster that cannot lease out new UIDs because it has already leased upto its 
max limit. Now, we try to live load the data with the given UIDs and the AssignIds complains
that the limit has reached. Hence, update the xidmap's maxSeenUid and make progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7743)
> fix(live): make live loader progress on a cluster with very high maxUid 

- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/e2e/auth/test_data.json
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
Fixes GRAPHQL-1159.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7740)
> fix(GraphQL): fix auth query rewriting with ID filter

- edgraph/server.go
- graphql/e2e/schema/schema_test.go
See [Discuss Issue](https://discuss.dgraph.io/t/disallow-dql-schema-changes-for-predicates-used-in-graphql-schema/13570) for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7742)
> feat(GraphQL): Disallow DQL schema changes for predicates used in GraphQL schema (DGRAPH-3245)

- chunker/json_parser.go
- chunker/json_parser_test.go
#7737 cherry pick
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7745)
> fix(Chunker): don't delete node with empty facet in mutation (#7737)

- gql/parser.go
- query/query.go
Fixes: https://discuss.dgraph.io/t/pick-random-node/10815
- random nodes can be selected from the graph using `random: <number of nodes>`
- random selection by replacement is used to select nodes
- Since selection is by replacement, you can get duplicates
- No error handling yet in the `applyRandom` function
- Making of new slice in lines 2430-2432 looks a little inefficient, there might a better way to do this.
This is my first PR here (and I'm new to Go), there will be a lot more issues I'm not aware of.
I have only tested this on a basic example from Ratel. This will need a lot more testing.
<details>
<summary>Mutation</summary>
```graphql
{
set {
_:luke <name> "Luke Skywalker" .
_:luke <dgraph.type> "Person" .
_:leia <name> "Princess Leia" .
_:leia <dgraph.type> "Person" .
_:han …
```
> feat(Query): Add random keyword in DQL

- graphql/schema/rules.go
When posting a schema that uses the @lambdaOnMutate directive, this error comes up:
```
{"errors":[{"message":"resolving updateGQLSchema failed because input:1: Type Author: has the @lambdaOnMutate directive, but the –graphql_lambda_url flag wasn't specified during alpha startup.\n (Locations: [{Line: 3, Column: 4}])","extensions":{"code":"Error"}}]}(base)
```
But when we start alpha with the suggested flag, we get:
```
./dgraph alpha --graphql_lambda_url http://127.0.0.1:8686
Error: unknown flag: --graphql_lambda_url
```
This PR fixes the error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7751)
> Fix(graphql): Fix error message of lambdaOnMutate directive

- graphql/schema/rules.go
The error message used to contain `--graphql_lambda_url" flag.
This flags has been deprecated. This change fixes the error
message of lambdaOnMutate directive to contain superflag.
(cherry picked from commit eb7dc76b29bba08680c646f80e0609ab92b8b906)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7754)
> cherry-pick release/v21.03: Fix(graphql): Fix error message of lambdaOnMutate directive  (#7751)

- systest/online-restore/online_restore_test.go
- worker/draft.go
- worker/online_restore.go
- worker/online_restore_ee.go
We should propose a snapshot immediately after the restore to prevent the restore from being replayed.
Earlier we were trying to do that too. Snapshot happens after the restore but that does not actually include the restore proposal as it has not been applied yet (n.Applied.Done() is not yet called for that proposal).
Now, we will first wait for the raft entry to be marked as done and then try to propose the snapshot.
(cherry picked from commit 72cebd1349e21f48e756c9ba9df4cbe98017ae9a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7750)
> release/v21.03: fix(raftwal): take snapshot after restore (#7719)

- systest/export/docker-compose.yml
- systest/export/export_test.go
- worker/export.go
- worker/export_test.go
Consider this data:
```
_:blank-0 <name> "Carol" (initial="C") .
_:blank-0 <dgraph.type> "Person" .
_:blank-0 <friend> _:blank-1 (close="yes") .
_:blank-1 <name> "Daryl" .
_:blank-1 <dgraph.type> "Person" .
```
Currently export generates this JSON for it:
```
[
{"uid":"0x1","name":"Carol","name|initial":"C"},
{"uid":"0x2","name":"Daryl"},
{"uid":"0x1","friend":[{"uid":"0x2"}],"friend|close":"yes"},
{"uid":"0x1","dgraph.type":"Person"},
{"uid":"0x2","dgraph.type":"Person"}
]
```
The above generated JSON is not right. In ` {"uid":"0x1","friend":[{"uid":"0x2"}],"friend|close":"yes"},` , we do not keep a mapping about the facet belongs to which uid in the list. And when this data is loaded, the facets gets lost.
After this change we will get this:
```
[ …
```
> fix(export): Fix facet export of reference type postings to JSON format

- dgraph/cmd/bulk/mapper.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/zero/oracle.go
- dgraph/cmd/zero/run.go
- go.mod
- go.sum
- worker/backup_ee.go
- worker/predicate_move.go
- worker/restore_map.go
- worker/restore_reduce.go
- worker/snapshot.go
- xidmap/trie.go
- xidmap/xidmap.go
Buffers and Trees in Ristretto have been updated to have a more friendly API. This PR brings those changes into Dgraph.
https://github.com/dgraph-io/ristretto/pull/268
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7747)
> Update Ristretto to bring in new Buffer and Tree API

- dgraph/cmd/debug/run.go
There is duplication of code for Histogram. That already exists in z package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7761)
> chore(debug): use z.Histogram in debug tool

- query/groupby.go
- query/query0_test.go
This PR extends support for var inside the @groupby query on a scalar predicate at root.
for example the given query now doesn't result to error:-
```
var(func: ... ) @groupby(age) {
c as count(uid)
}
```
Now the uid variable `c` contains map of uid to count of uids with the same age.
Suppose for the data :-
```{
"uid": "0x1",
"age": 38
},
{
"uid": "0x17",
"age": 15
},
{
"uid": "0x18",
"age": 15
},
{
"uid": "0x19",
"age": 17
}
```
The following groupby query:-
```
var(func: uid(1, 23, 24, 25)) @groupby(age) {
c as count(uid)
}
me(func: uid(c)) {
uid
val(c)
}
```
returns the result:-
```
"data": {
"me": [
{
"uid": "0x1",
"val(c)": 1
},
{
"uid": "0x17",
"val(c)": 2
},
{
"uid": "0x18",
"val(c)": 2
},
{
"uid": "0x19",
"val(c)": 1
}
]
}
```
The behaviour will be the same if there are multiple …
> feat(DQL): @groupby on scalar fields and count duplicate 

- dgraph/cmd/alpha/run.go
- go.mod
- go.sum
- worker/server_state.go
- worker/sink_handler.go
We used to support only the PLAIN mechanism for SASL in cdc-kafka.
This PR adds support for SCRAM-SHA-256 and SCRAM-SHA-512. 
We can specify the mechanism by the `sasl-mechanism` sub flag under the `--cdc` superflag.
I have tested this change on Amazon MKS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7765)
> feat(cdc): Add support for SCRAM SASL mechanism

- dgraph/cmd/alpha/run.go
- go.mod
- go.sum
- worker/server_state.go
- worker/sink_handler.go
We used to support only the PLAIN mechanism for SASL in CDC-Kafka.
This commit adds support for SCRAM-SHA-256 and SCRAM-SHA-512.
(cherry picked from commit 8925049ff80fa7aabaff8dbc64885d8568ddb6be)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7767)
> cherry-pick release/v21.03: feat(cdc): Add support for SCRAM SASL mechanism (#7765)

- dgraph/cmd/alpha/run.go
- go.mod
- go.sum
- worker/server_state.go
- worker/sink_handler.go
We used to support only the PLAIN mechanism for SASL in CDC-Kafka.
This commit adds support for SCRAM-SHA-256 and SCRAM-SHA-512.
(cherry picked from commit 8925049ff80fa7aabaff8dbc64885d8568ddb6be)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7766)
> cherry-pick release/v21.03-slash: feat(cdc): Add support for SCRAM SASL mechanism (#7765)

- graphql/resolve/auth_add_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/auth_update_test.yaml
- graphql/resolve/mutation.go
- graphql/resolve/mutation_rewriter.go
Motivation:
Auth Mutation rewriting tests now also ensure that the mutation returned a false for success in case of error. This PR fixes related tests.
This PR also fixes a potential bug where in in spite of failing on auth, the mutation would have succeeded without throwing an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7768)
> Fix(GraphQL): Make mutation rewriting tests more robust

- graphql/resolve/mutation.go
Motivation:
In case there is an error at the time of CommitOrAbort, wrong error ("authErr") was getting returned. This should have been "err" . As "authErr" was empty, the customer interpreted this as a successful mutation. In reality, the mutation had failed.
This PR fixes this and returns proper error message in case of transaction conflict. User can take corrective action on seeing this.
Fixes GRAPHQL-1168
Testing:
Tested locally that returning of this error recreates the issue mentioned in JIRA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7763)
> Fix(GraphQL): Fix returning of error in case of transaction conflict

- protos/pb.proto
- protos/pb/pb.pb.go
Settings used:
```
{ BasedOnStyle: google }
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7773)
> chore(proto): Format protos using clang-format

- ee/backup/run.go
In case of export backup, in the reduce phase the `kvBuf` is freed by the `(*reducer) Process()` function as a defer. 
`(*bufWriter) Write()` is called  from the `(*reducer) process()` so `(*bufWriter) Write()` doesn't need to free the `kvBuf`.
This PR fixes the issue of double free. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7780)
> fix(export-backup): Fix double free in export backup

- ee/backup/run.go
Fix issue of double-free in export-backup. kvBuf is released by
the reducer so the Writer shouldn't free it.
(cherry picked from commit 00a67d55536b5d49b79b9e9824d308953ef0fecd)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7783)
> release/v21.03-slash: fix(export-backup): Fix double free in export backup (#7780)

- edgraph/server.go
- graphql/resolve/mutation.go
- worker/server_state.go
Fixes GQLSAAS-1290
We were setting the hash after completing the transaction successfully. This leads to the failure of the commit as it won't contain the hash. This PR fixes that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7782)
> fix(txn): ensure that txn hash is set

- edgraph/server.go
We were setting the hash after completing the transaction successfully. This leads to the failure of the commit as it won't contain the hash. This PR fixes that issue.
(cherry picked from commit ae029f0e24189fc28c1dbc0e81bfc3078d4370a1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7784)
> release/v21.03: fix(txn): ensure that txn hash is set (#7782)

- posting/mvcc.go
The GetNew function may fetch the posting list from the cache. This
cached copy of the posting list might be still in use at other places
and so we need to acquire a lock on it before we read it.
Co-authored-by: NamanJain8 <jnaman806@gmail.com>
(cherry picked from commit 3f9effa96a8faff0d78cacc5b323138585727d0b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7671)
> fix(postingList): Acquire lock before reading the cached posting list (#7632)

- edgraph/access.go
- edgraph/access_ee.go
- edgraph/server.go
- posting/index.go
- posting/oracle.go
- systest/backup/multi-tenancy/backup_test.go
- worker/backup_ee.go
- worker/cdc_ee.go
- worker/draft.go
- worker/restore_map.go
This PR makes DropData namespace-aware in a multi-tenant system. Now, guardians of a namespace can call drop data on their namespace. Earlier only the guardian of the galaxy was allowed to do cluster-wide drop operation.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7789)
> feat(multi-tenancy): make drop data namespace aware

- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/run.go
- edgraph/server.go
- graphql/admin/admin.go
- graphql/admin/http.go
This PR replaces a panic with a user-facing error. In addition, it also adds the current namespace in logs where possible. That enables better error debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7791)
> chore(GraphQL): Improvise error logging

- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/run.go
- edgraph/server.go
- graphql/admin/admin.go
- graphql/admin/http.go
This PR replaces a panic with a user-facing error. In addition, it also adds the current namespace in logs where possible. That enables better error debugging.
(cherry picked from commit d2f1d81e46339fe8b87d16284add6a1b92c1f2fc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7793)
> cherry-pick v21.03: chore(GraphQL): Improvise error logging (#7791) (GRAPHQL-1208)

- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/run.go
- edgraph/server.go
- graphql/admin/admin.go
- graphql/admin/http.go
This PR replaces a panic with a user-facing error. In addition, it also adds the current namespace in logs where possible. That enables better error debugging.
(cherry picked from commit d2f1d81e46339fe8b87d16284add6a1b92c1f2fc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7794)
> cherry-pick v21.03-slash: chore(GraphQL): Improvise error logging (#7791) (GRAPHQL-1208)

- dgraph/cmd/alpha/run.go
- edgraph/server.go
- systest/online-restore/docker-compose.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7796)
> chore(graphql): fixing query timeouts for graphql queries too

- dgraph/cmd/live/run.go
Fixes DGRAPH-3285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7798)
> chore: Replace panic in live loader with errors

- dgraph/cmd/zero/tablet.go
- worker/predicate_move.go
Discuss post: https://discuss.dgraph.io/t/13888
Relates to DGRAPH-3321
This PR adds optimization to predicate move by staying in Phase I, it took more than 20 mins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7792)
> opt(predMove): iterate Phase I till there is major data to move

- go.mod
- go.sum
- graphql/admin/http.go
This PR passes the HTTP headers for a subscription request using the `RequestHeader` context key to the `Subscribe` call.
Earlier, the `Header` key in the context supported passing the headers to the `Subscribe` call, but that required one to send an init request for the subscription with the init payload being set to a JSON object representing the `Header`.
It is not possible in Dgraph cloud to modify the request payload, so we need to make this change.
Later, we should find one permanent fix for passing the HTTP headers for subscriptions. Also, our port of the `graphql-transport-ws` lib is far behind the source, so we should update that at some point.
--- …
> fix(GraphQL): Pass on HTTP request headers for subscriptions

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/schema.graphql
- graphql/resolve/update_mutation_test.yaml
Implementation:
This PR adds the implementing type name to the key. This ensures that different variable names are generated for different implementing types of the same interface with same XID (name and value). It also adds an error condition to give error in case two nodes of different types with same XID(with interface=true) flag are added.
It also fixes other bug related to referencing same node with multiple IDs in same mutation.
Testing:
Added yaml and e2e tests.
Note that two tests from yaml tests have been removed as they were wrong.
Fixes GRAPHQL-1164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7776)
> Fix(GraphQL): Fix duplicate XID error in case of interface XIDs

- worker/draft.go
- worker/proposal.go
Cherry-pick of #7741 to release/v20.11-slash.
Each proposal in alpha has a unique key but this unique key is not
guaranteed to be unique. We could end up creating duplicate keys and
these duplicate keys would get ignored in the raft loop.
This PR proposes a different way of creating the proposal keys so that
they are always unique.
Fixes - DGRAPH-3012, CLOUD-376
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7813)
> fix: Prevent proposal from being dropped accidentally (#7741)

- graphql/admin/admin.go
- graphql/admin/state.go
- graphql/e2e/multi_tenancy/multi_tenancy_test.go
- x/keys.go
Motivation:
Currently, there is no way to query namespaces. This adds namespaces field to state. This field can be used to query list of namespaces.
Note that this will output list of namespace only in case the user is an admin user (guardians of galaxy). In all other cases, it will return an empty list. 
Testing:
1. Added e2e test to ensure that namespaces is returned in case user is guardian of galaxy and not returned in case it is not.
Fixes DGRAPH-3310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7808)
> Feat(Multi-tenancy): Add namespaces field to state

- dgraph/Makefile
Before:
Dgraph version   : v20.11.0-g6fbca757f
Dgraph codename  : unnamed
Dgraph SHA-256   : f9e955ff0243bd7a3edab3f87ea78259b237b3bb84f2a270376b8c30294df6df
Commit SHA-1     : 6fbca757f
Commit timestamp : 2021-05-11 23:27:53 +0530
Branch           : master
Go version       : go1.16.3
jemalloc enabled : true
After:
Dgraph version   : v21.07.0-gd2bd8328e
Dgraph codename  : unnamed-mod
Dgraph SHA-256   : ec85ce729e264a4d635bc73066b4c2dea6771f94b27f330147b1f3fef515b7b4
Commit SHA-1     : d2bd8328e
Commit timestamp : 2021-05-13 20:10:40 +0530
Branch           : master
Go version       : go1.16.3
jemalloc enabled : true
Note the change in Dgraph version.
--- …
> Chore(Dgraph): Fix version in info logs while running Dgraph

- contrib/release.sh
- contrib/release/xgo.Dockerfile
- go.mod
- go.sum
- tools.go
Cherry-pick of #7621 to release/v20.11-slash.
Release Script Update:
* Update to release.sh script to include modularized version with support for go1.16.x and arm64 builds.
* GOVERSION set to 1.15.5 as this is version supported with dgraph v20.11.x
* add xgo.Dockerfile to support GOVERSION build arg
* add tools.go so that xgo can be installed with go install
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7819)
> chore(release) - update release.sh with GOVERSION=1.15.5 (#7621)

- schema/schema.go
- worker/snapshot.go
We were not using `stream.SinceTs` in snapshot transfer. Instead, we were using `ChooseKey` to skip the keys with a lesser version. This can be very slow and memory heavy, because we will have to iterate over the entire DB and skip the keys. Using `SinceTs`, we will be skipping the entire table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7826)
> opt(snapshot): optimize snapshot by using sinceTs

- contrib/systemd/centos/dgraph-alpha.service
- contrib/systemd/centos/dgraph-zero.service
Specify the open file descriptors limit to higher than typical default
settings in Linux (1024). This covers cases for larger databases where
there's a sizeable amount of data loaded into Dgraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7831)
> chore(contrib/systemd): Add file descriptors limit.

- edgraph/access_ee.go
- edgraph/server.go
- ee/acl/acl_test.go
Clients like `dgo` rely on GRPC status code for operations in scenarios like relogin if JWT expired. We must preserve the status code while returning and not just wrap it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7832)
> fix(auth): preserve the status code while returning error

- worker/restore_map.go
Fixes DGRAPH-3356
Reset the StreamId for the schema key.
We get the following error in the master while restoring a backup:
```
E0518 15:43:03.303267 2849821 draft.go:728] Applying proposal. Error: while stream writer flush: Levels Controller err: Inter: Biggest(j-1)[2]                                                                                                
00000000  04 00 00 00 00 00 00 00  00 00 0b 64 67 72 61 70  |...........dgrap|                                                                                                                                                                
00000010  68 2e 74 79 70 65 02 02  50 65 72 73 6f 6e bf 98  |h.type..Person..| …
```
> fix(restore): reset the kv.StreamId before sending to stream writer

- worker/restore_map.go
Reset the StreamId for the schema key to prevent ordering issues.
(cherry picked from commit 9557e56d03980fa2df2648f35b2d39b68f34b115)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7837)
> cloud: fix(restore): reset the kv.StreamId before sending to stream writer (#7833)

- ee/updatemanifest/run.go
- worker/backup_manifest.go
- worker/restore_map.go
- x/keys.go
With https://github.com/dgraph-io/dgraph/pull/7810 change, we changed the format of the predicate. We missed updating the schema and predicate. This PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7838)
> fix(restore): update the schema and type from 2103

- edgraph/access_ee.go
- edgraph/server.go
- ee/acl/acl_test.go
Clients like dgo rely on GRPC status code for operations in scenarios like relogin if JWT expired. We must preserve the status code while returning and not just wrap it.
(cherry picked from commit 1a92da4b98957bd4e64262a83203112452df406c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7834)
> cloud: fix(auth): preserve the status code while returning error (#7832)

- worker/restore_map.go
We were not considering the banned namespaces while bumping the lease. So, if we restore a backup with namespace 0,1,2 not-banned and 3,4 banned. We will bump only up to 2. This would error out when creating a namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7839)
> fix(restore): consider the banned namespaces while bumping

- graphql/admin/admin.go
- graphql/e2e/schema/schema_test.go
- worker/export_test.go
The `exportedFiles` field is now removed as part of the move to async tasks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7835)
> fix(admin): remove exportedFiles field

- graphql/admin/admin.go
- graphql/e2e/schema/schema_test.go
- worker/export_test.go
The exportedFiles field is now removed as part of the move to async tasks.
Cherry-picked from https://github.com/dgraph-io/dgraph/pull/7835.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7836)
> release/21.03-slash: fix(admin): remove exportedFiles field

- codec/codec.go
- dgraph/cmd/bulk/count_index.go
- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/debug/run.go
- go.mod
- go.sum
- posting/list.go
- posting/list_test.go
- query/fastjson_test.go
- query/groupby.go
- query/mutation.go
- query/query.go
- query/shortest.go
- worker/match.go
- worker/restore_map.go
- worker/sort.go
- worker/task.go
- worker/trigram.go
This PR replaces roaring64 with sroar in Dgraph. A bunch of things might slow down after this change because we are yet to optimize sroar's functionalities. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7840)
> feat(sroar): Bring sroar to Dgraph

- edgraph/multi_tenancy_ee.go
- worker/draft.go
- worker/mutation.go
We were starting `opIndexing` while schema update irrespective of whether index building is required or not. 
This caused Dgraph to be unable to create namespace while backup (or in fact any other conflicting task with opIndexing) is running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7845)
> fix(schema-update): Start opIndexing only when index creation is required.

- edgraph/server.go
Adds a `ns` attribute to traces for `doQuery` and `Server.CommitOrAbort`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7850)
> chore(tracing): Add ns attribute to doQuery

- edgraph/server.go
(cherry picked from commit b80efb69e0b61132aec9dbebbb00177324faf774)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7853)
> release/v21.03-slash: chore(tracing): Add ns attribute to doQuery (#7850)

- graphql/dgraph/graphquery.go
- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/schema.graphql
- graphql/resolve/auth_test.go
- graphql/resolve/custom_auth_query_test.yaml
- graphql/resolve/mutation_rewriter.go
- graphql/resolve/query.go
- graphql/resolve/query_rewriter.go
- graphql/resolve/resolver.go
- graphql/schema/wrappers.go
Fixes GRAPHQL-1171.
This PR adds support for @auth on custom DQL queries.
This PR also adds the parsing step to the DQL query.
The Algorithm tries to figure out the `queried type` at the root of the query either from the `root func` or `filters`.
Suppose if the root func is `func: type(Person)` or `func: has(Person.name)` or `func: eq(Person.age, 10)` then 
it infers that the queried type is `Person`. 
However, there are certain DQL queries on which @auth rules are not added currently since the queried type is not clear. 
for eg: 
```
me(func: uid(0x1, 0x2)) {
...
}
```
or the query:
```
me(func: has(name@en) {
...
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/777 …
> feat(GraphQL): Support auth with custom DQL

- posting/index.go
- schema/schema.go
- systest/backup/encryption/backup_test.go
- systest/backup/filesystem/backup_test.go
- systest/backup/minio-large/backup_test.go
- systest/backup/minio/backup_test.go
- testutil/backup.go
- worker/backup_ee.go
- worker/draft.go
- worker/groups.go
- worker/mutation.go
- worker/predicate_move.go
- worker/snapshot.go
**Issue:**
We used to write schema/types at `timestamp=1`. That single bit violates the Snapshot Isolation. Hence, we couldn't run schema updates and other operations like backup concurrently. This is an issue in a multi-tenant cluster because if the backup is running we couldn't update the schema. 
**Fix:**
This PR writes the schema/types at the `startTs` of the transaction and enables the schema updates to be made even if the backup is running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7852)
> feat(schema): do schema versioning and make backup non-blocking for indexing

- worker/predicate_move.go
In predicate move, we were using `kv.Version` while writing the schema at receiver, but we delete the schema at `in.ReadTs`. This fails when we move the same tablet from Group 1 -> Group 2 -> Group 1 if the schema for that predicate doesn't change between those 2 moves. 
This happens because the schema written at t1 was cleaned at timestamp t2 (t2>t1) while doing 1st predicate move. And in 2nd predicate move (G2 -> G1), we were writing the schema back at timestamp t1. Hence, the schema was written below the discard timestamp t2 and does not gets reflected. 
(cherry picked from commit 64b71b6b80aff7c52d5a514c550e45c60ae04d6e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph …
> fix(predMove): use the predicate move timestamp to write the schema 

- ee/backup/run.go
- graphql/admin/list_backups.go
- worker/backup.go
- worker/backup_ee.go
- worker/backup_manifest.go
- worker/online_restore.go
- worker/restore_map.go
This PR has the following changes
- Use thread-local buffer for codecs (Not applicable to the cherry pick)
- Add new ReadTs field to Manifest and use it instead of sinceTs
- Use snappy for backups (Not applicable to the cherry pick)
(cherry picked from commit 2715d88571950835ac3743a0656777fb5e7f1014)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7863)
> fix(Backup): use validReadTs from manifest for backward compatibility (#7601)

- dgraph/cmd/debug/wal.go
(cherry picked from commit d6d768db97cc796e1e42e1c098ca8217c7b77703)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7861)
> chore(debug): Print proposal key. (#7857)

- dgraph/cmd/debug/wal.go
(cherry picked from commit d6d768db97cc796e1e42e1c098ca8217c7b77703)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7860)
> release/v21.03-slash: chore(debug): Print proposal key. (#7857)

- dgraph/cmd/debug/wal.go
(cherry picked from commit d6d768db97cc796e1e42e1c098ca8217c7b77703)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7859)
> release/v21.03: chore(debug): Print proposal key. (#7857)

- go.mod
- go.sum
- worker/snapshot.go
When streaming the entire data in the snapshot (`snap.SinceTs=0`), we can do an entire table copy instead of iterating over the KVs. This brings about 3x performance improvement, as well as the CPU of the sender, is idle. Refer https://github.com/dgraph-io/badger/pull/1700 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7870)
> opt(snapshot): use full table copy when streaming the entire data

- compose/compose.go
Modified compose.go file to accept alias and custom alpha flags:
1. `--alias` - alias for the containers
2. `--custom_alpha_flags` Custom alpha flags for specific alphas, following {"1:custom_flags", "2:custom_flags"},
eg: {"2: -p <bulk_path>"}
`go run compose.go -a=2 -z=1 --alias=test --custom_alpha_flags={"2:-p <bulk_path>"}`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7872)
> compose.go changes

- dgraph/cmd/alpha/run.go
- edgraph/server.go
* fixing query timeouts for graphql queries too
* fixing online restore test
(cherry picked from commit bb0358e6db5e0731023af4d7a1163d1227959133)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7874)
> cherry-pick: chore(graphql): fixing query timeouts for graphql queries too (#7796)

- dgraph/cmd/alpha/admin.go
- dgraph/cmd/alpha/admin_backup.go
- graphql/admin/admin.go
- graphql/admin/export.go
- graphql/e2e/schema/schema_test.go
- systest/export/export_test.go
- worker/export_test.go
21.03.0 has async backups, but not exports. An earlier cherry-pick moved the async backups onto the async Task framework, but also made exports async, which breaks backwards compatibility.
This PR is a temporary fix to make exports sync just for 21.03.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7877)
> release/21.03: make exports synchronous again

- worker/restore_map.go
When restoring from backup taken on version `<v21.03`, we should append the galaxy namespace to the typename. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7880)
> fix(restore): append galaxy namespace to type name

- worker/restore_map.go
When restoring from backup taken on version <v21.03, we should append the galaxy namespace to the typename.
(cherry picked from commit 624202e13e1ef9c11511d7fe6db0cac06c3d8ed9)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7882)
> cloud: fix(restore): append galaxy namespace to type name (#7880)

- graphql/authorization/auth.go
- graphql/schema/schemagen.go
Fixes DGRAPH-3392.
This has been manually tested. This issue does not exist in `21.03` and is only present in previous versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7884)
> fix(GraphQL): fix JWT token error when Authorization is not enabled.

- query/query.go
- query/query0_test.go
Fixes DGRAPH-3370.
This PR reverts the change related to `cascade with sort` which is currently causing panic on the master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7885)
> fix(DQL): revert changes related to cascade pagination with sort

- query/query.go
- query/query0_test.go
Fixes DGRAPH-3370.
This PR reverts the change related to `cascade with sort` which is currently causing panic on the master.
(cherry picked from commit 5ae487fd4c7a9c7e7ce2263bec750eb33e386aec)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7888)
> fix(DQL): revert changes related to cascade pagination with sort (#7885)

- graphql/resolve/mutation.go
(cherry picked from commit b0aa7973da734e16c38f369a19f7023a51ae7776)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7894)
> [cherry-pick] Fix returning of error in case of transaction conflict (#7763)

- dgraph/cmd/debug/run.go
Add `--only-summary` flag in `dgraph debug` to show LSM tree and namespace sizes.
Sample:
```
[SUMMARY]
Level 0 size:       31 KiB
Level 1 size:          0 B
Level 2 size:          0 B
Level 3 size:          0 B
Level 4 size:          0 B
Level 5 size:      710 MiB
Level 6 size:      7.0 GiB
Total SST size:      7.6 GiB
Namespace 0x95 size:      1.6 GiB
Namespace 0x27 size:      1.3 GiB
Namespace 0x28 size:       16 MiB (banned)
Namespace 0x18 size:       46 MiB (banned)
Namespace 0x76 size:       32 MiB (banned)
Namespace 0x93 size:      1.6 GiB
Namespace 0x90 size:      291 MiB (banned)
Namespace 0x91 size:      2.2 GiB (banned)
Namespace 0x4a size:      222 MiB (banned)
Namespace 0x5d size:       15 MiB (banned)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> chore(debug): add summary to show LSM tree and namespace size

- README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7685)
> (docs) Update README - remove macOS build references

- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
Fixes GQLSAAS-1236.
This PR optimizes `eq` filter GraphQL queries.
For ex:
The below DQL query:
```
query {
queryPerson(filter: {nick: {eq: "Dgraph"}}){
id
name
nick
}
}
```
will now be written into:
```
query {
queryPerson(func: eq(Person.nick, "Dgraph")) @filter(type(Person)) {
Person.id : uid
Person.name : Person.name
Person.nick : Person.nick
}
}
```
which was earlier written into:-
```
query {
queryPerson(func: type(Person)) @filter(eq(Person.nick, "Dgraph")){
Person.id : uid
Person.name : Person.name
Person.nick : Person.nick
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7895)
> fix(GraphQL): optimize eq filter queries

- worker/restore_map.go
We should not try to ban the namespace while doing export_backup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7896)
> fix(export_backup): Do not try banning namespace in export_backup

- dgraph/cmd/debug/wal.go
Check for the length of wal entry's data before parsing it for key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7898)
> fix(debug): Check length of wal entry before parsing

- codec/codec.go
- query/query.go
We should consider the state of UIdMatrix (whether it was in the form of SortedUids or bitmap) in order to set the result after pagination. Pagination with cascade is handled separately, where it is possible to have no order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7902)
> fix(sroar): Fix TestAuthWithCustomDQL failure because of roaring bitmaps

- x/metrics.go
We've been tracking this metric but didn't actually expose it in the metrics
view, so Prometheus metrics in /metrics never showed it.
This change updates sets the view properly so it shows up in /metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7900)
> fix(metrics): Expose dgraph_num_backups_failed_total metric view.

- conn/node.go
When streaming raft messages in k8s cluster, we don't seem to get an
error if the send didn't succeed. The packets get queued up, but don't
fail and don't get sent. This causes a long re-election process.
This PR periodically tries to send a message to the destination node via
IsPeer, so it has another way to test the connection. If that fails, the
streaming fails too, and the node is marked as unreachable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7906)
> release/v20.11: fix(Raft): Detect network partition when streaming

- conn/node.go
When streaming raft messages in k8s cluster, we don't seem to get an
error if the send didn't succeed. The packets get queued up, but don't
fail and don't get sent. This causes a long re-election process.
This PR periodically tries to send a message to the destination node via
IsPeer, so it has another way to test the connection. If that fails, the
streaming fails too, and the node is marked as unreachable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7908)
> release/v21.03: fix(Raft): Detect network partition when streaming

- conn/node.go
When streaming raft messages in k8s cluster, we don't seem to get an
error if the send didn't succeed. The packets get queued up, but don't
fail and don't get sent. This causes a long re-election process.
This PR periodically tries to send a message to the destination node via
IsPeer, so it has another way to test the connection. If that fails, the
streaming fails too, and the node is marked as unreachable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7909)
> release/v21.03-slash: fix(Raft): Detect network partition when streaming

- conn/node.go
- systest/online-restore/docker-compose.yml
When streaming raft messages in k8s cluster, we don't seem to get an
error if the send didn't succeed. The packets get queued up, but don't
fail and don't get sent. This causes a long re-election process.
This PR periodically tries to send a message to the destination node via
IsPeer, so it has another way to test the connection. If that fails, the
streaming fails too, and the node is marked as unreachable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7907)
> release/v20.11-slash: fix(Raft): Detect network partition when streaming

- conn/pool.go
In case the heartbeats in a connection pool stop, try to re-establish the connection via a re-dial. That's a more robust way than waiting for current connection to become usable again. This allow much faster recovery from network partitions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7918)
> fix(conn): Reconnect via a redial

- conn/pool.go
In case the heartbeats in a connection pool stop, try to re-establish the connection via a redial. That's a more robust way than waiting for current connection to become usable again and allows much faster recovery from network partitions.
(cherry picked from commit 947a62bdc0526caa1985f2e39e6a5525118aaaab)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7921)
> Reconnect via a redial in case of disconnection. (#7918)

- graphql/schema/schemagen.go
Fixes DO-13.
This PR fixes validation for `extend type Query` or `extend type Mutation` defined in the schema for the custom queries and mutation mentioned which was earlier resulting in error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7916)
> fix(GraphQL): handle extend keyword for Queries and Mutations

- dgraph/cmd/bulk/mapper.go
- dgraph/cmd/bulk/run.go
- edgraph/access_ee.go
- ee/acl/run.go
Earlier, whenever the alpha starts(or restarts), we were upserting guardian and groot for all the namespaces. This is not actually needed.
The change was made in the PR https://github.com/dgraph-io/dgraph/pull/7759 to fix a bulk loader edge case. 
This PR fixes that by generating the required RDFs in the bulk loader itself. Essentially, it inserts the ACL RDFs when force loading into non-Galaxy namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7917)
> fix(groot): do not upsert groot for all namespaces on restart

- dgraph/cmd/bulk/mapper.go
- dgraph/cmd/bulk/run.go
- edgraph/access_ee.go
- ee/acl/run.go
Earlier, whenever the alpha starts(or restarts), we were upserting guardian and groot for all the namespaces. This is not actually needed.
The change was made in the PR #7759 to fix a bulk loader edge case.
This PR fixes that by generating the required RDFs in the bulk loader itself. Essentially, it inserts the ACL RDFs when force loading into non-Galaxy namespace.
(cherry picked from commit 6730f10b62da7c7dc3bf5985ef957f08d3c733b4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7924)
> cloud: fix(groot): do not upsert groot for all namespaces on restart (#7917)

- dgraph/cmd/debug/run.go
Earlier we were showing the opposite status: unbanned namespaces were shown as
banned. This change fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7928)
> fix(cmd/debug): Print banned namespaces correctly.

- ee/audit/interceptor_ee.go
- graphql/admin/admin.go
- graphql/admin/restore.go
- graphql/admin/schema.go
- worker/graphql_schema.go
- worker/online_restore.go
1. The issue is graphql layer relies upon the badger subscribe events to update the inmemory schema. But with new restore changes, where stream is used to backups, there were no subscribed updated events for the graphql layer. 
Hence after restores, gql schema was not getting updated. This PR refreshed the gql schema if there is a successful restore operation. One thing is dgraph stores schema in memory. This PR only makes the current node to refresh the inmemory state of schema. Now restore operation runs on every node. Therefore in the end each node will refresh its schema and thus returns to the stable state.
2. Skipping /probe/graphql from audit as this is used by cloud to check pods health status
--- …
> fix: fixing graphql schema update when the data is restored + skipping /probe/graphql from audit

- graphql/admin/backup.go
The `ForceFull` parameter was not being passed in the backup request queue, causing all the backups to be incremental despite the request with `forceFull=True`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7932)
> fix(backup): Fix full backup request

- worker/restore_map.go
The kv version should be set to restore timestamp for rolled-up keys and schema keys as well.
NOTE: I need to double-check if writing schema to restoreTs is right thing to do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7930)
> fix(restore): Set kv version to restoreTs for rolled up keys and schema keys

- graphql/admin/backup.go
The ForceFull parameter was not being passed in the backup request queue,
causing all the backups to be incremental despite the request with `forceFull=True`.
This commit fixes this issue.
(cherry picked from commit 8d08cc3368e0aa0113080923772c32593073efbc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7933)
> cloud: fix(backup): Fix full backup request (#7932)

- worker/restore_map.go
The kv version should be set to restore timestamp for rolled-up keys
and schema keys as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7935)
> fix(restore): Set kv version to restoreTs for rolled up keys and schema keys (#7930)

- graphql/admin/backup.go
The ForceFull parameter was not being passed in the backup request queue,
causing all the backups to be incremental despite the request with `forceFull=True`.
This commit fixes this issue.
(cherry picked from commit 8d08cc3368e0aa0113080923772c32593073efbc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7934)
> release/v21.03: fix(backup): Fix full backup request (#7932)

- graphql/admin/admin.go
- graphql/admin/state.go
- graphql/e2e/multi_tenancy/multi_tenancy_test.go
- x/keys.go
Motivation:
Currently, there is no way to query namespaces. This adds namespaces field to state. This field can be used to query list of namespaces.
Note that this will output list of namespace only in case the user is an admin user (guardians of galaxy). In all other cases, it will return an empty list.
(cherry picked from commit d2bd8328e6534dc7c894a4a9727a34674da0fd11)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7936)
> [cherry-pick] Add namespaces field to state

- graphql/admin/admin.go
- graphql/admin/state.go
- graphql/e2e/multi_tenancy/multi_tenancy_test.go
- x/keys.go
Motivation:
Currently, there is no way to query namespaces. This adds namespaces field to state. This field can be used to query list of namespaces.
Note that this will output list of namespace only in case the user is an admin user (guardians of galaxy). In all other cases, it will return an empty list.
(cherry picked from commit d2bd8328e6534dc7c894a4a9727a34674da0fd11)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7937)
> [cherry-pick] CLOUD: Add namespaces field to state

- schema/schema.go
- worker/groups.go
For big datasets, we're seeing a big slowdown due to loading schema and types serially using a single iterator. Using the Stream framework, makes this metadata loading step much faster, resulting in a much faster Alpha initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7938)
> opt(Alpha): Load schema and types using Stream framework

- schema/schema.go
- worker/groups.go
For big datasets, we're seeing a big slowdown due to loading schema and types serially using a single iterator. Using the Stream framework, makes this metadata loading step much faster, resulting in a much faster Alpha initialization.
(cherry picked from commit d03d5ad14e8ec5044d1e7f16c8be271d890346f1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7940)
> opt(Alpha): Load schema and types using Stream framework (#7938)

- dgraph/cmd/increment/increment.go
This PR fixes the example for `--cloud` command for `dgraph increment` by replacing the `:` with the `=` sign
Current syntax:
```
--cloud "addr: <endpoint>; jwt: <JWT>
```
Correct syntax:
```
--cloud "addr=<endpoint>; jwt=<JWT>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7903)
> Fix example for --cloud command for dgraph increment

- go.mod
- go.sum
Protobuf 1.4.x is not compatible with gogo-generated protos.
There were some improvements in 1.5.1 protobuf runtime that enabled some basic compatibility. Upgrading the protobuf version should fix some of the compatibility issues.
It fixes this crash.
```
panic: field raftpb.Entry.Type has invalid type: got raftpb.EntryType, want pointer
goroutine 294 [running]:
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x23a3c38, 0xc006734000, 0x1e17763, 0x4, 0x0, 0x0, 0x23a3d48, 0x1e8c900, 0x1e17769, 0x43, ...)
/home/dmai/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_field.go:228 +0x7f7
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc000152000, 0xffffffffffffffff, 0xffffffffffffffff, 0x30, 0xffffffffffffffff, 0xc0061f9c80, …
```
> protobuf: upgrade golang/protobuf library

- dgraph/cmd/zero/raft.go
- worker/draft.go
- worker/multi_tenancy_ee.go
- worker/mutation.go
- worker/online_restore.go
- worker/schema.go
- worker/snapshot.go
- worker/task.go
- worker/zero.go
JoinCluster loop was getting the connection from pool upfront, and then looping over it. This opened up a bug because in https://github.com/dgraph-io/dgraph/pull/7918 , we close the connection in case it becomes unhealthy.
This PR gets the latest connection available in the loop. This was the only place in the codebase where I found this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7950)
> fix(conn): JoinCluster loop should use latest conn

- dgraph/cmd/zero/raft.go
- worker/draft.go
- worker/multi_tenancy_ee.go
- worker/mutation.go
- worker/online_restore.go
- worker/schema.go
- worker/snapshot.go
- worker/task.go
- worker/zero.go
> JoinCluster loop was getting the connection from pool upfront, and then looping over it. This opened up a bug because in https://github.com/dgraph-io/dgraph/pull/7918 , we close the connection in case it becomes unhealthy.
>
> This PR gets the latest connection available in the loop. This was the only place in the codebase where I found this issue.
(cherry picked from commit 7531e95f9854f9f2315e5400a78cf43c080680d6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7951)
> fix(conn): JoinCluster loop should use latest conn (#7950)

- posting/list.go
- posting/list_test.go
- posting/mvcc_test.go
We should write rolled up keys at (maxTs of the deltas + 1) because if we write the rolled up keys at the same ts as
that of the delta, then in case of WAL replay the rolled-up key would get over-written by the
delta which can bring DB to an invalid state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7957)
> fix(rollups): Write rollup keys at ts+1

- posting/list.go
- posting/list_test.go
- posting/mvcc_test.go
Write rolled up keys at (max ts of the deltas + 1) because if we write
the rolled-up keys at the same ts as that of the delta, then in case of
WAL replay the rolled-up key would get over-written by the delta which
can bring DB to an invalid state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7959)
> fix(rollups): Write rolled-up keys at ts+1 (#7957)

- query/query.go
No need to execute filter subgraph if there are no source UIDs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7962)
> fix(query): Do not execute filters if there are no source uids

- conn/pool.go
- worker/groups.go
Fixes: https://discuss.dgraph.io/t/bug-mutex-lock-while-health-checking/14940
There was a race condition when accessing HealthInfo. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7963)
> fix(pool): use write lock when getting health info

- conn/pool.go
- worker/groups.go
Fixes: https://discuss.dgraph.io/t/bug-mutex-lock-while-health-checking/14940
There was a race condition when accessing HealthInfo. This PR fixes that.
(cherry picked from commit b41ff1f8910f6d5d7e289a8697a8507a106a8c42)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7967)
> fix(pool): use write lock when getting health info (#7963)

- worker/draft.go
Addresses DO-79.
We see frequent snapshots in an HA cluster because of the leadership re-election because of leader crash/shutdown. The local variable that we use for snapshot frequency is not synchronized across alphas. So each alpha thinks differently about the time the last snapshot was taken.
Copy of https://github.com/dgraph-io/dgraph/pull/7965 to master
(cherry picked from commit 43055bf0d3b483da93e604e64eb6ca02566d5921)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7968)
> fix(snapshot): update last snapshot time across members

- query/query.go
No need to execute filter subgraph if there are no source UIDs.
(cherry picked from commit 849b587e101100059287e15fea0bf0be689904ea)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7969)
> fix(query): Do not execute filters if there are no source uids (#7962)

- worker/export.go
Write to t instead of /tmp which in Cloud is mapped to the node storage instead
of the attached volume. /tmp can fill up easily since it's typically smaller than the
allocated storage for the Dgraph Alpha disk where the t directory is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7975)
> fix: Write temporary files for export to the t directory.

- codec/codec.go
- go.mod
- go.sum
- posting/list.go
There are some fixes in sroar, this PR brings those to master. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7977)
> fix(sroar): Bring latest sroar to master

- contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml
- contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
Before we cannot deploy to a cluster with a cluster domain name.
This removes the hard coded `.svc.cluster.local` and help Dgraph be deployed to any cluster with or without cluster domain name.
More context at https://discuss.dgraph.io/t/failed-to-install-dgraph-ha/15198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7976)
> fix(contrib/k8s): allow to deploy to cluster with domain name

- edgraph/access_ee.go
We store the groupId and userId in a predicate named dgraph.xid.There was a subtle bug where if a we create the group with same name as that of a user, then the user is not able to log in. This happens because we were not applying a filter by type.
This PR fixes that.
(cherry picked from commit 355385563636779655a70132eb9662fddd584d27)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7981)
> fix(acl): filter out the results based on type (#7978)

- contrib/sbs/go.mod
- contrib/sbs/go.sum
- contrib/sbs/sbs.go
- contrib/sbs/utils.go
- go.mod
- go.sum
This commit brings in sroar with some more optimizations like 
cleanup of the bitmap, it also implements histogram in the sbs
tool, which will help in better comparison.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7982)
> perf(sroar): Use latest sroar and add histogram in the sbs tool

- worker/restore_map.go
Sort the buffer before-hand instead of sorting it in the goroutine used for 
writing the buffer to disk. The `writeToDisk` goroutines are throttled and making it
expensive causes other goroutines to block.
This change significantly improves restore map phase.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7984)
> opt(restore): Sort the buffer before spinning the writeToDisk goroutine

- algo/uidlist.go
- codec/codec.go
- dgraph/cmd/bulk/count_index.go
- dgraph/cmd/bulk/reduce.go
- go.mod
- go.sum
- posting/list.go
- posting/mvcc.go
- query/groupby.go
- query/query.go
- query/recurse.go
- worker/sort.go
- worker/task.go
- worker/trigram.go
Optimise recurse by using reached map with bitmap as the value, so a direct 
bitmap `AndNot` can be done to get the list of unvisited edges. Also, use
range iterators and the fast iterator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7989)
> opt(recurse): Optimise recurse and bring range iterators from sroar

- go.mod
- go.sum
- query/outputrdf.go
- query/rdf_result_test.go
For RDF format output, the order of rdf's doesn't matter, so we can make them concurrent. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7988)
> opt(rdf-output): Make RDF output generation concurrent

- dgraph/cmd/alpha/run.go
- dgraph/cmd/increment/increment.go
- edgraph/server.go
- x/config.go
This is useful to avoid blowing up the number of goroutines handling queries, if the user bombards Dgraph with lots of concurrent / asynchronous requests.
Cherry pick from #7603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7990)
>  feat(query): cherry-pick Add mechanism to have a limit on number of pending queries 

- edgraph/access_ee.go
We were subscribing to the wrong predicates. Hence the ACL cache was not getting updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7992)
> fix(acl): subscribe for the correct predicates

- edgraph/access_ee.go
- edgraph/acl_cache.go
- ee/acl/acl_test.go
There are usecases that need read/write/modify permissions over all the predicates of the namespace. It is quite tedious to manage the permissions every time a new predicate is created.
This PR adds a feature to allow a group, access to all the predicates in the namespace using wildcard `dgraph.all`.
This example provides to `dev` group, read+write access to all the predicates 
```graphql
mutation {
updateGroup(
input: {
filter: { name: { eq: "dev" } }
set: { rules: [{ predicate: "dgraph.all", permission: 6 }] }
}
) {
group {
name
rules {
permission
predicate
}
}
}
}
``` 
**NOTE**: _The permission to a predicate for a group (say `dev`) is a union of permissions from `dgraph.all` and the permissions to specific predicate (say `name`). So suppose `dgraph.all` is given READ permission, while …
> feat(acl): allow access to all the predicates using wildcard

- edgraph/access_ee.go
- ee/acl/acl_test.go
- worker/acl_cache.go
Contains 2 cherry picks:
- feat(acl): allow access to all the predicates using wildcard (#7991) …
- fix(acl): subscribe for the correct predicates (#7992) …
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7993)
> feat(acl): allow access to all the predicates using wildcard (#7991)

- worker/restore_map.go
Cherry-pick of #7984.
Sort the buffer beforehand instead of sorting it in the goroutine used for
writing the buffer to disk. The writeToDisk goroutines are throttled and
making it expensive causes other goroutines to block.
This change significantly improves the restore map phase.
(cherry picked from commit 196624562acdb611cf724927c280c9e812a05d0f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7996)
> opt(restore): Sort the buffer before spinning the writeToDisk goroutine (#7984)

- go.mod
- go.sum
- posting/index.go
- posting/list.go
- posting/list_test.go
- posting/lists.go
- posting/mvcc.go
- posting/oracle.go
- posting/size.go
- worker/draft.go
- worker/server_state.go
- worker/snapshot.go
- Use some nifty techniques to make Ristretto caching work with MVCC posting lists.
- Use posting list cache by default.
- Set max pending to 64 by default.
This PR significantly improves query performance. This coupled with Roaring Bitmaps has shown to improve query latency by 20x for 50% of user queries, and 100x for 25% of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7995)
> opt(cache): Use Ristretto to store posting lists

- codec/codec.go
Return `nil` in from FromListWithCopy instead of a new bitmap.
We should also do the same for FromList.
NOTE: we'll soon make sroar to better handle the nils so that we can return nil and don't
worry about it in dgraph. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/7997)
> fix(codec): Return nil instead of a new bitmap

- algo/uidlist.go
- codec/codec.go
- go.mod
- go.sum
- posting/list.go
- query/groupby.go
- query/query.go
IndexOf was converting the bitmap to array and then used binary search to find the rank.
The conversion to array is extremely inefficient. This PR uses newly implemented
Rank API from sroar which finds the rank in an efficient way. This PR also does some
cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8002)
> Use rank() API from sroar and some cleanup

- go.mod
- go.sum
- graphql/schema/rules.go
This PR fixes the bug mentioned in https://discuss.dgraph.io/t/no-input-field-null-validation-on-non-nullable-fields/14085.
Issue is suppose a schema is defined type Task { name: String! }.
Now dgraph generates the mutation schema as follows:
```
type mutation {
addTask(input: [AddTaskInput]!): Result!
}
```
Now while executing mutation, graphql accept both arrays and single object as input. This means:
```
M1: 
mutation {
addTask(input: {name: string})
}
m2:
mutation {
addTask(input: [{name: string}])
}
```
both the above mutation are valid. But dgraph after the validation assumes that it will always be an list. This leads to some panics in the past and hence to make it compliant we added listInputCoercion which will change the value to List if needed so that there wont be any issue …
> fix: add validation of null values with correct order of graphql rule validation

- codec/codec.go
- go.mod
- go.sum
- query/recurse.go
Upgrade sroar to use optimized version of IsEmpty API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8010)
> opt(IsEmpty): Upgrade sroar to optimize IsEmpty API

- dgraph/cmd/zero/raft.go
- worker/draft.go
- worker/proposal.go
Change proposal's unique key to an atomic counter instead of using randomly generated key. For a randomly generated key of 32bits, there is a considerable probability of getting the same key used again. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8005)
> fix(proposals): Incremental proposal key for zero proposals

- dgraph/cmd/alpha/run.go
Fixes the race condition while spinning up the lambda server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8013)
> fix(lambda): fix race condition in lambda server spin up

- graphql/admin/admin.go
Currently, guardians of any namespace can enable/disable query logging, update the cache parameters, etc.
This operation should only be allowed to the guardian of the galaxy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8014)
> fix(admin): make config changes to pass through gog middlewares

- contrib/sbs/sbs.go
Some of the queries might fail. In that case, the response would be empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8018)
> fix(sbs): handle response error gracefully

- dgraph/cmd/bulk/loader.go
- systest/bulk_live/common/bulk_live_cases.go
With the format change of exported schema, the schema needs to be quoted at a later stage while bulk loading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8019)
> fix(bulk): quote the schema correctly in bulk loader

- go.mod
- go.sum
There was a deadlock in badger compaction which causes alpha to 
get stuck. This PR brings in the latest badger with the fix. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8025)
> fix(badger): Upgrade badger to fix deadlock

- worker/draft.go
If there is no delta proposal with a valid commit then the snapshot was
skipped. For the purpose of snapshot calculation, we should also
consider the restore timestamp. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8024)
> fix(snapshot): Fix snapshot calculation after restore

- dgraph/cmd/alpha/lambda_linux.go
- dgraph/cmd/alpha/lambda_others.go
- dgraph/cmd/alpha/run.go
We were already handling the graceful shutdown of node processes when alpha _shuts down_. 
In case alpha panics, the alpha gets stuck because the node processes.
We were passing the `closer.Ctx()` so that node process shuts down when alpha stops. But that is not sufficient when alpha _panics_. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8027)
> fix(lambda): shutdown node processes when alpha gets killed

- dgraph/cmd/alpha/lambda_linux.go
- dgraph/cmd/alpha/lambda_others.go
- dgraph/cmd/alpha/run.go
We were already handling the graceful shutdown of node processes when alpha shuts down. We were passing the closer.Ctx() so that node process shuts down when alpha stops. But that is not sufficient when alpha panics.
In case alpha panics, the alpha gets stuck because the node processes. This happens when sentry is also enabled. Sentry waits for all processes (child as well as grandchild to complete).
(cherry picked from commit d3285b8472d5871c6076adfd9dcb4a99873ad0d2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8030)
> fix(lambda): shutdown node processes when alpha gets killed (#8027)

- go.mod
- go.sum
- worker/config.go
- worker/server_state.go
Magic number is a unique identifier for the version of Dgraph. In 21.09 we
have changed the data format of posting lists by bringing in sroar. Running
Dgraph with sroar change on older p directory can cause data corruption.
This magic number prevents DB to start up if the version is not compatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8032)
> feat(magicNumber): Introduce magic number

- go.mod
- go.sum
- worker/config.go
- worker/server_state.go
Magic number is a unique identifier for the data format of dgraph. In 21.09 we
have changed the data format of posting lists by bringing in sroar. Running
Dgraph with sroar change on older p directory can cause data corruption.
This magic number prevents DB to start up if the version is not compatible.
(cherry picked from commit 59f6e7a775df6297dda0ae32e9304e2215065b7c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8033)
> cherrypick release/v21.09: feat(magicNumber): Introduce magic number (#8032)

- worker/restore_map.go
With this change, this is what we got on a 48 core AWS machine.
```
alpha1    | I0917 08:03:27.921912      17 restore_map.go:547] Restore MAP 01h04m30s len(reqCh): 0 len(writeCh): 0 read: 472 GiB. output: 1.6 TiB. rate: 437 MiB/sec. nextFileId: 2474 writers: 0 jemalloc: 0 B.
alpha1    | I0917 08:03:27.921934      17 restore_map.go:559] Restore MAP Done in 01h04m30s.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8038)
> opt(Restore): Make restore map phase faster

- graphql/admin/admin.go
Earlier the admin server mutex lock was used to protect the graphql schema `map`. But now we store that in schema store that internally handles the concurrency. Hence, we don't need to take the admin server's read lock to access schema.
`/probe/graphql` is used as health check and is called very frequently. This rlock on adminserver mutex makes the `/probe/graphql` requests block while lazy loading when restore operation gets triggered at the startup. That leads to so many go routines being spun up. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8037)
> fix(probe): do not contend for lock in lazy load

- dgraph/cmd/alpha/run.go
- worker/server_state.go
There is a logical race condition that causes panic. This happens because the node process did not complete its initialization before being killed. This PR fixes that issue.
This PR also increases the default restart timeout from `10s` to `30s` to make it more generous.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbf5f7b]
goroutine 175 [running]:
os.(*Process).signal(0x0, 0x279b908, 0x32592d8, 0x0, 0x0)
/usr/local/go/src/os/exec_unix.go:63 +0x3b
os.(*Process).Signal(...)
/usr/local/go/src/os/exec.go:135
os.(*Process).kill(...)
/usr/local/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
/usr/local/go/src/os/exec.go:120
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.setupLambdaServer.func2(0xc0003be …
```
> fix(lambda): make lambda active only after successful start

- dgraph/cmd/alpha/metrics_test.go
- x/metrics.go
These metrics have been part of Badger for a while. This PR exports them in Prometheus format at the /metrics endpoint.
* badger_blocked_puts_total
* badger_pending_writes_total
* badger_compactions_current
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8034)
> feat(metrics): Add Badger metrics.

- dgraph/cmd/alpha/run.go
- worker/server_state.go
There is a logical race condition that causes panic. This happens because the node process did not complete its initialization before being killed. This PR fixes that issue.
This PR also increases the default restart timeout from 10s to 30s to make it more generous.
(cherry picked from commit eaee2db257b623b1d7711b36f43b9beb13aa3029)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8044)
> fix(lambda): make lambda active only after successful start (#8036)

- dgraph/cmd/debug/run.go
- worker/online_restore.go
- worker/restore_map.go
Offline restore was using the same map directory for all the  groups. This causes the same map files to get reduced in multiple groups. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8047)
> fix(restore-test): Use separate map directory for each group in offline restore

- graphql/admin/restore.go
- worker/online_restore.go
- worker/restore_map.go
Add more information in the restore logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8050)
> chore(restore): Add more logs for restore request

- edgraph/server.go
Recently I faced a situation when my queries containing a lot of conditional mutations (+5000) took a long time to process. According to the servers reply the slowest part of the query handling was parsing. For example:
parsing_ns:835833349 processing_ns:157596840 encoding_ns:5105536 assign_timestamp_ns:454011 total_ns:1033841289 
So the parsing took several times longer that the processing itself!
The reason of the issue is in the ineffective implementation of buildUpsertQuery method. I suggest using String Builder instead of just simple string concatenation. After these changes the parsing speed increased significantly:
parsing_ns:134053025 processing_ns:114263143 encoding_ns:4992320 assign_timestamp_ns:495987 total_ns:286159717 
--- …
> perf: Speed up parsing of a huge query with a lot of conditional mutations

- dgraph/cmd/alpha/run.go
- ee/audit/audit_ee.go
- ee/audit/interceptor.go
- ee/audit/interceptor_ee.go
- graphql/admin/http.go
- x/jwt_helper.go
Audits were made to operate as a middleware for all the requests over the 8080 port of Dgraph alpha. This works great for grpc and http requests but not for graphQL subscriptions over websockets. websocket connections works in different way. They start as normal Http connection and then gets upgraded to the websocket connection. Till the upgrade is over, there is no transfer of metadata and headers across the network. This makes auditing impossible at the middleware layer for websocket connections.
This PR separates out the audit for websockets connection to the http.go#subscriber which will handle the auditing in the right manner.
--- …
> fix: fixing audit logs for websocket connections

- ee/audit/audit_ee.go
- ee/audit/interceptor.go
- ee/audit/interceptor_ee.go
- graphql/admin/http.go
- x/jwt_helper.go
* fix: fixing audit logs for websocket connections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8053)
> fix: fixing audit logs for websocket connections (#8048)

- graphql/admin/admin.go
Earlier the admin server mutex lock was used to protect the graphql schema map. But now we store that in schema store that internally handles the concurrency. Hence, we don't need to take the admin server's read lock to access schema.
/probe/graphql is used as health check and is called very frequently. This rlock on adminserver mutex makes the /probe/graphql requests block while lazy loading when restore operation gets triggered at the startup. That leads to so many go routines being spun up.
(cherry picked from commit 5ad40d8479163697049612f28ba40429652b765a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8041)
> fix(probe): do not contend for lock in lazy load (#8037)

- dgraph/cmd/alpha/run.go
- edgraph/server.go
- posting/lists.go
When alpha shuts down, we were earlier not waiting for the pending queries to process. We should wait for some time for those queries to complete processing. This also helps us prevent unpleasant _harmless_ panics caused due to those pending queries as they access the DB in the closed state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8057)
> fix(shutdown): wait for pending queries to process on alpha shutdown

- posting/lists.go
- posting/mvcc.go
- posting/oracle.go
- worker/draft.go
There was a data race in the transaction code. The `ReadKey()` function used to take lock and return a map, now the map is unprotected and any other write on it will cause data race. Same is the case with the `txn.cache.deltas`. This PR makes sure that the locks are properly acquired on them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8060)
> fix(txn): Fix data races in transaction code

- worker/online_restore.go
There is an issue caused due to retry of restore proposal, consider the following scenario:
```
1. alpha-2 gets the restore request (leader is alpha-0)
2. alpha-2 sends the request to alpha-0 (leader).
3. alpha-0 called proposeAndWait which proposed the req (index 24) at time=15:56:10
4. alpha-0 was still waiting for the proposal to be applied and rpc call for `Restore` by alpha-2 got "transport closing error" at time=15:59:08
5. transport closing is a retriable error, so alpha-2 again tried to proposeoOrSend, this time leader was alpha-1, so it sent it to alpha-1
6. alpha-1 proposed the restore request (index 28) at time=15:59:09
```
This PR removes the retry logic. If the restore fails, it should be re-triggered manually.
--- …
> fix(restore): Do not retry restore proposal

- go.mod
- go.sum
- posting/list.go
When there was a single plist to start from and there was nothing in mutationMap, the `encode` does not happen and hence the splits were not getting generated.
This PR fixes that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8062)
> fix(split): enable split of posting list with single plist

- worker/schema.go
Optimize populateSchema() by avoiding repeated lock acquisition,
we can get the schema for the predicate once and then check for
the required field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8068)
> opt(schema): Optimize populateSchema() by avoiding repeated lock acquisition

- dgraph/cmd/bulk/reduce.go
- dgraph/cmd/debug/run.go
- testutil/backup.go
- worker/backup.go
- worker/config.go
- worker/online_restore.go
- worker/server_state.go
- x/x.go
The bulk loader creates the p directory and hence should have the correct external magic version. With the change that introduced the magic version, somehow bulk loader got missed out. 
This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8070)
> fix(magic): fix the magic version in bulk loader etc

- dgraph/cmd/zero/zero.go
- graphql/admin/state.go
- x/keys.go
There is an issue in `ExtractNamespaceFromPredicate`. The issue is the parsing was done assuming `ns` in `<ns>-<attr>` to be decimal (actually it is hexadecimal). This leads to the following issues. 
- A predicate `a-name`, it was skipped.
- A predicate `11-name` was parsed as namespace 11, actually it is namespace 17 (0x11).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8091)
> fix(state): fix hex to uint64 response of list of namespaces

- ee/acl/acl_test.go
Update ACL tests to cover the behavior for `dgraph.all` permissions with reverse edges. When the `dgraph.all` permission is set, it also applies to reverse edges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8093)
> test(acl): Test reverse edge access with dgraph.all.

- worker/server_state.go
- worker/sink_handler.go
- x/tls_helper.go
This will attempt to connect to Kafka over TLS using the system certs.
* Add helper function x.TLSBaseConfig.
Sets the min TLS version to v1.2 along with the minimum cipher suites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8097)
> feat(cdc): Add superflag to enable TLS without CA or certs. (#7946)

- graphql/admin/state.go
- x/keys.go
There is an issue in ExtractNamespaceFromPredicate. The issue is the parsing was done assuming ns in <ns>-<attr> to be decimal (actually it is hexadecimal). This leads to the following issues.
A predicate a-name, it was skipped.
A predicate 11-name was parsed as namespace 11, actually it is namespace 17 (0x11).
(cherry picked from commit 0c9f60156b34a675d76695a912e07b45590644ff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8101)
> cherry: fix(state): fix hex to uint64 response of list of namespaces (#8091)

- worker/restore_map.go
(cherry picked from commit 89b573aafcc7e498a91ae769aba384abd0c40b95)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8099)
> cherry: fix(export-backup): Don't ban namespace in export_backup

- contrib/release.sh
* Go 1.17
* Node v14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8102)
> build: Update release.sh.

- dgraph/Makefile
`Dgraph version` should now be based on v21.12.
```
Dgraph version   : v21.12.0
Dgraph codename  : zion-mod
Dgraph SHA-256   : c94def6f0958000c005ec7ec0b06b9c569dcf225615d5316305ccb14a40846c8
Commit SHA-1     : d62ed5f15
Commit timestamp : 2021-12-02 21:20:09 +0530
Branch           : master
Go version       : go1.17.3
jemalloc enabled : true
```
The previous logic is only needed if the tagged version is not reachable from the master branch. For Dgraph v21.12, this isn't needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/8108)
> build: Fix Dgraph version string for master branch.

- .github/workflows/golangci-lint.yml
- contrib/config/docker/docker-compose-ha.yml
- contrib/config/docker/docker-compose-multi.yml
- contrib/config/docker/docker-compose.yml
The existing docker-compose files cause the following errors when trying to interact with `dgraphDB`:
```
Sudhishs-MacBook-Pro:Desktop sudhishkr$ curl -X POST localhost:8080/admin/schema --data-binary '@schema.graphql'
{"errors":[{"message":"resolving updateGQLSchema failed because unauthorized ip address: 172.18.0.1 (Locations: [{Line: 3, Column: 4}])","extensions":{"code":"Error"}}]}
```
The issue here is `unauthorized ip address`, caused because of [`whitelist settings`](https://dgraph.io/docs/deploy/dgraph-administration/#whitelisting-admin-operations). The fix is listed in the article [here](https://discuss.dgraph.io/t/update-schema-fails-unauthorized-ip-address/9250/4). The default dgraphDB setting to `127.0.0.1` creates the above problem - and this fix should help ease spinning up …
> opening up whitelist for local setup with docker-compose 

- README.md
Dgraph is production ready at version 21.03.0.  This PR updates this information in the README.
> fix(docs): Update readme to point to 21.03 version

- .github/workflows/ci-dgraph-tests.yml
- t/t.go
Bare Metal pipeline as code setup
- the steps to `build` binary & `run` tests are part of the `yaml`
- `subfolders` should get opened up one-by-one, after local runs
Currently this will show green because of `skips`
> fix(test): ci pipeline to trigger t.go, needs more work to open the test-folders

- .golangci.yml
- `lint` runs on certain test-folders 
- `lint` doesn't exclude certain test-files
- `lint` `gosimple` is a good to have vs. a necessity
- introduce skip-dirs (for folder skipping)
- introduce skip-files (for file skipping)
- comment out `gosimple` 
- introduce line limits for `lll` to `120`
`lint` error count reduces by 210+ with this change
- ##### before
```
> golangci-lint run | wc -l
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
507
```
- ##### after
```
> golangci-lint run | wc -l
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
291
```
> fix(test): adding lint ignore

- .github/workflows/ci-dgraph-tests.yml
- t/t.go
- current problem with `--skip` list is because the comparison is NOT happening on `fully qualified package name` but just the `folder name`
- when we try to `--skip` with a bunch of entries (with `dgraph` folder for tests), the conditional returns `true` and exits the loop as its comparing against `fully qualified package name` when it hits `dgraph` (this is an ordering problem in some sorts). If we move `dgraph` folder to the end of this list, we can bypass this problem.
- this causes the remaining skip list items to get ignored and breaks the `--skip` functionality, there by making it difficult & non-intuitive.
- the correct fix is to compare with `fully qualified package name` vs. just the `folder name` like before
- with this fix the ordering inside the `--skip` doesn't matter
> fix(test): bug fix for test driver skip functionality to use fully qualified package name

- t/t.go
Changing some default parameters in t.go for testing purposes.  We have had issues with concurrency flag and build.
Change j=3 to j=1 and set rebuild-binary to false.
> fix(testing): parallelism and binary build

- contrib/config/docker/docker-compose.yml
Change wording to show the need to change the volume to something besides "/tmp/*"
Tested on AWS. If the mount directory of the volume is not changed away from tmp then the data will not persists even though the volume is persistent with EBS.
Figured this out by reading this topic on discourse: https://discuss.dgraph.io/t/dgraph-in-docker-unable-to-reload-data-on-restart/5927/4?u=amaster507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgraph/5757)
> docs(Docker): Reword docker compose to show the need to change volume mount directories.

- .golangci.yml
Lint tests are failing
Phase1: we are skipping most known lint errors
Phase2: we will be unskipping them one by one
This addresses the Phase1
@joshua-goldstein @dshekhar95 this PR lint run results show only `lll` failures (which is what we want). When we merge https://github.com/dgraph-io/dgraph/pull/8191 - this will pass for `lll`.
> fix(test): unskip linters, we will open them one by one

- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-golang-lint.yml
The current CI is causing double triggers for tests (it's setup for `pull_request` & `push` events)
Also we don't have continuous scheduled triggers on `default` main branch (which should run every 30mins)
- modify the event triggers to avoid double runs
- add schedule triggers for every 30mins on `main` branch (this should also help us identify test-flakiness)
> fix(ci): modify ci trigger events

- .github/workflows/ci-aqua-security-trivy-tests.yml
docker layers are not tested for sec
enabling aqua trivy checks
this is how we build our docker image, and this step references a dockerfile as detailed here https://github.com/dgraph-io/dgraph/blob/skrdgraph/docker_sec_checks/Makefile#L76 ... which points to https://github.com/dgraph-io/dgraph/blob/skrdgraph/docker_sec_checks/contrib/Dockerfile
the GH-action in this PR checks for security CVEs using `trivy` and dumps the output into https://github.com/dgraph-io/dgraph/security/code-scanning (where we can analyze the severity, and make fixes)
This GH Action captures the exact CVEs.
> fix(test): adds docker sec checks

- t/t.go
when using the --pkg flag running tests thru t locally, currently it takes any suffix match.
ex. if i set --pkg=auth, it will run tests not only for auth but also for admin_auth
Add a "/" before the suffix check to ensure only full pkg name works
> possible fix for t pkg flag

- .golangci.yml
- Makefile
- chunker/json_parser.go
- conn/node.go
- dgraph/cmd/alpha/run.go
- dgraph/cmd/bulk/run.go
- dgraph/cmd/debug/run.go
- dgraph/cmd/live/batch.go
- dgraph/cmd/live/run.go
- dgraph/cmd/zero/assign.go
- dgraph/cmd/zero/oracle.go
- worker/sink_handler.go
- x/log_writer.go
- x/names-generator.go
- x/sentry_integration.go
- x/sentry_integration_test.go
- x/server.go
- x/tls_helper.go
- x/x.go
- xidmap/xidmap.go
This PR includes all fixes/directives that allow the gosec (gas) linter to pass.
Most of the commits are straightforward. However one in particular might need some more attention, see https://dgraph.atlassian.net/browse/D2209-168 for details.
One other commit (https://github.com/dgraph-io/dgraph/pull/8273/commits/a664c35365ace2669040f52f04337c84b3826753)  is actually a pretty important change that mitigates a DoS vulnerability.
> chore(lint:gosec): Fix or bypass gosec lint failures

- Makefile
- t/Makefile
Currently in order to run tests locally we are mirroring the workflow [here](https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/ci-dgraph-tests.yml#L32-L65).  On a local machine this requires running (from root dgraph directory):
```
make image-local
GOOS=linux GOARCH=amd64 make dgraph
cp dgraph/dgraph $GOPATH/bin
cd t; go build t
./t -r
go clean -testcache
./t --coverage=true --skip systest/backup,systest/online-restore,systest/loader,tlstest
./t -r
```
This is tedious to do repeatedly.
I modified the root Makefile and added a Makefile in the t directory to automate this workflow.  If you want to change which tests you run, simply modify t/Makefile appropriately.  This workflow was written with an Apple M1 in mind but it should also work on Linux.  To use this workflow now, …
> feat(testing): automate local testing workflow

- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests.yml
so the current issue is the cleanup step does not work because crufts left by `load-test` are in sudo user group. The action runner cannot clean those because of user perm issues. This was the original PR https://github.com/dgraph-io/dgraph/pull/8301 which I closed, but in hindsight had the right fix. The fix details are referenced in the solution section.
this is an elegant way to clean it, because the underlying container runs in sudo-ers group.
> fix(test) add cleanup at start

- README.md
TODOs badge in readme was pointing to `master` branch, and thus was outdated.
Point the TODOs badge to `main` branch instead
> fix TODOs badge in readme to point to main branch instead of master

- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests.yml
- contrib/gh-runner/gh-runner.sh
The previous fixes were introducing a cleanup step in our CI, which is not ideal & it is not consistent either - because any files created from within the container cannot be cleaned up by other steps because of root user issues. Docker runs as root. 
The correct fix is to have the runner run as root, which is the ideal way of dealing with this. There are security concerns here, but I have looked further to ensure we are not impacted. This change is made in this PR. The earlier PRs https://github.com/dgraph-io/dgraph/pull/8307 https://github.com/dgraph-io/dgraph/pull/8301 & issues https://github.com/actions/checkout/issues/211 https://github.com/Gamify-IT/issues/issues/60 talk about the fixes.
> fix(ci) fixing the file permission issue for CI runner

- .github/workflows/ci-aqua-security-trivy-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-golang-lint.yml
we have switched to self-hosted runners, and we are spending $'s for our runners. Our tests are now stable, and we ideal need 1-runner during the night for scheduled runs. And if we do get PRs etc. on our `main` branch - it would still be able to run those tests. We should not need 2 runners during the 12hr off-work window.
Adjust the schedule in such a way that `unit test run` is followed by `load test run` sequentially. This will keep the resource busy for ~20mins. And we will need only 1 runner for the night.
> fix(test) fix cron cycles

- ee/acl/acl_test.go
- worker/groups.go
This fixes cases where loop variables are incorrectly captured in
asynchronous code (parallel tests or Go routines). In the case of a
parallel test, the most likely scenario is that only the last test
case will be executed. In the case of Go routines that directly
access loop variables without any synchronization, the value stored in
the loop variable will likely not be the same as what it was when the
Go routine is created.
> fix(bug): use copy of loop variable in Go routines

- posting/list.go
- posting/list_test.go
[Cherry-pick-7609](https://github.com/dgraph-io/dgraph/pull/7609)
The old PR fixed an issue that arose after posting/list.go was significantly refactored when roaring bitmaps were incorporated.  The previous team first implemented roaring and then wrote the sroar library to compress the posting lists.  In 21.03 we are not using roaring nor sroar so this code should not be merged.  However a new test was written that we can bring in.
> fix(rollups): cherry-pick-7609

- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
Fixes GQLSAAS-1236.
This PR optimizes `eq` filter GraphQL queries.
For ex:
The below DQL query:
```
query {
queryPerson(filter: {nick: {eq: "Dgraph"}}){
id
name
nick
}
}
```
will now be written into:
```
query {
queryPerson(func: eq(Person.nick, "Dgraph")) @filter(type(Person)) {
Person.id : uid
Person.name : Person.name
Person.nick : Person.nick
}
}
```
which was earlier written into:-
```
query {
queryPerson(func: type(Person)) @filter(eq(Person.nick, "Dgraph")){
Person.id : uid
Person.name : Person.name
Person.nick : Person.nick
}
}
```
> fix(GraphQL): optimize eq filter queries (#7895)

- edgraph/server.go
- edgraph/server_test.go
Multiple entries for the same predicate can lead to inconsistent state,
hence adding an error for it instead.
Fixes DGRAPH-3225
> fix(query): Prevent multiple entries for same predicate in mutations.2022

- go.mod
- go.sum
- graphql/schema/rules.go
the previous merge was not squashed, this was the original PR https://github.com/dgraph-io/dgraph/pull/8320
… validation (#8007)
* fix: add validation of null values with correct order of graphql rule validation
> fix(GraphQL): add validation of null values with correct order of graphql rule validation

- Makefile
- README.md
1.)  When following install instructions for Linux, one will encounter the following error due to missing libraries:
```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
```
2.)  Makefile in root Dgraph directory included a deprecated SUBDIRS variables.  This was referenced when `make install` is called, giving an error.
1.)  Instead of `apt-get install make gcc` instructions should be `apt-get install build-essential` which includes gcc, make, as well as the necessary libc packages.
2.)  Update Makefile to run `make install` correctly.
> fix(build): Update linux build steps

- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests.yml
- contrib/gh-runner/gh-runner.sh
- Increase test frequency to capture more run results before RC
- add sleep post docker container cleanup
- adjust the gh-runner cruft cleanup bug
- change to `*/30 * * * *`
- introduce wait after cleanup
- make the gh-runner cruft run every 1s
> fix(test): adjust frequency

- testutil/client.go
need logging for identifying flaky test issue with `restore`
super verbose logging
> fix(test): adding logging to HttpLogin function

- graphql/e2e/multi_tenancy/multi_tenancy_test.go
- systest/acl/restore/acl_restore_test.go
- t/t.go
The current test harness has race conditions with EE license checks
Introduce sleeps to facilitate the EE license checks
Open Docker logs
> fix(test): enable docker logs & introduce sleep before tests

- contrib/gh-runner/gh-runner.sh
21million load test occasionally fails due to the file descriptor limit being too low
Increase the file descriptor limit in our github runners machine to 2000000
> fix(ci): increase file descriptor limit in gh-runners

- .github/workflows/cd-dgraph.yml
the latest docker container we build yields `latest` for `dgraph version`
I am changing this pattern where we build the versioned container & re-tag it with latest. This way the dgraph binary has the correct version and doesn't show latest.
> fix(cd): fix docker latest tag's dgraph version

- .github/workflows/cd-dgraph.yml
Eliminate manual binary & related SHA uploads
Adding automation to generate these binaries.
Reference PR from @joshua-goldstein https://github.com/dgraph-io/dgraph/pull/8378
> fix(cd): upload dgraph binary artifacts

- .github/workflows/ci-aqua-security-trivy-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-golang-lint.yml
Currently the tests runs on draft PR as well which is waste of resources.
Add a `if: ! github.event.pull_request.draft` check to prevent GH runs on draft PRs. Reference: https://stackoverflow.com/questions/68349031/only-run-actions-on-non-draft-pull-request
> fix(ci): add draft check in the workflow yaml

- contrib/gh-runner/gh-runner.sh
gh-runner.sh in contrib folder does not account for different installs in arm architecture
Adding if condition checks to install the right .tar files in the existing runner script
> fix(ci): gh-runner.sh refactored to account for ARM architecture

- .github/workflows/cd-dgraph.yml
fix(release): Current dgraph tar from Artifact has a folder (dgraph) with binary inside. We want the tar to directly return the binary when opened
Fix cd-dgraph.yml to point tar directly to dgraph binary
> Artifact fix to directly get dgraph binary from tar

- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-golang-lint.yml
Since we added arm64 runners, they are being picked up by our workflows.  Tests are failing after about 1 minute with exec format error (due to documented Badger/Ristretto issue).  
For more info on runner labels [see here.](https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-default-labels-to-route-jobs)
We modify workflows to only pickup amd runners.  We also pin the Go version.
> chore(ci): fix breaking tests

- Makefile
- go.mod
- go.sum
Dgraph currently uses Ristretto v0.1.0 and Badger v3.2103.1.  We encounter certain issues on arm64 machines that were patched in Ristretto v0.1.1 and Badger v3.2103.3.  Badger v3.2103.4 also fixes a potential manifest corruption issue.  
We bump up the dependencies.  
```
> go get github.com/dgraph-io/ristretto@v0.1.1
go: upgraded github.com/dgraph-io/ristretto v0.1.0 => v0.1.1
go: upgraded golang.org/x/sys v0.0.0-20220728004956-3c1f35247d10 => v0.0.0-20221010170243-090e33056c14
> go get github.com/dgraph-io/badger/v3@v3.2103.4
go: downloading github.com/dgraph-io/badger/v3 v3.2103.4
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go: upgraded github.com/dgraph-io/badger/v3 v3.2103.1 => v3.2103.4
> go mod tidy …
```
> fix(deps): update dependencies on badger + ristretto

- CONTRIBUTING.md
- compose/compose.go
- contrib/config/backups/azure/docker-compose.yml
- contrib/config/backups/client/docker-compose.yml
- contrib/config/backups/gcp/docker-compose.yml
- contrib/config/backups/nfs/docker-compose.yml
- contrib/config/backups/s3/docker-compose.yml
- contrib/config/docker/docker-compose-ha.yml
- contrib/config/docker/docker-compose-multi.yml
- contrib/config/docker/docker-compose.yml
- contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml
- contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
- contrib/standalone/Dockerfile
- contrib/standalone/run.sh
Users are having trouble starting some YML created in our documentation. Where a dgraph/dgraph:$Version container starts, which no longer has the Ratel binary.
I'm correctly arranging the tag images for Ratel.
Fix #8386
> Chore(Other|contrib): Fix Ratel refs.

- edgraph/server.go
- graphql/admin/admin.go
- graphql/admin/config.go
- wiki/content/graphql/admin/index.md
- worker/worker.go
- x/config.go
In order to add GraphQL Query Log(#8305) we need to rename the current DQL query log resolver and config.
> Rename: logRequest => logDQLRequest 
Important change:
```diff
--- glog.Infof("Got a query: %+v", req.req)
+++ glog.Infof("Got a DQL query: %+v", req.req)
```
> refactor(GraphQL): Rename logRequest name and its resolver.

- .github/workflows/ci-aqua-security-trivy-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests-arm64.yml
- .github/workflows/ci-dgraph-tests.yml
Arm tests were failing because skip list was not being parsed correctly by t.go.  We also perform some cleanup on the CI workflows (there was some redundancy in CI scripts).
We pass 
```
./t --skip="systest/export,systest/backup/minio,systest/backup/minio-large,graphql/e2e/normal,graphql/e2e/directives,graphql/e2e/custom_logic"
```
as an argument to t.go.  Failures in these packages are related to minio and lambda which we will work on resolving.  We also do some cleanup on the workflow file.
> chore(ci): fix arm workflows + minor CI cleanup

- x/x.go
This [commit](https://github.com/dgraph-io/dgraph/commit/786ff4af79802b146e8d67ba8ed4c009dd0a7f16) changes the behavior of `x/x.go/RunVlogGC` to run **unconditionally every minute**. But the author forgot to update the comments on the function to reflect that change. 
The doc comments still says it `"runs GC unconditionally after every 10 minutes. Additionally it also runs GC if vLogSize has grown more than 1 GB in last minute"`, so it can be confusing for readers.
Fix the comments to reflect the latest behavior, which is that it runs **uncoditionally every minute**
> chore(vlog): Fix outdated doc comments on RunVlogGC

- graphql/admin/admin.go
Cherry pick from #8014 
In #7955 the team made a change to the way lambda scripts were loaded into Dgraph.  This PR had a small conflict with that PR.  Any change related to #7955 should be made in another PR.
> fix(admin): make config changes to pass through gog middlewares (#8014)

- graphql/e2e/common/fragment.go
- graphql/schema/request.go
Fixes https://discuss.dgraph.io/t/graphql-field-collection-does-not-work-with-dgraph/15646
> fix(fragment): merge the nested fragments fields (#8075)

- .github/workflows/ci-dgraph-ldbc-tests.yml
- systest/ldbc/alpha.yml
- systest/ldbc/docker-compose.yml
- systest/ldbc/ldbc_test.go
- systest/ldbc/test_cases.yaml
- t/t.go
PR integrates LDBC tests as a CI/CD workflow.
Query descriptions can be found at https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf
> chore(test): Integrate LDBC Tests into CI Workflow

- graphql/resolve/auth_add_test.yaml
- graphql/resolve/auth_test.go
- graphql/resolve/auth_update_test.yaml
- graphql/resolve/mutation.go
- graphql/resolve/mutation_rewriter.go
* Make mutation rewriting tests more robust
* Fix lint
* Cherry pick: https://github.com/dgraph-io/dgraph/pull/7768
> Fix(GraphQL): Make mutation rewriting tests more robust (#7768)

- ee/backup/run.go
cherry pick from #7729
wrong config set for profiler (set to Restore instead of Backup)
set profiler to Backup.conf
> Fix(lsbackup): Fix profiler in lsBackup (#7729)

- query/common_test.go
- query/query0_test.go
- worker/sort.go
Cherry pick from #8077.
Steps to reproduce:
```
make image-local
cd contrib/local-test && make up
make schema-dql
make load-data-dql-rdf
make query-dql
curl: (52) Empty reply from server
make: *** [query-dql] Error 52
<alpha will crash and restart>
```
with the following minimal schema / data / query (should be placed in contrib/local-test):
schema.dql:
```
type Person {
name
age
friend
}
name: string @index(term)  .
age: int @index(int) .
friend: [uid] @count .
```
dql-data.rdf
```
{
set {
_:michael <name> "Michael" .
_:michael <dgraph.type> "Person" .
_:michael <age> "314" .
_:michael <friend> _:alice .
_:michael <friend> _:bob .
_:michael <friend> _:charlie .
_:alice <name> "Alice" .
_:alice <dgraph.type> "Person" .
_:alice <age> "1" .
_:bob <name> "Bob" .
_:bob <dgraph.type> "Person" …
```
> fix(sort): Only filter out nodes with positive offsets. (#8077)

- t/t.go
Previously running
```
./t --pkg="systest/backup/common,systest/backup/encryption"
```
would not run any packages, because the pkg flag is currently parsed as a single string and matched against the list of packages in the repository.  Internally, a pkg.ID looks like 
```
github.com/dgraph-io/dgraph/systest/backup/common
```
so we are matching against this string.
We split the string argument provided to --pkg by comma.  Now the above command will run two packages as expected.
> chore(ci): let pkg flag take multiple arguments

- .github/workflows/cd-dgraph.yml
- .github/workflows/ci-dgraph-ldbc-tests.yml
- .github/workflows/ci-golang-lint.yml
As per [Github](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/) the `ubuntu-latest` label is transitioning to Ubuntu 22.04.  We would like to continue running on Ubuntu 20.04 for now.
Pin runner to Ubuntu 20.04.
> chore(ci): pin runners to ubuntu-20.04

- dgraph/cmd/alpha/run_test.go
test cases missing for getIPsFromString
add test for empty string, error cases
> chore(test): add test cases for getIPsFromString

- edgraph/server.go
- worker/draft.go
- worker/task.go
- x/x.go
Adds logging and sets query `tag` for improved tracing in Jaeger.
> chore(logging): Add more logging and trace tags for debugging

- algo/uidlist_test.go
Add test cases for `IntersectWithLin`, `IntersectWithJump` and `IntersectWithBin`
> Add intersection tests for linear and binary methods

- ee/acl/acl_test.go
- systest/multi-tenancy/basic_test.go
- testutil/multi_tenancy.go
As per coverall report of [integration tests](https://coveralls.io/builds/54838866/source?filename=edgraph%2Fmulti_tenancy_ee.go#L91), we didn't have a test for `ResetPassword` flow. This PR adds a test.
This PR also removes `time.Sleep(defaultTimeToSleep)` at some places to make the acl tests run faster.
> Add tests for ResetPassword

- contrib/Dockerfile
The current problem with our Dgraph Docker environment is that the base linux packages are NOT pinned. We build the Docker container in our CI setup every time, and are pulling the `latest` tags. It's a good practice to make these dependencies static. This will avoid potential issues that can arise from environment changes.
use `apt-cache policy <package name>` to identify the candidate version & old installed version. 
pin the packages correctly, and maintain them when CVE fixes are needed in the future.
> fix(ci/cd): pin linux deps

- edgraph/access_ee.go
- edgraph/access_ee_test.go
Missing unit tests for validateToken (), getAcessJwt (), getRefreshJwt () of edgraph package
TestValidateToken (), TestGetAccessJwt () and TestRefreshJwt () generates a signed JSON Web token using the static data defined in the test file, using the helper function generateJWT (). The generated token includes the token expiry time which is passed as an argument to the helper function.
TestValidateToken () calls validateToken and extracts data from the signed token which is then compared to validate with the original data.
TestGetAccessJwt() and TestRefreshJwt () are direct wrappers over jwt.NewWithClaims () but with their predefined expiry duration.
> chore(tests): Unit test for edgraph/validateToken ()

- dgraph/Makefile
Dgraph version ldflag should not have arch (only version number).  We update the Makefile to not add this in the ldflags build arguments.
> chore(ci): remove arch from ldflag

- dgraph/Makefile
Dgraph version ldflag should not have arch (only version number). We update the Makefile to not add this in the ldflags build arguments.
(cherry picked from commit f065f6a764937d8b1ca616380211421dd072e9b4)
> chore(ci): remove arch from ldflag (#8546)

- edgraph/access_ee.go
- ee/acl/acl_test.go
- systest/multi-tenancy/basic_test.go
- testutil/json.go
- testutil/multi_tenancy.go
- testutil/utils.go
- worker/acl_cache.go
In the current implementation, when you update ACL rules across
different namespaces, the previous rules are overwritten. This results
in incorrect results for other namespaces (the ones which were created
earlier).
To reproduce:
1. Create a `namespace-1` with acl rules configured
2. Create a `namespace-2` with a different set of acl rules configured
3. Login to `namespace-1` and do a query. It will not respect the rules
configured in step-1.
1. `TestTwoPermissionSetsInNameSpacesWithAcl`
(cherry picked from commit de758acec0e046b78703e8c6ff3593c99cf71029)
> fix(ACL): Prevents permissions overrride and merges acl cache to persist permissions across different namespaces (#8418)

- edgraph/server.go
- graphql/admin/admin.go
- graphql/admin/config.go
- wiki/content/graphql/admin/index.md
- worker/draft.go
- worker/worker.go
- x/config.go
- x/x.go
Two cherry-picks
1. (cherry picked from commit 1e06e819f4364d3d65b7380ae73698f56d628aa2)
2. (cherry picked from commit bc5f584c29b92d64adae0ffb7f14dc64873a0a13)
> fix(chore): Add more logging for cloud instances

- edgraph/server.go
- telemetry/telemetry.go
- x/init.go
When you debug locally, without going through the build process. Dgraph doesn't set a default version. It returns empty. And that breaks Ratel and possibly some test that depends on the version information.
Check for missing version and put "dev" in place if it returns null.
> fix(chore): add the word "dev" to the version to avoid breaking the local test

- worker/draft.go
(cherry picked from commit db841dece9fde1243bf2ae3b1131513cf15408d6)
(cherry picked from commit 989c9dbdcbe81038a1c063d73c236a0d4ffdbae4)
> chore(logs): add logs to track dropped proposals (#8012)

- dgraph/docker-compose.yml
- systest/1million/1million_test.go
- systest/21million/bulk/run_test.go
- systest/bulk_live/bulk/docker-compose.yml
- systest/bulk_live/common/bulk_live_fixture.go
- systest/bulk_live/live/docker-compose.yml
- systest/ldbc/alpha.yml
- systest/ldbc/ldbc_test.go
- testutil/bulk.go
- testutil/minio.go
instead of a host mount, we do everything inside the container now. This avoids creating any files on the host and the delete error on during cleanup on the CI do not happen.
> test(systest): avoid host volume mount in minio test

- graphql/admin/http.go
Include headers from subscribe request and pass it along the downstream for processing.
Co-authored-by: aman-bansal <bansalaman2905@gmail.com>
Co-authored-by: Abhimanyu Singh Gaur <12651351+abhimanyusinghgaur@users.noreply.github.com>
(cherry picked from commit dbd57443992dd9f208f334095911069b3b3efa3f)
> fix(GraphQL): Pass on HTTP request headers for subscriptions (#7806) (#7807)

- contrib/Dockerfile
there are compatibility issues with base packages and curl package version
pin to latest
> fix(ci): unpin curl

- worker/schema.go
Optimize populateSchema() by avoiding repeated lock acquisition. we can get the schema for the predicate once and then check for the required field without taking a read lock.
(cherry picked from commit d935b8b767c3cc39518fe05286db59975bea9b5e)
> opt(schema): Optimize populateSchema() (#8068) (#8071)

- dgraph/cmd/zero/zero.go
Converting the smaller tablet proposals into a single bulk call makes the execution faster. Else, this update becomes of the order of O(n^2), where n is the number of tablet updates.
(cherry picked from commit 695c6d763b9e75edb0e47dd1f32a0af98222511a)
> fix(zero): fix update membership to make bulk tablet proposal instead of multiple small (#8090)

- graphql/e2e/auth/auth_test.go
- graphql/resolve/auth_query_test.yaml
- graphql/resolve/query_rewriter.go
Improves nested auth rule implementation in graphql.
(cherry picked from commit e7a19317a16214761e0db1f838ba48a0a382f0df)
Co-authored-by: minhaj-shakeel <minhaj@dgraph.io>
(cherry picked from commit 26845c431df5cc8cb3a1f0242b52a09aa4058840)
> fix(GraphQL): Nested Auth Rules not working properly. (#7915) (#8084)

- .github/workflows/ci-dgraph-code-coverage.yml
- .github/workflows/ci-dgraph-ldbc-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests-arm64.yml
- .github/workflows/ci-dgraph-tests.yml
Our scheduled runs happen too often. We now have a stable baseline - and we can limit these runs. We are also adjusting triggering evented runs when a PR is opened, and when a PR is merged*. Reducing the scheduled run makes more sense now.
changing these runs to happen twice daily
> fix(ci): adjust cron schedules

- .github/workflows/ci-dgraph-code-coverage.yml
- systest/ldbc/docker-compose.yml
- systest/ldbc/ldbc_test.go
- t/t.go
- testutil/bulk.go
Add code coverage for LDBC tests.
Previously I had verified that:
- LDBC doesn't update code coverage because the `query` package is well-tested.
- IC5 times out on `test-coverage-binary`
Therefore, I had not enabled the ldbc test suite on code-coverage workflow. 
Following @gajanan-dgraph 's prompt I gave this old PR another lookover and found a way to capture code-coverage from bulkload process. I also skip IC05 in LDBC tests.
+ `2%` increase -- Mostly due to increase in `/dgraph/cmd/bulk`. See: https://coveralls.io/jobs/112568583
> chore(ci): Capture coverage from bulk load and LDBC tests

- worker/server_state.go
- worker/sink_handler.go
- x/tls_helper.go
Does the following changes:
* will attempt to connect to Kafka over TLS using the system certs.
* add helper function x.TLSBaseConfig.
* sets the min TLS version to v1.2 along with the minimum cipher suites.
> feat(cdc): Add superflag to enable TLS without CA or certs (#7946)

- schema/schema.go
- worker/draft.go
- worker/groups.go
- worker/mutation.go
- worker/online_restore_ee.go
For big datasets, we're seeing a big slowdown due to loading schema and types serially using a single iterator. Using the Stream framework, makes this metadata loading step much faster, resulting in a much faster Alpha initialization.
(cherry picked from commit d03d5ad14e8ec5044d1e7f16c8be271d890346f1)
> opt(schema): Load schema and types using Stream framework 

- raftwal/encryption_test.go
A failure here: https://github.com/dgraph-io/dgraph/actions/runs/3952517043/jobs/6767694064
This happens when the length of data byte slice is 0. I do not think that is a valid case.
```
=== RUN   TestEntryReadWrite
encryption_test.go:48: 
Error Trace:	encryption_test.go:48
Error:      	Not equal: 
expected: []byte{}
actual  : []byte(nil)
Diff:
--- Expected
+++ Actual
@@ -1,3 +1,2 @@
-([]uint8) {
-}
+([]uint8) <nil>
Test:       	TestEntryReadWrite
--- FAIL: TestEntryReadWrite (0.02s)
FAIL
```
> fix(test): fix the corner case for raft entries test

- edgraph/access_ee.go
- edgraph/server.go
- posting/index.go
- posting/oracle.go
- systest/backup/multi-tenancy/backup_test.go
- worker/backup_ee.go
- worker/cdc_ee.go
- worker/draft.go
- worker/restore_map.go
> Cherry-pick namespace aware drop data

- .golangci.yml
- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/schema.go
- query/outputnode.go
- query/query.go
- upgrade/upgrade.go
GoLinter failures: 
- related to https://github.com/dgraph-io/dgraph/pull/8620 & https://github.com/dgraph-io/dgraph/actions/runs/3971511349/jobs/6815792372
- Addressing this partially https://github.com/dgraph-io/dgraph/pull/8572#issuecomment-1401541634 
- fix `gosimple` & `unused` linter reports
- comment the rest to address later
> fix(linter): address gosimple linter reports & errors

- edgraph/access_ee.go
- edgraph/server.go
- ee/audit/audit_ee.go
- ee/audit/interceptor.go
- ee/audit/interceptor_ee.go
- graphql/admin/http.go
- x/jwt_helper.go
- x/x.go
Fixing audit logs for websocket connections
(cherry picked from commit 3f8cff957b0ce34673f70ffd8793d0353bf2a910)
> fix: fixing audit logs for websocket connections (#8048) (#8053)

- worker/restore_map.go
We were not considering the banned namespaces while bumping the lease. So, if we restore a backup with namespace 0,1,2 not-banned and 3,4 banned. We will bump only up to 2. This would error out when creating a namespace
> fix(restore): consider the banned namespaces while bumping (#7839)

- worker/backup_ee.go
- worker/backup_handler.go
- worker/backup_manifest.go
We used to create the directory while creating a backup if one didn't exist. Slash branch doesn't create one but I think we should continue with the behaviour of creating a directory as was there in main branch.
> fix(backup): create directory before writing backup

- dgraph/cmd/alpha/upsert_test.go
- edgraph/server.go
- worker/graphql_schema.go
This change ensures that the value in the mutation is not too big. The challenge here is that the keys in badger have a limitation on their size (< 2<<16). We need to ensure that no key, either primary or secondary index key is bigger than that.
Fixes https://github.com/dgraph-io/projects/issues/73
> fix(mutation): validate mutation before applying it

- worker/restore_map.go
The kv version should be set to restore timestamp for rolled-up keys and schema keys as well. It would be inconsistent to write data at different timestamp compared to the timestamp that we use for writing schema keys.
> fix(restore): Set kv version to restoreTs for all keys (#7930)

- graphql/admin/admin.go
Earlier the admin server mutex lock was used to protect the graphql schema map. But now we store that in schema store that internally handles the concurrency. Hence, we don't need to take the admin server's read lock to access schema.
/probe/graphql is used as health check and is called very frequently. This rlock on adminserver mutex makes the /probe/graphql requests block while lazy loading when restore operation gets triggered at the startup. That leads to so many go routines being spun up.
(cherry picked from commit 5ad40d8479163697049612f28ba40429652b765a)
> fix(probe): do not contend for lock in lazy load (#8037) (#8041)

- testutil/docker.go
- testutil/schema.go
- worker/snapshot_test.go
Tests automated for following scenarios:
- After  snapshot stream is received from other running alpha , check  whether graphql schema is loaded into memory .
Sequence of steps during automation:
- Stop one alpha container 
- Add data into cluster + apply new graphql schema 
- Start alpha container
- Check whether the newly started alpha got graphql schema in snapshot.
> Add test that after snapshot is applied, GraphQL schema is updated

- worker/draft.go
- worker/server_state.go
- x/x.go
Whenever an error happens in CommitToDisk, we retry the function according to x.config.MaxRetries. However, the value was set to -1, which causes the function to get stuck in infinite loop. This leads to dgraph not being able to commit the transaction, nor move forward to newer queries. 
CommitToDisk function is required to be pushed to disk. In case of an error, different alphas in a group can end up having different data leading to data loss. To avoid such issues, we panic in case we are not able to CommitToDisk after 10 retries. Once the alpha is restarted, if the issue is fixed, the alpha would start to work again. This way, Alphas wont fail silently and we would know if there was any issue occuring.
Fixes: https://github.com/dgraph-io/projects/issues/85
> bug(core): Fixed infinite loop in CommitToDisk

- dgraph/cmd/zero/raft.go
- dgraph/cmd/zero/zero_test.go
- worker/proposal.go
Proposal key initialisation has a bug where we want to reserve first 2 bytes for node id but do not do because  we read random bytes in all 8 bytes and do a logical OR. This PR adds a test case and fixes the logic of initialising the proposal key.
> fix(proposalKey): Proposal key initialisation with correct byte ordering

- contrib/Dockerfile
This PR fixes issue in building docker-images during CI and releases. It uses cache busting to ensure `apt-get update` is always run. It also reduces the image size by removing `/var/lib/apt/lists`
See: `RUN` in https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
> fix(build): Update dockerfile to use cache busting and reduce image size

- dgraph/cmd/alpha/run.go
- edgraph/access_ee.go
- systest/acl/restore/acl_restore_test.go
- systest/backup/multi-tenancy/backup_test.go
- systest/cloud/cloud_test.go
- systest/cloud/docker-compose.yml
- systest/multi-tenancy/basic_test.go
- testutil/client.go
- testutil/docker.go
- testutil/multi_tenancy.go
- testutil/utils.go
- worker/server_state.go
- x/config.go
- x/minioclient.go
This PR adds a shared-instance flag to --limit superflag.
When set to true (false by default), it will:
- Restrict access to any of the ACL operations like Login, add/remove/update user from non-galaxy namespaces.
- Prevent the leaking of environment variables for minio and aws.
(cherry picked from commit 5f3cece75da375077c45ab64228cb7053cf03d02)
> feat(cloud): add shared-instance flag in limit superflag in alpha (#7770)

- dgraph/cmd/zero/assign.go
Fixes https://github.com/dgraph-io/projects/issues/87
> fix(mutation): Mutation request stuck when --limit flag is set 

- go.mod
- go.sum
Previous PR #8654 was a SHA not located on the new Badger release branch.  We use the latest SHA on `release/v4.0`.
> chore(deps): update badger dependency

- .github/workflows/ci-aqua-security-trivy-tests.yml
- .github/workflows/ci-dgraph-code-coverage.yml
- .github/workflows/ci-dgraph-ldbc-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests-arm64.yml
- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-golang-lint.yml
Currently we only run CI on our main branch.  We would like to run CI when changes are being considered on the release branches.
> chore(ci): run CI jobs on release branches

- contrib/config/marketplace/aws/tests/requirements.txt
There are 1 security vulnerabilities found in networkx 2.4
- [MPS-2022-15000](https://www.oscs1024.com/hd/MPS-2022-15000)
Upgrade networkx from 2.4 to  for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade networkx to 

- x/metrics.go
MonitorCacheHealth uses an internal function to record metrics. 2 calls are done always sequentially to this method. It always handles a case where the wrong type is used but that would never happen.
Get rid of that function and inline both calls sequentially
> refactor(metrics) record function is not needed as both calls are always made sequentially

- dql/parser.go
- dql/parser_test.go
This PR adds a check while evaluating order of arguments passed to eq function. This prevents `eq(val, len())`, and suggests the reverse order as a valid query.
Fixes: https://github.com/dgraph-io/dgraph/issues/8637
> fix(parser): Check order of inputs before evaluating nested eq func

- .github/workflows/ci-dgraph-code-coverage.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-tests-arm64.yml
- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-golang-lint.yml
Need more test runs because we are closing in on our next release
Increase frequency for critical CI runs to happen every 2hrs
This will increase our CI spends, but it's better we keep this running for a few days to detect any failures.
**note** 
- we are doing this because we noticed some flaky failures in our tests on `main` (*`scheduled runs`*)
- the last change was on jan-6  https://github.com/dgraph-io/dgraph/pull/8592, where we reduced the frequency because of a stable baseline
> fix(ci) increase frequency

- systest/backup/advanced-scenarios/acl-nonAcl/backup_test.go
- systest/backup/advanced-scenarios/acl-nonAcl/docker-compose.yml
This PR contains an Integration test for acl to nonacl backup/restore and vice versa
This test follows the following flow:
- Take a backup from acl enabled cluster and restore on non-acl cluster.
- Take a backup from non-acl cluster and restore on acl cluster.
> `chore`: Integration test for acl to nonacl backup/restore and vice versa

- dgraph/Makefile
current docker dgraph does not have the right version
for ex. v23.0.0-beta-arm64 -> v23.0.0
what we want 
v23.0.0-beta-arm64 -> v23.0.0-beta
use sed & make necessary fixes in makefile
> fix(makefile): fix dgraph version pinning inside container

- CHANGELOG.md
Follow Strict SerVer for Beta / RC & GA
https://commons.apache.org/releases/versioning.html
Beta Release Numbers
Beta releases are denoted by adding "beta<beta version number>" after the release number. For example, if the current release version is 2.0.4, and a developer wished to preview the next major release, the release would be labeled 3.0-beta1.
> fix(changelog): update release version

- .github/workflows/labeler.yml
Related to this change https://github.com/dgraph-io/dgraph/pull/8716
We will see labeler failing on community PRs without this change.
> fix(ci) update labeler to pull_request_target

- .golangci.yml
- chunker/json_parser_test.go
- codec/codec_test.go
- dgraph/cmd/alpha/run_test.go
- dgraph/cmd/increment/increment.go
- dgraph/cmd/live/batch.go
- dgraph/cmd/live/run.go
- dql/mutation.go
- edgraph/server.go
- ee/backup/run.go
- graphql/resolve/query_test.go
- graphql/resolve/resolver_error_test.go
- graphql/schema/wrappers_test.go
- posting/index_test.go
- posting/list_test.go
- query/outputnode.go
- query/shortest.go
- schema/parse.go
- task/conversion.go
- tok/tok_test.go
- types/facets/utils.go
- types/geo_test.go
- types/geofilter_test.go
- upgrade/change_v20.03.0.go
- worker/online_restore.go
- worker/task.go
- x/x.go
> chore(linter): add unconvert linter and address related issues

- Makefile
- chunker/json_parser.go
- codec/benchmark/benchmark.go
- codec/codec.go
- contrib/integration/swap/main.go
- contrib/integration/swap/words.go
- dgraph/cmd/bulk/loader.go
- dgraph/cmd/live/batch.go
- dgraph/cmd/live/run.go
- dgraph/cmd/migrate/datatype.go
- dgraph/cmd/zero/zero.go
- dgraph/cmd/zero/zero_test.go
- graphql/authorization/auth.go
- paper/dgraph.tex
- raftwal/meta.go
- tok/tok.go
- types/scalar_types.go
- x/keys.go
- x/log_writer.go
`nextWord()` used a global index and simply got the word from the list based on the index without checking if it's in the range.
Pass the index as an argument to the function and let the callers maintain the index themselves (increase it here), and check if the index is valid.
I also fixed some typo and comments by the way.
> fix: check index for next word and replace global index with local one

- contrib/Dockerfile
We used to only expose alpha ports in the docker image. This would unnecessarily expose alpha ports even when the container is running zero. That is not good from security point of view.
> contrib: stop exposing only Alpha ports in docker image

- chunker/json_parser.go
- codec/benchmark/benchmark.go
- dgraph/cmd/alpha/run_test.go
- dgraph/cmd/bulk/run.go
- dgraph/cmd/live/run.go
- dgraph/cmd/root.go
- graphql/bench/auth_test.go
- graphql/e2e/auth/auth_test.go
- graphql/e2e/auth/debug_off/debugoff_test.go
- graphql/e2e/auth_closed_by_default/auth_closed_by_default_test.go
- graphql/e2e/common/admin.go
- graphql/e2e/common/common.go
- graphql/e2e/normal/normal_test.go
- graphql/resolve/resolver_error_test.go
- query/outputnode.go
- query/outputnode_test.go
- systest/bgindex/count_test.go
- types/facets/facet_types.go
- worker/draft.go
- worker/queue.go
- x/config.go
- x/file.go
- x/init.go
- x/keys.go
- x/log.go
- x/sentry_integration.go
- x/server.go
- x/x.go
1. Some functions in package `x` are unused
2. package `x` provides `Panic` to simplify error checking and handling (for panics)
1. Remove unused functions
2. use `x.Panic` to replace 3-line codes like below:
```go
if err != nil {
panic(err)
}
```
> chore: remove unused functions in x and replace panic with x.Panic

- go.mod
- go.sum
- graphql/e2e/custom_logic/cmd/Dockerfile
Update Badger from `7677fcb` to `6ed45ae` (on main-deprecated branch).  This fixes https://github.com/dgraph-io/badger/pull/1752 and https://github.com/dgraph-io/badger/pull/1756.
First CI failed [here](https://github.com/dgraph-io/dgraph/actions/runs/4208376321/jobs/7304322951).  This issue was resolved by bumping up the Go version used in the container.
> fix(slash): update badger dep

- dgraph/cmd/alpha/metrics_test.go
- x/metrics.go
These metrics have been part of Badger for a while. This PR exports them in orometheus format at the /metrics endpoint.
* badger_blocked_puts_total
* badger_pending_writes_total
* badger_compactions_current
fixes #8481
> feat(metrics): add badger metrics (#8034)

- systest/backup/advanced-scenarios/deleted-namespace/docker-compose.yml
- testutil/docker.go
once the zero cluster is up, it applies a trial license. Until the license is not applied, health check for alpha returns that the cluster is an OSS cluster.
This PR ensures that the t driver code now waits for the license to be proposed and applied in the cluster. Then, it waits for the login to succeed before running the tests.
> fix(tests): wait for license to be applied before trying to login

- worker/acl_cache.go
- worker/aggregator.go
- worker/backup.go
- worker/backup_ee.go
- worker/backup_handler.go
- worker/backup_manifest.go
- worker/backup_oss.go
- worker/compare.go
- worker/draft.go
- worker/groups.go
- worker/match.go
- worker/restore_map.go
- worker/sort.go
`mapper` methods have different receiver names: `m` and `mw`.
Unify receiver names for `mapper`.
Simplify some code btw.
> chore(worker): unify mapper receiver names

- contrib/local-test/Makefile
**This is a makefile only for local testing purposes.  It spins up a toy cluster for testing.  This is not the makefile used in our pipelines.**
Currently the makefile sets `DGRAPH_VERSION` to local no matter what is set in the environment.  This is undesirable if one wants to use a specific version of Dgraph to spin up.  E.g.,
```
docker pull dgraph/dgraph:v22.0.2
DGRAPH_VERSION=v22.0.2 make up
```
should spin up a cluster using the desired version of Dgraph.  This change fixes that behavior.  Note that this does not break existing behavior.  E.g., if I want to build my image from source locally,
```
make docker-image # builds dgraph and creates dgraph/dgraph:local image
cd contrib/local-test
make up
```
has the expected behavior of spinning up a cluster with the version of Dgraph I just …
> chore(docs): fix local-test cluster makefile

- edgraph/server_test.go
This [PR](https://github.com/dgraph-io/dgraph/pull/8319) introduces some badger instances that are not closed.
We clean up the files.
> fix(test): Clean cruft from test run

- dgraphtest/cluster.go
- dgraphtest/image.go
- dgraphtest/local_cluster.go
- query/query0_test.go
- query/upgrade_test.go
When we do upgrade testing, it is possible that some of the tests that were added later fails for an older version of Dgraph. We would like to skip those tests when dgraph's version does not support that feature.
> chore(test): skip a test when dgraph's version does not support the feature

- query/query.go
- query/query0_test.go
Without the check, the code erraneously bubbles up nil error even when there's been an error in one of the child subgraph. This later causes a panic because the downstream code expects no error.
Reproduce this:
DQL Query:
```
{
var(func: eq(name, "Alicey")){
friend(orderdesc: id) {
f as count(uid)
}
}
q(func: uid(f)){
name
} 
}
```
Fixes: https://github.com/dgraph-io/projects-internal/issues/89
Add an error check.
> fix(Query): Do an error check before bubbling up nil error

- dgraphtest/cluster.go
- dgraphtest/config.go
- dgraphtest/dgraph.go
- dgraphtest/local_cluster.go
- query/upgrade_test.go
- systest/incremental-restore/incremental_restore_test.go
This PR adds the Export and DropAll function in dgraphtest package. The Export function enables to run export mutation and export data out of dgraph. The DropAll function drops all the data in the db.
> dgraphtest: add support for export

- .github/workflows/cd-dgraph.yml
In releases <=v21 we included the badger CLI tool in our dgraph docker images.  We make this a part of our cd pipeline again.
> chore(cd): add badger binary to dgraph docker image

- tok/stopwords_test.go
This was added in https://github.com/dgraph-io/dgraph/pull/8665 but seems to have been an oversight.
> chore: remove unused build tag

- systest/backup/nfs-backup/Dockerfile
- systest/backup/nfs-backup/docker-compose.yml
NFS backup tests fail frequently in CI. The test installs the NFS client before starting the alpha service because of this the Alpha container takes more time to reach a healthy state and may not pass the health check. To solve this, created new Docker file which is a combination of NFS-client and Dgraph, This has been added under the build key of docker-compose file. https://github.com/dgraph-io/dgraph/actions/runs/4744244095/jobs/8424889366
> chore(test): fix frequently failing NFS-backup tests

- dgraphtest/cluster.go
- dgraphtest/local_cluster.go
Seems like it takes longer for a 6 alpha cluster to be available for running queries.
> chore: wait longer for login to work

- CHANGELOG.md
v23 changelog needed
add changelog
> chore(changelog): v23 changelog

- .github/workflows/ci-dgraph-upgrade-tests.yml
- dgraphtest/cluster.go
- dgraphtest/config.go
- dgraphtest/image.go
- dgraphtest/local_cluster.go
- query/query_facets_test.go
- query/upgrade_test.go
- worker/restore_map.go
This PR allows us to run upgrade tests for various combinations of before and after dgraph versions in the query package.
> add upgrade tests in query package for all version combinations

- CHANGELOG.md
We add our CVE fixes to the changelog for v23.
> chore(changelog): add cves to changelog

- .github/workflows/ci-dgraph-tests.yml
- ee/acl/run.go
- ee/audit/run_ee_test.go
- systest/backup/common/utils.go
> fix failing oss build

- dgraph/cmd/bulk/reduce.go
On huge datasets, bulk import crashes with this stack trace:
```
panic: z.Buffer max size exceeded: 68719476736 offset: 68719476718 grow: 51
goroutine 421 [running]:
github.com/dgraph-io/ristretto/z.(*Buffer).Grow(0xc050d17c00, 0x33)
/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1/z/buffer.go:180 +0x55b
github.com/dgraph-io/ristretto/z.(*Buffer).SliceAllocate(0xc050d17c00, 0x2f)
/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1/z/buffer.go:266 +0x2e
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapIterator).Next(0xc00e56f410, 0x3?, {0xc034740c40, 0x1d, 0x20})
/home/runner/work/dgraph/dgraph/dgraph/cmd/bulk/reduce.go:206 +0x126
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).reduce.func2()
/home/runner/work/dgraph/dgraph/dgraph/cmd/bulk/reduce.go:486 +0x5aa …
```
> fix(bulk): removed buffer max size

- dgraphtest/config.go
- dgraphtest/local_cluster.go
1. check whether c is nil before cleanup. Sometimes, cleanup function can be called after cluster creation has failed. In that case, the pointer receiver c could be nil.
2. use a larger prefix for numbering containers. Sometimes in CI runs, I see something about a conflict and that the removal of volume has failed. By reducing the probability of collision of the container name prefix could eliminate the problem.
> dgraphtest: small fixes to dgraphtest lib

- .github/workflows/ci-dgraph-oss-build.yml
Previous commits broke OSS build.  Since we didn't have a test for this, it was undetected by CI.
Add a CI job to verify that we can make the dgraph OSS build, and run all dgraph OSS unit tests.  We do this in a separate workflow because this does not require a separate self-hosted runner (we can use github hosted runners for this job).
See also: https://github.com/dgraph-io/dgraph/pull/8832
> chore(ci): add workflow for OSS build + unit tests

- dgraphtest/cluster.go
when we do a restore, it is possible that one of the alphas do not do a restore but instead just stream the snapshot from one of the other alpahs. In the dgraphtest package, in the WaitForRestore function, we should wait for either restore to complete or snapshot to be streamed.
> chore: waitForRestore should check for receiving snapshot

- .github/workflows/ci-dgraph-code-coverage.yml
We were checking out main instead of the merge commit in one workflow (code coverage).  This is because we use `pull_request_target`, which has different defaults.
Specify the commit we should checkout.
> chore(ci): checkout merge commit on pull-request-target

- .github/workflows/ci-dgraph-upgrade-tests.yml
- dgraphtest/image.go
- dgraphtest/local_cluster.go
- query/upgrade_test.go
For some reason, when we use the worktree.Checkout, it seems to fail a lot in CI with errors
test panicked: error while checking out git repo with hash [a77bbe8ae0d42697a38069a9749cfe71c2dafbe6]:
open /home/ubuntu/actions-runner/_work/dgraph/repo/ee/updatemanifest: no such file or directory
Until we know why that is happening, I [Aman] have moved to use the git command line tool.
This PR also increases the timeout for the upgrade GitHub workflow to 2 hours and frequency of periodic runs to 4 hours.
> chore: use `git` cmd tool for checkout a git hash

- .github/workflows/ci-dgraph-code-coverage.yml
On merges to main, coverage cannot be sent because workflow is attempting to checkout a merge commit, which is not applicable on a push to main (or a scheduled run).
Add conditional logic to workflow.  Unfortunately AFAIK it is not possible to add the conditional logic to the specific step in the job, so we have to split this into two jobs, and select which one based on the type of event.  This creates some duplication but seems unavoidable.
> chore(ci): fix test coverage workflow

- dgraph/cmd/alpha/run.go
- dgraphtest/config.go
- dgraphtest/dgraph.go
- query/normalize_feature_flag_test.go
- query/outputnode.go
- worker/server_state.go
- x/config.go
This feature flag allows configuring @normalize in the query language such that if there are multiple fields with same alias, they could be returned as a list or non-list.
There was a breaking change at some point with the PR https://github.com/dgraph-io/dgraph/pull/7639. Some customers do not prefer a list response in case of @normalize. We would like to not make any breaking changes going forward, and hence, introducing this feature flag enables users to make that choice.
> feat(query): add feature flag list-in-normalize

- .github/workflows/ci-dgraph-upgrade-tests.yml
- dgraphtest/image.go
- dgraphtest/local_cluster.go
- dgraphtest/paths.go
- systest/multi-tenancy/upgrade_test.go
Description: Sometimes tests fail and container logs are empty. Now, we also print the output of inspecting the docker containers. We additionally also use existing dgraph repo on disk to clone a copy instead of downloading the whole repo again from GitHub for building binaries.
Closes: DGRAPHCORE-285 DGRAPHCORE-280
> test: print more logs if the upgrade tests fail

- dgraph/cmd/zero/raft.go
Added stack trace to the error message 
This was the error message before change
```2023/05/09 20:31:21 proto: Tablet: illegal tag 0 (wire type 0)
github.com/dgraph-io/dgraph/x.Check
/home/ash/go/src/github.com/dgraph-io/dgraph-release/x/error.go:42
github.com/dgraph-io/dgraph/dgraph/cmd/zero.run
/home/ash/go/src/github.com/dgraph-io/dgraph-release/dgraph/cmd/zero/run.go:338
github.com/dgraph-io/dgraph/dgraph/cmd/zero.init.0.func1
/home/ash/go/src/github.com/dgraph-io/dgraph-release/dgraph/cmd/zero/run.go:83
github.com/spf13/cobra.(*Command).execute
/home/ash/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
/home/ash/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute …
```
> chore(zero): improve error message while unmarshalling WAL

- dgraphtest/acl.go
- dgraphtest/cluster.go
- dgraphtest/compose_cluster.go
- dgraphtest/dgraph.go
- dgraphtest/image.go
- dgraphtest/paths.go
- ee/acl/acl_curl_test.go
- ee/acl/acl_integration_test.go
- ee/acl/acl_test.go
- ee/acl/integration_test.go
- ee/acl/upgrade_test.go
- systest/incremental-restore/incremental_restore_test.go
- systest/multi-tenancy/basic_test.go
- systest/multi-tenancy/upgrade_test.go
This PR also adds HealthForInstance API to dgraphtest package for checking health of Alpha through graphql.
> test(acl): add upgrade tests for ee/acl package

- dgraph/cmd/bulk/loader.go
- dgraph/cmd/bulk/run.go
- dgraphtest/cluster.go
- dgraphtest/config.go
- dgraphtest/dgraph.go
- dgraphtest/image.go
- dgraphtest/load.go
- dgraphtest/local_cluster.go
- systest/integration2/bulk_loader_test.go
- systest/integration2/incremental_restore_test.go
If only gql schema is provided, and DQL schema is missing bulk loader used to fail. This PR adds the ability to auto generate the DQL schema from the gql schema and use it in the bulk loader.
This PR also adds support for running bulk loader in the dgraphtest package. Additionally, this PR also changes the dgraphtest package to always copy the dgraph binary into a temp folder even when the version of the dgraph used is set to "local".
Closes: DGRAPHCORE-324
Docs PR: NA
> fix(bulk): enable running bulk loader with only gql schema

- .github/workflows/ci-dgraph-integration2-tests.yml
- .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
- dgraphtest/config.go
- dgraphtest/local_cluster.go
- ee/acl/upgrade_test.go
- query/upgrade_test.go
- systest/multi-tenancy/upgrade_test.go
This PR breaks down the earlier upgrade CI workflow into 3 different workflows:
1. upgrade tests from last release to main
2. upgrade tests from older releases to last release
3. integration2 tests workflow
We have added an env variable DGRAPH_UPGRADE_MAIN_ONLY so that we can identify what tests to run. This PR also updates the upgrade tests config to run tests with InPlace upgrade strategy as well.
Closes: DGRAPHCORE-273
Docs: NA
> ci(upgrade): break down upgrade tests CI workflow

- worker/queue.go
- worker/restore_reduce.go
- xidmap/trie.go
Fix compilation on 32bit machine
> fix: compilation on 32bit

- .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
GitHub has a limit on each job to 6 hours. This workflow needs to run longer.
> chore(upgrade): increase the job duration limit to 12h

- dgraphtest/cluster.go
- dgraphtest/compose_cluster.go
- dgraphtest/local_cluster.go
- go.mod
- go.sum
- systest/license/integration_test.go
- systest/license/license_test.go
- systest/license/upgrade_test.go
Description: this PR adds upgrade tests for  systest/license package using dgraphtest package.
Closes: DGRAPHCORE-303
> add upgrade tests for systest/license package

- dgraphtest/local_cluster.go
- systest/integration2/incremental_restore_test.go
- worker/online_restore.go
If we do mutations in between incremental restores, those will get lost. The next incremental restore will overwrite any data that is written in between two incremental restores. It is not very useful to try to block the next incremental restore after in between mutations because it is really hard to detect that a change was made.
For example, let's say we detect the mutations done in between two incremental restores by looking at the data in memtable. But then, if we restart Dgraph, or drop any other attribute (predicate), that may end up doing compaction and would persist all the data from memtable to sstables. This would make it impossible to figure out that a change was made.
It wouldn't be very useful to store this information (that a mutation was done) in an in memory flag either. …
> doc(restore): add docs for mutations in between incremental restores

- dgraphtest/cluster.go
- dgraphtest/load.go
- dgraphtest/local_cluster.go
- edgraph/server.go
- ee/acl/upgrade_test.go
- query/query3_test.go
- query/query4_test.go
- systest/multi-tenancy/upgrade_test.go
When we perform an export and import into the cluster, this ends up creating two groot users in the cluster. This PR implements a workaround so that two groot users are not created to begin with. With this workaround, now we can also run upgrade tests using ExportImport.
The workaround is as follows. We find the UIDs of groot user and guardian group from the new cluster. We modify the output of the export and replace the UIDs of groot user and guardian group with the UIDs we found in the new cluster.
Closes: DGRAPHCORE-300
> chore(test): add workaround for multiple groot issue in export-import

- dgraphtest/cluster.go
- dgraphtest/config.go
- dgraphtest/image.go
- dgraphtest/local_cluster.go
- dgraphtest/paths.go
This PR also fixes a bug in the code that compares the running Dgraph version vs the expected version. It is possible that the version is specified in e.g. long git hash format whereas we use the short git hash format of Dgraph version in the logs.
> chore(upgrade): run upgrade tests for v23.0.1

- Makefile
- dgraph/cmd/alpha/http.go
- dgraph/cmd/alpha/http_test.go
Fixes #8529
Closes: DGRAPHCORE-223
inspired from https://github.com/dgraph-io/dgraph/pull/8004
> feat(alpha): support RDF response via http query request (#8004) 

- dgraphtest/config.go
- dgraphtest/local_cluster.go
for certain binaries such as v22.0.0, dgraph version that gets printed is "local". We now instead use the commit sha to find the right running version of Dgraph for ensuring that we are running the version that we expect to run.
> fix(upgrade): check commit SHA to find running dgraph version

- dgraphtest/image.go
- dgraphtest/local_cluster.go
For in place upgrade, the container remains the same and the logs have the version string twice, one for the old container and one for the new container. We want the version string in the logs for the new container. Hence, we look for the string in the logs bottom up by using strings.LastIndex instead of strings.Index.
> fix(upgrade): look for version string in logs bottom up

- edgraph/server.go
- edgraph/server_test.go
we use a combination of namespace, start timestamp and ACL hmac secret key to make the transaction context more robust. Unfortunately, because the ACL secret is of type x.Sensitive, we ended up using "*****" as the key for computing hash. This commit fixes this issue. This is NOT a breaking change.
> sec(acl): convert x.Sensitive to string type for authn hash

- dgraph/cmd/alpha/run.go
- dgraph/cmd/zero/pgp_test.go
- dgraphtest/config.go
- dgraphtest/dgraph.go
- query/normalize_feature_flag_test.go
- query/outputnode.go
- worker/server_state.go
- x/config.go
This feature flag allows configuring @normalize in the query language such that if there are multiple fields with same alias, they could be returned as a list or non-list.
There was a breaking change at some point with the PR https://github.com/dgraph-io/dgraph/pull/7639. Some customers do not prefer a list response in case of @normalize. We would like to not make any breaking changes going forward, and hence, introducing this feature flag enables users to make that choice.
> feat(query): add feature flag normalize-compatibility-mode (#8845)

- algo/uidlist.go
- algo/uidlist_test.go
This PR improves the performance of IntersectCompressedWithBin. LDBC09 Query went from 38 second -> 22 second. Benchmarks show up to 80% improvement in performance.
> perf(query): Improve Intersection with UID pack

- Makefile
Description: Currently `codename` ldflag` is not mutable and set to `dgraph`.  We would like to make it configurable for cloud builds.
> chore(build): name codename configurable

- worker/cdc_ee.go
A CDC event can return an error during JSON marshalling like the following:
2021/10/12 21:58:11 json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]
github.com/dgraph-io/dgraph/x.Check
/ext-go/1/src/github.com/dgraph-io/dgraph/x/error.go:42
github.com/dgraph-io/dgraph/worker.(*CDC).processCDCEvents.func1
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/cdc_ee.go:207
github.com/dgraph-io/dgraph/worker.(*CDC).processCDCEvents.func2
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/cdc_ee.go:295
github.com/dgraph-io/dgraph/worker.(*CDC).processCDCEvents.func3
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/cdc_ee.go:331
github.com/dgraph-io/dgraph/worker.(*CDC).processCDCEvents
/ext-go/1/src/github.com/dgraph-io/dgraph/worker/cdc_ee.go:351 …
> fix: Skip bad events in CDC.

- edgraph/server.go
If a mutation has a lot of conditional mutations, this PR will speed up the parsing of the query. cherry-pick of PR (#7871)
> perf(query): speed up parsing of a huge query

- ee/acl/acl_test.go
- query/common_test.go
- query/integration_test.go
- query/mutation.go
- query/mutation_test.go
- query/query0_test.go
- query/upgrade_test.go
- systest/bgindex/count_test.go
Description: when data (non-reserved predicates) is added on UIDs that belong to groot user or guardian group, it is allowed. But when the same data is deleted, that is not allowed. This PR allows deletion of non-reserved predicates on special UIDs.
Closes: https://dgraph.atlassian.net/browse/DGRAPHCORE-355
Docs: NA
> fix(acl): allow data deletion for non-reserved predicates

- .github/workflows/ci-aqua-security-trivy-tests.yml
- .github/workflows/ci-dgraph-fuzz.yml
- .github/workflows/ci-dgraph-integration2-tests.yml
- .github/workflows/ci-dgraph-ldbc-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-oss-build.yml
- .github/workflows/ci-dgraph-tests-arm64.yml
- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
- .github/workflows/ci-dgraph-upgrade-tests.yml
- .github/workflows/ci-golang-lint.yml
In our [scheduled runs](https://github.com/dgraph-io/dgraph/actions?query=event%3Aschedule) we see a number of "ghost" jobs.  E.g. [1](https://github.com/dgraph-io/dgraph/actions/runs/5881148541).  This is probably due to the following sequence of events:
- github actions sends a notification to developer who created / modified cron job frequency
- if this person is no longer able to receive this notification (i.e. no longer receiving emails) the action raise this ghost job with an error about unverified email
This is a bug with github actions.  After contacting github support they suggested changing the cron job frequency in order to reset who receives the notifications.  This may solve the issue.
> chore: update cron job frequency to reset github notifications

- dgraph/cmd/migrate/dump.go
Description: This change wraps all the column names with backticks so that MySQL won't complain when a table has columns that are also reserved keywords in MySQL.
> fix(export): Escape MySQL column names

- telemetry/telemetry.go
- x/init.go
In order to distinguish Telemetry data coming from cloud instances, add build `Codename` to Telemetry data. This is the same approach we are using for distinguishing Sentry data.
> [feat] Add build Codename to Telemetry data

- CONTRIBUTING.md
Description: We no longer make releases this way, and it is also confusing for community folks to see these instructions when they are not applicable to them.
> chore(docs): remove release instructions from contrib

- ee/acl/acl_test.go
- query/mutation.go
- systest/bgindex/count_test.go
upgrade tests fail because of the change in the error. This PR undoes the change in the error made in the PR #8937.
> fix(acl): revert the error changed in #8937

- dgraphtest/.gitignore
- dgraphtest/config.go
- dql/parser.go
- query/mutation_test.go
TestUnreservedPredicateForDeletion should be run with dgraph versions in which the bug is fixed. This commit also updates the upgrade version to v23.1.0 in upgrade config.
> test(upgrade): skip test for dgraph version when the bug is not fixed

- dgraph/cmd/debug/run.go
This adds a `dgraph debug --parse_key` flag that can return the ParsedKey
struct of a hex key. This is useful if there's a lone key that you want parse
without having to have a p directory around. This flag does not need a p
directory, just the hex key string.
Example:
$ dgraph debug --parse_key 000000000000000000000b6467726170682e74797065000000000000000001
{d} Key: UID: 1, Attr: 0-dgraph.type, Data key
This tells you that the key 000000000000000000000b6467726170682e74797065000000000000000001
is for the predicate `0-dgraph.type` and the UID `1`.
docs PR: https://github.com/dgraph-io/dgraph-docs/pull/636
> feat(debug): add parse_key to debug tool

- dgraphtest/config.go
- dgraphtest/dgraph.go
The --telemetry superflag was introduced in v21 version. Before that version of Dgraph, we did not have super flags. This commit also modifies upgrade configuration to include some versions of Dgraph in the upgrade tests that are run with each PR.
> test(upgrade): handle different versions of Dgraph for --telemetry flag

- x/minioclient.go
Description: Many blob storage providers support the S3 API, e.g.: Cloudflare R2, Backblaze B2. This fix allows to use any S3 endpoint.
Fixes: #8940
> fix(export): Support for any s3 endpoint

- dgraphtest/config.go
- dgraphtest/dgraph.go
- dgraphtest/image.go
- dgraphtest/local_cluster.go
- systest/plugin/integration_test.go
- systest/plugin/plugin_test.go
- systest/plugin/upgrade_test.go
This is an existing 'integration' test, now transformed to run for 'integration' and 'upgrade' using dgraphtest framework. Additionally, leveraging 'testify/suite' package's SetupTest() / SetupSubTest() / TeardownTest() / TeardownSubTest() functionality during the test runs. 'integration' tests are still run using t.go and the dgraphtest framework acts as a no-op for now. Going forward, there are plans to have dgraphtest framework take over the t.go. 'upgrade' used in the tests is Dgraph version upgrade from a source version to a target version using 'BackupRestore' and 'InPlace'.
**Plugin insights:** Hope this link will help here https://dgraph.io/docs/query-language/indexing-custom-tokenizers/#implementing-a-plugin
Closes: https://dgraph.atlassian.net/browse/DGRAPHCORE-304
> test(upgrade): add upgrade tests for systest/plugin

- systest/integration2/incremental_restore_test.go
- worker/online_restore.go
This is a minor inconvenience while using the incremental restore API that when incrementalFrom is set to 1, we throw an error back. The restore API takes two backup numbers incrementalFrom & backupNum and restores all the backups including both the ends, i.e. following set notation all the backups in the set [incrementalFrom, backupNum] are restored. This should work fine when incrementalFrom is set to 1 which is a full backup.
> fix(restore): allow incrementalFrom to be 1 in restore API

- .github/workflows/ci-dgraph-code-coverage.yml
- .github/workflows/ci-dgraph-fuzz.yml
- .github/workflows/ci-dgraph-integration2-tests.yml
- .github/workflows/ci-dgraph-ldbc-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-oss-build.yml
- .github/workflows/ci-dgraph-tests-arm64.yml
- .github/workflows/ci-dgraph-tests.yml
- .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
- .github/workflows/ci-dgraph-upgrade-tests.yml
Description: Currently we use large 32gb self-hosted runners for jobs that require more resources.  Github now offers their own suite of hosted runners.  We can now transition to these new runners.  We also reduce the frequency of some scheduled jobs and remove some particular workflows from each PR run.
> ci(runners): use larger github hosted runners + reduce cron frequency

- algo/uidlist.go
- algo/uidlist_test.go
- codec/codec.go
Updated algo to intersect. Getting upto 175% improvment overall
```
goos: linux
goarch: amd64
pkg: github.com/dgraph-io/dgraph/algo
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
│     in1      │                 main_in                 │
│    sec/op    │    sec/op      vs base                  │
ListIntersectCompressBin/compressed:IntersectWith:ratio=0.01:size=100:overlap=0.01:-8       91.21n ± ∞ ¹   387.70n ± ∞ ¹         ~ (p=1.000 n=1) ²
ListIntersectCompressBin/compressed:IntersectWith:ratio=0.1:size=100:overlap=0.01:-8        336.0n ± ∞ ¹   1733.0n ± ∞ ¹         ~ (p=1.000 n=1) ²
ListIntersectCompressBin/compressed:IntersectWith:ratio=1:size=100:overlap=0.01:-8          1.093µ ± ∞ ¹    3.481µ ± ∞ ¹         ~ (p=1.000 n=1) ² …
```
> perf(query): Update CompressedBin IntersectionAlgo

- graphql/e2e/common/common.go
- graphql/e2e/common/mutation.go
- graphql/e2e/common/query.go
- graphql/e2e/directives/schema.graphql
- graphql/e2e/directives/schema_response.json
- graphql/e2e/normal/schema.graphql
- graphql/e2e/normal/schema_response.json
- graphql/resolve/add_mutation_test.yaml
- graphql/resolve/query_test.yaml
- graphql/resolve/schema.graphql
- graphql/schema/dgraph_schemagen_test.yml
- graphql/schema/gqlschema.go
- graphql/schema/gqlschema_test.yml
- graphql/schema/rules.go
- graphql/schema/schemagen.go
- graphql/schema/testdata/schemagen/input/language-tags.graphql
- graphql/schema/testdata/schemagen/output/language-tags.graphql
> Added lang support

- dgraphtest/config.go
- dgraphtest/dgraph.go
- dgraphtest/load.go
- dgraphtest/local_cluster.go
- dgraphtest/snapshot.go
- raftwal/storage.go
- systest/integration2/snapshot_test.go
- systest/online-restore/namespace-aware/restore_test.go
- worker/draft.go
Description: Certain issues arise when a snapshot is taken by the alpha leader in a cluster and a new node joins afterwards.
Closes: https://linear.app/hypermode/issue/HYP-163/alpha-leader-fails-to-stream-snapshot-to-new-alpha-nodes
> fix(raft):alpha leader fails to stream snapshot to new alpha nodes

- query/query0_test.go
- worker/task.go
Currently when we have a language tagged predicate (example: name). Querying name should return only untagged values. name@. should return any language.
Consider dataset
<1> <name> "first user" .
<2> <name@en> "second user" .
query (func: uid(1,2)) { uid name} would return "{uid: 1, name: first user}".
query (func: uid(1,2)) { uid name@.} would return "{{uid: 1, name@.: "first user"}, {uid: 2, name@.: "second user"}}".
However due to a bug, we are not enforcing this in @filter(has(name)). So this results in
query (func: has(dgraph.type)) @filter(has(name)) { uid name} results in
"{{uid: 1, name: "first user'}, {uid: 2}}"
Fix: We update @filter(has(name)) to filter on basis of language.
> fix(query): fix has function in filter

- worker/online_restore.go
Do not retry the restore proposal. It can cause issues in the edge case scenarios. Consider the following scenario:
1. alpha-2 gets the restore request (leader is alpha-0)
2. alpha-2 sends the request to alpha-0 (leader).
3. alpha-0 called proposeAndWait which proposed the req (index 24) at time=15:56:10
4. alpha-0 was still waiting for the proposal to be applied and RPC call for `Restore` by alpha-2 got "transport closing error" at time=15:59:08
5. transport closing is a retriable error, so alpha-2 again tried to proposeoOrSend, this time leader was alpha-1, so it sent it to alpha-1
6. alpha-1 proposed the restore request (index 28) at time=15:59:09
> fix(restore): do not retry restore proposal (#8058)

- worker/mutation_integration_test.go
- worker/mutation_unit_test.go
Splits apart the mutation_test.go in dgraph/worker into unit tests vs. integration tests. The purpose is to allow for more effective local tests.
> refactor(dql): Split mutation test

- query/vector_test.go
- worker/mutation.go
fix(vector): Show error is invalid input is provided to vector predicate
> fix(vector): Show error is invalid input is provided to vector predicate

- dgraph/cmd/debuginfo/debugging.go
Improving on #9070. A file must be closed if the function exits on an error.
> Fix(debug): Close file correctly before exiting on error

- dgraph/cmd/alpha/run.go
- posting/list.go
- systest/backup/encryption/backup_test.go
- worker/config.go
- worker/draft.go
- worker/server_state.go
- worker/task.go
Currently when we do queries like `func(uid: 0x1) @filter(type)`. We retrieve the entire type index. Sometimes, when the index is too big, fetching the index is quite slow. We realised that if we know we only want to check few `uids` are of the same, then we can just check those `uids` directly. Right now we are hard coding the number of `uids` threshold. This could be improved with a more statistical based model, where we figure out how many items does the type index have, how many we need to check.
> perf(core): Fix performance issue in type filter (#9065)

- graphql/resolve/query_rewriter.go
- graphql/resolve/query_test.yaml
- query/vector/vector_graphql_test.go
fixes https://linear.app/hypermode/issue/DGR-315/querysimilarthingsbyembedding-not-working-with-dotproduct-or-cosine
> fix(vector): Update query_rewriter to fix dotproduct and cosine query conversion

- posting/index.go
- posting/list.go
Update postinglistCountAndLength function to improve performance
> Perf(core): Update postinglistCountAndLength function to improve performance

- posting/mvcc.go
- query/vector/vector_test.go
- systest/vector/backup_test.go
- tok/hnsw/helper.go
- worker/draft.go
- worker/mutation.go
We call txn.Update() once the transaction has finished. This moves all the uncommited posting lists to a delta map in the txn. This can cause a deadlock with runMutation. Mostly we have seen it when a transaction has a timeout. RunMutation keeps on going, while txn.Update() gets triggered. This PR fixes it by not calling txn.Update() if the transaction has failed. We would futher look into cancelling runMutation at that time too. 
Fixes: https://linear.app/hypermode/issue/DGR-477/dgraph-v24-alpha-2-hangs
> Fix(core): Fix deadlock in runMutation and error handling

- .github/workflows/cd-dgraph.yml
When we run CD pipeline, it pushes Docker images to dgraph/dgraph Repo. There are situations when we want to push images to a different repo (for example to create a custom build) which we do not plan to make GA. Now we are exposing a workflow input `custom-build` which is false by default. When it is checked, then images are pushed to a repo called `dgraph-custom` instead of our official repo dgraph/dgraph
> Enhancing CD pipeline to add ability for pushing to a dgraph-custom repo

- chunker/json_parser.go
- chunker/json_parser_test.go
Currently when we parse an empty string, a json empty array is returned. This is a regression. This diff fixes it. We disallow any vector of empty length.
> fix(core): Fix regression in parsing json empty string

- graphql/authorization/auth.go
A logic error (redeclaring `i` in the loop) in this method disabled the intension of the method: try 3 times to fetch the *i-th* JWK
> Fix(graphql): issue with local variable squashing intended JWK index

- edgraph/server.go
- ee/acl/acl_integration_test.go
Currently namespace used by unique generator uses edge predicate to validate. This shouldn't be the case, we should use the namespace provided in context.
> fix(core): Fix namespace used by unique query generator

- graphql/e2e/schema/schema_test.go
- query/common_test.go
- query/query.go
- query/query0_test.go
- testutil/docker.go
Fixes: https://github.com/dgraph-io/dgraph/issues/9125
> fix(core): Fix regression in computing cond variables

- dgraph/cmd/live/batch.go
- graphql/e2e/common/common.go
- graphql/e2e/schema/schema_test.go
- systest/loader/loader_test.go
- testutil/client.go
- testutil/docker.go
- tlstest/certrequest/certrequest_test.go
- tlstest/certrequireandverify/certrequireandverify_test.go
- tlstest/certverifyifgiven/certverifyifgiven_test.go
Fixed aborts in live loader originating from @upsert directive. 
Also fixed derigster while retrying to allow more requests per second.
> fix(live): Fix derigster while retrying

- posting/list.go
- posting/list_test.go
- posting/lists.go
- worker/task.go
Description: Right now, when we read some data, we read the entire posting list. With this we populate List structure in memory, which has two layers. These two layers are then merge sorted. All of this takes a lot of time. In this diff, we are updating the query processor to just read the latest value in case of scalar types. 
LDBC test for IC09.
Before: 39 seconds
After: 30 seconds
> perf(query): Read just the latest value for scalar types

- .github/dependabot.yml
add Dependabot automated version bumps; behavior is configured as:
- group all patch version bumps into one PR
- group all minor version bumps into one PR
- open individual PRs for all major version bumps
> chore(): add Dependabot version bumps

- posting/index.go
- query/vector/vector_graphql_test.go
- query/vector/vector_test.go
- tok/hnsw/persistent_factory.go
Currently when we rebuild vector index, it only works if you drop it and then add again. With this change, you will be able to rebuild index by changing parameters.
We are also restricting vector index to only work with proper distance metric.
> fix(vector): fix index rebuild when options change

- edgraph/server.go
- systest/multi-tenancy/login_test.go
> fix(multi-tenancy): upsert groot for namespace after drop data

- posting/index.go
- posting/list.go
- posting/mvcc.go
- worker/task.go
Update rollup frequency so that txn too old error doesn't happen too frequently. 
Also added more context to the error to see where it's coming from.
> fix(core): Update error msg for txn too old to give more context

- dql/parser.go
- ee/acl/acl_test.go
- query/query4_test.go
fixes https://github.com/dgraph-io/dgraph/issues/9145
> fix(DQL): unsupported ordering should raise an error 

- .github/workflows/cd-dgraph.yml
Uploading artifacts is running into conflicts, so giving unique name to amd/arm artifacts
> Update cd-dgraph.yml to create unique artifacts

- .golangci.yml
- contrib/jepsen/main.go
- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/e2e/common/subscription.go
- graphql/resolve/webhook.go
- systest/backup/common/utils.go
- systest/bulk_live/common/bulk_live_cases.go
- testutil/backup.go
- close response bodies to prevent resource leaks ("The caller must close the response body when finished with it", see https://pkg.go.dev/net/http)
- add `bodyclose` linter to linter config
> chore(repo): close response bodies to prevent resource leaks

- edgraph/server.go
- systest/unique_test.go
fixes https://github.com/dgraph-io/dgraph/issues/9102
inspired from https://github.com/dgraph-io/dgraph/pull/9106
> fix unique query for non-latin predicate name and whitespace in query

- .github/workflows/cd-dgraph.yml
Dgraph CD pipeline was prematurely publishing Docker images to DockerHub even when one of the architectures failed. This PR makes the following changes to prevent this:
- dgraph-build-amd64 and dgraph-build-arm64 jobs build their respective images. But **do not** push them to DockerHub.
- Job **dgraph-docker-manifest** is renamed to **dgraph-docker-image-and-manifests-push** to reflect that it also pushes docker images for Dgraph/Custom/Standalone
> Enhancing Dgraph cd pipeline to only push images to Dockerhub when both AMD and ARM builds are successful

- CHANGELOG.md
> Adding 24.0.4 to CHANGELOG.md

- .github/workflows/cd-dgraph.yml
We have seen CD pipeline running into conflicts during artifact uploads. Having explicit names for arm/amd artifact to avoid this issue.
> Update cd-dgraph.yml to avoid conflict during artifact upload

- README.md
The README in Dgraph Repo referring **v24.0.2** as the latest version and was hyperlinked to https://github.com/dgraph-io/dgraph/releases/tag/v22.0.0 which was wrong.
Fixing it to referring v24.0.5 as the latest and pointing to the v24.0.5 release
> Fixing  README.md to mention 24.0.5 as latest also fixing wrong link

- tok/hnsw/persistent_hnsw.go
Remove visited uids from the vector hnsw index. It might hurt performance for now, but it fixes a oom error for now.
> fix(core): fix visited uids bitset memory (#9221)

- dgraph/cmd/debug/run.go
- posting/index.go
- posting/index_test.go
- posting/list.go
- posting/list_test.go
- posting/mvcc.go
- posting/mvcc_test.go
- posting/size.go
- posting/size_test.go
- systest/mutations-and-queries/mutations_test.go
- tok/hnsw/helper.go
- worker/mutation_unit_test.go
- worker/sort_test.go
- worker/worker_test.go
- x/debug.go
Currently the delta postings are being stored inside a map. When we are using cache, these deltas gets unnecessarily copied again and again because of the limitations of map. We have introduced a new struct, that would allow us to work on the list of 
deltas. 
With the introduction of this, we can now without copying the map, can pass around lists from one transaction to another without issue.
We are also going to store results like delete markers, uid to posting map and other stuff required to make queries go faster.
> perf(core): Introduce mutable map struct

- tok/hnsw/helper.go
- tok/hnsw/persistent_hnsw.go
Description: 
This PR improves error handling in the hnsw module. In some cases not all errors have to be propagated to the next caller, in this case the error string is currently compared with `strings.Contains(err.Error(), "some_error_text")` or directly `err.Error() == "some_error_string"`. This is bad practice. Instead errors should be directly compared with the native `errors.Is(err, target)` function, which traverses the tree of each error and detects if it contains the specified target error. 
This refactor also fixes two occurrences where the caller of a function compared the error string to a value which could never occur:
https://github.com/dgraph-io/dgraph/pull/9236/files#diff-3a3681ae8c7d51cf49f269f9a732cfe2941dee13903fed04a17a51d5ddff3540R323 …
> fix(core): Improve error handling in hnsw module

- .github/workflows/ci-dgraph-core-tests.yml
- .github/workflows/ci-dgraph-core-upgrade-tests.yml
- .github/workflows/ci-dgraph-system-upgrade-tests.yml
- .github/workflows/ci-dgraph-systest-tests.yml
- .github/workflows/ci-dgraph-vector-tests.yml
- t/t.go
This PR will divide ci-dgraph-tests and ci-dgraph-upgrade-tests workflows into three parts as follows: core, systest, and vector tests.
- Vector tests include only test packages related to vectors.
- Systest includes system test packages such as backup, restore, export, import, etc.
- All remaining packages fall under the core suite.
> ci: separate CI workflows

- .github/workflows/ci-dgraph-code-coverage.yml
- .github/workflows/ci-dgraph-core-tests.yml
- .github/workflows/ci-dgraph-ldbc-tests.yml
- .github/workflows/ci-dgraph-load-tests.yml
- .github/workflows/ci-dgraph-systest-tests.yml
- .github/workflows/ci-dgraph-tests-arm64.yml
- .github/workflows/ci-dgraph-vector-tests.yml
- t/t.go
This PR adds functionality to the test framework to generate test results in the form of JUnit XML. It also introduces a new job in the workflow to upload these test results to Trunk for flaky test detection.
> ci(test): integrate Trunk into multiple CI workflows to identify flaky tests

- .github/workflows/ci-dgraph-core-tests.yml
- .github/workflows/ci-dgraph-systest-tests.yml
- .github/workflows/ci-dgraph-vector-tests.yml
This PR will add a cron job to run the workflow once a day for better flaky test detection.
> ci: Add cron job to run workflow once a day

- posting/mvcc.go
This PR fixes a bug in the Process function of incrRollupi. The issue was caused by inconsistent time units between the doRollup and cleanupTick logic. Specifically, doRollup used time.Now().Unix() (seconds), while cleanupTick used time.Now().UnixNano() (nanoseconds). This mismatch caused cleanupTick to erroneously delete all entries in the map m during every cleanup cycle.
**Checklist**
> fix: ensure consistent time units and prevent erroneous cleanup in incrRollupi Process

- CONTRIBUTING.md
- dgraph/Makefile
- dgraphtest/image.go
- dgraphtest/local_cluster.go
- ee/acl/acl_curl_test.go
- protos/protos_test.go
- systest/audit/audit_test.go
- systest/audit_encrypted/audit_test.go
- systest/loader/loader_test.go
- t/Makefile
- t/README.md
- t/t.go
- testutil/client.go
- testutil/testaudit/audit.go
- tlstest/certrequest/certrequest_test.go
This PR updates testing code to make testing easier on non-Linux environments and fix some commonly failing tests. It also more thoroughly documents the `t` framework as well as offering guidance on other tests.
**Checklist**
> chore: make testing more resilient and update docs

- CHANGELOG.md
- graphql/e2e/common/common.go
- graphql/e2e/common/query.go
- graphql/e2e/directives/docker-compose.yml
- graphql/e2e/normal/docker-compose.yml
- graphql/resolve/query.go
- graphql/schema/response.go
This change adds the translated DQL query to the GraphQL's `extension` attribute set when the GraphQL debug superflag is set to true.
In Dgraph, GraphQL queries are translated to DQL before entering the query system. This change allows for an inspection of what the translator is doing behind the scenes.
Potential Use Cases:
* learning DQL
* aiding few shot prompting in LMs
* use in Dgraph "dashboards" or other helper apps
Note: this is for queries (reads) only. Mutations in DQL are pretty straightforward, but support for them could be added in the future.
**Checklist**
this PR
> feat(graphql): output translated DQL query when the graphql debug superflag is set

- compose/compose.go
- go.mod
- graphql/e2e/common/error.go
- graphql/e2e/custom_logic/cmd/go.mod
- graphql/e2e/custom_logic/cmd/go.sum
- graphql/e2e/custom_logic/cmd/main.go
- graphql/resolve/auth_test.go
- graphql/resolve/mutation_test.go
- graphql/resolve/query_test.go
- graphql/resolve/resolver_error_test.go
- graphql/schema/rules.go
- graphql/schema/schemagen_test.go
- graphql/schema/wrappers_test.go
- systest/ldbc/ldbc_test.go
Upgraded gopkg.in/yaml from v2 to v3 in all places. Mostly this is for housekeeping and to bring our fork more in line with main, so that we may remove the fork in near future.
**Checklist**
> chore: Upgrade from yaml v2 to v3 everywhere

- posting/list.go
> perf(core): Use Intersect to Narrow Iterate Range and Reduce Memory Allocation in pl.Uids()

- worker/mutation.go
We currently use y.Throttle type to ensure that  we do not concurrently build indexes for many predicates at the same time to avoid opening too many files on disk. This type allocates large memory initially to achieve this. By default, on my machine we allocate 128 MB of memory every time Alter is called. Now, Go is slow to release this memory back to OS increasing the memory usage.
This PR sets the max to 1024 predicates at a time. It would be lower if Alter request involves fewer predicates in the request
> Reduce memory usage during Alter execution

- .trunk/trunk.yaml
- CONTRIBUTING.md
- go.mod
- graphql/e2e/custom_logic/cmd/go.mod
- t/Makefile
- t/README.md
Bump Go patch version to 1.22.11 to resolve framework dependency vulnerabilities.
**Checklist**
> chore: bump Go patch version

- contrib/Dockerfile
We've been testing against Ubuntu v24.04, but still building images against v22.04. Bumping to align.
**Checklist**
> bump Ubuntu to v24.04

- dgraph/cmd/bulk/mapper.go
- dgraph/cmd/bulk/reduce.go
- go.mod
- go.sum
- worker/backup_ee.go
- worker/restore_map.go
- worker/restore_reduce.go
A small change, but i noticed https://github.com/klauspost/compress was already an indirect dependency of the repo, so this uses that version over the golang version as a drop in replacement. According to the repo it offers "better compression and concurrent streams".
**Checklist**
> Switch to s2 for bulk loader and backup/restore

- dgraph/docker-compose.yml
- x/flags.go
Affected versions: v24.1.1
we require a default for each flag and we removed the default value for sentry flag from the code.
> undo the breaking change made while removing sentry flag

- acl/acl.go
- acl/acl_test.go
- acl/utils.go
- audit/run.go
- backup/run.go
- check_upgrade/check_upgrade.go
- chunker/chunk.go
- chunker/json_parser.go
- chunker/json_parser_test.go
- chunker/rdf_parser.go
Replaced the `github.com/pkg/errors` package with the native `errors` package in the acl, algo, audit, backup, check_upgrade and chunker modules. Also fixed some error comparisons and error texts.
**Checklist**
this PR
[docs repo](https://github.com/hypermodeinc/docs) staged and linked here
> chore: replace github.com/pkg/errors with native error package in the acl, algo, audit, backup, check_upgrade and chunker modules 

- posting/list.go
- worker/mutation_unit_test.go
This PR fixes a bug where a reverse edge (`@reverse` predicate) with a count index (`@count`) may lose values when the same predicate is set and deleted multiple times within a single DQL mutation.
> fix(core): fix reverse edge loss when set and delete occur together

- dgraph/cmd/live/batch.go
- dgraph/cmd/live/load-json/load_test.go
- dgraph/cmd/live/load-uids/load_test.go
- dgraph/cmd/live/run.go
- dgraph/cmd/zero/zero_test.go
- edgraph/zero.go
- go.mod
- go.sum
- query/normalize_feature_flag_test.go
- systest/21million/live/run_test.go
- systest/bgindex/count_test.go
- systest/bgindex/parallel_test.go
- systest/bgindex/reverse_test.go
- systest/bgindex/string_test.go
- systest/bulk_live/common/bulk_live_fixture.go
- systest/integration2/incremental_restore_test.go
- systest/multi-tenancy/integration_basic_helper_test.go
- testutil/bulk.go
- worker/mutation.go
- worker/upgrade_test.go
- xidmap/xidmap.go
This PR implements the AllocateIDs API for allocating UIDs, namespaces and timestamps for bulk and live loader. For now, this PR also updates the live loader to use this API and completely avoid talking to zero directly.
> Add implementation for AllocateIDs and use the API in live loader

- dgraph/cmd/mcp/mcp_server.go
- dgraph/cmd/mcp/mcp_server_sse_test.go
- dgraph/cmd/mcp/prompt.txt
This PR adds the `validate_query_syntax` tool.
NOTE: the tool does not validate mutations. Long story, but the parser used removed its ability to parse mutation blocks way back.
**Checklist**
this PR
> feat(mcp): Add a tool that can validate the syntax of a DQL query

- CHANGELOG.md
- dgraph/cmd/alpha/run_test.go
- dgraphtest/image.go
- edgraph/server.go
- edgraph/server_test.go
This PR adds additional checks in edgraph/server.go::verifyUniqueWithinMutation for mutations that may have been conditionally pruned in `updateMutations` (called just before).
Also a basic test verifies not only the prevention of the panic but also assures unpruned mutations were applied. Note this is an improvement upon #9449 in that additional range and inner loop predicate checks were required (@gooohgb).
Assigning to @shivaji-kharse as the original author of this function.
**Checklist**
this PR
> fix(core): add additional checks in verifyUniqueWithinMutation for pruned mutations

- dgraph/cmd/root.go
- posting/list.go
- posting/mvcc.go
- schema/schema.go
This PR addresses several stability issues:
- Added read/write locks for concurrent access to maps to prevent race conditions.
- Ensured transactions created via `NewTransactionAt` are explicitly discarded to free `readTs` usage.
- Ensured file handles are explicitly closed after use to prevent file descriptor leaks.
These changes improve thread safety, avoid stale transactions blocking version GC, and prevent potential resource exhaustion.
**Checklist**
this PR
> fix(core): add map locking and ensure resource cleanup

- .github/workflows/ci-dgraph-vector-tests.yml
- dgraph/cmd/dgraphimport/import_test.go
- dgraphtest/image.go
- dgraphtest/load.go
- dgraphtest/local_cluster.go
- testutil/docker.go
This PR improves the speed and resiliency on tests that rely on the LocalCluster system
- adds additional health and login checks to prevent timing issues with cluster creation
- parallel-izes some creation, login and health check functions to minimize delays
- adds support for using local dgraph image correctly when the DGRAPH_BINARY envar is present (tests on non-Linux systems that rely on running the native dgraph image would fail prior to this)
- suppresses expected "error" log output before defined thresholds (helps minimize false positives when checking logs)
**Checklist**
> chore(test): Improve localcluster tests speed and resiliency
